import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import * as F from '@ee-labs/fields'
import {GUIDE_ANTENNA} from './guideLessons.js'

const groups={i:'I. Transmission lines',j:'J. Loss and dispersion'}
const C=z=>`${N(z[0])}${z[1]<0?'-':'+'}j${N(Math.abs(z[1]))}`
const lineSymbols=[['V(z,t),I(z,t)','Voltage (V) and current (A) at position z metres and time t seconds. Current is positive toward the load.'],[String.raw`L',C'`,'Inductance per metre (H/m) and capacitance per metre (F/m).'],['Z_0,v_p','Characteristic impedance (Ω) and phase velocity (m/s).'],[String.raw`\Gamma`,'Reflected voltage wave divided by incident voltage wave, dimensionless.']]
const z0=k('z0','Characteristic impedance',50,10,150,'Ω'),vp=k('vp','Wave velocity',2e8,1e8,F.C0,'m/s'),length=k('length','Line length',2,.1,100,'m')
const freq=k('f','Frequency',1e8,1e6,1e9,'Hz')
const chartGrid=[...[0,.2,.5,1,2,5].map(value=>({...F.resistanceCircle(value),family:'r',value})),...[-5,-2,-1,-.5,-.2,.2,.5,1,2,5].map(value=>({...F.reactanceCircle(value),family:'x',value}))]
function lesson(id,name,knobs,question,intro,route,limits,tryText,solve,symbols=lineSymbols){return{id,name,group:groups[id[0]],knobs,question,intro,route,limits,try:tryText,solve,symbols,flow:['Source and reference direction','Distributed inductance and capacitance','Load boundary and reflected wave']}}
function out(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,plotNote:'Change one setting, predict the direction of the change, then compare the curve and the worked substitution.',practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const logPoints=(fn)=>Array.from({length:161},(_,i)=>{const x=10**(4+4*i/160);return{x,y:fn(x)}})
const lossy=p=>F.describeLine({R:p.R,L:250e-9,G:1e-6,C:100e-12,len:100})

export const EXTENDED=[
lesson('i1',"The telegrapher’s equations",[z0,vp,length],'How do a cable’s distributed elements produce a delay?',
'Each small length stores magnetic energy in its series inductance and electric energy in its shunt capacitance. Local voltage and current balance become differential equations as that length tends to zero.',
'Use the time-domain wave equations for propagation and switching. For one sinusoidal frequency, phasors replace time derivatives with jω. A finite lumped state-space ladder approximates a distributed line; it is not the exact delay.',
'Uniform, lossless TEM line. The propagation velocity here is no greater than the speed of light.',
'Double the length, then double Z0. Which change affects the delay?',p=>{const x=F.describeLine({Z0:p.z0,vp:p.vp,len:p.length});return out([
s('Balance one short segment','A voltage drop supplies the changing inductor current; a current difference charges the capacitor.',String.raw`\frac{\partial V}{\partial z}=-L'\frac{\partial I}{\partial t},\qquad\frac{\partial I}{\partial z}=-C'\frac{\partial V}{\partial t}`),
s('Recover the per-metre elements','Solve Z0² = L′/C′ and vp² = 1/(L′C′) together.',String.raw`L'=Z_0/v_p,\qquad C'=1/(Z_0v_p)`,String.raw`L'=${N(p.z0)}/${N(p.vp)}=${N(x.L)}\,\mathrm{H/m},\quad C'=${N(x.C)}\,\mathrm{F/m}`),
s('Propagate the waveform','The load sees the forward waveform one flight time later, before adding any reflection.',String.raw`T=\ell/v_p,\quad V^+(z,t)=f(t-z/v_p)`,String.raw`T=${N(p.length)}/${N(p.vp)}=${N(x.delay*1e9)}\,\mathrm{ns}`)
],[r('Inductance',x.L*1e9,'nH/m'),r('Capacitance',x.C*1e12,'pF/m'),r('One-way delay',x.delay*1e9,'ns')],[curve('Flight time versus distance','Distance (m)','Delay (ns)',samples(l=>l/p.vp*1e9,0,p.length))],'Changing impedance at fixed velocity changes L′ and C′ in opposite directions; the flight time stays fixed.',x.delay*1e9,'ns','Calculate the one-way delay in nanoseconds.','Divide metres by metres/second, then multiply by 10⁹.') }),
lesson('i2','From coax geometry to impedance',[k('a','Inner conductor radius',.45e-3,.1e-3,.7e-3,'m'),k('b','Shield inner radius',1.475e-3,.8e-3,4e-3,'m'),k('epsr','Relative permittivity',2.25,1,6)],'How do the electrostatic and magnetic calculations become a transmission line?',
'The same coax geometry used earlier supplies both capacitance and external inductance per metre. Their ratio sets impedance; their product sets propagation speed.',
'Use the coax field integrals to obtain L′ and C′, then the lossless line identities. This connects the field route to the distributed circuit route.',
'Uniform dielectric, relative permeability one, perfect conductors, and negligible internal inductance. The shield radius must exceed the centre-conductor radius.',
'Increase dielectric permittivity. Predict what happens to impedance and velocity.',p=>{const x=F.lineFromGeometry({kind:'coax',a:p.a,b:p.b,epsr:p.epsr,mur:1,length:1});return out([
s('Integrate the coax fields','The logarithm follows from the radial 1/r electric and magnetic fields.',String.raw`C'=\frac{2\pi\epsilon_0\epsilon_r}{\ln(b/a)},\quad L'=\frac{\mu_0}{2\pi}\ln(b/a)`,String.raw`\ln(b/a)=${N(Math.log(p.b/p.a))},\quad C'=${N(x.C)}\,\mathrm{F/m},\quad L'=${N(x.L)}\,\mathrm{H/m}`),
s('Take the ratio for impedance','The logarithmic geometry factor remains in the ratio.',String.raw`Z_0=\sqrt{L'/C'}`,String.raw`Z_0=${N(x.Z0)}\,\Omega`),
s('Take the product for velocity','The geometry cancels from the product for this homogeneous TEM structure.',String.raw`v_p=1/\sqrt{L'C'}=c/\sqrt{\epsilon_r}`,String.raw`v_p/c=${N(x.vp/F.C0)}`)
],[r('Characteristic impedance',x.Z0,'Ω'),r('Velocity / c',x.vp/F.C0)],[curve('Dielectric slows the wave','Relative permittivity','Velocity / c',samples(e=>1/Math.sqrt(e),1,6))],'The radii affect impedance, while the homogeneous dielectric determines the velocity.',x.Z0,'Ω','Calculate the characteristic impedance.','Take the square root of L′ divided by C′.') },[...lineSymbols,['a,b','Inner conductor radius and shield inner radius (m).'],[String.raw`\epsilon_r`,'Relative dielectric permittivity; μr is fixed at one.']]),
lesson('i3','The reflection coefficient',[z0,k('load','Load resistance',100,0,500,'Ω'),k('open','Open circuit (0: no, 1: yes)',0,0,1,'',1)],'What reflected voltage enforces the load boundary condition?',
'At the load, incident and reflected voltages add. Their currents subtract because the reflected wave travels toward the source.',
'Apply V/I = RL at the load to solve for Γ. The same coefficient relates sinusoidal phasors and lossless step amplitudes for a resistive termination.',
'Real nonnegative load on a real lossless line. Reflected power fraction is |Γ|² under this real reference impedance.',
'Compare 100 Ω, 25 Ω, a short, and the open-circuit setting.',p=>{const RL=p.open?Infinity:p.load,g=F.reflectionCoefficient(RL,p.z0)[0];return out([
s('Write both waves at the load','Define V+ as incident amplitude. Reflected voltage is ΓV+ and reflected current is −ΓV+/Z0.',String.raw`V_L=V^+(1+\Gamma),\quad I_L=\frac{V^+}{Z_0}(1-\Gamma)`),
s('Enforce the termination','Substitute into RL = VL/IL and solve. At an open, IL = 0 gives Γ = 1 directly.',p.open?String.raw`I_L=0\Rightarrow\Gamma=1`:String.raw`\Gamma=\frac{R_L-Z_0}{R_L+Z_0}`,p.open?null:String.raw`\Gamma=\frac{${N(p.load)}-${N(p.z0)}}{${N(p.load)}+${N(p.z0)}}=${N(g)}`),
s('Check energy balance','The accepted power fraction is one minus the reflected fraction.',String.raw`P_r/P_i=\Gamma^2,\quad P_L/P_i=1-\Gamma^2`,String.raw`P_r/P_i=${N(g*g)},\quad P_L/P_i=${N(1-g*g)}`)
],[r('Reflection coefficient',g),r('Reflected power',100*g*g,'%')],[curve('Reflection versus termination','Load resistance (Ω)','Voltage reflection coefficient',samples(R=>(R-p.z0)/(R+p.z0),0,500))],g<0?'The reflected voltage reverses sign.':g===0?'The matched load absorbs the incident power.':'The reflected voltage has the same sign as the incident voltage.',g,'','Calculate the voltage reflection coefficient.','Use the resistance difference divided by the resistance sum.') }),
lesson('i4','Follow every reflected arrival',[z0,vp,length,k('Vs','Source step',5,.1,10,'V'),k('Rs','Source resistance',25,1,200,'Ω'),k('RL','Load resistance',150,1,500,'Ω')],'Why can a cable’s load overshoot its final DC voltage?',
'The source initially sees Z0, before information about the load returns. Each boundary then reflects part of the arriving wave; the sum builds the measured voltage.',
'Use the exact lossless travelling-wave event sum for steps. Use phasors for steady sinusoids. The DC divider checks the final value but cannot describe the intermediate arrivals.',
'Ideal step, lossless uniform line, real positive end resistances. Finite rise time, dispersion, and lossy wave spreading are omitted.',
'Set Rs equal to Z0 to absorb the returning wave. Then set RL equal to Z0.',p=>{const d=F.bounceDiagram({Z0:p.z0,vp:p.vp,len:p.length,Vs:p.Vs,Rs:p.Rs,RL:p.RL}),tr=F.loadTrace(d,{until:9*d.T});const second=d.atEnd(3*d.T).v;return out([
s('Launch before the load is known','The first divider contains the line impedance, not the load resistance.',String.raw`V_0^+=V_s\frac{Z_0}{R_s+Z_0}`,String.raw`V_0^+=${N(p.Vs)}\frac{${N(p.z0)}}{${N(p.Rs+p.z0)}}=${N(d.first)}\,\mathrm V`),
s('Reflect at both boundaries','A return trip multiplies the incident amplitude by both reflection coefficients.',String.raw`\Gamma_L=\frac{R_L-Z_0}{R_L+Z_0},\quad\Gamma_s=\frac{R_s-Z_0}{R_s+Z_0}`,String.raw`\Gamma_L=${N(d.gammaL)},\quad\Gamma_s=${N(d.gammaS)}`),
s('Add each load arrival','The kth load arrival occurs at (2k+1)T. Its voltage increment includes the new reflection at the load.',String.raw`\Delta V_{L,k}=V_0^+(1+\Gamma_L)(\Gamma_s\Gamma_L)^k,\quad t_k=(2k+1)T`,String.raw`V_L(T)=${N(d.atEnd(d.T).v)}\,\mathrm V,\quad V_L(3T)=${N(second)}\,\mathrm V`),
s('Sum the convergent geometric series','The limit must equal the DC resistor divider after the line stops storing changing energy.',String.raw`V_L(\infty)=\frac{V_0^+(1+\Gamma_L)}{1-\Gamma_s\Gamma_L}=V_s\frac{R_L}{R_s+R_L}`,String.raw`V_L(\infty)=${N(d.steady.v)}\,\mathrm V`)
],[r('One-way delay',d.T*1e9,'ns'),r('First load voltage',d.atEnd(d.T).v,'V'),r('Final voltage',d.steady.v,'V')],[curve('Load voltage after switching','Time (ns)','Load voltage (V)',tr.t.map((t,i)=>({x:t*1e9,y:tr.v[i]}))),{label:'First six travelling waves',xLabel:'Position (m)',yLabel:'Arrival time (ns)',traces:d.waves.slice(0,6).map(w=>({label:`Wave ${w.index+1}: ${fmt(w.amp)} V`,points:[{x:w.xStart*p.length,y:w.launchedAt*1e9},{x:w.dir>0?p.length:0,y:w.arrivesAt*1e9}]}))}],
'Load arrivals are separated by a round trip: T, 3T, 5T. Alternating increments can overshoot while still converging to the DC divider.',second,'V','Calculate the load voltage immediately after the arrival at 3T.','Add the k = 0 and k = 1 voltage increments.',{table:{headers:['Load arrival','Time (ns)','Load voltage (V)'],rows:[0,1,2,3,4].map(i=>[i+1,(2*i+1)*d.T*1e9,d.atEnd((2*i+1)*d.T).v])},check:`Geometric sum and DC divider differ by ${fmt(d.steady.v-p.Vs*p.RL/(p.Rs+p.RL))} V.`}) }),
lesson('i5','Impedance changes with line length',[z0,freq,k('fraction','Length / wavelength',.25,.01,.5),k('RL','Load resistance',100,1,300,'Ω'),k('open','Open load (0: no, 1: yes)',0,0,1,'',1)],'What impedance does the source see through a length of line?',
'The reflected wave rotates in phase during its round trip. Therefore the voltage/current ratio seen at the source depends on electrical length even when the load is unchanged.',
'Use phasor voltage and current propagation for sinusoidal steady state. Use the bounce route for switching; a single-frequency input impedance is not a transient solution.',
'Lossless line at one frequency, fixed velocity 2×10⁸ m/s. Ideal open-stub resonances can have infinite impedance.',
'Compare one quarter and one half wavelength. With an open load, try one eighth wavelength.',p=>{const ln=F.describeLine({Z0:p.z0,vp:2e8,len:p.fraction*2e8/p.f}),ZL=p.open?Infinity:p.RL,z=F.inputImpedance(ln,ZL,p.f).Z,finite=z!==Infinity,re=finite?z[0]:0,im=finite?z[1]:0;return out([
s('Turn distance into phase','β is phase advance per metre. A wavelength corresponds to 2π radians.',String.raw`\lambda=v_p/f,\quad\beta\ell=2\pi\ell/\lambda`,String.raw`\ell=${N(ln.len)}\,\mathrm m,\quad\beta\ell=${N(2*Math.PI*p.fraction)}\,\mathrm{rad}`),
s('Propagate the load impedance','For an open, take the infinite-load limit before evaluating the expression.',p.open?String.raw`Z_{in}=-jZ_0\cot(\beta\ell)`:String.raw`Z_{in}=Z_0\frac{R_L+jZ_0\tan(\beta\ell)}{Z_0+jR_L\tan(\beta\ell)}`,finite?String.raw`Z_{in}=${C(z)}\,\Omega`:String.raw`Z_{in}\to\infty\quad\text{(ideal open resonance)}`),
s('Check the special lengths','A quarter wavelength inverts impedance. A half wavelength repeats the load.',String.raw`Z_{in}(\lambda/4)=Z_0^2/Z_L,\quad Z_{in}(\lambda/2)=Z_L`)
],finite?[r('Input resistance',re,'Ω'),r('Input reactance',im,'Ω')]:[],[curve('Round-trip reflection phase','Length / wavelength','Unwrapped phase rotation (degrees)',samples(u=>-720*u,0,.5))],finite?'A lossless line can transform both the magnitude and angle of the input impedance.':'This ideal open-stub resonance is infinite; no finite reading is substituted.',-720*p.fraction,'degrees','Calculate the round-trip phase rotation toward the generator.','A full wavelength changes the round-trip phase by −720 degrees.') }),
lesson('i6','Design a quarter-wave transformer',[k('source','Source resistance',50,10,200,'Ω'),k('load','Load resistance',100,10,300,'Ω'),freq,k('reactance','Load reactance',0,-100,100,'Ω')],'What line impedance matches two real resistances at one frequency?',
'At a quarter wavelength, the input impedance is the line impedance squared divided by the load. Solving that equation gives the geometric mean.',
'Use the frequency-domain quarter-wave identity, then verify reflection at the source. A reactive load needs an additional matching operation before this simple real-impedance design.',
'Lossless transformer with realizable positive real characteristic impedance. A nonzero load reactance is explicitly declined by this design rule.',
'Double the design frequency and inspect physical length. Add load reactance to see why the simple rule stops applying.',p=>{const Zt=Math.sqrt(p.source*p.load),len=2e8/(4*p.f),allowed=p.reactance===0;return out([
s('Use the quarter-wave boundary relation','The input target is the real source resistance.',String.raw`Z_{in}=Z_t^2/Z_L,\quad Z_{in}=R_s`),
s('Solve the real-load design','For a reactive load this square root would generally be complex, outside the assumed real lossless line.',String.raw`Z_t=\sqrt{R_sR_L}`,allowed?String.raw`Z_t=\sqrt{${N(p.source)}(${N(p.load)})}=${N(Zt)}\,\Omega`:String.raw`\operatorname{Im}Z_L\ne0:\quad\text{simple quarter-wave design declined}`),
s('Convert the target phase to physical length','The physical length follows from the fixed propagation speed.',String.raw`\ell=v_p/(4f)`,String.raw`\ell=${N(len)}\,\mathrm m`)
],allowed?[r('Transformer impedance',Zt,'Ω'),r('Physical length',len,'m')]:[r('Quarter-wave length',len,'m')],allowed?[curve('Match away from design frequency','Frequency / design frequency','Reflection magnitude',samples(q=>{const z=F.inputImpedance(F.describeLine({Z0:Zt,vp:2e8,len}),p.load,q*p.f).Z;return Math.hypot(...F.reflectionCoefficient(z,p.source))},.5,1.5))]:[],allowed?'The match is exact at the design frequency and generally degrades away from it.':'The reactive-load design is declined. Cancel or transform its reactance before applying this rule.',len,'m','Calculate the quarter-wave physical length.','Use the stated 2×10⁸ m/s velocity and divide by four times frequency.') }),
lesson('i7','Read and rotate the Smith chart',[z0,k('R','Load resistance',100,0,300,'Ω'),k('X','Load reactance',50,-200,200,'Ω'),k('distance','Distance / wavelength',.125,0,.5)],'How does a load impedance become a point on the Smith chart?',
'Normalize impedance to the line reference, then apply the bilinear reflection map. Travelling toward the source rotates a lossless line’s reflection clockwise without changing its magnitude.',
'Use the Smith chart to see matching geometry and the complex formula to calculate the same point. Both represent the same sinusoidal steady-state solution.',
'Real positive reference impedance and lossless travel. Constant-resistance circles and constant-reactance arcs are clipped to the passive unit disc.',
'Set resistance equal to Z0 and reactance to zero. Then restore mismatch and travel half a wavelength.',p=>{const g=F.reflectionCoefficient([p.R,p.X],p.z0),rot=F.towardsGenerator(g,2*Math.PI*p.distance),zin=F.loadFromGamma(rot,p.z0);return out([
s('Normalize the impedance','Normalization removes units while retaining the reference impedance explicitly.',String.raw`z=Z_L/Z_0=r+jx`,String.raw`z=${N(p.R/p.z0)}+j${N(p.X/p.z0)}`),
s('Map impedance to reflection','The centre is a matched load; the right and left edges are open and short.',String.raw`\Gamma_L=(z-1)/(z+1)`,String.raw`\Gamma_L=${C(g)}`),
s('Rotate for the round trip','The factor of two accounts for travel to the load and back.',String.raw`\Gamma(d)=\Gamma_L e^{-j2\beta d},\quad Z(d)=Z_0\frac{1+\Gamma(d)}{1-\Gamma(d)}`,String.raw`\angle\text{rotation}=${N(-720*p.distance)}^\circ,\quad\Gamma(d)=${C(rot)}`)
],[r('Reflection magnitude',Math.hypot(...g)),r('Rotation',-720*p.distance,'degrees')],[{kind:'smith',z0:p.z0,grid:chartGrid,points:[{gamma:g,label:'load'},{gamma:rot,label:'input'}],paths:[{label:'toward generator',points:samples(u=>u,0,p.distance).map(q=>F.towardsGenerator(g,2*Math.PI*q.x))}],caption:zin===Infinity?'Input is an ideal open circuit.':`Input impedance: ${fmt(zin[0])} + j(${fmt(zin[1])}) Ω.`}],
'The graphical and complex-number routes agree: half a wavelength makes one complete reflection-plane turn.',Math.hypot(...g),'','Calculate the reflection-coefficient magnitude.','Take the magnitude of (ZL − Z0)/(ZL + Z0).') }),
...['j1','j2'].map(id=>lesson(id,id==='j1'?'A lossy line at every frequency':'Why a lossy step needs a different model',[k('R','Series resistance per metre',.5,0,2,'Ω/m'),k('f','Frequency',1e6,1e4,1e8,'Hz')],id==='j1'?'How do resistance and leakage alter propagation?':'Why can’t the lossless bounce diagram represent this lossy step?',
'The series impedance and shunt admittance are complex functions of frequency. Their product gives propagation; their ratio gives characteristic impedance.',
id==='j1'?'Use complex frequency-domain equations for the specified RLGC line. A phasor sweep shows loss and phase together.':'Compare frequency-dependent phase velocities before selecting a time model. The finite lossless-arrival route is unavailable here; a separately validated inverse transform or distributed approximation would be required.',
'Uniform frequency-independent R′, L′ = 250 nH/m, G′ = 1 μS/m, C′ = 100 pF/m over a 100 m line. Skin effect is not added to R′. The general lossy line is not replaced with a finite exact state-space model.',
'Compare 10 kHz with 1 MHz, then reduce the series resistance.',p=>{const ln=lossy(p),x=F.lineAt(ln,p.f),lo=F.lineAt(ln,1e4),hi=F.lineAt(ln,1e6),phase=Math.atan2(x.Z0[1],x.Z0[0])*180/Math.PI;return out([
s('Form the per-metre impedance and admittance','R′ dissipates series power; G′ dissipates shunt power. Both retain their SI per-metre units.',String.raw`z'=R'+j\omega L',\quad y'=G'+j\omega C',\quad\omega=2\pi f`),
s('Take the passive square-root branch','α is attenuation in nepers per metre and β is phase advance in radians per metre.',String.raw`\gamma=\sqrt{z'y'}=\alpha+j\beta,\quad Z_0=\sqrt{z'/y'}`,String.raw`\gamma=${C(x.gamma)}\,\mathrm{m^{-1}},\quad Z_0=${C(x.Z0)}\,\Omega`),
s('Interpret the propagation','Amplitude decays as exp(−αℓ). Phase velocity is ω/β; it can vary across the frequency content of a step.',String.raw`A_{dB}=20\log_{10}(e)\alpha\ell,\quad v_p=\omega/\beta`,String.raw`A_{dB}=${N(x.alpha*100*20/Math.LN10)},\quad v_p=${N(x.vp)}\,\mathrm{m/s}`),
...(id==='j2'?[s('Check the time-domain assumption','A single flight time cannot preserve a broadband waveform when its Fourier components have different phase delays.',String.raw`v_p(10\,\mathrm{kHz})\ne v_p(1\,\mathrm{MHz})`,String.raw`v_{p,low}=${N(lo.vp)},\quad v_{p,high}=${N(hi.vp)}\quad\mathrm{m/s}`)]:[])
],[r('Impedance magnitude',x.Z0mag,'Ω'),r('Impedance phase',phase,'degrees'),r('Loss over 100 m',x.alpha*100*20/Math.LN10,'dB')],[{...curve('Lossy propagation velocity','Frequency (Hz)','Phase velocity (m/s)',logPoints(f=>F.lineAt(ln,f).vp)),logX:true},{...curve('Attenuation over 100 m','Frequency (Hz)','Attenuation (dB)',logPoints(f=>F.lineAt(ln,f).alpha*100*20/Math.LN10)),logX:true}],
id==='j2'?'The finite lossless bounce model is declined for this dispersive line. The displayed frequency-domain solution remains available.':'Both the impedance magnitude and phase depend on frequency; a single nominal Z0 hides this behaviour.',x.alpha*100*20/Math.LN10,'dB','Calculate the attenuation over the 100 m line.','Convert exp(−αℓ) to amplitude decibels: loss = 20 αℓ / ln(10).') },[...lineSymbols,[String.raw`R',G'`,'Series resistance (Ω/m) and shunt conductance (S/m).'],[String.raw`\alpha,\beta`,'Attenuation (Np/m) and phase constant (rad/m).'],[String.raw`\omega`,'Angular frequency 2πf (rad/s).']])),
...GUIDE_ANTENNA,
]
