import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import * as F from '@ee-labs/fields'

const wr90={a:.02286,b:.01016}
const guideSymbols=[['a,b','Guide width and height (m); width is the larger dimension.'],['f,f_c','Operating frequency and mode cutoff frequency (Hz).'],[String.raw`\lambda_g`,'Guide wavelength: distance for one full phase turn along the guide (m).'],['v_p,v_g','Phase velocity and group velocity (m/s).']]
const antennaSymbols=[[String.raw`\theta`,'Angle measured from the wire or array axis; 90° is broadside.'],[String.raw`U(\theta)`,'Radiation intensity (power per solid angle), proportional to squared field pattern.'],['D,G','Linear directivity and power gain relative to an isotropic radiator.'],[String.raw`\eta`,'Radiation efficiency: radiated power / accepted power, between zero and one.'],['u','Total dipole length divided by wavelength, dimensionless.']]
function L(id,name,knobs,question,intro,route,limits,tryText,solve,symbols){return{id,name,group:id[0]==='k'?'K. Waveguides and cavities':'L. Antennas and links',knobs,question,intro,route,limits,try:tryText,solve,symbols:symbols??(id[0]==='k'?guideSymbols:antennaSymbols),flow:id[0]==='k'?['Metal boundary and allowed field shape','Propagation or stored resonant energy','Cutoff, wavelength and loss']:['Driven current distribution','Radiated angular power pattern','Directivity, gain and received power']}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,plotNote:'Read the axis definition before comparing curves. Antenna patterns show normalized power, not electric-field amplitude.',practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const patternPlot=(pattern,max=1)=>({...curve('Normalized radiation pattern','Angle from axis (degrees)','Normalized power',samples(deg=>pattern(deg*Math.PI/180)**2/max,0,180,361)),polar:true})
const logPoints=(fn,lo,hi)=>Array.from({length:161},(_,i)=>{const x=lo*(hi/lo)**(i/160);return{x,y:fn(x)}})
export const GUIDE_ANTENNA=[
L('k1','A hollow guide has a cutoff',[k('f','Frequency',5e9,1e9,20e9,'Hz')],'When can a rectangular guide carry a travelling mode?',
'Metal walls require a transverse field shape. A mode can propagate only when the operating frequency can support that transverse variation and a real longitudinal phase constant.',
'Solve the waveguide boundary eigenvalues for cutoff, then evaluate the longitudinal propagation constant. Lumped circuit and TEM line formulas do not supply a hollow-guide TEM mode.',
'Air-filled ideal WR-90 guide, 22.86 × 10.16 mm. A single decaying evanescent mode below cutoff carries no net axial average power; a finite below-cutoff section can still transmit through coupling at both ends.',
'Move from 5 GHz to 10 GHz, then above 13.114 GHz. Watch the single-mode assumption change.',p=>{const band=F.singleModeBand(wr90),m=F.modeAt(wr90,p.f),fc=F.cutoff(wr90,1,0);return O([
s('Find the transverse eigenvalue','For TE10, one half-wave fits across width a and there is no variation across b.',String.raw`f_{c,mn}=\frac c2\sqrt{(m/a)^2+(n/b)^2},\quad f_{c,10}=\frac c{2a}`,String.raw`f_{c,10}=${N(fc/1e9)}\,\mathrm{GHz}`),
s('Select propagating or evanescent behaviour','Above cutoff β is real. Below cutoff the longitudinal field decays with real α.',m.propagating?String.raw`\beta=\frac{2\pi f}c\sqrt{1-(f_c/f)^2}`:String.raw`\alpha=\frac{2\pi}c\sqrt{f_c^2-f^2}`,m.propagating?String.raw`\beta=${N(m.beta)}\,\mathrm{rad/m}`:String.raw`\alpha=${N(m.alpha)}\,\mathrm{Np/m}`),
s('Check the next allowed mode','TE20 is the next cutoff in WR-90. The strict interval between these cutoffs supports only TE10.',String.raw`f_{c,10}<f<f_{c,20},\quad f_{c,20}=c/a`,String.raw`${N(band.from/1e9)}<f_{GHz}<${N(band.to/1e9)}`)
],[r('TE10 cutoff',fc/1e9,'GHz'),r('Next cutoff',band.to/1e9,'GHz'),r(m.propagating?'Phase constant':'Field decay',m.propagating?m.beta:m.dbPerMetre,m.propagating?'rad/m':'dB/m')],[curve('TE10 transverse field shape','Position across width (mm)','Normalized electric field',samples(mm=>F.te10Field(wr90,mm/1000).ey,0,wr90.a*1000))],m.propagating?(p.f<band.to?'TE10 propagates within the single-mode interval.':'TE10 propagates, but higher modes are also allowed. Excitation determines which appear.'):'At this frequency the single decaying TE10 solution is evanescent.',fc/1e9,'GHz','Calculate the TE10 cutoff in gigahertz.','Divide c by twice the 22.86 mm width.') }),
L('k2','Guide wavelength and two velocities',[k('f','Frequency',10e9,6.6e9,13e9,'Hz')],'How can phase velocity exceed c while energy travels slower than c?',
'A waveguide’s axial phase pattern is the projection of a field with transverse variation. Its phase crests and its wave-packet envelope therefore move at different velocities.',
'Differentiate the dispersion relation to obtain group velocity, or use the reciprocal phase/group factors for this ideal guide. Phasors determine phase velocity; a narrowband packet motivates group velocity.',
'Ideal air-filled WR-90, TE10 in the single-mode interval. Group velocity describes a narrowband envelope in this lossless dispersion relation, not an arbitrary pulse in every medium.',
'Approach cutoff. Predict which velocity grows and which shrinks.',p=>{const m=F.modeAt(wr90,p.f),q=m.factor;return O([
s('Calculate the propagation factor','The cutoff reduces the longitudinal phase constant relative to a free-space wave.',String.raw`q=\sqrt{1-(f_c/f)^2},\quad\beta=(2\pi f/c)q`,String.raw`q=${N(q)}`),
s('Find wavelength and phase velocity','One full longitudinal phase cycle occupies 2π/β metres.',String.raw`\lambda_g=2\pi/\beta=\lambda_0/q,\quad v_p=\omega/\beta=c/q`,String.raw`\lambda_g=${N(m.lambdaGuide*1000)}\,\mathrm{mm},\quad v_p/c=${N(m.vp/F.C0)}`),
s('Differentiate for group velocity','From ω² = c²β² + ωc², differentiation gives dω/dβ = c²β/ω.',String.raw`v_g=\frac{d\omega}{d\beta}=cq,\quad v_pv_g=c^2`,String.raw`v_g/c=${N(m.vg/F.C0)},\quad v_pv_g/c^2=${N(m.vp*m.vg/F.C0**2)}`)
],[r('Guide wavelength',m.lambdaGuide*1000,'mm'),r('Phase velocity / c',m.vp/F.C0),r('Group velocity / c',m.vg/F.C0)],[{label:'Phase and group velocities',xLabel:'Frequency (GHz)',yLabel:'Velocity / c',traces:[{label:'Phase velocity',points:samples(f=>F.modeAt(wr90,f*1e9).vp/F.C0,6.6,13)},{label:'Group velocity',points:samples(f=>F.modeAt(wr90,f*1e9).vg/F.C0,6.6,13)}]}],'Superluminal phase crests do not imply superluminal energy or information transport.',m.lambdaGuide*1000,'mm','Calculate the guide wavelength in millimetres.','Divide the free-space wavelength c/f by q.') }),
L('k3','A closed guide becomes a resonator',[k('d','Cavity length',.02,.012,.05,'m'),k('sigma','Wall conductivity',5.8e7,1e3,6.3e7,'S/m')],'How do cavity dimensions and wall loss set resonance and bandwidth?',
'Closing both ends forces an integer standing-wave pattern along the guide. The stored electric and magnetic energies exchange at resonance; finite wall resistance dissipates a small amount each cycle.',
'Use the cavity eigenfrequency first, then Q = ωW/P from the ideal mode’s field integrals. The bandwidth estimate follows from the isolated high-Q resonance approximation.',
'TE101 air cavity, WR-90 cross section. Unloaded Q includes conductor loss only. The perturbation estimate is accepted only when skin depth / smallest cavity dimension ≤ 0.001; external coupling adds further loss.',
'Increase length to lower resonance. Reduce conductivity until the wall-loss approximation fails its stated guard.',p=>{const spec={...wr90,d:p.d},x=F.cavityQ(spec,{sigma:p.sigma}),ok=x.guard.ok;return O([
s('Fit the standing wave to the box','TE101 has one half-wave across a and one along d.',String.raw`f_{101}=\frac c2\sqrt{a^{-2}+d^{-2}}`,String.raw`f_{101}=${N(x.f/1e9)}\,\mathrm{GHz}`),
s('Find the conducting-wall surface resistance','Skin depth relates bulk conductivity to the high-frequency surface resistance.',String.raw`\delta=\sqrt{\frac2{\omega\mu_0\sigma}},\quad R_s=1/(\sigma\delta)`,String.raw`\delta=${N(x.delta*1e9)}\,\mathrm{nm},\quad R_s=${N(x.Rs)}\,\Omega`),
s('Integrate the ideal mode and apply the guard','For peak electric-field scale E0 = 1 V/m, W = ε0abd/8. Wall power integrates squared tangential magnetic field over all six faces; E0 cancels from Q.',String.raw`W=\epsilon_0abd/8,\quad P_{wall}=\frac{R_s}{2}\int_{walls}|H_t|^2\,dA,\quad Q=\omega W/P_{wall}`,String.raw`W=${N(x.storedEnergy)}\,\mathrm J,\quad P_{wall}=${N(x.wallLoss)}\,\mathrm W,\quad\delta/d_{min}=${N(x.guard.value)}`),
s('Convert quality factor to bandwidth','Only interpret these values as the guarded perturbation estimate.',String.raw`Q=\omega W/P_{wall},\quad B\simeq f_0/Q`,ok?String.raw`Q=${N(x.Q)},\quad B=${N(x.bandwidth/1e6)}\,\mathrm{MHz}`:String.raw`\delta/d_{min}>10^{-3}:\quad\text{Q estimate outside accepted regime}`)
],[r('Resonance',x.f/1e9,'GHz'),r('Skin depth',x.delta*1e9,'nm'),...(ok?[r('Unloaded Q',x.Q),r('Bandwidth',x.bandwidth/1e6,'MHz')]:[])],ok?[curve('Isolated resonance approximation','Detuning / bandwidth','Normalized stored energy',samples(t=>1/(1+4*t*t),-3,3))]:[],x.guard.says,x.f/1e9,'GHz','Calculate the TE101 resonance in gigahertz.','Use both reciprocal squared dimensions a and d.') },[...guideSymbols,['d','Closed cavity length (m).'],[String.raw`\sigma,\delta,R_s`,'Wall conductivity (S/m), skin depth (m), and surface resistance (Ω).'],['W,P_{wall},Q','Stored energy (J), wall loss (W), and unloaded quality factor (dimensionless).']]),
L('l1','The Hertzian element radiates sine squared',[k('u','Element length / wavelength',.01,.001,.05)],'Why does a short current element radiate broadside but not along its axis?',
'For a uniform electrically short current element, the far electric field is proportional to sin θ. Power intensity is therefore proportional to sin² θ.',
'Integrate power over solid angle to obtain directivity, then relate radiated power to peak current to define radiation resistance.',
'Uniform-current Hertzian element, not a centre-fed short dipole with triangular current. The short-element formula is accepted for length / wavelength ≤ 0.02; thicker or longer structures need another current model.',
'Double the element length while remaining below 0.02 wavelength. Predict the resistance ratio.',p=>{const x=F.hertzianDipole(p.u),d=F.directivityOf(x.pattern),ok=p.u<=.02;return O([
s('Square the field to get power','Normalize the broadside intensity to one.',String.raw`|E_\theta|\propto\sin\theta,\quad U(\theta)=U_{max}\sin^2\theta`),
s('Integrate over the sphere','The solid-angle element contributes another sin θ. Integrating sin³ θ from zero to π gives 4/3.',String.raw`P_{rad}=2\pi U_{max}\int_0^\pi\sin^3\theta\,d\theta=\frac{8\pi}{3}U_{max}`,String.raw`D=4\pi U_{max}/P_{rad}=3/2\quad\text{(numerical: }${N(d.directivity)}\text{)}`),
s('Refer radiated power to peak current','The common free-space coefficient uses η0 ≈ 120π Ω.',String.raw`R_{rad}=2P_{rad}/I_{pk}^2\simeq80\pi^2u^2`,String.raw`R_{rad}\simeq80\pi^2(${N(p.u)})^2=${N(x.radiationResistance)}\,\Omega`)
],[r('Ideal-pattern directivity',d.directivity),...(ok?[r('Radiation resistance',x.radiationResistance,'Ω')]:[])],[patternPlot(x.pattern)],ok?'Radiation resistance grows with length squared; directivity stays 1.5 within this assumed pattern.':'This length exceeds the declared short-element limit. The plotted sin² pattern is the ideal model, not an accepted prediction for this length.',1.5,'','Calculate directivity from the power integral.','Divide 4π by 8π/3.') }),
L('l2','The half-wave dipole',[k('radius','Wire radius / wavelength',.001,.0001,.01)],'How does a half-wave current distribution change the radiation pattern?',
'A thin centre-fed half-wave wire has approximately sinusoidal current along its length. Integrating its radiated field gives a narrower broadside pattern than a uniform short element.',
'Use the assumed sinusoidal current distribution to integrate the far field and then the power. A separate closed-form resistance is an independent numerical check at exactly half a wavelength.',
'Free-space isolated thin wire with assumed sinusoidal current. Radius / wavelength ≤ 0.002 is the declared thin-wire guard. Feed impedance also includes reactance, which is not solved by this radiation-resistance calculation.',
'Increase wire radius past the guard and inspect which physical assumption becomes unreliable.',p=>{const x=F.dipole(.5,{wireRadius:p.radius});return O([
s('Integrate the current distribution','At u = 1/2, cos(πu) = 0. Use the limiting value zero on the axis.',String.raw`F(\theta)=\frac{\cos[(\pi/2)\cos\theta]}{\sin\theta},\quad U\propto|F|^2`),
s('Normalize by total radiated power','Numerical solid-angle integration determines directivity without assuming a tabulated gain.',String.raw`D=\frac{2\max|F|^2}{\int_0^\pi|F(\theta)|^2\sin\theta\,d\theta}`,String.raw`D=${N(x.directivity)},\quad D_{dBi}=10\log_{10}D=${N(x.directivityDbi)}`),
s('Refer the power to the feed current','For the normalized one-ampere peak current, radiation resistance is twice the radiated power. Half-power angles determine beamwidth.',String.raw`R_{rad}=2P_{rad}/I_{pk}^2,\quad U(\theta_{HP})=U_{max}/2`,String.raw`R_{rad}=${N(x.radiationResistance)}\,\Omega,\quad HPBW=${N(x.beamwidthDeg)}^\circ`)
],[r('Model directivity',x.directivityDbi,'dBi'),r('Model beamwidth',x.beamwidthDeg,'degrees'),...(x.guard.ok?[r('Radiation resistance',x.radiationResistance,'Ω')]:[])],[patternPlot(x.pattern,x.Umax)],x.guard.says,x.directivityDbi,'dBi','Convert the calculated linear directivity to dBi.','Directivity is a power ratio: use 10 log10.',{check:`Quadrature and the independent half-wave closed form differ by ${fmt(x.radiationResistance-x.radiationResistanceClosed)} Ω. The common 73.13 Ω table value rounds η0/(4π) to 30; this model retains physical constants.`}) }),
L('l3','Separate directivity, gain and efficiency',[k('u','Wire length / wavelength',.5,.1,1.25),k('eff','Radiation efficiency',90,1,100,'%')],'Why does concentrating radiation not guarantee high antenna gain?',
'Directivity describes where the radiated power goes. Radiation efficiency describes how much accepted power becomes radiation. Gain includes both effects.',
'Calculate directivity from the normalized pattern, then multiply by efficiency. Decibels turn that multiplication into addition.',
'Thin isolated wire with assumed sinusoidal current; efficiency is supplied independently. This is gain referenced to accepted power, not realized gain including feed mismatch. The length sweep ends at 1.25 wavelengths and makes no global optimality claim.',
'Change efficiency without changing length, then compare half-wave, full-wave, and 1.25-wave patterns.',p=>{const x=F.dipole(p.u),g=F.gainOf(x.directivity,p.eff/100);return O([
s('Calculate the pattern for this length','u is total wire length / wavelength, and θ is measured from the wire axis.',String.raw`F(\theta)=\frac{\cos(\pi u\cos\theta)-\cos(\pi u)}{\sin\theta}`),
s('Normalize intensity by total radiated power','Directivity is independent of a common current scale.',String.raw`D=\frac{4\pi U_{max}}{\int U\,d\Omega}`,String.raw`D=${N(x.directivity)}`),
s('Account for dissipated accepted power','The percentage efficiency must first be divided by 100.',String.raw`G=\eta D,\quad G_{dBi}=10\log_{10}D+10\log_{10}\eta`,String.raw`G=(${N(p.eff/100)})(${N(x.directivity)})=${N(g.gain)},\quad G_{dBi}=${N(g.gainDbi)}`)
],[r('Directivity',x.directivityDbi,'dBi'),r('Gain',g.gainDbi,'dBi'),r('Efficiency loss',g.lossDb,'dB')],[patternPlot(x.pattern,x.Umax)],'Efficiency scales total radiated power without changing this normalized pattern. A longer wire can also create additional lobes.',g.gainDbi,'dBi','Calculate antenna gain in dBi.','Add 10 log10(efficiency / 100) to directivity in dBi.') }),
L('l4','Build and steer an array',[k('n','Element count',4,2,12,'',1),k('spacing','Spacing / wavelength',.5,.25,1.5),k('phase','Progressive phase',0,-90,90,'degrees')],'How do element count, spacing and phase shape the beam?',
'Each element contributes a phasor with a direction-dependent path phase and an imposed feed phase. Adding these phasors produces constructive beams and destructive nulls.',
'Sum the element phasors or use the geometric-series array factor. Integrate its power pattern for directivity instead of assuming D = N at every spacing.',
'Uniform amplitudes, isotropic elements on a line, no mutual coupling. The actual element pattern must multiply the array factor for a physical antenna. Positive progressive phase uses ψ = 2πd cos θ + β, so +90° at half-wave spacing steers to 120°.',
'Double element count, then increase spacing to 1.5 wavelengths. Compare +90° and −90° steering.',p=>{const x=F.arrayFactor({n:p.n,spacingOverLambda:p.spacing,betaDeg:p.phase}),beam=x.mainBeamDeg;return O([
s('Combine path and feed phase','d here is spacing normalized to wavelength; convert the feed phase from degrees to radians.',String.raw`\psi(\theta)=2\pi d\cos\theta+\beta,\quad\beta=\beta_{deg}\pi/180`),
s('Sum the normalized field phasors','At ψ = 2πm use the continuous limiting value one.',String.raw`AF=\left|\frac1N\sum_{n=0}^{N-1}e^{jn\psi}\right|=\left|\frac{\sin(N\psi/2)}{N\sin(\psi/2)}\right|`),
s('Find the principal steering direction','The order-zero beam requires ψ = 0 and a cosine within [−1,1]. Other integer orders can create grating lobes.',String.raw`\cos\theta_0=-\beta/(2\pi d),\quad 2\pi d\cos\theta_m+\beta=2\pi m`,beam===null?String.raw`\text{No visible order-zero beam for these settings.}`:String.raw`\theta_0=${N(beam)}^\circ`),
s('Normalize the radiated power','Directivity comes from the squared factor integrated over the sphere.',String.raw`D=\frac{2\max |AF|^2}{\int_0^\pi|AF|^2\sin\theta\,d\theta}`,String.raw`D=${N(x.directivity)}`)
],[r('Directivity',x.directivity),...(beam===null?[]:[r('Order-zero beam',beam,'degrees')]),r('Other full-strength orders',x.grating.length)],[patternPlot(x.mag,x.Umax)],x.grating.length?'Additional full-strength directions exist: the array has grating lobes.':'No additional full-strength grating orders are visible for these settings.',x.directivity,'','Calculate directivity from the displayed normalized-power integral.','Use two times maximum power divided by the polar-angle integral.',{table:{headers:['Beam order','Angle from array axis (degrees)'],rows:[...(beam===null?[]:[[0,beam]]),...x.grating.map(g=>[g.order,g.thetaDeg])]}}) },[...antennaSymbols,['N,d','Element count and element spacing / wavelength.'],[String.raw`\beta,\psi`,'Progressive feed phase and total adjacent-element phase (rad).']]),
L('l5','From antenna gain to a link budget',[k('f','Frequency',2.4e9,1e8,10e9,'Hz'),k('distance','Separation',1000,.1,10000,'m'),k('power','Transmitted power',.1,.001,10,'W'),k('gt','Transmit gain',12,0,30,'dBi'),k('gr','Receive gain',2,0,30,'dBi'),k('aperture','Largest physical antenna dimension',.5,.01,3,'m')],'How much transmitted power reaches a distant matched receiver?',
'Transmit gain concentrates the outgoing power density. The receiving antenna intercepts power through its effective aperture, which depends on gain and wavelength.',
'Derive Friis from power density times effective aperture, then repeat the same calculation as a decibel link budget.',
'Free space, far field, aligned polarizations, matched ports, and no obstruction or extra losses. The guard checks distance ≥ 2D²/λ using the supplied largest antenna dimension; near-field cases are declined.',
'Double separation and predict the received-power change. Reduce separation below the displayed far-field boundary.',p=>{const gt=10**(p.gt/10),gr=10**(p.gr/10),x=F.friis({f:p.f,distance:p.distance,powerT:p.power,gainT:gt,gainR:gr,apertureT:p.aperture,apertureR:p.aperture}),ar=F.effectiveAperture(gr,x.lambda),at=F.effectiveAperture(gt,x.lambda),ok=x.guard.ok;return O([
s('Find wavelength and validate separation','Physical size D belongs in the far-field guard; effective area Ae belongs in the intercepted-power calculation.',String.raw`\lambda=c/f,\quad R_{FF}=2D^2/\lambda`,String.raw`\lambda=${N(x.lambda)}\,\mathrm m,\quad R_{FF}=${N(x.guard.fraunhofer)}\,\mathrm m`),
s('Multiply incident power density by effective aperture','Both gains must be linear power ratios for this equation.',String.raw`S=P_tG_t/(4\pi R^2),\quad A_{e,r}=G_r\lambda^2/(4\pi),\quad P_r=SA_{e,r}`,String.raw`A_{e,r}=${N(ar)}\,\mathrm{m^2}`),
s('Write the equivalent decibel budget','dBm is referenced to 1 mW; antenna gains are dBi and free-space loss is dB.',String.raw`P_{r,dBm}=10\log_{10}(P_t/10^{-3})+G_{t,dBi}+G_{r,dBi}-20\log_{10}(4\pi R/\lambda)`,ok?String.raw`P_{r,dBm}=${N(10*Math.log10(p.power/.001))}+${N(p.gt)}+${N(p.gr)}-${N(x.freeSpaceLossDb)}=${N(x.receivedDbm)}`:String.raw`R<R_{FF}:\quad\text{received-power prediction declined}`)
],[r('Far-field boundary',x.guard.fraunhofer,'m'),r('Transmit effective aperture',at*1e4,'cm²'),...(ok?[r('Free-space loss',x.freeSpaceLossDb,'dB'),r('Received power',x.receivedDbm,'dBm')]:[])],[{...curve('Far-field received power','Separation (m)','Received power (dBm)',logPoints(R=>F.friis({f:p.f,distance:R,powerT:p.power,gainT:gt,gainR:gr}).receivedDbm,Math.max(x.guard.fraunhofer,1),Math.max(10000,x.guard.fraunhofer*10))),logX:true}],x.guard.says,at*1e4,'cm²','Calculate the transmit antenna’s effective aperture in square centimetres.','Use linear transmit gain times λ²/(4π), then multiply m² by 10⁴.') },[['P_t,P_r','Transmitted and received powers (W); dBm values use a 1 mW reference.'],['G_t,G_r','Transmit and receive antenna gains as linear power ratios.'],[String.raw`\lambda,R,D`,'Wavelength, antenna separation, and largest physical antenna dimension (m).'],['A_e','Effective receiving area (m²), distinct from the physical aperture dimension.']]),
]
