import {knob as k,step as s,reading as r,curve,texnum as N,fmt} from '@ee-labs/lessons/model'
import {covarianceHistory,covarianceEnsemble} from './covariance.js'
const knobs=[k('dt','Sample interval',.1,.02,.5,'s'),k('q','Acceleration variance per interval',1,.01,10,'m²/s⁴'),k('r','Position measurement variance',.04,.001,1,'m²'),k('p0','Initial diagonal covariance scale',1,.01,10)]
const symbols=[['x_k','State column [position (m), velocity (m/s)] at sample k.'],[String.raw`\hat x_k^-,\hat x_k^+`,'Predicted estimate before the kth measurement and corrected estimate after it. Superscripts − and + indicate update stages, not negative and positive values.'],['P_k^-,P_k^+','Prediction and posterior error covariance matrices. Diagonal entries are position variance (m²) and velocity variance (m²/s²); off-diagonal entries are cross covariance (m²/s).'],['A,G,H','State transition, acceleration-input column and position-observation row.'],['q,r','Independent acceleration variance per interval (m²/s⁴) and sensor position variance (m²).'],['Q_d,K_k,S_k','Process covariance GqGᵀ, Kalman gain column, and innovation variance (m²).'],['z_k,w_k,v_k','Measured position, random acceleration and sensor noise. Both noises are zero-mean independent Gaussian variables.']]
const matrix=P=>String.raw`\begin{bmatrix}${N(P[0])}&${N(P[1])}\\${N(P[1])}&${N(P[2])}\end{bmatrix}`
function L(id,name,more,question,intro,tryText,solve){return{id,name,group:'F. Kalman covariance and ensembles',knobs:[...knobs,...more],question,intro,try:tryText,solve,symbols,flow:['Predict position and velocity','Measure position with uncertain sensor','Correct estimate and its covariance'],route:'Use a discrete state-space model for recursive estimation. The covariance route predicts uncertainty before seeing data; a seeded ensemble checks that prediction. A transfer function describes the settled linear filter, but does not show its changing startup uncertainty.',limits:'Two-state constant-velocity example following F1/F2’s observer ideas. Each interval has one independent constant random acceleration, not continuous white acceleration. The initial covariance is diagonal: scale × 1 m² and scale × 1 (m/s)². The estimator assumes the stated model and independent Gaussian noise.',...{id,name}}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,plotNote:'A covariance is an ensemble prediction. A single trajectory can lie outside its uncertainty band without disproving the model.',practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const setup=p=>s('Specify the state and sampling model','Position advances by velocity times sample interval. A random acceleration changes both position and velocity over that interval.',String.raw`x_k=Ax_{k-1}+Gw_k,\quad z_k=Hx_k+v_k,\quad A=\begin{bmatrix}1&\Delta t\\0&1\end{bmatrix},\ G=\begin{bmatrix}\Delta t^2/2\\\Delta t\end{bmatrix},\ H=\begin{bmatrix}1&0\end{bmatrix}`,String.raw`\Delta t=${N(p.dt)}\,\mathrm s,\quad Q_d=qGG^T,\quad \operatorname{Var}(v_k)=r=${N(p.r)}\,\mathrm{m^2}`)
export const EXTENDED=[
L('F3','Predict and update the covariance',[k('sample','Inspect sample',1,1,100,'',1)],'How does uncertainty change between measurements and at an update?',
'The estimator carries two objects: an estimated state and an error covariance. The prediction propagates earlier uncertainty and adds process uncertainty; the measurement then reduces uncertainty in the observed direction.',
'Inspect sample 1, then later samples. Increase sensor variance and compare the gain and posterior variance.',p=>{const x=covarianceHistory(p),h=x.history[p.sample-1];return O([
setup(p),
s('Predict covariance before the measurement','A multiplies both sides because covariance tracks products of state errors. Process uncertainty adds independently.',String.raw`P_k^-=AP_{k-1}^+A^T+Q_d`,String.raw`P_${p.sample}^-=${matrix(h.prior)}`),
s('Weight the new information','Innovation variance combines predicted position variance with sensor variance. The gain has one component for each state.',String.raw`S_k=HP_k^-H^T+r,\quad K_k=P_k^-H^T/S_k`,String.raw`S_${p.sample}=${N(h.S)},\quad K_${p.sample}=\begin{bmatrix}${N(h.K[0])}\\${N(h.K[1])}\end{bmatrix}`),
s('Correct state and uncertainty','The Joseph covariance form remains symmetric and positive semidefinite under rounding.',String.raw`\hat x_k^+=\hat x_k^-+K_k(z_k-H\hat x_k^-),\quad P_k^+=(I-K_kH)P_k^-(I-K_kH)^T+K_krK_k^T`,String.raw`P_${p.sample}^+=${matrix(h.posterior)}`)
],[r('Prior position variance',h.prior[0],'m²'),r('Posterior position variance',h.posterior[0],'m²'),r('Position gain',h.K[0])],[{label:'Position uncertainty before and after each measurement',xLabel:'Sample',yLabel:'Position error variance (m²)',traces:[{label:'Prediction',points:x.history.map(h=>({x:h.k,y:h.prior[0]}))},{label:'Corrected',points:x.history.map(h=>({x:h.k,y:h.posterior[0]}))}]}],'The measurement corrects velocity too because position and velocity errors become correlated through the prediction model.',h.posterior[0],'m²','Calculate the posterior position variance at the selected sample.','For the observed position entry, P+pp = (1 − Kp) P−pp.') }),
L('F4','When the Kalman gain settles',[],'Why can a constant gain eventually replace the changing startup gain?',
'With fixed dynamics and noise statistics, the covariance map approaches a fixed point. That limit gives a constant gain, while the transient recursion remains important when initial uncertainty is different.',
'Change initial covariance scale and observe that the limiting gain stays the same. Then change the process or sensor variance.',p=>{const x=covarianceHistory(p),st=x.steady;return O([
setup(p),
s('Write the covariance fixed-point equation','A steady posterior covariance reproduces itself after one complete prediction and correction.',String.raw`P_\infty^-=AP_\infty^+A^T+Q_d,\quad P_\infty^+=P_\infty^--\frac{P_\infty^-H^THP_\infty^-}{HP_\infty^-H^T+r}`,String.raw`P_\infty^+=${matrix(st.posterior)}`),
s('Calculate the settled gain','The gain is determined by the steady covariance and sensor variance, not by the measurement values.',String.raw`K_\infty=P_\infty^-H^T/(HP_\infty^-H^T+r)`,String.raw`K_\infty=\begin{bmatrix}${N(st.K[0])}\\${N(st.K[1])}\end{bmatrix}`),
s('Check convergence instead of assuming it','Iteration stops when the largest covariance-entry change is below 10⁻¹² times the larger of one and the largest covariance magnitude. The state variables use the fixed SI scales stated above.',String.raw`\|P_{next}-P\|_{max}<10^{-12}\max(1,\|P\|_{max})`,String.raw`iterations=${x.iterations},\quad residual=${N(x.residual)}`)
],[r('Settled position gain',st.K[0]),r('Settled velocity gain',st.K[1],'s⁻¹'),r('Steady position variance',st.posterior[0],'m²')],[{label:'Startup gain approaches its steady value',xLabel:'Sample',yLabel:'Position gain',traces:[{label:'Recursive gain',points:x.history.map(h=>({x:h.k,y:h.K[0]}))},{label:'Steady gain',points:x.history.map(h=>({x:h.k,y:st.K[0]})),dashed:true}]}],'A constant gain is appropriate once the covariance has settled and the assumed statistics remain fixed. It need not represent startup or changing sensor quality.',st.K[0],'','Calculate the settled position gain.','Divide the steady predicted position variance by that variance plus r.') }),
L('F5','Check uncertainty with an ensemble',[k('runs','Independent trajectories',500,100,3000,'',1),k('seed','Reproducible seed',42,1,1000,'',1),k('actualScale','Actual / assumed sensor variance',1,.25,4)],'Does the measured spread of estimation errors agree with the covariance prediction?',
'Many independent trajectories share the same filter assumptions and initial distribution. Their estimation errors provide a sample variance that can be compared with the predicted covariance, with sampling uncertainty stated.',
'Increase ensemble size, then change the seed. Set actual sensor variance to four times the assumed value to reveal overconfidence.',p=>{const x=covarianceEnsemble(p),last=x.history.at(-1),pos=x.position;return O([
setup(p),
s('Generate independent realizations','Each run draws an initial state from the stated covariance, then independent acceleration and sensor noise at each interval. The seed makes the experiment reproducible.',String.raw`w_k\sim\mathcal N(0,q),\quad v_k\sim\mathcal N(0,\alpha r)`,String.raw`M=${p.runs},\quad\alpha=${N(p.actualScale)}`),
s('Measure errors across runs at sample 100','This is variance across independent runs at one time, not time variance along a single nonstationary trajectory.',String.raw`e_m=\hat p_m-p_m,\quad\bar e=M^{-1}\sum_m e_m,\quad s_e^2=\frac1{M-1}\sum_m(e_m-\bar e)^2`,String.raw`s_e^2=${N(pos.variance)}\,\mathrm{m^2},\quad P_{pp,100}^+=${N(last.posterior[0])}\,\mathrm{m^2}`),
s('Attach a confidence interval to the measured variance','For independent Gaussian errors, the scaled sample variance has a chi-square distribution with M−1 degrees of freedom.',String.raw`CI_{95\%}=\left[\frac{(M-1)s_e^2}{\chi^2_{.975,M-1}},\frac{(M-1)s_e^2}{\chi^2_{.025,M-1}}\right]`,String.raw`CI_{95\%}=[${N(pos.ci[0])},${N(pos.ci[1])}]\,\mathrm{m^2}`)
],[r('Predicted position variance',last.posterior[0],'m²'),r('Measured position variance',pos.variance,'m²'),r('95% lower limit',pos.ci[0],'m²'),r('95% upper limit',pos.ci[1],'m²')],[{label:'One trajectory: estimate and truth',xLabel:'Sample',yLabel:'Position (m)',traces:[{label:'True position',points:x.first.map(h=>({x:h.k,y:h.position}))},{label:'Measured position',points:x.first.map(h=>({x:h.k,y:h.measurement})),dashed:true},{label:'Estimate',points:x.first.map(h=>({x:h.k,y:h.estimate}))}]},{label:'Ensemble variance versus covariance prediction',xLabel:'Sample',yLabel:'Position error variance (m²)',traces:[{label:'Measured ensemble variance',points:x.variance.map((v,i)=>({x:i+1,y:v}))},{label:'Predicted covariance',points:x.history.map(h=>({x:h.k,y:h.posterior[0]}))}]}],p.actualScale===1?'With a correctly specified model, measured spread should agree within sampling uncertainty. A 95% interval does not cover the true value on every random seed.':'The sensor variance differs from the estimator’s assumption. More trajectories improve the measurement of this mismatch; they do not correct the filter model.',last.posterior[0],'m²','Calculate the model’s predicted position variance at sample 100.','Use the covariance recursion with the assumed r, even when the actual sensor variance differs.',{table:{headers:['State error at sample 100','Predicted variance','Measured variance','95% lower','95% upper'],rows:[['Position (m²)',last.posterior[0],pos.variance,...pos.ci],['Velocity (m²/s²)',last.posterior[2],x.velocity.variance,...x.velocity.ci]]},check:`Mean position error ${fmt(pos.bias.value)} m; approximate 95% mean interval [${fmt(pos.bias.ci[0])}, ${fmt(pos.bias.ci[1])}] m.`}) }),
]
