import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {nominalParts,section,corners,toleranceRuns,yields,canon,methodDrawing} from './designMethods.js'
const T=String.raw,tol=k('tolerance','Part tolerance or three-sigma spread',.01,.001,.05),seed=k('seed','Ensemble seed',7,1,999,'',1),runs=k('runs','Number of simulated circuits',2000,200,10000,'',1)
const symbols=[[T`R_1,R_2,C_1,C_2`,'Sallen–Key resistances (Ω) and capacitances (F). Nominal R1=R2=1 kΩ, C1=2.25079 nF, C2=1.12540 nF. C1 returns to the follower output.'],[T`f_0,Q,f_c,s`,'Ideal natural frequency (Hz), ideal quality factor, finite-follower −3 dB cutoff relative to DC (Hz), and Laplace variable (s⁻¹).'],[T`p_i,\delta_i,S_{p_i}^y,t,\sigma`,'A component value, its fractional error, normalized sensitivity of output y to that component, tolerance fraction, and fractional standard deviation. Here t denotes tolerance, not time.']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'I. Sensitivity, corners, yield and datasheet calculations',knobs,question,intro,try:attempt,solve,symbols,flow:['Define the circuit and uncertainty model','Work through derivatives, bounds or probabilities','Check the design and state what the result guarantees'],route:'Circuit equations give each nominal or perturbed response. Sensitivity differentiates that response; corners examine a bounded set; Monte Carlo estimates probabilities under a specified distribution. These answer different design questions and can be used together.',limits:'Ideal passives and a declared follower model. Statistical results require the stated independent component distributions. Neither a finite random sample nor a corner table proves bounds for an arbitrary nonlinear output.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const cdf=(data,key)=>[...data].sort((a,b)=>a[key]-b[key]).map((v,i)=>({x:100*i/(data.length-1),y:100*v[key]})).filter((_,i)=>i%Math.max(1,Math.floor(data.length/200))===0||i===data.length-1)
export const DESIGN_METHOD_LESSONS=[
L('i1','Sensitivity: identify which part changes the result',[k('rf','Amplifier feedback resistance',10000,1000,100000,'Ω'),k('rg','Amplifier ground resistance',1000,100,10000,'Ω'),k('error','One-part fractional change',.01,-.05,.05)],
 'Which tolerance should you tighten for gain, frequency or Q?',
 'A sensitivity is a local derivative, not a component tolerance. Multiply it by a small fractional part change to predict a fractional output change. An ideal non-inverting amplifier and the ideal Sallen–Key filter show why the same part can matter differently to different outputs.',
 'Compare the exact gain change with its linear prediction. Then inspect why equal filter resistors have zero first-order Q sensitivity even though each changes f0.',p=>{const gain=1+p.rf/p.rg,S=(gain-1)/gain,x=section(),exact=(1+p.rf/p.rg*(1+p.error))/gain-1;return O([
 s('Define a dimensionless derivative','The derivative has output units per component unit. Multiplying by p/y removes both units.',T`S_p^y=\frac{p}{y}\frac{\partial y}{\partial p},\quad \frac{\Delta y}{y}\simeq S_p^y\frac{\Delta p}{p}`,T`\delta=${N(p.error)},\quad100\delta=${N(p.error*100)}\%`),
 s('Differentiate the amplifier equation','For an ideal non-inverting amplifier, increasing Rf raises gain; increasing Rg lowers it. Only the Rf finite change is applied here.',T`A=1+R_f/R_g,\quad S_{R_f}^A=(A-1)/A,\quad S_{R_g}^A=-(A-1)/A`,T`A=1+${N(p.rf)}/${N(p.rg)}=${N(gain)},\quad S_{R_f}^A=${N(S)},\quad S_{R_g}^A=${N(-S)}`),
 s('Substitute the selected change','The Rf-only change is exactly linear at fixed Rg. Simultaneous changes or a finite Rg change need the original ratio.',T`\Delta A/A=S_{R_f}^A\delta`,T`\Delta A/A=${N(S)}(${N(p.error)})=${N(exact*100)}\%`),
 s('Differentiate the filter denominator','For an ideal unity follower, the denominator is 1+sC2(R1+R2)+s²R1R2C1C2. Natural frequency is not generally the −3 dB cutoff.',T`f_0=\frac1{2\pi\sqrt{R_1R_2C_1C_2}},\quad Q=\frac{\sqrt{R_1R_2C_1/C_2}}{R_1+R_2}`,T`f_0=${N(x.f0)}\,Hz,\quad Q=${N(x.q)}`),
 s('Rank sensitivities for the actual output','Every part has frequency sensitivity −1/2. Equal resistors cancel their own first-order Q effects; the capacitor ratio remains.',T`\mathbf S^{f_0}=(-1/2,-1/2,-1/2,-1/2),\quad\mathbf S^Q=(1/2-R_1/(R_1+R_2),1/2-R_2/(R_1+R_2),1/2,-1/2)`,T`\mathbf S^Q=(0,0,1/2,-1/2)\quad\text{at matched resistors}`)
 ],[r('Amplifier gain',gain),r('Feedback-resistor sensitivity',S),r('Selected gain change',exact*100,'%')],[curve('Exact gain change when only Rf changes','Rf change (%)','Gain change (%)',samples(e=>100*((1+p.rf/p.rg*(1+e/100))/gain-1),-5,5))],
 'Tighten tolerances according to the output that must pass. Zero first-order sensitivity does not mean immunity to large changes or to interactions.',S,'','Calculate normalized gain sensitivity to Rf.','Use (A−1)/A.',{schematic:methodDrawing(),table:{headers:['Filter part','Sensitivity of f0','Sensitivity of Q'],rows:['R1','R2','C1','C2'].map((v,i)=>[v,fmt(x.sf[i]),fmt(x.sq[i])])}})}, {symbols:[...symbols,[T`A,R_f,R_g,\Delta y`,'Ideal amplifier gain, feedback and ground resistances (Ω), and finite change in an output.']]}),
L('i2','Corners: a box needs a monotonicity argument',[tol,k('gbw','Follower gain-bandwidth product',1e6,.5e6,1.5e6,'Hz')],
 'When do sixteen corner calculations bound the whole component box?',
 'Four independent bounded passive values give 2⁴=16 vertices. The natural frequency decreases with every part, so its extrema are provably at opposite corners. The finite-follower cutoff table is a set of evaluated vertices, not a proof of a global bound.',
 'Increase tolerance and find the lowest cutoff vertex. Inspect Q while varying R1 through its box face: the interior is higher than both endpoints.',p=>{const x=corners(p),b=x.base,tau=b.h/(2*Math.PI*p.gbw);return O([
 s('Enumerate the parameter box','A sign vector chooses the low or high value for each passive. GBW is held at the selected value for this sixteen-vertex table.',T`p_i=p_{i0}(1+\epsilon_i t),\quad\epsilon_i\in\{-1,+1\},\quad N_v=2^4=16`,T`t=${N(p.tolerance)},\quad GBW=${N(p.gbw/1e6)}\,MHz`),
 s('Prove the natural-frequency bounds','The four normalized derivatives are negative everywhere for positive parts. All-high components minimize f0; all-low maximize it.',T`f_{0,min}=f_{0,nom}/(1+t)^2,\quad f_{0,max}=f_{0,nom}/(1-t)^2`,T`f_{0,min}=${N(x.fLow/1000)}\,kHz,\quad f_{0,max}=${N(x.fHigh/1000)}\,kHz`),
 s('Retain finite follower dynamics for cutoff','Use h=100000/100001, τ=h/(2πGBW), a=R1R2C1C2, b=C2(R1+R2), d=R1C1. This is a cubic response, not an ideal second-order shortcut.',T`H(s)=\frac h{1+[b+\tau+d(1-h)]s+[a+(b+d)\tau]s^2+a\tau s^3}`,T`\tau=${N(tau*1e9)}\,ns,\quad |H(j2\pi f_c)|=h/\sqrt2`),
 s('Report exactly what was searched','Find the half-power root separately at each vertex. The lowest value in this table is a vertex result; no monotonicity proof for fc is asserted.',T`f_{c,vertex,min}=\min_{\epsilon\in\{-1,+1\}^4} f_c(\epsilon)`,T`f_{c,vertex,min}=${N(x.worst.fc/1000)}\,kHz`),
 s('Catch an interior maximum on a face','Hold R2,C1,C2 nominal and vary R1. Q is stationary at R1=R2 and is lower at either endpoint, so endpoint-only reasoning misses this face maximum.',T`\frac{\partial\ln Q}{\partial\ln R_1}=\frac12-\frac{R_1}{R_1+R_2}=0\iff R_1=R_2`,T`Q_{left}=${N(x.qEnds[0])},\quad Q_{center}=${N(x.qFace)},\quad Q_{right}=${N(x.qEnds[1])}`)
 ],[r('Guaranteed lowest ideal f0',x.fLow/1000,'kHz'),r('Lowest evaluated finite cutoff',x.worst.fc/1000,'kHz')],[curve('Face check: Q is highest at an interior R1','R1 change (%)','Ideal Q',x.face)],
 'A corner table is evidence about the evaluated points. A global bound additionally needs monotonicity or a suitable bounded search. A Gaussian distribution has no hard tolerance box.',x.fLow/1000,'kHz','Calculate the guaranteed lowest ideal natural frequency.','Divide nominal f0 by (1+t)².',{schematic:methodDrawing(nominalParts,p.gbw),table:{headers:['R1 R2 C1 C2 signs','Ideal f0 (kHz)','Ideal Q','Finite fc (kHz)'],rows:x.vertices.map(v=>[v.signs.map(s=>s>0?'+':'−').join(' '),fmt(v.f0/1000),fmt(v.q),fmt(v.fc/1000)])}})}, {symbols:[...symbols,[T`h,\tau,a,b,d,\epsilon_i,N_v`,'Follower DC gain and time constant (s); a (s²), b and d (s), component endpoint signs, and number of vertices.']]}),
L('i3','Monte Carlo: a spread is not a worst case',[tol,runs,seed],
 'How do component distributions become frequency and Q distributions?',
 'Read the selected tolerance as three standard deviations of independent, zero-mean Gaussian fractional component errors. This unbounded statistical model differs from the hard box in I2. Each simulated circuit is evaluated with the exact ideal f0 and Q equations, then compared with first-order predictions.',
 'Change the seed, then increase the sample count. The estimates fluctuate, while the analytic first-order sigmas stay fixed. Large spreads make nonlinear bias easier to see.',p=>{const x=toleranceRuns(p),approxSeF=x.predF/Math.sqrt(2*(p.runs-1)),approxSeQ=x.predQ/Math.sqrt(2*(p.runs-1));return O([
 s('Translate three sigma into a distribution','The seeded xoshiro generator supplies independent Gaussian draws. A stated ±t manufacturing bound would require a different model.',T`\delta_i\sim\mathcal N(0,\sigma_p^2),\quad\sigma_p=t/3,\quad p_i=p_{i0}(1+\delta_i)`,T`\sigma_p=${N(x.sigma*100)}\%,\quad N=${p.runs}`),
 s('Propagate frequency error to first order','All four independent contributions enter with coefficient −1/2. Add their variances, not their standard deviations.',T`\delta_f\simeq-\tfrac12(\delta_{R1}+\delta_{R2}+\delta_{C1}+\delta_{C2}),\quad\sigma_f^2=4(1/2)^2\sigma_p^2`,T`\sigma_f=${N(x.predF*100)}\%`),
 s('Propagate Q error at matched resistors','The two resistor derivatives vanish at the nominal point. Capacitor errors enter with opposite signs.',T`\delta_Q\simeq\tfrac12(\delta_{C1}-\delta_{C2}),\quad\sigma_Q=\sigma_p/\sqrt2`,T`\sigma_Q=${N(x.predQ*100)}\%`),
 s('Measure the nonlinear sample spread','Compute each circuit with the original equations. The sample standard deviation uses N−1; its mean can shift because products and ratios are nonlinear.',T`s_y=\sqrt{\frac{\sum_{j=1}^N(y_j-\bar y)^2}{N-1}},\quad SE(\bar y)=s_y/\sqrt N`,T`s_f=${N(x.fs.sd*100)}\%,\quad s_Q=${N(x.qs.sd*100)}\%,\quad\bar\delta_f=${N(x.fs.mean*100)}\%`),
 s('Put the corner and estimator uncertainty in context','For nearly Gaussian outputs, the first-order standard error of a measured sigma is σ/√[2(N−1)]. Exact endpoint events have probability zero in a continuous distribution.',T`SE(s)\simeq\sigma/\sqrt{2(N-1)},\quad \delta_{f,box,max}=(1-t)^{-2}-1`,T`SE(s_f)\simeq${N(approxSeF*100)}\%,\quad\delta_{f,box,max}=${N(x.cornerHigh*100)}\%`),
 s('Check the linear approximation on this ensemble','Normalize RMS exact-minus-linear error by predicted output sigma. The learning check flags either residual above 1% of that sigma; this is a sample diagnostic, not a global bound.',T`D_y=\frac{\sqrt{N^{-1}\sum_j(\delta_{y,j}-\delta_{y,j,linear})^2}}{\sigma_{y,linear}},\quad D_y\le0.01`,T`D_f=${N(x.residualF*100)}\%,\quad D_Q=${N(x.residualQ*100)}\%`)
 ],[r('Measured frequency sigma',x.fs.sd*100,'%'),r('Measured Q sigma',x.qs.sd*100,'%'),r('Predicted frequency sigma',x.predF*100,'%')],[curve('Empirical frequency-error quantiles','Empirical percentile (%)','Frequency error (%)',cdf(x.data,'f')),curve('Empirical Q-error quantiles','Empirical percentile (%)','Q error (%)',cdf(x.data,'q'))],
 `${x.linearCheck?'The sample linearization check is within 1% of predicted sigma.':'The sample linearization residual exceeds 1% of predicted sigma; use the exact circuit samples for quantitative decisions.'} Monte Carlo describes this assumed population and seed, not a guaranteed worst case. The curves are empirical quantiles. First-order sigma uncertainty is approximate when nonlinear outputs depart from Gaussian.`,x.predQ*100,'%','Calculate first-order Q sigma as a percentage.','Divide t by 3√2, then multiply by 100.',{schematic:methodDrawing(),table:{headers:['Output','Predicted sigma (%)','Measured sigma (%)','Approx. SE of sigma (%)','Mean error ± approx. 95% interval (%)'],rows:[['f0',fmt(x.predF*100),fmt(x.fs.sd*100),fmt(approxSeF*100),`${fmt(x.fs.mean*100)} ± ${fmt(1.96*x.fs.se*100)}`],['Q',fmt(x.predQ*100),fmt(x.qs.sd*100),fmt(approxSeQ*100),`${fmt(x.qs.mean*100)} ± ${fmt(1.96*x.qs.se*100)}`]]}})}, {symbols:[...symbols,[T`N,j,\bar y,s_y,SE,\mathcal N,D_y`,'Sample count and index, sample mean, sample standard deviation, standard error of an estimator, Gaussian distribution, and RMS linearization residual normalized by predicted sigma. Fractional output errors are relative to the nominal circuit.']]}),
L('i4','Yield: count passes and show the uncertainty',[tol,runs,seed,k('fLimit','Allowed fractional natural-frequency error',.01,.001,.03),k('qLimit','Allowed fractional Q error',.005,.001,.03)],
 'What fraction of circuits pass both requirements, and how precisely is it known?',
 'Use the same seeded population as I3. Compare three objects: exact ideal-circuit pass counts, pass counts from the linearized outputs, and the closed-form Gaussian prediction for those linearized outputs. Independence is justified only for the stated first-order Gaussian model.',
 'Tighten the Q limit, then widen both limits until every sample passes. Notice that the confidence interval still has width.',p=>{const x=yields(p),joint=x.exact[2];return O([
 s('State both acceptance events','The windows are centered on nominal f0 and Q. A sample must satisfy both inequalities to count as a joint pass.',T`|f_0/f_{0,nom}-1|\le a_f,\quad|Q/Q_{nom}-1|\le a_Q`,T`a_f=${N(p.fLimit*100)}\%,\quad a_Q=${N(p.qLimit*100)}\%`),
 s('Integrate the linear Gaussian predictions','A centered Gaussian lies inside ±a with probability erf[a/(√2σ)]. These probabilities apply to first-order errors.',T`Y_f=\operatorname{erf}\frac{a_f}{\sqrt2\sigma_f},\quad Y_Q=\operatorname{erf}\frac{a_Q}{\sqrt2\sigma_Q}`,T`Y_f=${N(x.analytic[0]*100)}\%,\quad Y_Q=${N(x.analytic[1]*100)}\%`),
 s('Justify the product before using it','The capacitor sum in frequency and capacitor difference in Q have zero covariance when all four errors are independent with equal Gaussian variance. Joint Gaussianity then gives independence. Nonlinear ratios do not inherit that proof.',T`\operatorname{Cov}(\delta_f,\delta_Q)=(-1/2)(1/2)\sigma_p^2+(-1/2)(-1/2)\sigma_p^2=0`,T`Y_{both,linear}=Y_fY_Q=${N(x.analytic[2]*100)}\%`),
 s('Count actual simulated passes','Use the exact ideal-circuit result for every draw. This is a binomial estimate conditional on the assumed component model.',T`\hat Y=k/N,\quad SE(\hat Y)=\sqrt{\hat Y(1-\hat Y)/N}`,T`\hat Y_{both}=${joint.k}/${joint.n}=${N(joint.value*100)}\%,\quad SE=${N(joint.se*100)}\text{ percentage points}`),
 s('Use a Wilson interval even with zero failures','For z=1.959964, form center c and half-width w. A 95% interval quantifies sampling uncertainty, not uncertainty in the chosen process model. The three intervals are pointwise, not simultaneous.',T`c=\frac{\hat Y+z^2/(2N)}{1+z^2/N},\quad w=\frac{z\sqrt{\hat Y(1-\hat Y)/N+z^2/(4N^2)}}{1+z^2/N}`,T`CI_{both,95\%}=[${N(joint.ci[0]*100)},${N(joint.ci[1]*100)}]\%`)
 ],[r('Exact-circuit joint yield estimate',joint.value*100,'%'),r('Linear-model joint prediction',x.analytic[2]*100,'%'),r('Joint 95% lower bound',joint.ci[0]*100,'%')],[curve('Exact-circuit cumulative joint pass fraction','Simulated circuits','Joint passes (%)',Array.from({length:40},(_,i)=>{const n=Math.round(p.runs*(i+1)/40);return{x:n,y:100*x.data.slice(0,n).filter(v=>Math.abs(v.f)<=p.fLimit&&Math.abs(v.q)<=p.qLimit).length/n}}))],
 'More samples reduce sampling uncertainty but do not repair a wrong distribution, correlation assumption or circuit model. The analytic product belongs to the linear Gaussian comparison; the exact joint yield is counted directly.',x.analytic[2]*100,'%','Calculate the first-order joint yield prediction.','Multiply the two analytic marginal probabilities, then convert to percent.',{table:{headers:['Requirement','Linear prediction (%)','Linear sample (%)','Circuit sample (%)','Circuit 95% CI (%)'],rows:['f0','Q','Both'].map((v,i)=>[v,fmt(x.analytic[i]*100),fmt(x.linear[i].value*100),fmt(x.exact[i].value*100),x.exact[i].ci.map(y=>fmt(y*100)).join(' to ')])}})}, {symbols:[...symbols,[T`a_f,a_Q,Y,\hat Y,k,N,z,c,w,CI`,'Fractional acceptance limits, population yield, estimated yield, passing count, total sample count, normal coverage factor, Wilson center/half-width, and confidence interval.'],[T`\operatorname{erf},\operatorname{Cov}`,'Gaussian error function and covariance.']]}),
L('i5','Datasheet calculations: reproduce a number with its conditions',[k('gain','741 ideal noise gain',11,2,101),k('peak','NE5532 output sine peak',10,1,10,'V'),k('bandwidth','Rectangular noise bandwidth',20000,1000,100000,'Hz'),k('lower','LM317 lower programming resistor',720,240,2000,'Ω'),k('cap','555 timing capacitor',10e-9,1e-9,100e-9,'F')],
 'Which datasheet field and model assumption produced each estimate?',
 'These are four separate circuits, not a composite device model. Use typical values under the cited conditions, state each approximation, and calculate the resulting circuit behavior. A headline calculation cannot certify every datasheet limit.',
 'Double noise bandwidth and compare RMS noise. Then change the LM317 programming resistor and see both the ideal ratio term and adjust-current correction change.',p=>{const x=canon(p);return O([
 s('741: distinguish a one-pole estimate from a guarantee','Use typical GBW=1 MHz from the linked TI LM741 product table in a one-pole approximation. The Rev D LM741 slew field applies at ±15 V, 25°C and unity gain. Divide by ideal noise gain; the 0.5 V/µs typical slew field is a separate large-signal limit.',T`f_{CL}\simeq GBW/A_N`,T`f_{CL}\simeq10^6/${N(p.gain)}=${N(x.corner/1000)}\,kHz`),
 s('555: derive timing from threshold ratios','For the ideal VCC/3 and 2VCC/3 thresholds, recurring charge and discharge times give the frequency. RA=RB=10 kΩ; startup was treated separately in H1.',T`f=\frac1{\ln2(R_A+2R_B)C}`,T`f=\frac1{\ln2(10000+20000)(${N(p.cap)})}=${N(x.timer/1000)}\,kHz`),
 s('LM317: retain the adjust-pin current','Use typical Vref=1.25 V and Iadj=50 µA from the linked TI sheet. Rupper=240 Ω. The regulator must separately satisfy load, headroom and thermal conditions.',T`V_o=V_{ref}(1+R_{lower}/R_{upper})+I_{adj}R_{lower}`,T`V_o=${N(x.idealVoltage)}+${N(x.adjust)}=${N(x.voltage)}\,V`),
 s('NE5532: use the cited revision rather than a family memory','TI SLOS075K (December 2025), ±15 V and 25°C, lists typical unity-gain slew 5 V/µs. This gives a necessary slope limit, not a distortion specification.',T`f_{full}\le SR/(2\pi V_p)`,T`f_{full}\le\frac{5\times10^6}{2\pi(${N(p.peak)})}=${N(x.fullPower/1000)}\,kHz`),
 s('Integrate a declared white-noise approximation','The same sheet gives typical input voltage-noise density 5 nV/√Hz at 1 kHz. Extending that value over a rectangular bandwidth is a model assumption; it omits low-frequency excess noise, input-current noise and resistor noise.',T`v_{n,rms}=e_n\sqrt B`,T`v_{n,rms}=5\times10^{-9}\sqrt{${N(p.bandwidth)}}=${N(x.noise*1e6)}\,\mu V`)
 ],[r('741 estimated corner',x.corner/1000,'kHz'),r('555 periodic frequency',x.timer/1000,'kHz'),r('LM317 programmed voltage',x.voltage,'V'),r('NE5532 voltage-noise estimate',x.noise*1e6,'µV rms')],[curve('White voltage-noise estimate versus bandwidth','Noise bandwidth (kHz)','Input noise (µV rms)',samples(b=>5e-9*Math.sqrt(b*1000)*1e6,1,100))],
 'Keep the part, datasheet revision, field, test conditions and approximation attached to every number. These calculations use typical behavior; they do not establish production minimum/maximum performance.',x.voltage,'V','Calculate LM317 voltage including adjust current.','Add 50 µA times Rlower to 1.25(1+Rlower/240).',{table:{headers:['Separate circuit','Source input / assumption','Calculated result'],rows:[['LM741','1 MHz one-pole approximation',`${fmt(x.corner/1000)} kHz`],['555','Ideal 1/3 and 2/3 thresholds',`${fmt(x.timer/1000)} kHz`],['LM317','1.25 V, 50 µA typical',`${fmt(x.voltage)} V`],['NE5532','5 V/µs, 5 nV/√Hz typical',`${fmt(x.fullPower/1000)} kHz; ${fmt(x.noise*1e6)} µV rms`]]}})}, {symbols:[[T`A_N,GBW,f_{CL},SR,V_p,f_{full}`,'Ideal noise gain, gain-bandwidth product (Hz), closed-loop corner estimate (Hz), slew rate (V/s), sine peak (V), and necessary full-power frequency limit (Hz).'],[T`V_{ref},I_{adj},R_{upper},R_{lower},V_o`,'Regulator reference (V), adjust current (A), programming resistances (Ω) and output (V).'],[T`e_n,B,v_{n,rms},R_A,R_B,C`,'Voltage-noise density (V/√Hz), rectangular noise bandwidth (Hz), RMS voltage noise (V), timer resistances (Ω), and capacitor (F).']],sources:[['TI LM741 product table: typical GBW','https://www.ti.com/product/LM741'],['TI LM741 Rev D','https://www.ti.com/lit/ds/symlink/lm741.pdf'],['TI xx555 timer','https://www.ti.com/lit/ds/symlink/ne555.pdf'],['TI LM317 Rev Z','https://www.ti.com/lit/ds/symlink/lm317.pdf'],['TI NE5532 Rev K','https://www.ti.com/lit/ds/symlink/ne5532.pdf']]}),
]
