import {FRONTEND_LESSONS} from './frontendLessons.js'
import {REGULATOR_LESSONS} from './regulatorLessons.js'
import {PRECISION_LESSONS} from './precisionLessons.js'
import {STABILITY_LESSONS} from './stabilityLessons.js'
import {knob as k,step as s,reading as r,curve,samples,texnum as N} from '@ee-labs/lessons/model'
import {PARTS,amplifier,ampSchematic,slewTrace,filter,filterSchematic,inputNoise,offset,supply} from './models.js'
const choose={...k('part','Amplifier class',0,0,5,'',1),options:PARTS.map(p=>p.name)},gain=k('gain','Noise gain 1 + Rf/Rg',11,2,101),Rs=k('resistance','Source resistance',1e5,100,1e6,'Ω'),B=k('bandwidth','Noise bandwidth',2e4,100,1e5,'Hz')
const symbols=[['V_{in},V_{out}','Input and output node voltages relative to ground (V).'],['A_0,G_N','DC open-loop voltage gain (100,000) and noise gain 1 + Rf/Rg (dimensionless).'],['GBW,f_c','Gain-bandwidth product and closed-loop −3 dB frequency (Hz).'],['SR','Output slew-rate limit (V/s).'],['e_n,i_n','Input voltage-noise (V/√Hz) and current-noise (A/√Hz) amplitude densities.'],['R_s,B,k_B,T','Source resistance (Ω), one-sided noise bandwidth (Hz), Boltzmann constant 1.380649×10⁻²³ J/K, and absolute temperature (K).'],['V_{OS},I_B','Input offset voltage (V) and input bias current (A).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'A. Read the limits of a real amplifier',knobs,question,intro,try:attempt,solve,symbols,flow:['Choose a device class and operating condition','Calculate the limiting mechanism','Compare the result with the design requirement'],route:'Use a transfer function or phasor for linear frequency response. Use the time-domain state model for slew and settling. Noise powers and DC error budgets require their own calculations; a gain plot alone cannot answer them.',limits:'Six illustrative curriculum classes, not manufacturer part specifications or SPICE models. Parameters isolate tradeoffs; consult a current datasheet before choosing a physical part. Noise is white, uncorrelated and input-referred; flicker noise is omitted.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,plotNote:'Change one setting, predict the direction, and compare the plotted response with the calculated results.',practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const table=()=>({headers:['Class index and model','GBW (MHz)','SR (V/μs)','Voltage noise (nV/√Hz)','Bias current (nA)'],rows:PARTS.map((p,i)=>[`${i}: ${p.name}`,p.gbw/1e6,p.sr/1e6,p.en/1e-9,p.ib/1e-9])})
export const EXTENDED=[
L('a1','Choose the amplifier by its limits',[choose,gain],'Why can two amplifiers with the same resistor gain behave differently?',
'The resistor ratio specifies a target. Finite open-loop gain and a dominant pole determine the actual low-frequency gain and bandwidth. Explore six stated class models and compare their other limits before calling one “better”.',
'Select each class at gain 11. Then double the resistor-defined gain and predict bandwidth.',p=>{const x=amplifier(p);return O([
s('Close the feedback loop','The divider feeds back Vout/GN. Substitute that voltage into the op-amp equation and collect the output terms.',String.raw`V_{out}=A(s)[V_{in}-V_{out}/G_N],\quad H(s)=\frac{A(s)}{1+A(s)/G_N}`,String.raw`G_N=${N(p.gain)},\quad A_0=10^5`),
s('Keep the finite DC gain','The ideal resistor gain is approached as A0 becomes large compared with GN.',String.raw`H(0)=\frac{A_0}{1+A_0/G_N}`,String.raw`H(0)=\frac{100000}{1+100000/${N(p.gain)}}=${N(x.dc)}`),
s('Find the pole of the closed loop','With A(s)=A0/(1+s A0/(2πGBW)), collecting powers of s gives a single closed-loop pole.',String.raw`H(s)=\frac{H(0)}{1+s/(2\pi f_c)},\quad f_c=GBW(1/A_0+1/G_N)`,String.raw`f_c=${N(x.fc/1000)}\,\mathrm{kHz},\quad GBW/G_N\simeq${N(x.gbw/p.gain/1000)}\,\mathrm{kHz}`)
],[r('DC voltage gain',x.dc),r('Bandwidth',x.fc/1000,'kHz')],[{...curve(`${x.name}: small-signal response`,'Frequency (Hz)','Gain (dB)',Array.from({length:161},(_,i)=>{const f=10**(1+7*i/160);return{x:f,y:20*Math.log10(x.dc/Math.hypot(1,f/x.fc))}})),logX:true}],`${x.name} gives the displayed linear bandwidth. Its slew, noise and bias-current limits still need separate checks.`,x.fc/1000,'kHz','Calculate the finite-A0 closed-loop bandwidth.','Multiply GBW by (1/A0 + 1/GN).',{schematic:ampSchematic(p),table:table()})}),
L('a2','Finite bandwidth changes an active filter',[k('gbw','Amplifier GBW',1e6,.5e6,20e6,'Hz'),k('f0','Ideal filter frequency',1e5,1e4,2e5,'Hz')],'Why does a unity-gain Sallen–Key filter miss its ideal cutoff?',
'Two resistor-capacitor sections and an op-amp follower form a second-order low-pass filter only when the follower is ideal. Its finite pole introduces a third state and changes both cutoff and peaking.',
'Increase GBW from 1 MHz to 20 MHz and watch the response approach the ideal design.',p=>{const x=filter(p),[c0,c1,c2,c3]=x.c;return O([
s('Choose the ideal component ratios','For equal 1 kΩ resistors, C1 = 2C2 gives a Butterworth Q of 1/√2 when the follower is ideal.',String.raw`C_2=\frac1{2\pi f_0R\sqrt2},\quad C_1=2C_2,\quad Q=\frac{\sqrt{C_1C_2}}{2C_2}`,String.raw`C_1=${N(x.C1*1e9)}\,\mathrm{nF},\quad C_2=${N(x.C2*1e9)}\,\mathrm{nF}`),
s('Write the two node equations and follower constraint','Node a joins both resistors and C1 to the output; node b joins R2, C2 to ground and the non-inverting input.',String.raw`\frac{V_a-V_{in}}R+\frac{V_a-V_b}R+sC_1(V_a-V_{out})=0,\quad\frac{V_b-V_a}R+sC_2V_b=0,\quad V_{out}=h(s)V_b`),
s('Eliminate the internal voltages','Define a = R²C1C2, b = 2RC2 and h(s)=h0/(1+sτ). The resulting cubic denominator makes the extra amplifier state visible.',String.raw`H(s)=\frac{h_0}{1+c_1s+c_2s^2+c_3s^3},\quad c_1=b+\tau+RC_1(1-h_0),\ c_2=a+b\tau+RC_1\tau,\ c_3=a\tau`,String.raw`H(s)=\frac{${N(x.h)}}{${N(c0)}+(${N(c1)})s+(${N(c2)})s^2+(${N(c3)})s^3}`),
s('Measure the cutoff relative to the actual DC gain','Evaluate at s=j2πf and solve |H|=h0/√2. The plotted maximum is sampled over 0.01f0 to 100f0.',String.raw`|H(j2\pi f_c)|=h_0/\sqrt2,\quad h_0=A_0/(1+A_0),\quad\tau=h_0/(2\pi GBW)`,String.raw`f_c=${N(x.fc/1000)}\,\mathrm{kHz},\quad \Delta f=${N(100*(x.fc/p.f0-1))}\%,\quad peak\simeq${N(x.peak)}\,\mathrm{dB}`)
],[r('Actual cutoff',x.fc/1000,'kHz'),r('Sampled peaking',x.peak,'dB')],[{...curve('Finite-GBW Sallen–Key response','Frequency (Hz)','Gain (dB)',x.points),logX:true}], 'A frequency-domain solve gives the same linear response as this eliminated state model. Slew and clipping require a separate large-signal check.',x.fc/1000,'kHz','Read the frequency at which gain is 3 dB below DC.','Use the cubic response rather than assuming fc equals f0.',{schematic:filterSchematic(p)})},{symbols:[...symbols,['V_a,V_b','Internal filter node voltages (V).'],['R,C_1,C_2','Equal resistors (Ω), output-to-node-a capacitor and node-b-to-ground capacitor (F).'],[String.raw`s,h_0,\tau`,'Laplace variable (s⁻¹), follower DC gain and follower time constant (s).'],['a,b,c_1,c_2,c_3','Denominator coefficients with units s², s, s, s² and s³ respectively.']]}),
L('a3','Small-signal bandwidth is not full-power bandwidth',[choose,k('peak','Output sine peak',10,.1,10,'V'),k('frequency','Sine frequency',2e4,100,1e5,'Hz')],'Can the output move fast enough to follow the requested sine?',
'A sine can lie inside the gain bandwidth and still demand too much output slope. The native piecewise-linear op-amp solver also shows the time-domain response to a positive step of the same peak size at gain 11.',
'Compare the general-purpose and JFET classes at 10 V peak and 20 kHz.',p=>{const x=amplifier(p),required=2*Math.PI*p.frequency*p.peak,full=x.sr/(2*Math.PI*p.peak),trace=slewTrace(p);return O([
s('Differentiate the requested output','The maximum cosine magnitude is one, so the largest required slope occurs at a sine zero crossing.',String.raw`V_o(t)=V_p\sin(2\pi ft),\quad\dot V_o(t)=2\pi fV_p\cos(2\pi ft)`,String.raw`|\dot V_o|_{max}=${N(required/1e6)}\,\mathrm{V/\mu s}`),
s('Compare with the class slew limit','A necessary condition for undistorted tracking is that the available slope exceeds the requested one.',String.raw`2\pi fV_p\le SR,\quad f_{full}=\frac{SR}{2\pi V_p}`,String.raw`SR=${N(x.sr/1e6)}\,\mathrm{V/\mu s},\quad f_{full}=${N(full/1000)}\,\mathrm{kHz}`),
s('Estimate a lower bound on step travel time','A step requires at least ΔV/SR to travel through its voltage range. Linear settling can take longer, and a small step may never enter slew limiting.',String.raw`t_{travel}\ge\Delta V/SR`,String.raw`t_{travel}\ge${N(p.peak/x.sr*1e6)}\,\mu\mathrm s`)
],[r('Required slew',required/1e6,'V/μs'),r('Available slew',x.sr/1e6,'V/μs'),r('Full-power bandwidth',full/1000,'kHz')],[curve('Native op-amp step response (gain 11)','Time (μs)','Output (V)',trace)],required<=x.sr?'The sine passes this necessary slew-rate check. Bandwidth, output swing and load capability still apply.':'The requested sine fails the slew-rate check even if its frequency lies within the small-signal bandwidth.',full/1000,'kHz','Calculate full-power bandwidth at the selected peak voltage.','Divide SR by 2π times peak voltage.',{schematic:ampSchematic()})},{symbols:[...symbols,[String.raw`V_p,f,t,\dot V_o`,'Output sine peak (V), sine frequency (Hz), time (s), and output voltage rate of change (V/s).']]}),
L('a4','A low voltage-noise amplifier can lose on a high-impedance source',[choose,Rs,B],'Which noise term dominates before amplification?',
'Input voltage noise, source Johnson noise and input-current noise through the source resistance are independent. Add their squared densities, then integrate over an explicitly stated equivalent noise bandwidth.',
'Compare low-voltage-noise bipolar and JFET classes at 100 Ω, 100 kΩ and 1 MΩ.',p=>{const x=inputNoise(p);return O([
s('Refer each density to the input','Current noise becomes a voltage through Rs; the resistor contributes its own thermal voltage noise.',String.raw`S_v=e_n^2+(i_nR_s)^2+4k_BTR_s`,String.raw`e_n=${N(PARTS[p.part].en/1e-9)},\quad i_nR_s=${N(Math.sqrt(x.current)/1e-9)},\quad e_R=${N(Math.sqrt(x.thermal)/1e-9)}\quad\mathrm{nV/\sqrt{Hz}}`),
s('Integrate power, then take a square root','B is equivalent noise bandwidth, not automatically a filter’s −3 dB corner.',String.raw`v_{n,rms}=\sqrt{S_vB}`,String.raw`v_{n,rms}=${N(x.rms*1e6)}\,\mu\mathrm V`),
s('Compare with a 1 mV rms source signal','Gain multiplies signal and input-referred noise equally in this simplified budget.',String.raw`SNR=20\log_{10}(V_{signal,rms}/v_{n,rms})`,String.raw`SNR=20\log_{10}(10^{-3}/${N(x.rms)})=${N(x.snr)}\,\mathrm{dB}`)
],[r('Input noise',x.rms*1e6,'μV rms'),r('Input SNR',x.snr,'dB')],[{...curve('Source impedance changes the noise winner','Source resistance (Ω)','Input noise (μV rms)',Array.from({length:161},(_,i)=>{const resistance=10**(2+4*i/160);return{x:resistance,y:inputNoise({...p,resistance}).rms*1e6}})),logX:true}], 'Choose the noise model with the source impedance in view. This budget omits feedback-resistor noise and flicker noise; it is not a full amplifier output-noise specification.',x.rms*1e6,'μV','Calculate the total input rms noise.','Add the three density powers, multiply by bandwidth, then take the square root.',{table:{headers:['Input-referred contribution','Rms voltage (μV)'],rows:[['Voltage noise',Math.sqrt(x.voltage*p.bandwidth)*1e6],['Current noise through source',Math.sqrt(x.current*p.bandwidth)*1e6],['Source Johnson noise',Math.sqrt(x.thermal*p.bandwidth)*1e6]]}})}),
L('a5','Bias current and temperature create DC error',[choose,Rs,k('temp','Ambient temperature',25,0,85,'°C'),gain],'Will input bias current create more error than input offset voltage?',
'A source resistance turns bias current into a voltage error. This exercise assumes the two error signs add, and isolates source-side error before feedback-resistor balancing or output clipping.',
'Compare the JFET class at 25 °C and 85 °C, then reduce the source resistance.',p=>{const x=offset(p),d=PARTS[p.part],factor=[2,5].includes(p.part)?2**((p.temp-25)/10):1;return O([
s('State the temperature assumptions','JFET/CMOS bias current doubles every 10 °C in this illustrative model; other classes keep bias current fixed. Offset uses the listed linear drift.',String.raw`I_B(T)=I_{B,25}m(T),\quad V_{OS}(T)=V_{OS,25}+D(T-25)`,String.raw`m=${N(factor)},\quad I_B=${N(x.ib/1e-9)}\,\mathrm{nA},\quad D=${N(d.drift*1e6)}\,\mathrm{\mu V/{}^\circ C}`),
s('Calculate the source-side input error','The assumed positive bias-current error and positive offset add. Real devices can have either offset sign.',String.raw`V_{error,in}=I_BR_s+V_{OS}`,String.raw`V_{error,in}=${N(x.bias)}+${N(x.voltage)}=${N(x.total)}\,\mathrm V`),
s('Refer the error to the output','This is the unclipped noise-gain estimate. A result exceeding available swing calls for a different design, not a claimed physical output.',String.raw`V_{error,out}\simeq G_NV_{error,in}`,String.raw`V_{error,out}\simeq${N(x.out)}\,\mathrm V`)
],[r('Bias-current error',x.bias*1e3,'mV'),r('Input total error',x.total*1e3,'mV'),r('Unclipped output error',x.out,'V')],[curve('Assumed DC error versus temperature','Temperature (°C)','Input error (mV)',samples(temp=>offset({...p,temp}).total*1000,0,85))],Math.abs(x.out)>12?'The unclipped error exceeds the illustrative ±12 V swing; this operating condition cannot produce the predicted linear output.':'Bias-current and offset errors must both be budgeted. The temperature laws here are illustrative assumptions, not guaranteed part limits.',x.total*1e3,'mV','Calculate the input error under the stated additive-sign assumption.','Multiply bias current by source resistance and add the temperature-adjusted offset.',{schematic:ampSchematic(p)})},{symbols:[...symbols,['D,m(T)','Offset drift (V/°C) and dimensionless bias-current temperature multiplier.']]}),
L('a6','Decoupling and the complete preamplifier choice',[choose,k('inductance','Supply-loop inductance',10e-9,1e-9,100e-9,'H'),k('capacitance','Local bypass capacitance',100e-9,10e-9,10e-6,'F'),k('current','Load current change',.02,.001,.1,'A'),k('rise','Current edge duration',10e-9,1e-9,1e-6,'s')],'What can the amplifier choice fix, and what requires the supply layout to change?',
'Complete a 1 mV rms, 100 kΩ-source preamplifier budget over 20 kHz noise bandwidth. Then examine three separate supply-edge estimates: wiring inductance, capacitor charge and 50 mΩ ESR.',
'Choose a class that clears 40 dB input SNR. Then reduce loop inductance rather than assuming a larger capacitor fixes every edge.',p=>{const x=supply(p),noise=inputNoise({part:p.part}),a=amplifier({part:p.part}),required=2*Math.PI*2e4*(Math.SQRT2*.001*11);return O([
s('Calculate the inductive voltage demand','The approximation assumes a linear current edge. L is the entire supply-return loop inductance.',String.raw`|V_L|\simeq L\Delta I/t_r`,String.raw`|V_L|\simeq${N(x.inductive)}\,\mathrm V`),
s('Calculate charge droop and resistive drop separately','A rectangular current demand of duration tr removes ΔI tr charge. The actual ramp removes half as much; this is the conservative rectangular estimate.',String.raw`|\Delta V_C|\simeq\Delta I\,t_r/C,\quad |V_{ESR}|=R_{ESR}\Delta I`,String.raw`|\Delta V_C|\simeq${N(x.capacitive)}\,\mathrm V,\quad |V_{ESR}|=${N(x.esr)}\,\mathrm V`),
s('Identify the ideal LC resonance','These separate estimates are not a simulated simultaneous supply waveform. Damping and interconnection determine the actual transient.',String.raw`f_{LC}=1/(2\pi\sqrt{LC})`,String.raw`f_{LC}=${N(x.resonance/1e6)}\,\mathrm{MHz}`),
s('Check the amplifier against this signal task','Use 40 dB SNR, at least 20 kHz small-signal bandwidth and enough slew for the gain-11 sine peak. DC error and supply coupling still need review.',String.raw`SNR\ge40\,\mathrm{dB},\quad f_c\ge20\,\mathrm{kHz},\quad SR\ge2\pi(20000)(11\sqrt2\times10^{-3})`,String.raw`SNR=${N(noise.snr)}\,\mathrm{dB},\quad f_c=${N(a.fc/1000)}\,\mathrm{kHz},\quad SR_{required}=${N(required/1e6)}\,\mathrm{V/\mu s}`)
],[r('Inductive demand',x.inductive,'V'),r('Charge droop estimate',x.capacitive,'V'),r('LC resonance',x.resonance/1e6,'MHz'),r('Preamplifier SNR',noise.snr,'dB')],[{...curve('Faster edges demand more inductive voltage','Edge duration (s)','Inductive voltage (V)',Array.from({length:161},(_,i)=>{const rise=10**(-9+3*i/160);return{x:rise,y:supply({...p,rise}).inductive}})),logX:true}],noise.snr>=40&&a.fc>=2e4&&a.sr>=required?'This class clears the three stated signal checks. A real release also needs DC-error, output/load and supply-coupling checks.':'This class misses at least one stated signal check. Supply decoupling cannot repair an unsuitable input-noise or bandwidth choice.',x.inductive,'V','Calculate the voltage needed across the supply-loop inductance.','Multiply L by current change divided by edge duration.',{table:table()})},{symbols:[...symbols,['L,C,R_{ESR}','Supply-loop inductance (H), bypass capacitance (F), and 0.05 Ω series resistance.'],[String.raw`\Delta I,t_r,f_{LC}`,'Current change (A), edge duration (s), and ideal LC resonant frequency (Hz).']]}),
...STABILITY_LESSONS,
...PRECISION_LESSONS,
...REGULATOR_LESSONS,...FRONTEND_LESSONS
]
