import {knob as k,step as s,reading as r,curve,texnum as N,fmt} from '@ee-labs/lessons/model'
import {spec,prototype,tolerance,section,sectionDrawing,cascade,db,logpoints} from './filterDesign.js'
const T=String.raw
const source=['TI: Active Low-Pass Filter Design','https://www.ti.com/lit/an/sloa049d/sloa049d.pdf']
const symbols=[[T`f,f_p,f_s,f_c,\omega`,'Frequency, passband edge, stopband edge, and filter corner (Hz); angular frequency ω=2πf (rad/s). Here fs is a stopband edge, not a sampling clock.'],[T`A_p,A_s,n,\epsilon^2,H(s)`,'Allowed passband loss and required stopband attenuation (dB), integer order, ripple factor, and voltage transfer function.'],[T`s,j,\tau_g,Q`,'Laplace variable (s⁻¹), imaginary unit, group delay (s), and dimensionless quality factor. H(jω) is the steady-state phasor ratio.']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'F. Filters to a specification',knobs,question,intro,try:attempt,solve,symbols,sources:[source],flow:['Translate the requirement into an equation','Choose and calculate a realizable response','Check the whole response against the requirement'],route:'Use magnitude equations to choose order and corner. Evaluate the same transfer function at s=jω for steady-state gain and phase. Its state equations add initial conditions and step response; the three descriptions must represent the same circuit.',limits:'Ideal continuous-time prototypes unless finite amplifier bandwidth is explicitly selected. Component parasitics, rail limits, slew, noise and device-specific tolerances are excluded.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const mask=[k('pass','Passband edge',1e5,1e3,2e5,'Hz'),k('ratio','Stopband / passband edge',5,2,10),k('ripple','Allowed passband loss',.5,.1,1,'dB'),k('stop','Required stopband attenuation',40,20,80,'dB')]
function orderLesson(cheb){return L(cheb?'f2':'f1',cheb?'Chebyshev: trade ripple for fewer poles':'Butterworth: let the specification set the order',mask,
 'How many poles are needed to meet both edges of the mask?',
 cheb?'A type I Chebyshev filter distributes loss as passband ripple. Compare its minimum order with Butterworth under the identical mask.':'Start with two inequalities, not an arbitrary corner. A Butterworth response is monotone, so its passband edge is its largest passband loss.',
 'Increase stopband attenuation, then move the stopband farther away. Predict when the rounded order changes.',p=>{const x=spec(p,cheb),other=spec(p,!cheb);return O([
 s('Translate decibels into squared amplitude ratios','Attenuation is −20 log10|H|. The squared-magnitude denominator must be no larger than 10^(Ap/10) at the passband edge.',T`\epsilon^2=10^{A_p/10}-1,\quad D_s=10^{A_s/10}-1,\quad r=f_s/f_p`,T`\epsilon^2=10^{${N(p.ripple)}/10}-1=${N(x.eps2)},\quad D_s=${N(x.target)},\quad r=${N(p.ratio)}`),
 s('Eliminate the corner and solve for the real-valued order',cheb?'For x≥1, Tn(x)=cosh(n acosh x). Take acosh on both sides of ε²Tn(r)²≥Ds.':'Divide the stopband inequality by the passband equality. Taking logarithms isolates n.',cheb?T`n_* =\frac{\operatorname{acosh}\sqrt{D_s/\epsilon^2}}{\operatorname{acosh}r}`:T`n_* =\frac{\ln(D_s/\epsilon^2)}{2\ln r}`,T`n_*=${N(x.raw)},\quad n=\lceil n_*\rceil=${x.order}`),
 s('Set the frequency scale',cheb?'The Chebyshev normalization uses fp, its ripple edge. This is not a −3 dB corner.':'Choose the smallest corner allowed by the passband constraint; this maximizes stopband rejection for the chosen order.',cheb?T`|H(j2\pi f)|^2=\frac1{1+\epsilon^2T_n(f/f_p)^2},\quad T_n(x)=\cos(n\arccos x)\ (|x|\le1)`:T`f_c=\frac{f_p}{(\epsilon^2)^{1/(2n)}},\quad |H(j2\pi f)|^2=\frac1{1+(f/f_c)^{2n}}`,T`f_{scale}=${N(x.corner/1000)}\,kHz`),
 s('Substitute the actual integer order into the stopband equation','Rounding order upward changes the achieved attenuation. Calculate it again instead of displaying the requested number.',T`A(f)=-20\log_{10}|H(j2\pi f)|`,T`A(f_p)=${N(x.attenuation(p.pass))}\,dB,\quad A(${N(p.pass*p.ratio/1000)}\,kHz)=${N(x.achieved)}\,dB`),
 s('Compare the cost using the same mask','Each complex pole pair usually needs one biquad; an odd order also needs a first-order section. Chebyshev ripple includes DC loss for even order.',T`N_{biquad}=\lfloor n/2\rfloor,\quad N_{first}=n\bmod2`,T`N_{biquad}=${Math.floor(x.order/2)},\quad N_{first}=${x.order%2},\quad n_{other}=${other.order}`)
 ],[r('Required real order',x.raw),r('Implemented order',x.order),r('Stopband attenuation',x.achieved,'dB'),r(cheb?'Ripple edge':'−3 dB corner',x.corner/1000,'kHz')],[{label:'Same mask, two prototype families',xLabel:'Frequency (Hz)',yLabel:'Attenuation (dB)',logX:true,traces:[{label:'Butterworth',points:logpoints(f=>spec(p).attenuation(f),p.pass/100,p.pass*p.ratio*2)},{label:'Chebyshev I',points:logpoints(f=>spec(p,true).attenuation(f),p.pass/100,p.pass*p.ratio*2)}]}],
 'Meet both constraints before choosing a topology. Fewer poles can reduce parts, but ripple and transient ringing may be unacceptable for the signal being measured.',x.achieved,'dB','Calculate the attenuation at the stopband edge using the rounded order.','Evaluate the displayed magnitude equation at fs/fp.',{table:{headers:['Family','Order','At passband edge (dB)','At stopband edge (dB)'],rows:[false,true].map(c=>{const y=spec(p,c);return[c?'Chebyshev I':'Butterworth',y.order,fmt(y.attenuation(p.pass)),fmt(y.achieved)]})}})})}
export const FILTER_LESSONS=[orderLesson(false),orderLesson(true),
L('f3','Bessel: compare delay and ringing on the same frequency scale',[k('corner','Shared −3 dB frequency',1e5,1e3,2e5,'Hz')],
 'What does a flatter group delay buy, and what rejection does it cost?',
 'Compare fourth-order Bessel and Butterworth filters after scaling BOTH to the same −3 dB frequency. Delay-normalized and magnitude-normalized corners are different quantities.',
 'Inspect attenuation and delay together, then compare the unit-step overshoot. Change the corner: normalized shapes stay the same while time scales inversely.',p=>{const b=prototype('bessel',p.corner),w=prototype('butter',p.corner);return O([
 s('Write the normalized denominators','q is a dimensionless Laplace variable s/ωscale. Bessel coefficients here use the reverse polynomial, with DC group delay 1 in normalized time.',T`H_B(q)=\frac{105}{q^4+10q^3+45q^2+105q+105},\quad H_W(q)=\frac1{q^4+2.61312593q^3+3.41421356q^2+2.61312593q+1}`,T`H_B(0)=H_W(0)=1`),
 s('Find and rescale the half-power point','Solve |H(jq3)|²=1/2 separately for each prototype. This prevents comparing different bandwidth definitions.',T`\omega_{scale}=2\pi f_c/q_3,\quad q=s/\omega_{scale}`,T`q_{3,B}=${N(b.q3)},\quad q_{3,W}=${N(w.q3)},\quad\omega_{scale,B}=${N(b.scale)}\,s^{-1}`),
 s('Differentiate phase to obtain delay','For a constant numerator, group delay equals Re{D′(jq)/D(jq)}/ωscale. This analytic derivative avoids noisy phase differencing.',T`\tau_g=-\frac{d\arg H(j\omega)}{d\omega}=\frac{\Re[D'(jq)/D(jq)]}{\omega_{scale}}`,T`\tau_{g,B}(0)=${N(b.delay(0)*1e6)}\,\mu s,\quad\tau_{g,B}(f_c)=${N(b.delay(p.corner)*1e6)}\,\mu s`),
 s('Use the denominator as a state equation','With normalized time θ=ωscale t, choose x=[y,y′,y″,y‴]. All initial states are zero. The fourth equation is obtained by isolating the highest derivative; u becomes a unit step at t=0.',T`x'_1=x_2,\ x'_2=x_3,\ x'_3=x_4,\ x'_4=b_0u-a_0x_1-a_1x_2-a_2x_3-a_3x_4`,T`x(0^-)=x(0^+)=0,\quad (a_3,a_2,a_1,a_0,b_0)_B=(10,45,105,105,105)`),
 s('Measure overshoot from the state response','The trace is propagated using the matrix exponential. The reported peak is the maximum of 601 samples over the shown interval.',T`M_p=100\max_t(y(t)-1)`,T`M_{p,B}=${N(b.overshoot)}\%,\quad M_{p,W}=${N(w.overshoot)}\%`)
 ],[r('Bessel DC delay',b.delay(0)*1e6,'µs'),r('Bessel overshoot',b.overshoot,'%'),r('Butterworth overshoot',w.overshoot,'%')],[{label:'Magnitude at equal half-power bandwidth',xLabel:'Frequency (Hz)',yLabel:'Gain (dB)',logX:true,traces:[b,w].map((x,i)=>({label:i?'Butterworth':'Bessel',points:logpoints(f=>db(x.at(f)),p.corner/100,10*p.corner)}))},{label:'Group delay',xLabel:'Frequency (Hz)',yLabel:'Delay (µs)',logX:true,traces:[b,w].map((x,i)=>({label:i?'Butterworth':'Bessel',points:logpoints(f=>x.delay(f)*1e6,p.corner/100,3*p.corner)}))},{label:'Zero-state unit-step response',xLabel:'Time (µs)',yLabel:'Output / step',traces:[b,w].map((x,i)=>({label:i?'Butterworth':'Bessel',points:x.response.map(p=>({x:p.x*1e6,y:p.y}))}))}],
 'Bessel preserves low-frequency delay more evenly and rings less, but rejects high frequencies less strongly at equal −3 dB bandwidth. Choose using the signal waveform and the rejection mask together.',b.delay(0)*1e6,'µs','Calculate Bessel DC group delay.','The normalized DC delay is 1; divide by ωscale and convert seconds to µs.',{table:{headers:['Frequency / fc','Bessel delay (µs)','Butterworth delay (µs)','Bessel loss (dB)'],rows:[0,.5,1,2].map(f=>[f,fmt(b.delay(f*p.corner)*1e6),fmt(w.delay(f*p.corner)*1e6),fmt(-db(b.at(f*p.corner)))])}})}),
L('f4','Sallen–Key: sensitivities predict a distribution',[k('tolerance','Independent uniform part tolerance',.01,.001,.05),k('seed','Monte Carlo seed',7,1,999,'',1)],
 'How does a ±1% part specification translate into a standard deviation?',
 'Use a unity-gain Sallen–Key section: input–R1–a–R2–b, Cg from b to ground, Cf from a to output, and a voltage follower from b to output. Nominal R1=R2=1 kΩ, Cf=2 nF and Cg=1 nF.',
 'Compare the predicted and sampled standard deviations, then change the seed. Double the tolerance and predict how the spread changes.',p=>{const x=tolerance(p);return O([
 s('Derive the pole frequency and quality factor from KCL','The ideal follower holds vo=vb. The node-b current gives va=vb(1+sR2Cg). Substitute into node-a KCL.',T`\frac{v_a-v_i}{R_1}+\frac{v_a-v_b}{R_2}+sC_f(v_a-v_o)=0,\quad \frac{v_b-v_a}{R_2}+sC_gv_b=0`,T`H(s)=\frac1{1+sC_g(R_1+R_2)+s^2R_1R_2C_fC_g}`),
 s('Identify coefficients of the standard second-order denominator','Write H=1/[1+s/(Qω0)+(s/ω0)²] and match coefficients.',T`f_0=\frac1{2\pi\sqrt{R_1R_2C_fC_g}},\quad Q=\frac{\sqrt{R_1R_2C_fC_g}}{C_g(R_1+R_2)}`,T`f_0=${N(x.nom.f/1000)}\,kHz,\quad Q=${N(x.nom.q)}`),
 s('Differentiate logarithms, then check numerically','Sxp=(p/x)∂x/∂p. At equal resistors, the two resistor sensitivities of Q vanish to first order; capacitor sensitivities are +1/2 and −1/2.',T`S_{f_0}^{R_1,R_2,C_f,C_g}=-\tfrac12,\quad S_Q^{R_1}=\tfrac12-\frac{R_1}{R_1+R_2},\quad S_Q^{C_f}=\tfrac12,\quad S_Q^{C_g}=-\tfrac12`,T`S_Q^{R_1}=S_Q^{R_2}=0,\quad h=10^{-5}`),
 s('Distinguish tolerance from standard deviation','Each independent part error is uniform on [−t,+t], so its standard deviation is t/√3. Add squared sensitivities because the errors are independent.',T`\frac{\sigma_x}{x}\simeq\sqrt{\sum_p(S_x^p)^2t^2/3},\quad \sigma_f/f_0=t/\sqrt3,\quad \sigma_Q/Q=t/\sqrt6`,T`100\sigma_f/f_0=${N(100*x.predF)}\%,\quad100\sigma_Q/Q=${N(100*x.predQ)}\%`),
 s('Compare with independently perturbed circuits','Draw 2000 sets of four parts using the stated seed. Recompute exact f0 and Q for each. Use sample standard deviation, divided by the nominal value.',T`\widehat\sigma_x=\sqrt{\frac{\sum_{i=1}^{M}(x_i-\bar x)^2}{M-1}},\quad M=2000`,T`100\widehat\sigma_f/f_0=${N(100*x.sigmaF)}\%,\quad100\widehat\sigma_Q/Q=${N(100*x.sigmaQ)}\%`)
 ],[r('Predicted frequency spread',100*x.predF,'%'),r('Sampled frequency spread',100*x.sigmaF,'%'),r('Predicted Q spread',100*x.predQ,'%'),r('Sampled Q spread',100*x.sigmaQ,'%')],[curve('First 200 independent builds','Trial','Frequency deviation (%)',x.trials.slice(0,200).map((v,i)=>({x:i,y:100*(v.f/x.nom.f-1)})))],
 'A tolerance limit is not a standard deviation. These predictions depend on independent uniform errors; correlated parts or a different distribution change the answer.',100*x.predF,'%','Calculate the predicted relative standard deviation of f0.','Divide the fractional tolerance by √3, then multiply by 100.',{schematic:sectionDrawing({R:1000,c1:2e-9,c2:1e-9}),table:{headers:['Part','Analytic Sf','Numerical Sf','Analytic SQ','Numerical SQ'],rows:x.sensitivities.map((a,i)=>[a.key,-.5,fmt(a.f),[0,0,.5,-.5][i],fmt(a.q)])}})}, {symbols:[...symbols,[T`R_1,R_2,C_f,C_g,S_x^p,t,\sigma`,'Resistances (Ω), feedback and grounded capacitances (F), normalized sensitivity, fractional tolerance half-width, and standard deviation.']]}),
L('f5','Multiple feedback: verify finite-bandwidth filter sections',[k('gbw','Amplifier gain-bandwidth',3e6,1e6,10e6,'Hz'),{...k('topology','Cascade topology',0,0,1),options:['Sallen–Key','Multiple feedback']},k('scale','Cascade corner adjustment',1,.8,1.2),k('damping','Cascade Q multiplier',1,.9,1)],
 'Can two practical sections still meet the original 0.5 dB / 40 dB mask?',
 'Compare equal-f0, equal-Q unity-magnitude sections. MFB uses input–R–a, output–R–a, a–R–b, C1 from a to ground, C2 from b to output, and an inverting amplifier at b. Sallen–Key uses the F4 connections.',
 'Set GBW to 3 MHz or less. Try both cascade topologies and adjust the corner and Q multiplier. For a starting feasible SK design, try corner ×1.1 and Q ×0.95 at 3 MHz. The passband must stay between −0.5 and 0 dB through 100 kHz, and reach 40 dB loss at 500 kHz.',p=>{const sk=section({gbw:p.gbw}),m=section({gbw:p.gbw,topology:1}),c=cascade(p);return O([
 s('Write MFB node equations before applying an ideal amplifier','With all three resistors equal to R, node a joins the input, output, inverting input b, and grounded capacitor C1. No input current flows into the amplifier.',T`\frac{v_a-v_i}{R}+\frac{v_a-v_o}{R}+\frac{v_a-v_b}{R}+sC_1v_a=0,\quad\frac{v_b-v_a}{R}+sC_2(v_b-v_o)=0`,T`v_b=0\Rightarrow H_{MFB}(s)=\frac{-1}{1+3RC_2s+R^2C_1C_2s^2}`),
 s('Select components for the same target poles','Use C2=1 nF in both sections. MFB requires C1=9Q²C2 and R=1/(3Qω0C2); unity-gain SK requires Cf=4Q²Cg and R=1/(2Qω0Cg).',T`\omega_0=2\pi(100000),\quad Q=1/\sqrt2`,T`R_{MFB}=${N(m.R)}\,\Omega,\ C_{1,MFB}=${N(m.c1*1e9)}\,nF,\quad R_{SK}=${N(sk.R)}\,\Omega,\ C_{f,SK}=${N(sk.c1*1e9)}\,nF`),
 s('Replace the ideal amplifier equation','The same dominant-pole model A(s)=ωt/s is used for both topologies. Solve the full complex KCL matrix at every plotted frequency. This retains the extra dynamics instead of assigning an empirical corner error.',T`\omega_t=2\pi GBW,\quad v_b=-\frac{s}{\omega_t}v_o\ (MFB),\quad v_b=(1+s/\omega_t)v_o\ (SK)`,T`GBW=${N(p.gbw/1e6)}\,MHz,\quad f_{3,SK}=${N(sk.actual3/1000)}\,kHz,\quad f_{3,MFB}=${N(m.actual3/1000)}\,kHz`),
 s('Cascade the two fourth-order Butterworth pole pairs','The isolated Q=0.707 comparison above is not a fourth-order design. The ideal prototype needs Q1=0.541196 and Q2=1.306563. The Q multiplier η deliberately retunes both sections to compensate finite bandwidth; a retuned response is judged against the mask rather than called an exact Butterworth prototype.',T`H_{total}=H_1H_2,\quad f_0=\alpha f_{c,F1},\quad (Q_1,Q_2)=\eta(0.541196,1.306563)`,T`\eta=${N(p.damping)},\quad f_0=${N(c.sections[0].corner/1000)}\,kHz,\quad A(100\,kHz)=${N(c.passLoss)}\,dB,\quad A(500\,kHz)=${N(c.stopLoss)}\,dB`),
 s('Check the mask including passband peaking','Evaluate 501 logarithmic passband samples plus DC. A peak above 0 dB fails this chosen mask even if both edge values pass. This sampled check is a design aid; final hardware needs denser corner and tolerance verification.',T`-0.5\le20\log_{10}|H(f)|\le0\ (0\le f\le100\,kHz),\quad A(500\,kHz)\ge40`,T`G_{min}=${N(c.min)}\,dB,\quad G_{max}=${N(c.max)}\,dB`)
 ],[r('SK half-power shift',sk.error,'%'),r('MFB half-power shift',m.error,'%'),r('Cascade passband minimum',c.min,'dB'),r('Cascade stopband loss',c.stopLoss,'dB')],[{label:'Equal-target isolated biquads',xLabel:'Frequency (Hz)',yLabel:'Gain magnitude (dB)',logX:true,traces:[{label:'Ideal |H|',points:logpoints(f=>db(sk.ideal(f)),1e3,1e6)},{label:'SK finite GBW',points:logpoints(f=>db(sk.at(f)),1e3,1e6)},{label:'MFB finite GBW',points:logpoints(f=>db(m.at(f)),1e3,1e6)}]},{...curve('Selected fourth-order cascade','Frequency (Hz)','Gain (dB)',logpoints(f=>db(c.at(f)),1e3,1e6)),logX:true}],
 c.meets?'The selected cascade passes the sampled mask. If GBW is at most 3 MHz it also meets the exercise bandwidth constraint; document both before adding tolerance and device nonidealities.':'The selected cascade misses the sampled mask. Adjust the corner, Q multiplier or topology and inspect peaking as well as both edge losses; increasing GBW above 3 MHz does not satisfy the exercise constraint.',m.actual3/1000,'kHz','Read the solved MFB −3 dB frequency.','Use the full KCL response and find where |H|²=1/2.',{schematic:sectionDrawing(p.topology?m:sk,p.topology),table:{headers:['GBW (MHz)','SK half-power shift (%)','MFB half-power shift (%)'],rows:[1,3,10].map(v=>[v,fmt(section({gbw:v*1e6}).error),fmt(section({topology:1,gbw:v*1e6}).error)])}})}, {symbols:[...symbols,[T`v_i,v_a,v_b,v_o,R,C_1,C_2,A(s),GBW,\alpha,\eta`,'Input, intermediate, amplifier input, output voltages (V); resistance (Ω), capacitances (F), open-loop voltage gain, unity-gain frequency (Hz), cascade corner multiplier, and Q multiplier.']]})
]
