import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {highSide,lowSide,rtd,thermocouple,typeK,antiAlias,K_COEFFICIENTS} from './frontends.js'
const T=String.raw
const current=k('current','Load current',1,.05,5,'A'),shunt=k('shunt','Shunt resistance',.1,.01,.2,'Ω')
const staticRoute='Use the voltage and current equations for the operating point and the error budget. They expose which physical error changes the reading. Phasors are useful for frequency-dependent disturbances, and state equations for stored-energy transients; neither adds information to this static model.'
function L(id,name,knobs,question,intro,attempt,symbols,limits,solve,extra={}) {return {id,name,group:'E. Sensor front ends',knobs,question,intro,try:attempt,symbols,limits,solve,route:staticRoute,flow:['Identify the sensed quantity and reference node','Derive the signal and each input-referred error','Compare the result with the measurement requirement'],...extra}}
function O(steps,readings,plots,conclusion,question,answer,unit,hint,extra={}) {return {steps,readings,plots,conclusion,practice:{question,answer,unit,hint,reason:conclusion},...extra}}
export const FRONTEND_LESSONS=[
L('e1','High-side sensing: signal versus common-mode leakage',[current,shunt,k('common','Common-mode voltage',12,0,48,'V'),k('gain','Nominal differential gain',1,1,20),{...k('tolerance','Resistor tolerance fraction',.001,0,.01),group:'Error budget'},{...k('cmrr','Integrated amplifier CMRR',100,60,120,'dB'),group:'Error budget'}],
 'Why can a small resistor mismatch hide a 100 mV shunt signal?',
 'The two shunt terminals sit near the supply voltage. A difference amplifier must subtract that common voltage while preserving the small difference. Compare one explicitly defined resistor corner with a separately specified current-sense amplifier.',
 'Set common mode to zero, then restore 12 V. Set tolerance to zero. Identify which error each change removes before increasing gain.',
 [[T`I,R_s,V_s,P_s`,'Load current (A), shunt resistance (Ω), voltage difference Vs=IRs (V), and shunt dissipation (W).'],[T`V_{CM},v_+,v_-`,'Shunt common mode and terminal voltages v±=VCM±Vs/2 (V). These terminal labels are not the op-amp input nodes.'],[T`G,t,a,b`,'Nominal gain G, fractional resistor tolerance t (0.001=0.1%), actual ratios a=R2/R1 and b=R4/R3. R1 and R3 nominally 10 kΩ; R2 and R4 nominally G·10 kΩ.'],[T`v_p,v_o,A_d,A_c`,'Ideal op-amp noninverting node voltage and output (V); differential and common-mode gains (V/V).'],[T`e_{CM},e_G,e_{int},CMRR`,'Errors referred through nominal gain to the shunt input (V); specified integrated-amplifier rejection in dB.']],
 'Ideal op-amp with unloaded shunt terminals and unlimited input/output range. The four resistor deviations are a declared opposing corner, not a random distribution or a universal tolerance-to-CMRR formula. The integrated amplifier comparison includes only its specified DC CMRR, with a chosen positive error sign; offset, gain tolerance and bandwidth are excluded.',p=>{const x=highSide(p);return O([
 s('Find the signal before amplifying','Current flows from the higher shunt terminal toward the lower. The desired difference is independent of their average voltage.',T`V_s=IR_s,\quad P_s=I^2R_s,\quad v_\pm=V_{CM}\pm V_s/2`,T`V_s=${N(p.current)}(${N(p.shunt)})=${N(x.signal)}\,V,\quad P_s=${N(x.power)}\,W`),
 s('Name the four resistor deviations','R1 and R4 are low by t; R2 and R3 are high by t. First compute the two actual ratios. Equal nominal resistances alone do not guarantee equal actual ratios.',T`a=G\frac{1+t}{1-t},\quad b=G\frac{1-t}{1+t}`,T`a=${N(p.gain)}\frac{1+${N(p.tolerance)}}{1-${N(p.tolerance)}}=${N(x.a)},\quad b=${N(x.b)}`),
 s('Solve the divider and the inverting-node KCL','The ideal op-amp holds its inverting node at vp. Substitute the divider voltage into KCL, then collect differential and common terms.',T`v_p=\frac{b}{1+b}v_+,\quad\frac{v_--v_p}{R_1}+\frac{v_o-v_p}{R_2}=0,\quad v_o=(1+a)\frac b{1+b}v_+-av_-`,T`A_c=\frac{b-a}{1+b}=${N(x.ac)},\quad A_d=\frac12\left[\frac{(1+a)b}{1+b}+a\right]=${N(x.ad)}`),
 s('Refer each error to the measured shunt voltage','Divide by nominal gain because the current readout assumes G. Keep common-mode leakage and differential-gain error separate.',T`e_{CM}=A_cV_{CM}/G,\quad e_G=(A_d/G-1)V_s,\quad\widehat V_s=V_s+e_{CM}+e_G`,T`e_{CM}=${N(x.commonError*1000)}\,mV,\quad e_G=${N(x.gainError*1000)}\,mV,\quad e_{total}=${N(x.error*1000)}\,mV`),
 s('Compare a specified CMRR on the same input basis','The specified ratio is an amplitude ratio, hence divide the dB value by 20. CMRR alone does not check supply or pin-voltage compatibility.',T`e_{int}=V_{CM}10^{-CMRR/20},\quad\epsilon=100e/V_s`,T`e_{int}=${N(p.common)}10^{-${N(p.cmrr)}/20}=${N(x.integratedError*1e6)}\,\mu V,\quad\epsilon_{int}=${N(100*x.integratedError/x.signal)}\%`)
 ],[r('Shunt voltage',x.signal*1000,'mV'),r('Shunt power',x.power,'W'),r('Resistor-corner input error',x.error*1000,'mV'),r('Specified-CMRR input error',x.integratedError*1e6,'µV')],[{label:'Common voltage leaking into the input-referred reading',xLabel:'Common-mode voltage (V)',yLabel:'Input error (mV)',traces:[{label:'Resistor corner, total',points:samples(common=>highSide({...p,common}).error*1000,0,48)},{label:'Specified CMRR only',points:samples(common=>highSide({...p,common}).integratedError*1000,0,48)}]}],
 'Ratio matching rejects common mode. More gain can change the resistor-corner sensitivity, but it also increases output demand. Choose a real amplifier only after checking its input common-mode range, output swing and offset.', 'Calculate the common-mode input error of the specified integrated amplifier.',x.integratedError*1e6,'µV','Divide common mode by 10^(CMRR/20), then convert V to µV.',{table:{headers:['Error source','Input error (mV)','Fraction of signal (%)'],rows:[['Resistor common mode',fmt(x.commonError*1000),fmt(100*x.commonError/x.signal)],['Resistor differential gain',fmt(x.gainError*1000),fmt(100*x.gainError/x.signal)],['Integrated CMRR only',fmt(x.integratedError*1000),fmt(100*x.integratedError/x.signal)]]}})},
 {sources:[['Analog Devices: High-side current sensing','https://www.analog.com/en/resources/analog-dialogue/articles/high-side-current-sensing.html']]}),
L('e2','Low-side sensing: follow the return current',[current,shunt,k('trace','Shared return trace',.01,0,.1,'Ω'),{...k('kelvin','Sense connection',1,0,1),options:['Shared trace included','Kelvin across shunt']}],
 'What moves when the shunt is placed in the load return?',
 'Start at board ground, cross the shared trace, then cross the shunt to reach the load return. Kelvin sense wires can exclude trace resistance from the current measurement; they cannot remove the voltage that the load return physically develops.',
 'Toggle Kelvin sensing. The inferred current changes, but the load-return rise does not. Increase trace resistance to see the distinction.',
 [[T`I,R_s,R_t`,'Current (A), shunt resistance and shared return trace resistance (Ω).'],[T`V_s,V_t,V_{return},V_{sense}`,'Shunt drop, trace drop, load return relative to board ground, and sensed voltage (V).'],[T`\widehat I,e_I,P_{return}`,'Inferred current (A), its signed error (A), and total dissipation in shunt plus trace (W).']],
 'DC series current path with an ideal current load and zero-current sense wires. Return lift here is Rs plus Rt; the extra trace contribution is shown separately. No trace inductance, amplifier offset or ground-plane spreading resistance is included.',p=>{const x=lowSide(p);return O([
 s('Draw the voltage ladder from board ground','Board ground is 0 V. The trace comes first and the shunt second when walking toward the load return.',T`V_t=IR_t,\quad V_s=IR_s,\quad V_{return}=V_t+V_s`,T`V_t=${N(x.traceDrop)}\,V,\quad V_s=${N(x.signal)}\,V,\quad V_{return}=${N(x.ground)}\,V`),
 s('Choose the two measurement terminals','Kelvin wires terminate at the shunt pads. Shared-trace sensing uses board ground instead of the lower shunt pad.',T`V_{sense,K}=IR_s,\quad V_{sense,shared}=I(R_s+R_t)`,T`V_{sense,selected}=${N(x.measured)}\,V`),
 s('Convert sensed voltage back to current','The readout divides by shunt resistance only. Any included trace voltage is therefore mistaken for additional current.',T`\widehat I=V_{sense}/R_s,\quad e_I=\widehat I-I`,T`\widehat I=${N(x.measured)}/${N(p.shunt)}=${N(x.inferred)}\,A,\quad e_I=${N(x.error)}\,A`),
 s('Check both measurement and power consequences','The load return stays elevated even when the current reading becomes exact. A separate low-level signal referenced to board ground sees that elevation.',T`P_{return}=I^2(R_s+R_t),\quad\Delta V_{extra}=IR_t`,T`P_{return}=${N(x.power)}\,W,\quad\Delta V_{extra}=${N(x.traceDrop*1000)}\,mV`)
 ],[r('Shunt drop',x.signal*1000,'mV'),r('Additional trace drop',x.traceDrop*1000,'mV'),r('Total load-return rise',x.ground*1000,'mV'),r('Inferred current',x.inferred,'A')],[{label:'What Kelvin wiring changes',xLabel:'Load current (A)',yLabel:'Sensed voltage (V)',traces:[{label:'Kelvin',points:samples(current=>current*p.shunt,0,5)},{label:'Shared trace',points:samples(current=>current*(p.shunt+p.trace),0,5)}]}],
 'Kelvin sensing removes the shared trace from the measurement equation. It does not move the load return back to board ground. Low-side sensing therefore needs a system-level grounding decision.', 'Calculate the total load-return voltage above board ground.',x.ground*1000,'mV','Add the shunt and trace resistances before multiplying by current.',{table:{headers:['Connection','Inferred current (A)','Return rise (mV)'],rows:[['Kelvin',fmt(p.current),fmt(x.ground*1000)],['Shared trace',fmt(p.current*(1+p.trace/p.shunt)),fmt(x.ground*1000)]]}})}),
L('e3','RTD excitation: sensitivity, lead error and self-heating',[k('temp','Ambient temperature',0,0,100,'°C'),k('current','Excitation current',.001,.0001,.005,'A'),k('lead','Resistance of each lead',.5,0,2,'Ω'),{...k('theta','Thermal resistance',500,100,1000,'K/W'),group:'Thermal model'}],
 'Why does increasing excitation improve the voltage signal while worsening the temperature reading?',
 'Use a local linear Pt100 model to isolate two errors: unwanted lead voltage and heating from the measurement current. Solve the thermal feedback rather than evaluating power only at the unheated resistance.',
 'Compare 1 mA and 2 mA. Sensitivity doubles, but heating grows by about four times. Set lead resistance to zero: four-wire sensing has already removed that term, but heating remains.',
 [[T`T_a,T_s,\Delta T`,'Ambient and sensor temperatures (°C); temperature rise ΔT=Ts−Ta (K).'],[T`R_0,a,R_a,R(T_s)`,'100 Ω at 0 °C, local slope a=0.3851 Ω/K, ambient resistance R0+aTa, and heated resistance (Ω). This is a local linear teaching law.'],[T`I,R_l,\theta,C_{th}`,'Excitation (A), resistance of EACH lead (Ω), thermal resistance (K/W), and thermal capacitance 0.002 J/K.'],[T`\lambda,\tau,\dot{\Delta T},t`,'Dimensionless thermal feedback factor θI²a, effective thermal time constant (s), time derivative of rise (K/s), and elapsed time (s).']],
 'Local linear Pt100 law, not the full IEC Callendar–Van Dusen calibration. Perfect four-wire voltage sensing, constant current and one thermal body with temperature-independent θ and Cth. The allowed controls keep λ<1; no thermal runaway is modeled beyond this range.',p=>{const x=rtd(p);return O([
 s('Define the unheated resistance and voltage sensitivity','A degree Celsius difference equals one kelvin. Temperature is referred to the 0 °C resistance anchor.',T`R_a=R_0+aT_a,\quad \frac{dV}{dT_s}=Ia`,T`R_a=100+0.3851(${N(p.temp)})=${N(x.ambient)}\,\Omega,\quad Ia=${N(x.sensitivity*1e6)}\,\mu V/K`),
 s('Close the electrothermal balance','Current produces I²R heat; the heated resistance itself rises. Substitute the linear resistance law into ΔT=θP and collect ΔT.',T`\Delta T=\theta I^2(R_a+a\Delta T),\quad\lambda=\theta I^2a,\quad\Delta T_\infty=\frac{\theta I^2R_a}{1-\lambda}`,T`\lambda=${N(x.feedback)},\quad\Delta T_\infty=${N(x.rise)}\,K,\quad P=I^2R(T_s)=${N(x.power*1e6)}\,\mu W`),
 s('Separate lead error from heating','Two equal current-carrying leads add 2Rl. Four-wire sensing removes both lead drops when sense current is negligible. Both methods still measure the heated sensor.',T`\widehat T_{2w}=T_a+\Delta T+2R_l/a,\quad\widehat T_{4w}=T_a+\Delta T`,T`2R_l/a=2(${N(p.lead)})/0.3851=${N(x.leadError)}\,K,\quad\widehat T_{2w}=${N(x.twoWire)}\,{}^\circ C,\quad\widehat T_{4w}=${N(x.fourWire)}\,{}^\circ C`),
 s('Use a state equation to see warm-up','The state is temperature rise, not absolute temperature. Before excitation ΔT(0−)=0; thermal capacitance makes ΔT(0+)=0 too. A dot means a derivative with respect to seconds.',T`C_{th}\dot{\Delta T}=I^2(R_a+a\Delta T)-\Delta T/\theta,\quad\tau=\frac{\theta C_{th}}{1-\lambda}`,T`\tau=${N(x.tau)}\,s,\quad\Delta T(0^-)=\Delta T(0^+)=0`),
 s('Solve the same first-order balance','The equilibrium came from setting the state derivative to zero. The exponential describes how that equilibrium is approached.',T`\Delta T(t)=\Delta T_\infty(1-e^{-t/\tau}),\quad t\ge0`,T`\Delta T(\tau)=${N(x.rise)}(1-e^{-1})=${N(x.at(x.tau))}\,K`)
 ],[r('Voltage sensitivity',x.sensitivity*1e6,'µV/K'),r('Self-heating',x.rise,'K'),r('Two-lead error',x.leadError,'K'),r('Thermal time constant',x.tau,'s')],[curve('Sensor warm-up after excitation turns on','Time (s)','Temperature rise (K)',samples(x.at,0,5*x.tau)),curve('Excitation changes self-heating','Excitation (mA)','Temperature rise (K)',samples(i=>rtd({...p,current:i/1000}).rise,.1,5))],
 'Four wires remove lead resistance from an ideal measurement, but they do not remove self-heating. Choose excitation using the required voltage sensitivity and the allowed heating error together.', 'Calculate the temperature error due to the two leads alone.',x.leadError,'K','Both leads carry excitation: divide twice the per-lead resistance by 0.3851 Ω/K.',{table:{headers:['Readout','Temperature (°C)','Error from ambient (K)'],rows:[['Two-wire',fmt(x.twoWire),fmt(x.twoWire-p.temp)],['Four-wire',fmt(x.fourWire),fmt(x.rise)]]}})},
 {route:'Use static resistance and thermal balance to predict the final error. Use the state equation for warm-up and initial conditions; it reaches the same equilibrium. A thermal phasor model could describe small periodic heating around that point, but the turn-on step is more directly interpreted in time.',sources:[['TI: A Basic Guide to RTD Measurements','https://www.ti.com/lit/an/sbaa275a/sbaa275a.pdf']]}),
L('e4','Thermocouple voltage needs a cold-junction reference',[k('hot','Hot-junction temperature',500,50,1000,'°C'),k('cold','Cold-junction temperature',25,5,80,'°C'),k('coldError','Cold-junction measurement error',1,-5,5,'K'),k('offset','Input-referred amplifier offset',.001,-.001,.001,'V'),{...k('gain','Amplifier gain',200,1,250),group:'Amplifier'}],
 'Why must cold-junction compensation be added in voltage before converting back to temperature?',
 'A type K thermocouple measures the voltage difference between two temperatures. Use its nonlinear ITS-90 reference curve, then compare with the familiar local 41 µV/K shortcut. All voltage quantities use V notation.',
 'Set both errors to zero and move the cold junction: the corrected hot temperature stays correct. Add 1 mV offset, then compare the exact error with offset divided by the local slope.',
 [[T`F_K(T),T_h,T_c,\widehat T_c`,'Type K reference voltage at temperature T versus a 0 °C reference (V); hot, actual cold, and measured cold temperatures (°C).'],[T`V_{TC},V_{os},V_m,V_{corr},G`,'Thermocouple voltage difference, input-referred offset, measured input voltage, reference-corrected voltage (V), and ideal amplifier gain.'],[T`S_h,S_c,\delta T_c,\widehat T_h`,'Local reference-curve slopes at hot/cold junctions (V/K), cold sensor error (K), and inferred hot temperature (°C).']],
 'ITS-90 type K reference function on 0–1372 °C, evaluated with its polynomial plus exponential correction. Controls keep both temperatures and inferred result within this domain. Ideal gain, unlimited output swing, no noise or thermocouple wire tolerance. The 41 µV/K comparison is a local approximation, not a calibration across 1000 °C.',p=>{const x=thermocouple(p);return O([
 s('Evaluate the reference function at each junction','The reference curve is nonlinear. Its coefficients are supplied in Explore for reproducibility; coefficients produce mV before conversion to V.',T`F_K(T)=10^{-3}\left[\sum_{i=0}^{9}c_iT^i+0.1185976e^{-0.0001183432(T-126.9686)^2}\right]`,T`F_K(T_h)=${N(x.hotV*1000)}\,mV,\quad F_K(T_c)=${N(x.coldV*1000)}\,mV`),
 s('Subtract the physical junction voltages','The measured thermocouple voltage is referenced to the actual cold junction. Input-referred offset is added before gain.',T`V_{TC}=F_K(T_h)-F_K(T_c),\quad V_m=V_{TC}+V_{os},\quad V_o=GV_m`,T`V_{TC}=${N(x.signal*1000)}\,mV,\quad V_m=${N(x.measured*1000)}\,mV,\quad V_o=${N(x.output)}\,V`),
 s('Add the measured cold-junction reference in voltage','Convert the cold sensor reading to the same reference-voltage scale. Adding temperatures directly would assume constant sensitivity.',T`\widehat T_c=T_c+\delta T_c,\quad V_{corr}=V_m+F_K(\widehat T_c)`,T`\widehat T_c=${N(p.cold+p.coldError)}\,{}^\circ C,\quad V_{corr}=${N(x.corrected*1000)}\,mV`),
 s('Invert the reference curve to recover temperature','Solve FK(T)=Vcorr by bounded bisection. This numerical inverse uses the same direct curve and avoids switching to an inconsistent linear calibration.',T`F_K(\widehat T_h)=V_{corr},\quad e_T=\widehat T_h-T_h`,T`\widehat T_h=${N(x.estimate)}\,{}^\circ C,\quad e_T=${N(x.error)}\,K`),
 s('Explain the local error terms','Differentiate the reference curve at both junctions. The cold-junction error transfers with a ratio of local slopes; it is not always exactly one for one.',T`S_h=F'_K(T_h),\quad S_c=F'_K(T_c),\quad e_T\approx\frac{V_{os}}{S_h}+\frac{S_c}{S_h}\delta T_c`,T`S_h=${N(x.sensitivity*1e6)}\,\mu V/K,\quad e_{os}\approx${N(x.offsetEstimate)}\,K,\quad e_{CJ}\approx${N(x.coldEstimate)}\,K`)
 ],[r('Thermocouple voltage',x.signal*1000,'mV'),r('Inferred hot temperature',x.estimate,'°C'),r('Exact temperature error',x.error,'K'),r('41 µV/K shortcut error',x.linearEstimate-p.hot,'K')],[{label:'Reference curve versus the local linear shortcut',xLabel:'Temperature (°C)',yLabel:'Reference voltage (mV)',traces:[{label:'Type K reference',points:samples(t=>typeK(t)*1000,0,1000)},{label:'41 µV/K',points:samples(t=>.041*t,0,1000)}]}],
 'Cold-junction compensation belongs on the voltage scale. A larger amplifier gain cannot reduce input-referred offset error; it amplifies the signal and that error together.', 'Calculate the thermocouple voltage before amplifier offset.',x.signal*1000,'mV','Subtract the cold reference voltage from the hot reference voltage.',{plotNote:'The polynomial coefficients below use T in °C and output in mV. They are reference-function data, not a device accuracy guarantee.',table:{headers:['Coefficient','Value (mV / °C^i)'],rows:K_COEFFICIENTS.map((v,i)=>[`c${i}`,String(v)])}})},
 {sources:[['NIST: ITS-90 reference functions','https://its90.nist.gov/'],['TI: A Basic Guide to Thermocouple Measurements','https://www.ti.com/lit/pdf/sbaa274']]}),
L('e5','Anti-aliasing: satisfy the passband and stopband together',[k('clock','Sampling frequency',1e6,.5e6,4e6,'Hz'),k('band','Signal-band edge',1e5,2e4,2e5,'Hz'),k('rejection','Required alias rejection',74,40,100,'dB'),k('ripple','Allowed passband loss',.1,.01,3,'dB'),k('order','Filter order',5,1,12,'',1),k('corner','Butterworth corner',150e3,2e4,8e5,'Hz')],
 'Why does rounding up the stopband-only order still miss a flat passband requirement?',
 'A tone near fs−B folds into the desired band at B. Derive the allowed corner-frequency interval from BOTH requirements, then choose an integer order whose interval is nonempty.',
 'At the defaults, compare orders 4 and 5. Set the corner to 100 kHz and inspect passband loss. Increase sampling frequency and see how the feasible interval changes.',
 [[T`f_s,B,f_a,f_c,n`,'Sample rate (Hz), desired band edge (Hz), first positive alias-band edge fa=fs−B, Butterworth −3 dB corner (Hz), and integer order.'],[T`A_p,A_s,L(f),\epsilon_p^2,\epsilon_s^2`,'Allowed passband loss, required alias rejection and actual attenuation (dB); eps²=10^(A/10)−1.'],[T`H(s),j,\omega`,'Continuous-time transfer, imaginary unit, and angular frequency ω=2πf (rad/s). The phasor magnitude is evaluated before sampling.']],
 'Ideal unity-DC-gain Butterworth magnitude and ideal uniform sampling; no finite op-amp bandwidth, component tolerances or ADC acquisition loading. Rejection is a specified interference budget, not an automatic consequence of ADC bit count. The constraints here always keep B<fs/2.',p=>{const x=antiAlias(p);return O([
 s('Locate the frequencies that fold into the signal band','The first positive image of [0,B] begins at fs−B. An analog filter must attenuate it before the sampler; a digital filter cannot undo an alias already in band.',T`f_a=f_s-B,\quad f_{alias}=|f-kf_s|\le f_s/2`,T`f_a=${N(p.clock)}-${N(p.band)}=${N(x.stop)}\,Hz,\quad f_{alias}(f_a)=${N(x.alias(x.stop))}\,Hz`),
 s('Translate dB requirements into magnitude inequalities','Butterworth attenuation is monotone. Checking the band edge and first alias edge therefore checks these two entire intervals.',T`|H(j2\pi f)|^2=\frac1{1+(f/f_c)^{2n}},\quad L(f)=10\log_{10}[1+(f/f_c)^{2n}]`,T`\epsilon_p^2=10^{${N(p.ripple)}/10}-1=${N(x.ep)},\quad\epsilon_s^2=10^{${N(p.rejection)}/10}-1=${N(x.es)}`),
 s('Solve each inequality for the corner','Passband flatness requires a sufficiently high corner; stopband rejection requires a sufficiently low corner. Both must hold for the same filter.',T`f_{c,min}=\frac B{(\epsilon_p^2)^{1/(2n)}},\quad f_{c,max}=\frac{f_a}{(\epsilon_s^2)^{1/(2n)}}`,T`f_{c,min}=${N(x.minimum)}\,Hz,\quad f_{c,max}=${N(x.maximum)}\,Hz`),
 s('Find the minimum integer order','Require fc,min≤fc,max, take logarithms, and round upward. Choosing fc=B would impose 3.0103 dB loss, which is a different passband specification.',T`n\ge\frac{\ln(\epsilon_s^2/\epsilon_p^2)}{2\ln(f_a/B)},\quad n_{min}=\lceil n_{real}\rceil`,T`n_{real}=${N(x.exact)},\quad n_{min}=${x.required},\quad n_{selected}=${p.order}`),
 s('Measure the selected filter against both limits','A sufficient order only makes a solution possible. The selected corner must also lie in its allowed interval.',T`L(B)\le A_p,\quad L(f_a)\ge A_s`,T`L(B)=${N(x.pass)}\,dB,\quad L(f_a)=${N(x.attenuation)}\,dB`)
 ],[r('Minimum integer order',x.required),r('Selected passband loss',x.pass,'dB'),r('Selected alias rejection',x.attenuation,'dB'),r('First alias-band edge',x.stop/1000,'kHz')],[{...curve('Attenuation before sampling','Analog frequency (Hz)','Attenuation (dB)',Array.from({length:201},(_,i)=>{const f=p.band/10*(10*p.clock/p.band)**(i/200);return{x:f,y:x.loss(f)}})),logX:true}],
 x.meets?'The selected order and corner meet both ideal magnitude constraints. Next check implementation tolerances and ADC loading.':x.feasible?'This order admits a solution, but the selected corner misses at least one requirement. Move it into the listed interval.':'No corner can meet both requirements at this order. Increase order or sample rate, or revise the specification.', 'Calculate the minimum integer order that satisfies both specifications.',x.required,'','Use the logarithmic order inequality, then round upward.',{table:{headers:['Constraint','Measured (dB)','Required (dB)','Result'],rows:[['Passband',fmt(x.pass),`≤ ${p.ripple}`,x.pass<=p.ripple?'Pass':'Miss'],['Alias edge',fmt(x.attenuation),`≥ ${p.rejection}`,x.attenuation>=p.rejection?'Pass':'Miss']]}})},
 {route:'Use sampling geometry to locate the alias band, then phasor magnitude to size the analog filter. The inequalities make the design tradeoffs explicit. A state-space or time-domain circuit model is the next step for settling and implementation details; this lesson does not infer those from magnitude alone.'})
]
