import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt as F} from '@ee-labs/lessons/model'
import {PARTS} from './models.js'
import {difference,instrumentation,offsetBudget,chopping,calibration,differenceDrawing,instrumentationDrawing} from './precision.js'
const errors=[1,2,3,4].map(i=>k('e'+i,'R'+i+' fractional error',[0,-.001,.001,.001,-.001][i],-.01,.01)),part={...k('part','Amplifier class',0,0,5,'',1),options:PARTS.map(d=>d.name)},cm=k('vcm','Common-mode input',12,-12,12,'V'),vd=k('vd','Differential input',.01,-.1,.1,'V')
const symbols=[[String.raw`V_p,V_m,V_{CM},V_d,V_o`,'Input node voltages, their average (Vp+Vm)/2, their difference Vp−Vm, and output voltage (V).'],[String.raw`A_d,A_{CM},CMRR`,'Differential and common-mode voltage gains; rejection ratio |Ad/ACM|, expressed in decibels with 20 log10.'],[String.raw`a,b,\kappa,A_0`,'Resistor ratios R2/R1 and R4/R3, finite-gain correction A0/(A0+1+a), and open-loop gain 10⁶.'],[String.raw`G_N,G_S,V_{OS},\alpha_{OS},\Delta T`,'Noise gain, signed signal gain, input offset (V), offset temperature coefficient (V/K), and change from calibration temperature (K).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'C. Precision and calibration',sources:[['Analog Devices: precision amplifier topologies','https://www.analog.com/en/resources/technical-articles/choosing-precision-amplifier-topology.html']],knobs,question,intro,try:attempt,solve,symbols,flow:['Separate the wanted signal from each error','Derive and substitute the relevant gains','Check the actual error against a requirement'],route:'Use DC nodal equations to distinguish differential gain, common-mode gain and offset gain. Use state equations and harmonics for chopped ripple. Calibration removes an identified transfer error; it is not a substitute for drift, headroom or nonlinearity checks.',limits:'Illustrative linear amplifier models. Difference stages use finite A0=10⁶ without intrinsic CMRR, output saturation or input-range modeling. The class table is the same curriculum model as Group A, not a manufacturer guarantee.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const cmrrRead=x=>x.cmrr===null?[]:[r('Common-mode rejection',x.cmrr,'dB')]
const gains=x=>[r('Differential gain',x.dm),r('Common-mode gain',x.cm),...cmrrRead(x),r('Output',x.out,'V')]
export const PRECISION_LESSONS=[
L('c1','Four resistors decide common-mode rejection',[...errors,cm,vd],'How does a large shared input become an unwanted output?',
'A difference amplifier should respond to Vp−Vm. The two resistor ratios must agree for their common-mode contributions to cancel. Enter the error of each physical resistor separately, rather than assigning the finished circuit an unexplained CMRR.',
'Set all four errors to zero, then restore the opposing errors. Compare a 10 mV differential input with a 12 V common input.',p=>{const x=difference(p);return O([
s('Resolve the two input paths','Each actual resistor is 10 kΩ times one plus its fractional error. The non-inverting divider gives V+=b Vp/(1+b). KCL gives V−=(a Vm+Vo)/(1+a).',String.raw`a=R_2/R_1,\quad b=R_4/R_3,\quad V_o=A_0(V_+-V_-)`,String.raw`a=${N(x.a)},\quad b=${N(x.b)},\quad\kappa=${N(x.k)}`),
s('Collect the output and change input coordinates','Substitute Vp=VCM+Vd/2 and Vm=VCM−Vd/2. Keep the common and differential terms separate.',String.raw`V_o=\kappa[(1+a)bV_p/(1+b)-aV_m]=A_dV_d+A_{CM}V_{CM}`,String.raw`A_d=${N(x.dm)},\quad A_{CM}=${N(x.cm)}`),
s('Compute rejection and the signed output error','The common-mode contribution can add to or subtract from the wanted signal. Exact matching gives zero common-mode gain in this model; no finite CMRR number is fabricated for that case.',String.raw`CMRR=|A_d/A_{CM}|,\quad V_{error}=A_{CM}V_{CM}`,String.raw`V_{error}=${N(x.cm*p.vcm)}\,\mathrm V,\quad V_o=${N(x.dm*p.vd)}+(${N(x.cm*p.vcm)})=${N(x.out)}\,\mathrm V`)
],gains(x),[curve('Common input leaking into the output','Common-mode input (V)','Output error (V)',samples(v=>x.cm*v,-12,12))],x.cmrr===null?'These resistor ratios cancel common-mode gain exactly in the stated model. A physical amplifier’s intrinsic CMRR and input range remain separate limitations.':'The wanted differential signal and resistor-induced common-mode error can be comparable. Matching the ratios matters more than merely choosing the same nominal resistance.',x.cm*p.vcm,'V','Calculate the signed common-mode contribution.','Multiply ACM by the selected common-mode input.',{schematic:differenceDrawing(p),check:`Independent native nodal output: ${F(x.native)} V.`,table:{headers:['Resistor','Actual resistance','Fractional error'],rows:x.resistances.map((v,i)=>['R'+(i+1),F(v)+' Ω',F(p['e'+(i+1)])])}})}),
L('c2','An instrumentation amplifier amplifies the difference first',[...errors,{...cm,value:2},vd,k('resistance','Each first-stage feedback resistor',24900,1000,50000,'Ω'),k('bridge','Gain-setting bridge resistor',1000,100,10000,'Ω'),k('rail','Illustrative output limit magnitude',15,5,18,'V')],'Why does gain before the difference stage improve rejection?',
'Two non-inverting amplifiers share a gain-setting resistor between their feedback nodes. Their common output follows the input common mode, while their output difference is amplified. A third amplifier then subtracts those outputs.',
'Reduce the bridge resistor to raise differential gain. Check both first-stage output voltages before assuming the higher gain is usable.',p=>{const x=instrumentation(p),headroom=p.rail-Math.max(Math.abs(x.frontPlus),Math.abs(x.frontMinus),Math.abs(x.out));return O([
s('Separate the first-stage common and differential modes','With equal feedback resistors R and bridge RG, ideal differential gain is G1=1+2R/RG. Finite open-loop gain affects common and differential gains differently.',String.raw`G_1=1+2R/R_G,\quad G_{1d}=G_1/(1+G_1/A_0),\quad G_{1c}=1/(1+1/A_0)`,String.raw`G_1=${N(x.g)},\quad G_{1d}=${N(x.gd)},\quad G_{1c}=${N(x.gc)}`),
s('Find both intermediate node voltages','The common component is shared by both outputs, while the differential components have opposite signs.',String.raw`V_{op}=G_{1c}V_{CM}+G_{1d}V_d/2,\quad V_{om}=G_{1c}V_{CM}-G_{1d}V_d/2`,String.raw`V_{op}=${N(x.frontPlus)}\,\mathrm V,\quad V_{om}=${N(x.frontMinus)}\,\mathrm V`),
s('Cascade the same physical difference stage','The third stage has the four resistor errors from C1. Overall Ad=A3dG1d and ACM=A3CMG1c, so differential gain improves rejection without amplifying the common mode equally.',String.raw`V_o=A_dV_d+A_{CM}V_{CM},\quad CMRR=|A_d/A_{CM}|`,String.raw`A_d=${N(x.dm)},\quad A_{CM}=${N(x.cm)},\quad V_o=${N(x.out)}\,\mathrm V`),
s('Check a stated headroom limit','This check compares the linear prediction with the selected output limit. A failed result does not pretend to simulate saturation or guarantee an input common-mode range.',String.raw`M_V=V_{limit}-\max(|V_{op}|,|V_{om}|,|V_o|)`,String.raw`M_V=${N(headroom)}\,\mathrm V`)
],[...gains(x),r('Output headroom margin',headroom,'V')],[curve('Differential gain versus bridge resistance','RG (Ω)','Overall differential gain',samples(bridge=>instrumentation({...p,bridge}).dm,100,10000))],headroom>=0?'All three linear output predictions fit the selected limit. Device input common-mode range and dynamic settling still require separate checks.':'At least one predicted output exceeds the selected limit. This gain/common-mode combination cannot be accepted from the linear model alone.',x.g,'','Calculate the ideal first-stage differential gain.','Use 1 + 2R/RG.',{schematic:instrumentationDrawing(p),check:`Native three-amplifier nodal solution: ${F(x.native)} V.`,table:{headers:['Node','Predicted voltage','Limit check'],rows:[['First positive output',x.frontPlus],['First negative output',x.frontMinus],['Final output',x.out]].map(([n,v])=>[n,F(v)+' V',Math.abs(v)<=p.rail?'Within selected limit':'Outside selected limit'])}})}),
L('c3','Offset follows noise gain, not signed signal gain',[part,k('gain','Noise gain',1000,2,1000),k('delta','Temperature change',60,-40,100,'K'),{...k('inverting','Signal connection',0,0,1,'',1),options:['Non-inverting','Inverting']}],'Which gain multiplies an amplifier’s input offset?',
'The offset acts as a small differential voltage inside the amplifier. Feedback multiplies it by noise gain even when the external signal follows an inverting path with a different signed gain.',
'Compare the two signal connections at noise gain 2, then compare amplifier classes over 60 K.',p=>{const x=offsetBudget(p);return O([
s('Name the two gains','For a non-inverting signal GN=GS. For an inverting signal GS=−Rf/Rg while GN=1+Rf/Rg; the offset still follows GN.',String.raw`G_N=1+R_f/R_g,\quad G_{S,inv}=1-G_N`,String.raw`G_N=${N(p.gain)},\quad G_S=${N(x.signalGain)}`),
s('Keep initial offset and temperature change separate','The selected Group A class supplies VOS at the reference temperature and its signed illustrative drift coefficient.',String.raw`V_{OS}(T)=V_{OS,0}+\alpha_{OS}\Delta T,\quad V_{o,error}=G_NV_{OS}(T)`,String.raw`V_{OS,0}=${N(x.vos)}\,\mathrm V,\quad\alpha_{OS}=${N(x.drift)}\,\mathrm{V/K}`),
s('Refer the output error to the external signal input','The input-referred magnitude uses the absolute signal gain. It is not always the amplifier’s internal offset voltage.',String.raw`V_{o,error}=G_NV_{OS,0}+G_N\alpha_{OS}\Delta T,\quad V_{in,eq}=V_{o,error}/|G_S|`,String.raw`V_{o,error}=${N(x.initial)}+(${N(x.drift*p.gain*p.delta)})=${N(x.total)}\,\mathrm V,\quad V_{in,eq}=${N(x.input*1e6)}\,\mu\mathrm V`)
],[r('Initial output offset',x.initial,'V'),r('Temperature contribution',p.gain*x.drift*p.delta,'V'),r('Total output offset',x.total,'V')],[curve('Offset versus temperature change','ΔT (K)','Output offset (V)',samples(delta=>offsetBudget({...p,delta}).total,-40,100))],'A room-temperature trim can remove initial offset, but it does not remove future drift. The class parameters here stay consistent with Group A.',x.total,'V','Calculate the output offset at the selected temperature change.','Add initial input offset and drift times ΔT, then multiply by noise gain.') }),
L('c4','Chopped offset leaves ripple after filtering',[k('gain','Offset-path gain',1000,10,1000),k('vos','Offset being chopped',1e-3,10e-6,2e-3,'V'),k('residual','Unmodulated residual input offset',5e-6,0,50e-6,'V'),k('corner','Output low-pass corner',1000,100,20000,'Hz'),k('clock','Chopping clock',1e5,1e4,1e6,'Hz')],'How does a chopped square-wave error become a filtered ripple?',
'This explicit model multiplies offset by an ideal ±1 clock and passes it through a first-order low-pass. A separately declared unmodulated residual models errors that chopping does not remove. Neither residual offset nor total ripple is inferred from the clock alone.',
'Compare the exact peak ripple with its fundamental amplitude. Raise the filter corner until the ten-to-one frequency-separation guard fails.',p=>{const x=chopping(p);return O([
s('Write the error path and its stored state','A=GN VOS is the square-wave amplitude. The low-pass state y follows the signed clock drive q(t), with τ=1/(2πfc).',String.raw`\tau\dot y+y=Aq(t),\quad q\in\{-1,+1\},\quad\tau=1/(2\pi f_c)`,String.raw`A=${N(x.amplitude)}\,\mathrm V,\quad\tau=${N(x.tau)}\,\mathrm s`),
s('Solve the periodic state exactly','During the positive half-cycle, y=A+(y0−A)e^(−t/τ). Periodic symmetry makes y0=−P and y(Ts/2)=+P.',String.raw`P=A\tanh\left(\frac{T_s}{4\tau}\right),\quad V_{ripple,pp}=2P`,String.raw`P=${N(x.peak*1000)}\,\mathrm{mV},\quad V_{ripple,pp}=${N(2*x.peak*1000)}\,\mathrm{mV}`),
s('Distinguish the first harmonic from the total peak','A square wave’s fundamental has amplitude 4A/π. Filtering it gives the exact first-harmonic amplitude; higher harmonics still contribute to the time-domain peak.',String.raw`V_1=\frac{4A/\pi}{\sqrt{1+(f_{chop}/f_c)^2}}\simeq\frac{4A}{\pi}\frac{f_c}{f_{chop}}`,String.raw`V_1=${N(x.fundamental*1000)}\,\mathrm{mV},\quad approximation=${N(x.approx*1000)}\,\mathrm{mV}`),
s('Keep residual DC and the approximation boundary visible','The exact switched RC trace is shown at every setting. Only the high-separation estimate is accepted when fchop/fc≥10.',String.raw`V_{DC}=G_NV_{residual},\quad f_{chop}/f_c\ge10`,String.raw`V_{DC}=${N(x.dc*1000)}\,\mathrm{mV},\quad f_{chop}/f_c=${N(p.clock/p.corner)}`)
],[r('Exact peak ripple',x.peak*1000,'mV'),r('First-harmonic amplitude',x.fundamental*1000,'mV'),r('Residual DC output',x.dc*1000,'mV')],[curve('Native periodic RC output including residual DC','Time (μs)','Output error (V)',x.points)],x.allowed?'The separation guard is met. The simple expression estimates the first harmonic; the native state trace measures the complete filtered square wave.':'The high-separation approximation is not accepted at this setting. Use the exact filtered waveform and harmonic expression.',2*x.peak*1000,'mV','Calculate peak-to-peak ripple.','Double A tanh(Ts/(4τ)).',{plotNote:'The RC state starts at its exact periodic initial condition. The residual DC term is added separately; this is not a transistor-level chopper model.'})},{symbols:[...symbols,[String.raw`A,q(t),y,\tau,T_s,P,f_c,f_{chop}`,'Square-wave amplitude (V), ±1 clock, filter state (V), time constant and chopping period (s), peak ripple (V), filter corner and chopping frequency (Hz).']]}),
L('c5','Calibration removes a fitted line, not every error',[{...part,value:4},k('gainError','Initial fractional gain error',.005,-.02,.02),k('gainDrift','Gain temperature coefficient',2,0,20,'ppm/K'),k('delta','Temperature after calibration',60,0,100,'K'),k('nonlinearity','Full-scale bow nonlinearity',.0001,0,.001)],'Can a calibrated 10 mV bridge measurement stay within 0.05% over temperature?',
'Nominal gain 1000 maps a 0–10 mV bridge input to x=0–10 V. Calibrate the actual output at both endpoints at ΔT=0, then apply that fixed calibration after temperature changes. An explicitly defined bowed transfer term models nonlinearity.',
'Compare amplifier classes after calibration. Change drift and nonlinearity independently and check the 5 mV output-equivalent error budget.',p=>{const x=calibration(p),at5=x.error(5);return O([
s('Write the complete synthetic measurement law','x denotes the ideal output-equivalent signal, not the bridge voltage. g0 is initial gain error, αg is gain drift and n(x) is zero at both calibration endpoints.',String.raw`m(x,\Delta T)=[1+g_0+\alpha_g\Delta T]x+G[V_{OS,0}+\alpha_{OS}\Delta T]+n(x),\quad n(x)=4\epsilon x(1-x/F)`,String.raw`G=1000,\quad F=10\,\mathrm V,\quad n(F/2)=${N(p.nonlinearity*10)}\,\mathrm V`),
s('Use the two measured endpoint values','A fixed affine calibration maps m(0,0) to zero and m(F,0) to F. It does not remeasure either endpoint when temperature changes.',String.raw`\hat x=F\frac{m(x,\Delta T)-m(0,0)}{m(F,0)-m(0,0)}`,String.raw`m(0,0)=${N(x.lo)}\,\mathrm V,\quad m(F,0)=${N(x.hi)}\,\mathrm V,\quad scale=${N(x.scale)}`),
s('Derive what remains after calibration','Initial offset and initial gain error cancel, but drift and bow remain divided by the calibrated gain. Calling the nonlinear residual unchanged would miss that scale factor.',String.raw`e(x)=\hat x-x=\frac{\alpha_g\Delta T\,x+G\alpha_{OS}\Delta T+n(x)}{1+g_0}`,String.raw`e(5\,\mathrm V)=${N(at5*1000)}\,\mathrm{mV}`),
s('Check the whole input interval against the target','Evaluate both endpoints and any interior stationary point of this quadratic error; a coarse plot sample is not used as the worst-case detector.',String.raw`E_{max}=\max_{0\le x\le F}|e(x)|,\quad E_{limit}=0.0005F`,String.raw`E_{max}=${N(x.worst*1000)}\,\mathrm{mV},\quad E_{limit}=5\,\mathrm{mV},\quad E_{max}/G=${N(x.worst/x.G*1e6)}\,\mu\mathrm V`)
],[r('Worst calibrated error',x.worst*1000,'mV'),r('Target margin',(x.limit-x.worst)*1000,'mV'),r('Bridge-input equivalent error',x.worst/x.G*1e6,'μV')],[{label:'Errors before and after fixed calibration',xLabel:'Ideal output equivalent x (V)',yLabel:'Error (mV)',traces:[{label:'Raw at selected temperature',points:samples(v=>1000*(x.raw(v,p.delta)-v),0,10)},{label:'Calibrated at selected temperature',points:samples(v=>1000*x.error(v),0,10)}]}],x.worst<=x.limit?'This declared drift/nonlinearity model meets the 0.05% full-scale target. Sensor drift, resistor errors, noise and calibration-measurement uncertainty need additional budget entries in a physical design.':'The selected model misses the 0.05% full-scale target despite exact endpoint calibration. Reduce the responsible drift or nonlinearity contribution.',x.worst*1000,'mV','Calculate the worst residual error over the input interval.','Check endpoints and the quadratic’s interior stationary point.',{table:{headers:['Contribution','Before calibration','After calibration'],rows:[['Initial offset',F(x.initialOffset)+' V','Removed at calibration temperature'],['Initial gain error',F(p.gainError),'Removed at calibration temperature'],['Temperature offset',F(x.temperatureOffset)+' V',F(x.temperatureOffset*x.scale)+' V'],['Bow at midscale',F(p.nonlinearity*10)+' V',F(p.nonlinearity*10*x.scale)+' V']]}})},{symbols:[...symbols,[String.raw`x,\hat x,m,F,G,g_0,\alpha_g,n(x),\epsilon`,'Ideal and calibrated output equivalents, measured output and full-scale output (V), nominal bridge gain 1000, initial fractional gain error, gain tempco (K⁻¹), bow error (V), and fractional full-scale bow amplitude.']]})
]
