import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {clamp,inputStage,groundLoop,shield,grid,db,clampDrawing,shieldDrawing,shieldLink} from './protection.js'
const T=String.raw
const symbols=[[T`V_{in},V_p,V_R,V_F,I_D,R_s`,'Applied voltage, protected pin voltage, symmetric rail magnitude and diode drop (V), signed source current (A), and series resistance (Ω).'],[T`k_B,T,B,e_R,I_B`,'Boltzmann constant 1.380649×10⁻²³ J/K, temperature 300 K, one-sided noise bandwidth (Hz), resistor rms noise (V), and amplifier input bias current (A).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'G. Protection and the real world',knobs,question,intro,try:attempt,solve,symbols,flow:['Draw the unwanted current or coupling path','Solve the signal and error using the same circuit','Check operating limits and the measurement cost'],route:'Use KCL and operating regions for static faults. Use phasor impedances for frequency-dependent cable loading. Capacitor states are needed for transient or stored-energy behavior; a DC clamp calculation does not predict a fast surge waveform.',limits:'Illustrative circuit models, not protection ratings for a particular device. Each lesson states its rails, diode law, current paths and excluded effects.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const source=['TI: Input overvoltage protection','https://www.ti.com/lit/pdf/sbaa227']
export const PROTECTION_LESSONS=[
L('g1','Clamp a fault without hiding the resistor cost',[k('input','Applied fault voltage',100,-100,100,'V'),k('resistance','Series resistance',1000,100,20000,'Ω'),k('duration','Rectangular fault duration',100e-6,1e-6,.001,'s')],
 'What limits the clamp current, and what does that resistor cost during normal measurement?',
 'Connect a resistor to an unloaded input with constant-drop diodes to ±12 V rails. Positive current flows from the applied source toward the pin; negative current flows in the opposite direction. The rail sources can absorb the injected current in this model.',
 'Compare 1 kΩ with 8.77 kΩ at +100 V, then reverse the fault. Compare fault current, pulse energy, normal-operation resistor noise and bias error.',p=>{const x=clamp(p);return O([
 s('Choose a physically consistent diode region','Both diodes are off while the pin can follow the source between the clamp thresholds. Beyond either threshold one diode conducts.',T`V_p=\operatorname{clip}(V_{in},-V_R-V_F,V_R+V_F)`,T`V_R=12\,V,\quad V_F=0.3\,V,\quad V_p=${N(x.pin)}\,V`),
 s('Use the resistor voltage, not the full source voltage','KCL gives the signed source current. The diode receives its magnitude in a fault; the rail voltage removes part of the applied voltage from the resistor.',T`I_D=(V_{in}-V_p)/R_s`,T`I_D=(${N(p.input)}-${N(x.pin)})/${N(p.resistance)}=${N(x.current*1000)}\,mA`),
 s('Find resistance for a declared 10 mA limit','This current target belongs to the exercise, not a universal component rating. The native PWL solution independently checks the chosen diode state and pin voltage.',T`R_{min}=\max(0,|V_{in}|-V_R-V_F)/(0.01\,A)`,T`R_{min}=${N(x.required)}\,\Omega,\quad V_{p,PWL}=${N(x.native.sol.v.pin)}\,V`),
 s('Calculate both instantaneous power and rectangular pulse energy','The ideal voltage sources hold the clamp fixed throughout the declared rectangular pulse. Actual surge shape and resistor pulse ratings require separate data.',T`P_R=I_D^2R_s,\quad W_R=P_Rt_p`,T`P_R=${N(x.power)}\,W,\quad W_R=${N(x.energy*1000)}\,mJ`),
 s('Return to normal operation and count measurement errors','With clamps off, assume 100 nA bias current and a 20 kHz rectangular noise band. Johnson noise and bias voltage have different units and cannot be added as equivalent deterministic errors.',T`e_R=\sqrt{4k_BTR_sB},\quad |V_{bias}|=I_BR_s`,T`e_R=${N(x.noise*1e6)}\,\mu V\ rms,\quad |V_{bias}|=${N(x.offset*1e6)}\,\mu V`)
 ],[r('Signed clamp current',x.current*1000,'mA'),r('Minimum resistance for 10 mA',x.required,'Ω'),r('Pulse energy',x.energy*1000,'mJ'),r('Added resistor noise',x.noise*1e6,'µV rms')],[curve('Fault current follows the conducting region','Applied voltage (V)','Signed current (mA)',samples(input=>clamp({...p,input}).current*1000,-100,100))],
 'Increasing resistance lowers fault current but raises noise and bias error. Check whether the real supply can sink clamp current, as well as diode current and resistor pulse-energy ratings; the ideal rail model assumes it can.',x.current*1000,'mA','Calculate the signed clamp current.','Subtract the clamped pin voltage before dividing by resistance.',{schematic:clampDrawing(p),table:{headers:['Series resistance (Ω)','Fault current (mA)','Normal bias error (µV)','Noise (µV rms)'],rows:[1000,8770,10000].map(resistance=>{const y=clamp({...p,resistance});return[resistance,fmt(y.current*1000),fmt(y.offset*1e6),fmt(y.noise*1e6)]})}})}, {sources:[source]}),
L('g2','Input junction conduction is not the common-mode limit',[k('input','Applied input voltage',6,-10,10,'V'),k('resistance','External current-limiting resistance',1000,100,10000,'Ω')],
 'Does zero clamp current prove an amplifier input is operating correctly?',
 'Model the input protection junctions with ±5 V rails and 0.65 V forward drops. Separately declare a valid signal common-mode interval of ±4.5 V. This simple model detects junction conduction; it does not simulate latch-up or phase reversal.',
 'Compare 4.4 V, 5.2 V and 6 V. The middle case has no junction current but is already outside the declared linear signal range.',p=>{const x=inputStage(p);return O([
 s('Separate the two boundaries','The declared valid common-mode range concerns signal operation. Forward junction conduction begins at a different voltage set by the rails and diode law.',T`|V_p|\le4.5\,V\quad\text{signal range},\qquad |V_p|=5+0.65=5.65\,V\quad\text{clamp threshold}`,T`V_{in}=${N(p.input)}\,V`),
 s('Solve each current branch','Below the lower clamp the source current is negative. Between thresholds it is zero in this unloaded ideal model; above the upper clamp it is positive.',T`I_{in}=\begin{cases}(V_{in}+5.65)/R_s&V_{in}<-5.65\\0&|V_{in}|\le5.65\\(V_{in}-5.65)/R_s&V_{in}>5.65\end{cases}`,T`I_{in}=${N(x.current*1000)}\,mA`),
 s('Recover the actual pin voltage','The source voltage and pin voltage differ once current flows through the external resistor. Check the pin against the signal range, not only the source.',T`V_p=V_{in}-I_{in}R_s`,T`V_p=${N(x.pin)}\,V,\quad\text{within signal range: ${x.linear?'yes':'no'}}`),
 s('Check the native circuit state without inventing failure behavior','The PWL solve enumerates the diode states. It has no parasitic thyristor or transistor input-pair model, so it cannot establish whether a particular amplifier latches or reverses phase.',T`V_{p,PWL}=V_p,\quad I_{source}=I_{upper}-I_{lower}`,T`I_{upper}=${N(x.native.sol.i.DH*1000)}\,mA,\quad I_{lower}=${N(x.native.sol.i.DL*1000)}\,mA`)
 ],[r('Pin voltage',x.pin,'V'),r('Signed input current',x.current*1000,'mA'),r('Within declared signal range',x.linear?1:0,'1=yes')],[curve('Three protection-current regions','Applied voltage (V)','Input current (mA)',samples(input=>inputStage({...p,input}).current*1000,-10,10))],
 x.linear?'The pin is inside this model’s declared common-mode interval. Other signal and output limits still belong to the selected device.':'The pin is outside the declared signal interval. An off clamp does not restore linear operation; inspect the actual device’s common-mode and input-current limits.',x.pin,'V','Calculate the pin voltage.','Subtract the external resistor drop from the applied input.',{schematic:clampDrawing({...p,rail:5,drop:.65}),table:{headers:['Applied input (V)','Pin (V)','Input current (mA)','Signal range'],rows:[4.4,5.2,6].map(input=>{const y=inputStage({...p,input});return[input,fmt(y.pin),fmt(y.current*1000),y.linear?'Inside':'Outside']})}})}, {sources:[source]}),
L('g3','Ground return current becomes measurement error',[k('current','Shared return current',.1,.001,1,'A'),k('resistance','Shared ground resistance',.01,.001,.1,'Ω'),k('cmrr','Differential receiver CMRR',100,40,120,'dB')],
 'Which voltage does a single-ended receiver mistake for signal?',
 'A 10 mV source is referred to a remote board ground. Shared return current lifts that ground relative to receiver ground. Compare an ideal single-ended receiver with a differential receiver whose common-mode gain is specified.',
 'Increase return resistance tenfold. Predict both errors, then increase CMRR by 20 dB and identify which receiver improves.',p=>{const x=groundLoop(p);return O([
 s('Follow the shared current through the ground impedance','Define remote-ground lift as positive for current returning toward receiver ground. This DC model uses resistance only.',T`V_g=I_gR_g`,T`V_g=${N(p.current)}(${N(p.resistance)})=${N(x.ground*1000)}\,mV`),
 s('Write the single-ended measurement reference','The source is 10 mV above remote ground, which is itself Vg above receiver ground. Those voltages add.',T`V_{SE}=V_s+V_g,\quad e_{SE}=V_g`,T`V_{SE}=${N(x.single*1000)}\,mV,\quad e_{SE}=${N(x.ground*1000)}\,mV`),
 s('Refer common-mode leakage through the differential gain','The differential receiver observes source and remote ground together. With Ad=1, Ac=10^(−CMRR/20), calculate the incremental error caused by lifting both receiver inputs by Vg. Any baseline response to Vs/2 common mode is calibrated out; choose positive leakage sign for comparison.',T`CMRR=20\log_{10}|A_d/A_c|,\quad e_{DIFF}=V_g10^{-CMRR/20}`,T`e_{DIFF}=${N(x.ground)}10^{-${N(p.cmrr)}/20}=${N(x.error*1e9)}\,nV`),
 s('Distinguish rejection from removal of the physical voltage','The shared ground still rises by Vg. Differential sensing suppresses its measurement contribution only while both inputs remain in range and CMRR holds at the disturbance frequency.',T`V_{DIFF}=V_s+e_{DIFF}`,T`V_{DIFF}=${N(x.differential*1000)}\,mV`)
 ],[r('Remote-ground lift',x.ground*1000,'mV'),r('Single-ended error',x.ground*1000,'mV'),r('Differential input error',x.error*1e9,'nV')],[curve('Specified CMRR suppresses input-referred leakage','CMRR (dB)','Input error (nV)',samples(cmrr=>groundLoop({...p,cmrr}).error*1e9,40,120))],
 'A differential connection rejects shared ground voltage; it does not eliminate that voltage or replace a sound return path. Real CMRR depends on frequency and resistor matching.',x.error*1e9,'nV','Calculate differential input-referred error.','Divide ground lift by 10^(CMRR/20), then convert volts to nanovolts.',{table:{headers:['Receiver','Measured signal (mV)','Error (µV)'],rows:[['Single-ended',fmt(x.single*1000),fmt(x.ground*1e6)],['Differential',fmt(x.differential*1000),fmt(x.error*1e6)]]}})}, {symbols:[[T`V_s,V_g,V_{SE},V_{DIFF},e`,'Source signal 10 mV, remote-ground lift, single-ended and differential measurements, and input-referred error (V).'],[T`I_g,R_g,A_d,A_c,CMRR`,'Shared return current (A), shared resistance (Ω), differential/common-mode gains (V/V), and rejection ratio (dB).']]}),
L('g4','Driven shield: less cable loading, another feedback path',[k('length','Cable length',1,.2,5,'m'),k('resistance','Source resistance',1e4,1000,1e5,'Ω'),k('gbw','Buffer gain-bandwidth',10e6,.5e6,20e6,'Hz'),k('ro','Buffer output resistance',50,10,200,'Ω')],
 'Can a driven shield be replaced by a fixed one-percent capacitance?',
 'The cable has 100 pF/m between signal and shield, and the shield has 100 pF/m to ground. A unity buffer senses the signal node and drives the shield through Ro. This bootstrap path interacts with the source resistance.',
 'Compare grounded and driven shields. Increase cable length or buffer bandwidth and watch the complete loop margin; better tracking at one frequency does not guarantee stability.',p=>{const x=shield(p);return O([
 s('Start with a grounded shield','The source resistance and signal-to-shield capacitance make one low-pass pole when the shield is grounded.',T`C_c=100\,pF/m\cdot\ell,\quad f_{ground}=1/(2\pi R_sC_c)`,T`C_c=${N(x.cable*1e12)}\,pF,\quad f_{ground}=${N(x.grounded/1000)}\,kHz`),
 s('Write the driven-shield node equations','Let v be the signal node, w the shield, and u the amplifier’s internal output. The buffer has A(s)=ωt/s; the shield’s capacitance to ground is CL.',T`(v-v_{in})/R_s+sC_c(v-w)=0,\quad(w-u)/R_o+sC_Lw+sC_c(w-v)=0,\quad u=A(s)(v-w)`,T`C_L=${N(x.load*1e12)}\,pF,\quad\omega_t=2\pi GBW=${N(x.wt)}\,s^{-1}`),
 s('Solve shield tracking before assigning effective capacitance','The tracking ratio B=w/v is complex and frequency dependent. A fixed B=0.99 would leave 0.01Cc, but the actual buffer does not maintain that real ratio at all frequencies.',T`B(s)=\frac{\omega_t+s^2R_oC_c}{\omega_t+s+s^2R_o(C_L+C_c)},\quad H(s)=\frac1{1+sR_sC_c[1-B(s)]}`,T`f_{B=0.99}=100f_{ground}=${N(x.naive/1e6)}\,MHz\quad\text{hypothetical only}`),
 s('Include source coupling in the buffer return ratio','With the source grounded, movement of the shield also moves the signal node. The denominator must retain this coupling, as well as the output load.',T`T(s)=\frac{\omega_t}{s[1+s(R_sC_c+R_o(C_L+C_c))+s^2R_sC_cR_oC_L]}`,T`f_u=${N(x.crossover/1e6)}\,MHz,\quad PM=${N(x.pm)}^\circ`),
 s('Check closed-loop stability before reporting a bandwidth','The cubic characteristic is a3s³+a2s²+s+ωt. With positive coefficients, the Routh condition is a2>a3ωt. An unstable frequency-domain curve is not an achieved usable bandwidth.',T`a_2=R_sC_c+R_o(C_L+C_c),\quad a_3=R_sC_cR_oC_L,\quad a_2-a_3\omega_t>0`,T`a_2-a_3\omega_t=${N(x.routh)}\,s,\quad\text{stable: ${x.stable?'yes':'no'}}`)
 ],[r('Grounded-shield corner',x.grounded/1000,'kHz'),r('Complete loop margin',x.pm,'°'),r('Closed-loop stable',x.stable?1:0,'1=yes'),...(x.stable?[r('Driven half-power frequency',x.corner/1e6,'MHz')]:[])],[{label:'Signal-node response; driven curve is usable only when stable',xLabel:'Frequency (Hz)',yLabel:'Magnitude (dB)',logX:true,traces:[{label:'Grounded shield',points:grid(f=>db(x.passive(f)),1e3,1e8)},{label:'Actual driven shield',points:grid(f=>db(x.at(f)),1e3,1e8)}]}],
 x.stable?'The complete loop is stable at these settings. Inspect peaking and tracking phase before interpreting the half-power crossing as useful signal bandwidth.':'The complete loop is unstable at these settings. Its formal AC response is shown for diagnosis, but no operating bandwidth is claimed. Reduce load, change the driver or add a compensation strategy.',x.grounded/1000,'kHz','Calculate the grounded-shield corner.','Use 1/(2πRsCc).',{schematic:shieldDrawing(p),handover:shieldLink(x),table:{headers:['Closed-loop pole','Real part (s⁻¹)','Imaginary part (s⁻¹)'],rows:x.poles.map((z,i)=>[i+1,fmt(z[0]),fmt(z[1])])}})}, {symbols:[[T`v_{in},v,w,u,B(s),H(s),T(s)`,'Source, signal node, shield and internal amplifier voltages (V); shield tracking ratio, signal transfer, and full return ratio.'],[T`R_s,R_o,C_c,C_L,\ell,GBW,\omega_t,s`,'Source/output resistances (Ω), cable/shield-ground capacitances (F), cable length (m), gain-bandwidth (Hz), unity angular frequency (s⁻¹), and Laplace variable.']]})
]
// Glossary additions are lesson-specific so every displayed state and diagnostic has a unit.
const protectionSymbols={
 g1:[[T`P_R,W_R,t_p,R_{min},V_{bias}`,'Resistor power (W), rectangular pulse energy (J), pulse duration (s), resistance for the stated current target (Ω), and normal-operation bias voltage (V).']],
 g4:[[T`a_2,a_3,f_u,PM,f_{ground}`,'Cubic coefficients with units s and s² after the s coefficient is normalized to one, loop unity-crossing frequency (Hz), phase margin (degrees), and grounded-shield corner (Hz).']]
}
for(const lesson of PROTECTION_LESSONS)if(protectionSymbols[lesson.id])lesson.symbols=[...lesson.symbols,...protectionSymbols[lesson.id]]
