import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {BG,returnRatioAt,complex} from '@ee-labs/network'
import {reference,ldo,thermal,selection,logGrid,db,nativeSupply,ldoDrawing} from './regulators.js'
const T=String.raw,load=k('load','Load current',.1,.001,1,'A'),cap=k('cap','Output capacitance',10e-6,1e-6,100e-6,'F'),esr=k('esr','Capacitor ESR',.1,0,2,'Ω'),fa={...k('fa','Error-amplifier pole',100,10,1000,'Hz'),group:'Amplifier model'}
const sources=[['TI: ESR, Stability, and the LDO Regulator','https://www.ti.com/lit/an/slva115a/slva115a.pdf'],['TI: LDO Basics','https://e2e.ti.com/cfs-file/__key/communityserver-discussions-components-files/196/1538.slyy151a.pdf']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'D. References and regulators',knobs,question,intro,try:attempt,solve,sources,flow:['Define the operating point and disturbances','Derive the relevant voltage, current or power balance','Check the result against the design requirement'],...extra}}
function O(steps,readings,plots,conclusion,practice,extra={}){return{steps,readings,plots,conclusion,practice:{...practice,reason:conclusion},...extra}}
const circuitSymbols=[
 [T`V_O,I_L,R_L,R_p,g_{ds}`,'Nominal output 3.3 V, DC load current (A), incremental resistive load RL=3.3/IL (Ω), pass-device output resistance Rp=10 kΩ, and gds=1/Rp (S).'],
 [T`v_o,v_a,v_c,v_r,v_s`,'Small changes from bias, in volts: output, amplifier pole-state voltage, ideal capacitor voltage, reference input and supply disturbance. They are not absolute rail voltages.'],
 [T`A_0,A(s),f_a,\tau_a,g_m,\beta`,'Amplifier DC gain 10,000; A(s)=A0/(1+sτa); amplifier pole (Hz), τa=1/(2πfa) (s); pass transconductance 0.1 S; sensed fraction β=1.25/3.3. Positive va sources current into out.'],
 [T`C,R_e,R,\tau_o,\tau_z,Z_o`,'Output capacitance (F), its series ESR (Ω), parallel resistance R=RL∥Rp (Ω), output time constant (R+Re)C (s), ESR time constant ReC (s), and open-loop output impedance (Ω).'],
 [T`s,j,\omega,f,T(s),K,H(s)`,'Laplace variable (s⁻¹), imaginary unit, angular frequency ω=2πf (rad/s), frequency (Hz), return ratio, DC return ratio K, and closed reference-to-output transfer. The characteristic equation is 1+T(s)=0.'],
 [T`f_o,f_z,f_x,PM`,'Output pole, ESR zero and loop unity-gain crossing (Hz); phase margin PM=180°+unwrapped phase of T at that crossing.']
]
const circuitLimits='Declared linear LDO model about a regulated 3.3 V operating point. The feedback sensor is ideal and does not load the output. One amplifier pole, pass gm and gds, a resistive load and capacitor ESR are included. Extra pass/gate poles, capacitor ESL, current limit, dropout and temperature dependence are excluded here; D4 checks headroom separately. Modern LDOs may use different compensation; this model does not prescribe ESR for every part.'
const route='Start with current balance to derive the circuit. Substitute s=j2πf for phasors and loop margin: this is efficient for sinusoidal steady state but does not show startup. Keep the capacitor voltages as states to compute settling and initial-condition effects. The transfer function connects both routes for this linear model; its zero-state response assumes initially settled incremental states.'
const operating=x=>s('Name the circuit before combining it','The supply is AC ground for this loop calculation. Rp therefore parallels the resistive load; the sensor returns βvo to the negative amplifier input.',T`R_L=3.3/I_L,\quad R=(1/R_L+1/R_p)^{-1},\quad A(s)=\frac{A_0}{1+s\tau_a}`,T`R_L=${N(x.rl)}\,\Omega,\quad R=${N(x.r)}\,\Omega,\quad\tau_a=${N(x.ta)}\,\mathrm s,\quad\beta=${N(x.beta)}`)
const impedance=(x,p)=>s('Solve the output-node current balance','Capacitor current leaves out through ESR and C. With supply disturbance zero, injected pass current is gm va. Dividing voltage by this current gives Zo.',T`g_mv_a=\frac{v_o}{R}+\frac{sCv_o}{1+sR_eC},\quad Z_o(s)=\frac{v_o}{g_mv_a}=\frac{R(1+s\tau_z)}{1+s\tau_o}`,T`\tau_z=${N(p.esr)}\cdot${N(p.cap)}=${N(x.tz)}\,\mathrm s,\quad\tau_o=(${N(x.r)}+${N(p.esr)})${N(p.cap)}=${N(x.to)}\,\mathrm s`)
const handover=x=>({app:'control-lab',label:'Inspect this LDO loop in Control Lab',patch:{plant:{type:'custom',params:[0,...x.loop.b,...x.loop.a]},ctrl:{type:'p',params:[1]},from:{app:'applied-analog-lab',id:'d2',label:'LDO return ratio'}},note:'Transfers the exact return ratio T(s), including ESR, as a custom plant with unity control. Control Lab shows T/(1+T); multiply that output by 1/β to recover the reference-to-output gain here. This is an incremental model, not a regulator startup simulation.'})
export const REGULATOR_LESSONS=[
L('d1','A voltage reference cancels one temperature slope',[
 k('temp','Temperature',26.85,-40,125,'°C'),k('n','Junction area ratio',8,2,16),k('trim','Fractional multiplier trim',0,-.05,.05)
],'How can a falling junction voltage and a rising thermal voltage make a nearly constant reference?',
 'A reference supplies the voltage target that an LDO later tries to hold. Add a weighted PTAT voltage, which rises with absolute temperature, to a CTAT junction voltage, which falls. Choose the weight at 300 K, then inspect the curvature across the full temperature range.',
 'Start with zero trim. Compare the local slope at 26.85 °C with the full-range variation. Add a 0.01 fractional trim and see where the slope becomes zero.',p=>{const x=reference(p),temp=p.temp+273.15;return O([
 s('Convert temperature and define the two voltage terms','Temperature laws use kelvin. UT is thermal voltage; N is the area/current-density ratio of the two ideal junctions. Natural logarithms are used.',T`T_K=T_C+273.15,\quad U_T=(k_B/q)T_K,\quad\Delta V_{BE}=U_T\ln N`,T`T_K=${N(temp)}\,\mathrm K,\quad\Delta V_{BE}=${N(x.ptat)}\,\mathrm V`),
 s('Evaluate the falling junction voltage','The shared junction law is anchored at T0=300 K. Vg is expressed as an equivalent voltage. The logarithmic term produces curvature.',T`V_{BE}(T_K)=V_g+(V_{BE0}-V_g)\frac{T_K}{T_0}-\eta U_T\ln(T_K/T_0)`,T`V_{BE}=${N(BG.eg)}+(${N(BG.vbe0)}-${N(BG.eg)})\frac{${N(temp)}}{300}-3\frac{k_B}{q}${N(temp)}\ln(${N(temp)}/300)=${N(x.vbe)}\,\mathrm V`),
 s('Differentiate before choosing the weight','The PTAT derivative includes ln N. Use the CTAT derivative at the trim temperature T0, not the selected temperature, to choose a fixed multiplier.',T`\frac{d\Delta V_{BE}}{dT_K}=\frac{k_B}{q}\ln N,\quad\frac{dV_{BE}}{dT_K}=\frac{V_{BE0}-V_g}{T_0}-\eta\frac{k_B}{q}[\ln(T_K/T_0)+1],\quad M_*=-\frac{V'_{BE}(T_0)}{(k_B/q)\ln N}`,T`\Delta V'_{BE}=${N(x.slopePTAT*1e6)}\,\mathrm{\mu V/K},\quad M_*=${N(x.optimum)},\quad M=M_*(1+${N(p.trim)})=${N(x.m)}`),
 s('Add the weighted voltages and their slopes','A zero slope is a local statement. With a fixed M, the CTAT logarithm still bends the sum away from the trim temperature.',T`V_{ref}=V_{BE}+M\Delta V_{BE},\quad V'_{ref}=V'_{BE}+M\Delta V'_{BE}`,T`V_{ref}=${N(x.vbe)}+${N(x.m)}(${N(x.ptat)})=${N(x.reference)}\,\mathrm V,\quad V'_{ref}=${N(x.slope*1e6)}\,\mathrm{\mu V/K}`),
 s('Measure the full temperature span','Evaluate both endpoints and any stationary point inside −40 to 125 °C. The box coefficient divides peak-to-peak variation by the 300 K reference and 165 K span; it is not the local derivative.',T`\Delta V_{pp}=V_{max}-V_{min},\quad TC_{box}=\frac{10^6\Delta V_{pp}}{165V_{ref}(300\,K)}`,T`\Delta V_{pp}=${N(x.span*1000)}\,\mathrm{mV},\quad TC_{box}=${N(x.box)}\,\mathrm{ppm/K}`)
 ],[r('Reference voltage',x.reference,'V'),r('Local slope',x.slope*1e6,'µV/K'),r('Full-range variation',x.span*1000,'mV'),r('Box coefficient',x.box,'ppm/K')],
 [curve('Reference curvature with one fixed multiplier','Temperature (°C)','Reference (V)',samples(t=>x.at(t).reference,-40,125)),{label:'The two terms that add to the reference',xLabel:'Temperature (°C)',yLabel:'Voltage (V)',traces:[{label:'CTAT junction',points:samples(t=>x.at(t).vbe,-40,125)},{label:'Weighted PTAT',points:samples(t=>x.m*x.at(t).ptat,-40,125)}]}],
 'First-order compensation cancels a slope at one temperature. It does not remove curvature, loading error or the need to buffer a reference before driving a load.',{question:'Calculate the multiplier that cancels the slope at 300 K.',answer:x.optimum,unit:'',hint:'Divide the magnitude of the 300 K CTAT slope by (kB/q) ln N.'},{plotNote:'The selected temperature changes the readings. Each plotted temperature uses the same multiplier; the reference is not retrimmed at every point.',table:{headers:['Temperature (°C)','Reference (V)','Local slope (µV/K)'],rows:[-40,26.85,125].map(t=>[t,fmt(x.at(t).reference),fmt(x.at(t).slope*1e6)])}})},
 {symbols:[[T`T_C,T_K,T_0`,'Celsius temperature, absolute temperature in kelvin, and the 300 K trim temperature.'],[T`k_B,q,U_T`,'Boltzmann constant 1.380649×10⁻²³ J/K, electron charge 1.602176634×10⁻¹⁹ C, and thermal voltage (V).'],[T`N,M_*,M,\delta`,'Junction area ratio (>1), ideal slope-canceling weight, actual PTAT weight, and dimensionless fractional trim δ; 0.01 means +1%.'],[T`V_{BE},\Delta V_{BE},V_{ref}`,'CTAT junction voltage, PTAT voltage difference, and their weighted sum (V). A prime denotes differentiation with respect to kelvin.'],[T`V_g,V_{BE0},\eta`,'Bandgap-equivalent voltage 1.206 V (material parameter, not a voltage-source label), junction voltage 0.650 V at 300 K, and dimensionless curvature parameter 3.'],[T`\Delta V_{pp},TC_{box}`,'Peak-to-peak reference variation (V) and full-range box temperature coefficient (ppm/K).']],route:'Use the temperature equation to evaluate the reference, then differentiate it to choose the compensation weight. A phasor or state-space model would address circuit dynamics; neither is required for this static temperature calculation.',limits:'The exact same ideal junction law as Analog IC B3. This is a reference-core model, without transistor bias circuitry, resistor drift, finite beta, amplifier offset, reference noise or output loading.',sources:[['Analog Devices: Understanding and Applying Voltage References','https://www.analog.com/en/resources/app-notes/an-82f.html']]}),
L('d2','The LDO loop, its output pole, and the ESR zero',[load,cap,esr,fa],
 'Why can changing only capacitor ESR change an LDO’s settling?',
 'The amplifier and output capacitor store two independent states. The load sets one pole, while ESR adds a zero. Trace the same circuit from KCL to a transfer function, then to phasor margin and a small-step state response.',
 'Compare ESR = 0, 0.1 and 1 Ω. Then reduce load current. Compare the pole, phase margin and ringing rather than reading DC gain alone.',p=>{const x=ldo(p),native=returnRatioAt(x.net,'A1',2*Math.PI*x.crossover),error=Math.hypot(...complex.csub(native,x.at(x.crossover)));return O([
 operating(x),impedance(x,p),
 s('Close the feedback path algebraically','Substitute va=A(s)(vr−βvo) into vo=gm Zo va. Move the output term to the left. The return ratio is the factor multiplying the returned output.',T`v_o=g_mZ_oA(s)(v_r-\beta v_o),\quad T(s)=\beta g_mA(s)Z_o(s)=\frac{K(1+s\tau_z)}{(1+s\tau_a)(1+s\tau_o)},\quad K=\beta g_mA_0R`,T`K=${N(x.beta)}(${N(x.gm)})(${N(x.a0)})(${N(x.r)})=${N(x.k)},\quad H(s)=\frac{v_o}{v_r}=\frac{T(s)}{\beta[1+T(s)]}`),
 s('Read poles and zero from their factors','A factor 1+sτ changes near f=1/(2πτ). If ESR is zero, τz is zero and there is no finite ESR zero.',T`f_o=\frac1{2\pi(R+R_e)C},\quad f_z=\frac1{2\pi R_eC}\;(R_e>0)`,T`f_o=${N(x.pole)}\,\mathrm{Hz},\quad ${x.zero?T`f_z=${N(x.zero)}\,\mathrm{Hz}`:T`\text{No finite ESR zero}`}`),
 s('Use phasors at the actual unity crossing','Evaluate s=j2πf and solve |T|=1. Phase is unwrapped over the sweep; every crossing is listed below. Phase margin belongs to the loop, not to the output transfer.',T`|T(j2\pi f_x)|=1,\quad PM=180^\circ+\arg T(j2\pi f_x)`,T`f_x=${N(x.crossover)}\,\mathrm{Hz},\quad PM=${N(x.pm)}^\circ`),
 s('Choose the states and define the initial condition','Let x=[va, vc]ᵀ. A dot is time derivative (V/s). x(0−)=0 means the incremental circuit is settled before the 1 mV reference step; both capacitor states remain continuous, so x(0+)=0. The output vo is reconstructed from the two states.',T`q_r=\frac R{R+R_e},\quad d=R_eq_rg_m,\quad v_o=q_rv_c+dv_a,\quad x(0^-)=x(0^+)=\begin{bmatrix}0\\0\end{bmatrix}`,T`q_r=${N(x.q)},\quad d=${N(x.d)},\quad v_r(t\ge0)=0.001\,\mathrm V`),
 s('Write and solve the two state equations','Amplifier charge balance gives τa·dva/dt=−va+A0(vr−βvo). Output capacitor charge balance gives τo·dvc/dt=Rgmva−vc. Substitute vo to obtain the matrix. The exponential propagates the difference from the new equilibrium.',T`\dot x=\underbrace{\begin{bmatrix}-(1+A_0\beta d)/\tau_a&-A_0\beta q_r/\tau_a\\Rg_m/\tau_o&-1/\tau_o\end{bmatrix}}_{\mathbf F}x+\begin{bmatrix}A_0/\tau_a\\0\end{bmatrix}v_r,\quad x(t)=x_\infty+e^{\mathbf Ft}[x(0^+)-x_\infty]`,T`\mathbf F=\begin{bmatrix}${N(x.state[0][0])}&${N(x.state[0][1])}\\${N(x.state[1][0])}&${N(x.state[1][1])}\end{bmatrix}\,\mathrm{s^{-1}},\quad v_o(\infty)=${N(x.dc)}(0.001)=${N(x.dc*.001)}\,\mathrm V`)
 ],[r('Output pole',x.pole,'Hz'),r('Loop crossover',x.crossover/1000,'kHz'),r('Phase margin',x.pm,'°'),r('Reference/output DC gain',x.dc)],
 [{...curve('Return ratio: unity gain is 0 dB','Frequency (Hz)','Loop gain (dB)',logGrid(f=>db(x.at(f)))),logX:true},{...curve('Loop phase: evaluate at the same crossover','Frequency (Hz)','Phase (°)',logGrid(f=>(Math.atan(2*Math.PI*f*x.tz)-Math.atan(2*Math.PI*f*x.ta)-Math.atan(2*Math.PI*f*x.to))*180/Math.PI)),logX:true},curve('Two-state response to a 1 mV reference step','Time (µs)','Output change (mV)',samples(t=>x.response(t/1e6)*1000,0,x.tEnd*1e6,601))],
 x.pm<45?'This model has less than 45° phase margin and a ringing response. ESR moves a zero, but a real LDO’s additional poles and capacitor requirements still determine its allowed operating range.':'This model has at least 45° phase margin. Check the step response as well; margin alone does not specify all settling behavior.',
 {question:'Calculate the output pole in hertz.',answer:x.pole,unit:'Hz',hint:'Use R=RL∥Rp, then 1/[2π(R+ESR)C].'},
 {schematic:ldoDrawing(p),handover:handover(x),check:`Independent native loop break and the displayed transfer differ by ${fmt(error)} at crossover.`,plotNote:'The state trace starts from zero incremental capacitor voltages. It shows eight decay time constants or up to eight ringing cycles, whichever is shorter; a lightly damped circuit may still be settling at the right edge.',table:{headers:['Unity crossing','Frequency (Hz)','Phase margin (°)'],rows:x.crossings.map(c=>[c.direction,fmt(c.crossover),fmt(c.pm)])}})},
 {symbols:[...circuitSymbols,[T`x,\dot x,x(0^-),x(0^+),x_\infty,\mathbf F,q_r,d`,'State vector [va, vc]ᵀ (V), its time derivative, states just before/after the step, final equilibrium, state matrix (s⁻¹), resistance-divider factor, and direct output coefficient. Both qᵣ and d are dimensionless.']],route,limits:circuitLimits}),
L('d3','Supply rejection follows every coupling path',[load,cap,{...esr,value:1},fa,k('frequency','Ripple frequency',100,1,1e7,'Hz'),k('ripple','Input ripple RMS',.1,.001,.2,'V'),{...k('rho','Reference supply coupling',0,0,.001),group:'Additional supply paths'},{...k('alpha','Amplifier supply coupling',0,0,1),group:'Additional supply paths'}],
 'Does high loop gain guarantee the same amount of supply rejection?',
 'Drive the input supply with a sine and keep the independent reference signal at zero. Ripple can enter through pass-device output resistance, the reference, or the amplifier. Add these complex paths before taking the magnitude.',
 'Start with both additional paths zero. Increase frequency, then set reference coupling to 0.001. Compare actual PSRR with feedback suppression alone.',p=>{const x=ldo(p),f=p.frequency,h=x.paths(f),m=Math.hypot(...h.total),native=nativeSupply(x,f),rejection=-db(h.total),output=m*p.ripple;return O([
 operating(x),impedance(x,p),
 s('Keep the supply term in KCL','Unlike D2, the top of Rp is now driven by vs. Moving vs/Rp to the right identifies a supply-injected current. Define ρ as supply coupling at the reference input and α as coupling at the amplifier drive before its pole.',T`\frac{v_o-v_s}{R_p}+\frac{v_o}{R_L}+\frac{sCv_o}{1+sR_eC}=g_mv_a,\quad v_a=\frac{A_0(v_r+\rho v_s-\beta v_o)+\alpha v_s}{1+s\tau_a}`,T`\rho=${N(p.rho)},\quad\alpha=${N(p.alpha)},\quad g_{ds}=1/R_p=${N(1/x.rpass)}\,\mathrm S,\quad v_r=0`),
 s('Solve for the closed supply transfer','Define F(s)=1/(1+sτa). The three numerator terms are different entry paths. They share the same feedback denominator; their phases must be preserved when added.',T`H_s(s)=\frac{v_o}{v_s}=\frac{Z_o(s)\,[g_{ds}+g_mA(s)\rho+g_m\alpha F(s)]}{1+T(s)}`),
 s('Evaluate one phasor at the selected frequency','Each term in the table is already divided by 1+T. Add real and imaginary parts to get the total complex voltage ratio. Negative PSRR is possible near a resonance or with strong coupling.',T`H_s=H_{pass}+H_{ref}+H_{amp}`,T`H_s(j2\pi\cdot${N(f)})=${N(h.total[0])}+j(${N(h.total[1])}),\quad |H_s|=${N(m)}`),
 s('Convert coupling to rejection and output ripple','PSRR uses input/output amplitude, hence the minus sign. RMS-to-RMS scaling is valid for this single sinusoid. Feedback suppression |1+T| omits the open-loop feedthrough numerator and is not generally PSRR.',T`PSRR=-20\log_{10}|H_s|,\quad V_{o,rms}=|H_s|V_{s,rms}`,T`PSRR=${N(rejection)}\,\mathrm{dB},\quad V_{o,rms}=${N(m)}(${N(p.ripple)})=${N(output*1e6)}\,\mathrm{\mu V}`)
 ],[r('Supply rejection',rejection,'dB'),r('Output ripple RMS',output*1e6,'µV'),r('Feedback suppression only',db(complex.cadd([1,0],x.at(f))),'dB')],
 [{label:'Actual supply rejection versus feedback suppression',xLabel:'Frequency (Hz)',yLabel:'Ratio (dB)',logX:true,traces:[{label:'PSRR: −20 log |Hs|',points:logGrid(f=>-db(x.paths(f).total))},{label:'Feedback only: 20 log |1+T|',points:logGrid(f=>db(complex.cadd([1,0],x.at(f))))}]}],
 'Large low-frequency loop gain suppresses pass-path disturbances, while reference coupling can approach ρ/β. PSRR and intrinsic regulator noise are separate specifications.',
 {question:'Calculate the output ripple in microvolts RMS.',answer:output*1e6,unit:'µV RMS',hint:'Multiply input RMS ripple by 10^(−PSRR/20), then convert to microvolts.'},
 {schematic:ldoDrawing(p),check:`A native AC supply excitation differs from the analytical complex transfer by ${fmt(Math.hypot(...complex.csub(native,h.total)))}.`,table:{headers:['Closed supply path','Real ratio (V/V)','Imaginary ratio (V/V)'],rows:[['Pass resistance',h.pass],['Reference',h.reference],['Amplifier',h.amplifier],['Total',h.total]].map(([name,z])=>[name,fmt(z[0]),fmt(z[1])])},plotNote:'The sweep keeps the same load and capacitor. The selected frequency changes the table and RMS readings. All coupling coefficients are illustrative and frequency independent before the named amplifier pole.'})},
 {symbols:[...circuitSymbols,[T`\rho,\alpha,F(s),H_s,H_{pass},H_{ref},H_{amp}`,'Dimensionless supply/reference coupling, supply/amplifier-drive coupling, unit-gain amplifier pole, total supply transfer and its three complex contributions.'],[T`PSRR,V_{s,rms},V_{o,rms}`,'Supply rejection in dB and RMS sinusoidal input/output ripple amplitudes (V).']],route:'Use KCL to identify every supply path, then solve with phasors for a sinusoidal disturbance. Complex addition captures reinforcement and cancellation. A state solution is useful for a supply step; replacing it with one-frequency PSRR would lose the transient.',limits:circuitLimits}),
L('d4','Headroom and heat limit the usable output',[k('vin','Input voltage',12,3.3,15,'V'),load,k('iq','Quiescent current',50e-6,0,.005,'A'),k('ron','Declared pass on-resistance',.3,.05,2,'Ω'),k('ambient','Ambient temperature',25,-20,85,'°C'),k('theta','Junction-to-ambient resistance',50,10,150,'K/W')],
 'Can an LDO regulate the desired voltage and stay below its thermal limit?',
 'Check voltage headroom before trusting the linear loop. Then account for both load-current loss and quiescent-current loss. A junction-to-ambient thermal resistance converts that same power into a steady-state temperature estimate.',
 'At 100 mA compare 12 V with 5 V input. Lower input to 3.3 V to expose dropout. At 12 V increase load to 1 A and inspect the thermal margin.',p=>{const x=thermal(p);return O([
 s('Check the declared dropout boundary','Use an illustrative fully-on pass resistance. This tests whether the desired 3.3 V is feasible; it does not solve the output after loss of regulation.',T`V_{head}=V_{in}-V_O,\quad V_{DO}=I_LR_{on},\quad V_{head}\ge V_{DO}`,T`V_{head}=${N(p.vin)}-3.3=${N(x.headroom)}\,\mathrm V,\quad V_{DO}=${N(p.load)}(${N(p.ron)})=${N(x.dropout)}\,\mathrm V`),
 s('Build one power ledger','IQ is drawn from the input supply to ground. The pass device carries IL. If headroom fails, this ledger is only the hypothetical target operating point.',T`P_{in}=V_{in}(I_L+I_Q),\quad P_{out}=V_OI_L,\quad P_{loss}=P_{in}-P_{out}=(V_{in}-V_O)I_L+V_{in}I_Q`,T`P_{loss}=(${N(p.vin)}-3.3)${N(p.load)}+${N(p.vin)}(${N(p.iq)})=${N(x.loss)}\,\mathrm W`),
 s('Include quiescent current in efficiency','Vout/Vin is the IQ=0 limit. At light load, ground current can be a significant fraction of input current.',T`\eta=\frac{P_{out}}{P_{in}}=\frac{V_OI_L}{V_{in}(I_L+I_Q)}`,T`\eta=\frac{${N(x.pout)}}{${N(x.pin)}}=${N(100*x.eta)}\%`),
 s('Convert dissipation to junction temperature','θJA is an assumed steady-state package-and-board thermal resistance. The declared maximum for this lesson is 125 °C. An estimate above that limit rejects the design; it does not model shutdown.',T`\Delta T_J=\theta_{JA}P_{loss},\quad T_J=T_A+\Delta T_J,\quad M_T=125^\circ\mathrm C-T_J`,T`T_J=${N(p.ambient)}+${N(p.theta)}(${N(x.loss)})=${N(x.tj)}^\circ\mathrm C,\quad M_T=${N(x.thermalMargin)}\,\mathrm K`),
 s('Return to the load-dependent pole','Even if temperature and headroom are acceptable, changing load changes the stability problem. Keep Rp=10 kΩ, C=10 µF and ESR=0.1 Ω for this comparison. This linearized pole is conditional on regulation.',T`R=(I_L/V_O+1/R_p)^{-1},\quad f_o=[2\pi(R+R_e)C]^{-1}`,T`f_o(I_L=${N(p.load)}\,\mathrm A)=${N(x.pole)}\,\mathrm{Hz},\quad f_o(1\,\mathrm{mA})=${N(thermal({load:.001}).pole)}\,\mathrm{Hz}`)
 ],[r('Headroom margin',x.headroom-x.dropout,'V'),r(x.regulated?'Dissipation':'Target dissipation (infeasible)',x.loss,'W'),r(x.regulated?'Estimated junction temperature':'Target junction temperature (infeasible)',x.tj,'°C'),r('Thermal margin at target',x.thermalMargin,'K')],
 [curve('Target temperature versus input voltage','Input voltage (V)','Target junction temperature (°C)',samples(v=>thermal({...p,vin:v}).tj,3.3,15)),{...curve('Conditional output pole versus load','Load current (A)','Pole (Hz)',logGrid(i=>thermal({...p,load:i}).pole,.001,1)),logX:true}],
 !x.regulated?'Headroom is insufficient. The desired 3.3 V operating point is infeasible; the target power, temperature and pole calculations are conditional, not a prediction of the dropped-out output.':x.tj>125?'Headroom is sufficient, but the target exceeds 125 °C. Reduce dissipation or thermal resistance before treating this as a usable operating point.':'The target passes the declared headroom and steady-state thermal checks. Recheck loop behavior at this load in D2.',
 {question:'Calculate total dissipation at the desired 3.3 V operating point.',answer:x.loss,unit:'W',hint:'Add (Vin−3.3)IL and VinIQ. If dropout fails, interpret the result as a hypothetical target.'},
 {table:{headers:['Target power ledger','Power (W)'],rows:[['Input',fmt(x.pin)],['Delivered to load',fmt(x.pout)],['Pass-device loss',fmt((p.vin-3.3)*p.load)],['Quiescent loss',fmt(p.vin*p.iq)],['Total loss',fmt(x.loss)]]},plotNote:'Temperature is a target calculation: points below the headroom boundary are infeasible, and points above 125 °C fail the thermal requirement. The load-pole sweep uses fixed component values, not a temperature-dependent transistor simulation.'})},
 {symbols:[[T`V_{in},V_O,I_L,I_Q,R_{on},V_{head},V_{DO}`,'Input voltage, target output 3.3 V, load current, quiescent input-to-ground current, declared pass on-resistance, available headroom and required dropout (V, A, Ω).'],[T`P_{in},P_{out},P_{loss},\eta`,'Input, output and dissipated powers (W), and dimensionless efficiency.'],[T`T_A,T_J,\Delta T_J,\theta_{JA},M_T`,'Ambient and estimated junction temperatures (°C), junction rise (K), thermal resistance (K/W), and thermal margin below 125 °C (K).'],[T`R_L,R_p,R,R_e,C,f_o`,'Resistive load, 10 kΩ pass output resistance, their parallel resistance, 0.1 Ω ESR, 10 µF capacitor and linear output pole (Hz).']],route:'Use DC voltage balance for headroom and power conservation for efficiency. The steady thermal resistance estimates the final temperature; a thermal state model would be needed for warm-up time. Phasors describe the conditional electrical pole, but cannot certify dropout or heat limits.',limits:'Declared on-resistance headroom check, not a nonlinear dropout solve. Fixed IQ and θJA; no current limit, temperature-dependent losses or thermal shutdown. The plotted temperatures are conditional target estimates; θJA depends on the real package, copper area and airflow.'}),
L('d5','Choose a regulator for both power and signal quality',[
 k('vin','Input voltage',5,4,15,'V'),{...load,value:.2,min:.05},k('eta','Assumed buck efficiency',.9,.7,.98),
 {...k('enLinear','Linear white-noise density',100e-9,10e-9,1e-6,'V/√Hz'),group:'Noise and ripple assumptions'},
 {...k('enBuck','Buck white-noise density',500e-9,10e-9,2e-6,'V/√Hz'),group:'Noise and ripple assumptions'},
 {...k('ripple','Switching ripple peak',.01,.0001,.1,'V'),group:'Noise and ripple assumptions'},
 {...k('fs','Switching frequency',1e6,5e4,2e6,'Hz'),group:'Noise and ripple assumptions'},
 {...k('adc','ADC sample rate',96000,8000,192000,'Hz'),group:'Sampling assumptions'}
 ],'Which architecture meets a 3.3 V rail’s heat and noise requirements?',
 'Compare a linear regulator and a buck at the same target voltage and load. The task is less than 100 µV RMS over 0–100 kHz. Use declared noise densities and a declared buck efficiency, then distinguish out-of-band ripple from the signal an ADC might alias.',
 'At 5 V and 200 mA, compare both noise budgets. Lower buck noise density to 100 nV/√Hz. Then compare 12 V at 1 A, and move switching frequency into the 100 kHz band.',p=>{const x=selection(p),band=1e5;return O([
 s('Fix the task before choosing the architecture','The output target and integration band are fixed. This comparison uses 50 µA linear IQ, 0.3 Ω pass on-resistance, 25 °C ambient and 50 K/W thermal resistance.',T`V_O=3.3\,\mathrm V,\quad B=100000\,\mathrm{Hz},\quad V_{n,max}=100\,\mathrm{\mu V_{rms}},\quad P_{out}=V_OI_L`,T`P_{out}=3.3(${N(p.load)})=${N(x.pout)}\,\mathrm W`),
 s('Compute loss from the same delivered power','The buck efficiency is an explicit scenario assumption, not a simulated part result. Changing efficiency changes its required input power.',T`P_{loss,L}=(V_{in}-V_O)I_L+V_{in}I_Q,\quad P_{loss,B}=P_{out}(1/\eta_B-1)`,T`P_{loss,L}=${N(x.linear.loss)}\,\mathrm W,\quad P_{loss,B}=${N(x.pout)}(1/${N(p.eta)}-1)=${N(x.buckLoss)}\,\mathrm W`),
 s('Integrate the stated white-noise spectrum','en is a one-sided output voltage amplitude density. Squaring it gives PSD; integrating 0 to B gives variance. This simplified comparison excludes 1/f noise and does not count switching ripple as white noise.',T`S_v(f)=e_n^2,\quad V_{n,rms}=\sqrt{\int_0^B S_v(f)\,df}=e_n\sqrt B`,T`V_{n,L}=${N(p.enLinear)}\sqrt{100000}=${N(x.linearNoise*1e6)}\,\mathrm{\mu V},\quad V_{n,B}=${N(p.enBuck)}\sqrt{100000}=${N(x.buckNoise*1e6)}\,\mathrm{\mu V}`),
 s('Count in-band ripple separately','Ripple is one sinusoid with the specified peak amplitude. Its RMS is peak/√2. Add its power to uncorrelated noise only when its frequency lies inside the stated brick-wall measurement band.',T`V_{B,band}^2=e_{n,B}^2B+\begin{cases}V_{r,pk}^2/2&f_s\le B\\0&f_s>B\end{cases}`,T`f_s=${N(p.fs)}\,\mathrm{Hz},\quad V_{B,band}=${N(x.buckTotal*1e6)}\,\mathrm{\mu V_{rms}}`),
 s('Check what an unfiltered ADC can see','Out-of-band analog ripple can alias after sampling. Fold switching frequency into [0, fADC/2]. A real analog anti-alias filter must reduce the ripple before sampling; a digital filter cannot undo aliasing.',T`f_{alias}=|f_s-m f_{ADC}|,\quad m=\operatorname{round}(f_s/f_{ADC})`,T`f_{alias}=|${N(p.fs)}-${Math.round(p.fs/p.adc)}(${N(p.adc)})|=${N(x.alias)}\,\mathrm{Hz}`),
 s('Compare power and signal requirements together','For the linear candidate, check dropout, junction temperature and in-band noise. For the buck, the displayed pass/fail covers the declared signal budget only; its thermal, stability and loss design remain to be checked in Power Lab.',T`M_{n,L}=100-V_{n,L}[\mathrm{\mu V}],\quad M_{n,B}=100-V_{B,band}[\mathrm{\mu V}]`,T`M_{n,L}=${N(100-x.linearNoise*1e6)}\,\mathrm{\mu V},\quad M_{n,B}=${N(100-x.buckTotal*1e6)}\,\mathrm{\mu V}`)
,
 s('Prepare the ideal buck operating point','The Power Lab link uses duty D=3.3/Vin and load resistance RL=3.3/IL. Choose at least 100 µH, increasing L when necessary so the estimated peak-to-peak inductor ripple stays below 40% of the average load. This keeps the linked ideal buck in continuous conduction.',T`D=V_O/V_{in},\quad R_L=V_O/I_L,\quad\Delta I_{L,pp}\simeq\frac{V_O(1-D)}{Lf_s},\quad L=\max\!\left(100\,\mathrm{\mu H},\frac{V_O(1-D)}{0.4I_Lf_s}\right)`,T`D=${N(x.duty)},\quad R_L=${N(x.rl)}\,\Omega,\quad L=${N(x.inductance*1e6)}\,\mathrm{\mu H}`)
 ],[r('Linear dissipation',x.linear.loss,'W'),r('Buck assumed dissipation',x.buckLoss,'W'),r('Linear in-band RMS',x.linearNoise*1e6,'µV'),r('Buck in-band RMS',x.buckTotal*1e6,'µV'),r('Unfiltered ripple alias',x.alias,'Hz')],
 [{label:'Dissipation at the same load and output target',xLabel:'Input voltage (V)',yLabel:'Loss (W)',traces:[{label:'Linear, including IQ',points:samples(v=>thermal({vin:v,load:p.load}).loss,4,15)},{label:'Buck, fixed assumed efficiency',points:samples(()=>x.buckLoss,4,15)}]},
 {label:'Integrated white noise, before adding the ripple tone',xLabel:'Upper integration frequency (Hz)',yLabel:'Noise (µV RMS)',traces:[{label:'Linear',points:samples(b=>p.enLinear*Math.sqrt(b)*1e6,0,band)},{label:'Buck',points:samples(b=>p.enBuck*Math.sqrt(b)*1e6,0,band)}]}],
 `${x.linearPass?'The linear candidate passes the declared headroom, thermal and noise checks.':'The linear candidate misses at least one declared headroom, thermal or noise check.'} ${x.buckPass?'The buck meets the assumed in-band signal budget; its physical implementation still needs verification.':'The buck misses the assumed in-band signal budget; lower noise or added filtering is required.'}`,
 {question:'Calculate buck dissipation at the selected assumed efficiency.',answer:x.buckLoss,unit:'W',hint:'Use 3.3 IL(1/ηB−1); do not assign that assumed efficiency to the ideal switching model.'},
 {table:{headers:['Requirement or tradeoff','Linear candidate','Buck candidate'],rows:[['In-band RMS below 100 µV',x.linearNoise<100e-6?'Pass':'Fail',x.buckPass?'Pass':'Fail'],['Linear headroom check',x.linear.regulated?'Pass':'Fail','Requires converter design'],['Junction ≤125 °C',x.linear.tj<=125?'Pass':'Fail','Not established by assumed efficiency'],['Main advantage','No switching tone in this model','Lower assumed power loss'],['Main cost','Heat from input/output voltage difference','Switching ripple, filtering and converter design']]},plotNote:'Noise and efficiency are declared assumptions, not device specifications. The 100 kHz integration band is an analog measurement definition, not an anti-alias filter. The alias calculation assumes no input filtering; at an integer clock ratio the ripple can appear as phase-dependent DC.',
 handover:{app:'power-lab',label:'Explore this operating point as an ideal buck',patch:{blocks:[{type:'buck',params:[p.vin,x.duty,x.inductance,100e-6,x.rl,p.fs]}],from:{app:'applied-analog-lab',id:'d5',label:'3.3 V regulator comparison'}},note:`Open Power Lab B3 with Vin=${fmt(p.vin)} V, duty=${fmt(x.duty)}, load=${fmt(x.rl)} Ω, L=${fmt(x.inductance*1e6)} µH, C=100 µF, and fs=${fmt(p.fs)} Hz. Duty is 3.3/Vin. Inductance is max(100 µH, 3.3(1−D)/(0.4 IL fs)), keeping estimated ripple at or below 40% of load current so the ideal converter remains in continuous conduction. The declared efficiency and noise budget above are not transferred or claimed as switching-simulation results.`}})},
 {symbols:[[T`V_{in},V_O,I_L,I_Q,P_{out},P_{loss,L},P_{loss,B},\eta_B`,'Input and output voltages, load and linear quiescent currents, output power, linear/buck losses (W), and assumed buck efficiency (fraction).'],[T`e_{n,L},e_{n,B},S_v(f),B,V_{n,L},V_{n,B}`,'Linear/buck white-noise amplitude densities (V/√Hz), one-sided voltage PSD (V²/Hz), integration bandwidth (Hz), and integrated noise (V RMS).'],[T`V_{r,pk},f_s,V_{B,band},V_{n,max}`,'Switching ripple peak (V), switching frequency (Hz), total buck ripple-plus-noise in the band (V RMS), and the 100 µV RMS limit.'],[T`D,R_L,L,\Delta I_{L,pp}`,'Ideal buck duty (fraction), load resistance (Ω), link inductance (H), and estimated peak-to-peak inductor-current ripple (A).'],[T`f_{ADC},m,f_{alias},M_{n,L},M_{n,B}`,'ADC sample rate (Hz), nearest integer clock multiple, folded ripple frequency (Hz), and remaining linear/buck noise margin (µV).']],route:'Use a power ledger to compare losses and a PSD integral to compare noise. Phasors can predict ripple attenuation through a filter; sampled-time analysis predicts aliasing. A switching state model in Power Lab can then test the physical converter. No single gain or efficiency number answers all these questions.',limits:'Illustrative architecture comparison with independent output white-noise densities, a single ripple tone, and fixed assumed buck efficiency. Linear headroom and thermal checks are inherited from D4. Buck stability, magnetics, EMI and device temperature are not established here. Noise densities and the ripple tone are scenario inputs; they are not inferred from the LDO small-signal model.'})
]
