import {knob as k,step as s,reading as r,curve,texnum as N} from '@ee-labs/lessons/model'
import {A0,loadCircuit,tiaCircuit,compositeCircuit,stability,at,logSamples,loopHandover,loadDrawing,tiaDrawing} from './stability.js'
const gbw=k('gbw','Gain-bandwidth product',10e6,1e6,30e6,'Hz'),ro=k('ro','Open-loop output resistance',50,10,200,'Ω'),cl=k('cl','Load capacitance',1e-9,100e-12,10e-9,'F'),rf=k('rf','Feedback resistance',1e6,1e5,5e6,'Ω'),cin=k('cin','Input capacitance',25e-12,5e-12,100e-12,'F')
const symbols=[[String.raw`A_0,A(s),GBW,\tau_a`,'DC open-loop gain 100,000, amplifier transfer, gain-bandwidth product (Hz), and dominant-pole time constant A0/(2πGBW) (s).'],[String.raw`s,j,f,T(s)`,'Laplace variable (s⁻¹), imaginary unit, frequency (Hz), and dimensionless negative-feedback return ratio. T is defined so the loop characteristic is 1+T=0.'],[String.raw`f_x,PM`,'Loop unity-gain crossover (Hz) and phase margin 180° + phase(T) at that crossover.'],[String.raw`V_{in},V_{amp},V_{out}`,'Input, pre-isolation amplifier output and load voltages, all relative to ground (V).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'B. Stability on a board',knobs,question,intro,try:attempt,solve,symbols,flow:['Identify the feedback sensing point','Compute loop gain and close the same circuit','Compare stability, settling and useful output'],sources:[['TI: Transimpedance amplifier design considerations','https://www.ti.com/document-viewer/lit/html/ssztbc4']],route:'Use the phasor return ratio to locate crossover and phase margin. Solve the capacitor state equations to see ringing and settling. The transfer-function route connects both descriptions, while a DC gain check alone misses stability.',limits:'Linear, single-dominant-pole amplifiers with finite DC gain. The native circuit and displayed transfer share the same resistances and capacitors. Small test steps avoid a large-signal claim; slew, clipping, extra device poles and layout coupling are excluded.',...extra}}
function O(x,steps,conclusion,practice,extra={}){const band=[x.crossover/100,x.crossover*100];return{steps,readings:[r('Loop crossover',x.crossover/1000,'kHz'),r('Phase margin',x.pm,'°'),r('Closed-loop −3 dB bandwidth',x.bandwidth/1000,'kHz'),r('Native first-peak overshoot',x.overshoot,'%')],plots:[{...curve('Return-ratio magnitude','Frequency (Hz)','Loop gain (dB)',logSamples(f=>20*Math.log10(Math.hypot(...at(x.loop,f))),...band)),logX:true},{...curve('Return-ratio phase','Frequency (Hz)','Phase (°)',logSamples(f=>{const z=at(x.loop,f);return Math.atan2(z[1],z[0])*180/Math.PI},...band)),logX:true},curve('Native circuit response to a small step','Time (μs)','Output / final output',x.points)],conclusion,practice:{...practice,reason:conclusion},plotNote:'Crossover belongs to the return ratio T(s). Closed-loop bandwidth belongs to the output transfer and is a different frequency. The time trace comes from native state propagation, not a sketch inferred from phase margin. Lightly damped traces show up to eight ringing cycles; they can require longer to settle.',check:`Native loop-breaking and the displayed rational return ratio differ by ${N(x.checkError)} in complex magnitude at crossover.`,handover:loopHandover(x,extra.id),...extra}}
const margins=x=>s('Locate crossover before reading phase','Solve |T(j2πfx)|=1, then measure phase at that same frequency. All models here have one loop magnitude crossing.',String.raw`|T(j2\pi f_x)|=1,\quad PM=180^\circ+\arg T(j2\pi f_x)`,String.raw`f_x=${N(x.crossover/1000)}\,\mathrm{kHz},\quad PM=${N(x.pm)}^\circ`)
const resultStep=x=>s('Close the loop and check the time response','The native circuit propagates its capacitor states after a small step. Its first maximum and transfer-function bandwidth describe the actual output, not the loop gain.',String.raw`H(s)=V_{out}/V_{in},\quad |H(j2\pi f_{3dB})|=|H(0)|/\sqrt2`,String.raw`f_{3dB}=${N(x.bandwidth/1000)}\,\mathrm{kHz},\quad overshoot\simeq${N(x.overshoot)}\%`)
export const STABILITY_LESSONS=[
L('b1','A capacitive load takes away phase margin',[gbw,ro,cl],'Why does a unity-gain buffer ring even when its DC gain is correct?',
'The internal amplifier pole is only one stored state. Output resistance and load capacitance add a second pole inside the feedback loop. The two delays reduce phase margin at unity loop gain.',
'Increase load capacitance by ten. Compare phase margin and the native output overshoot.',p=>{const x=stability(loadCircuit(p));return O(x,[
s('Locate both physical poles','The amplifier has A(s)=A0/(1+sτa). With no DC load or isolation resistor, Ro and CL form the output pole.',String.raw`\tau_a=A_0/(2\pi GBW),\quad f_L=1/(2\pi R_oC_L)`,String.raw`\tau_a=${N(x.tau)}\,\mathrm s,\quad f_L=${N(x.pole/1e6)}\,\mathrm{MHz}`),
s('Build the return ratio from the feedback path','The feedback senses the loaded output. The output pole therefore multiplies the amplifier transfer inside T.',String.raw`T(s)=\frac{A_0}{(1+s\tau_a)(1+sR_oC_L)},\quad H(s)=\frac{T(s)}{1+T(s)}`),margins(x),resultStep(x)
], 'The DC loop corrects output error, but the delayed correction overshoots. A wide gain bandwidth does not guarantee a well-damped loaded buffer.',{question:'Calculate the load pole in megahertz.',answer:x.pole/1e6,unit:'MHz',hint:'Use 1/(2πRoCL), then convert hertz to megahertz.'},{id:'b1',schematic:loadDrawing({...p,riso:0,rl:Infinity})})},{symbols:[...symbols,[String.raw`R_o,C_L,f_L`,'Internal output resistance (Ω), load capacitance (F), and their pole frequency (Hz).']]}),
L('b2','An isolation resistor trades stability for load accuracy',[gbw,ro,cl,k('riso','Isolation resistor',50,0,200,'Ω'),k('rl','DC load resistance',1000,500,10000,'Ω')],'Can moving the capacitive load outside the sensing point restore stability?',
'Feedback senses Vamp before Riso. The resistor introduces a stabilizing zero in the loop, but the DC load voltage is lower than Vamp. Both consequences must be included in the same model.',
'Compare Riso = 0, 22, 50 and 100 Ω. Then lower RL and compare the achieved load voltage.',p=>{const x=stability(loadCircuit(p)),d=p.riso/(p.riso+p.rl);return O(x,[
s('Keep the actual load impedance','The capacitor and resistor are in parallel; the feedback divider therefore depends on frequency.',String.raw`Z_L=\frac{R_L}{1+sR_LC_L},\quad K(s)=\frac{R_{iso}+Z_L}{R_o+R_{iso}+Z_L},\quad T=A(s)K(s)`),
s('Separate sensing-point and load transfers','Only Vamp is sensed. The load transfer includes the additional divider after that point.',String.raw`\frac{V_{amp}}{V_{in}}=\frac{T}{1+T},\quad\frac{V_{out}}{V_{amp}}=\frac{Z_L}{R_{iso}+Z_L}`,String.raw`\frac{V_{out}(0)}{V_{amp}(0)}=\frac{${N(p.rl)}}{${N(p.rl+p.riso)}}=${N(1-d)},\quad divider\ loss=${N(100*d)}\%`),margins(x),resultStep(x)
], 'The isolation resistor can improve phase margin while reducing delivered DC voltage. Moving feedback to the far side would create a different loop and would need a new stability check.',{question:'Calculate the DC divider loss as a percentage.',answer:100*d,unit:'%',hint:'Use 100 Riso/(Riso+RL). This is the loss from Vamp to Vout.'},{id:'b2',schematic:loadDrawing(p),table:{headers:['Quantity','Value'],rows:[['Load/input DC gain',x.dc],['Load/amp DC ratio',1-d],['Load pole without isolation (Hz)',1/(2*Math.PI*p.ro*p.cl)]]}})},{symbols:[...symbols,[String.raw`R_o,R_{iso},R_L,C_L,Z_L`,'Internal resistance, isolation resistance, DC load (Ω), load capacitance (F) and complex parallel load impedance (Ω).'],[String.raw`K(s)`,'Dimensionless transfer from the amplifier’s internal controlled voltage to its sensed output.']]}),
L('b3','Input capacitance destabilizes a photodiode amplifier',[gbw,rf,cin],'Why does a transimpedance amplifier with a large feedback resistor ring?',
'Input capacitance lets high-frequency current bypass the feedback resistor. The noise gain rises with frequency, making the return ratio fall with nearly two poles before crossover.',
'Increase photodiode/input capacitance and compare the noise-gain zero with the loop crossover.',p=>{const x=stability(tiaCircuit(p),{input:1e-9}),approx=Math.sqrt(p.gbw/(2*Math.PI*p.rf*p.cin));return O(x,[
s('Write current balance at the summing node','Positive photocurrent enters the summing node. The finite-gain amplifier drives the output negative to remove that current through Rf.',String.raw`I_{ph}=sC_{in}V_-+(V_--V_o)/R_f,\quad V_o=-A(s)V_-`),
s('Separate feedback factor and noise gain','With the input current killed, the return path is an RC low-pass. Noise gain is its reciprocal.',String.raw`NG(s)=1+sR_fC_{in},\quad T(s)=A(s)/NG(s)`,String.raw`f_z=1/(2\pi R_fC_{in})=${N(x.noiseZero/1000)}\,\mathrm{kHz}`),
s('Estimate crossover from the two asymptotes','The square-root estimate assumes the amplifier is above its dominant pole and noise gain is well above one. The next step evaluates the finite-A0 model.',String.raw`|A|\simeq GBW/f,\quad |NG|\simeq2\pi fR_fC_{in},\quad f_{x,approx}=\sqrt{GBW/(2\pi R_fC_{in})}`,String.raw`f_{x,approx}=${N(approx/1000)}\,\mathrm{kHz}`),margins(x),
s('Read the transimpedance and ringing','Unlike a voltage-gain buffer, the output/input transfer now has units of ohms. The normalized step trace uses the negative final output.',String.raw`Z_t(s)=\frac{V_o}{I_{ph}}=-\frac{A_0R_f}{(1+s\tau_a)(1+sR_fC_{in})+A_0}`,String.raw`Z_t(0)=${N(x.dc/1e6)}\,\mathrm{M\Omega},\quad overshoot\simeq${N(x.overshoot)}\%`)
], 'A nearly correct DC transimpedance can coexist with very poor damping. Compensation must address the loop shape, not just the nominal resistor gain.',{question:'Calculate the asymptotic crossover estimate in kilohertz.',answer:approx/1000,unit:'kHz',hint:'Take the square root of GBW/(2πRfCin).'}, {id:'b3',schematic:tiaDrawing({...p,cf:0})})},{symbols:[...symbols,[String.raw`I_{ph},V_-,R_f,C_{in},NG,Z_t`,'Photocurrent entering the node (A), summing-node voltage (V), feedback resistance (Ω), total input capacitance (F), dimensionless noise gain, and transimpedance (Ω).']]}),
L('b4','A feedback capacitor shapes noise gain',[gbw,rf,cin,k('cf','Feedback capacitance',Math.sqrt(2*25e-12/(2*Math.PI*1e6*10e6)),.1e-12,5e-12,'F')],'How does a tiny feedback capacitor turn ringing into a controlled response?',
'Cf is in parallel with Rf. It limits high-frequency noise gain and returns phase to the loop. The familiar Butterworth sizing expression is a starting approximation, which the exact finite-gain circuit then checks.',
'Compare the chosen Cf with the suggested value, and distinguish crossover from the closed-loop −3 dB corner.',p=>{const x=stability(tiaCircuit(p),{input:1e-9});return O(x,[
s('Include the feedback impedance in node balance','Cf changes both the feedback factor and the closed-loop denominator.',String.raw`I_{ph}=sC_{in}V_-+(V_--V_o)(1/R_f+sC_f),\quad V_o=-A(s)V_-`),
s('Compute the bounded noise gain','At high frequency the noise gain tends to 1+Cin/Cf rather than growing indefinitely.',String.raw`NG(s)=\frac{1+sR_f(C_{in}+C_f)}{1+sR_fC_f},\quad NG(\infty)=1+C_{in}/C_f`,String.raw`NG(\infty)=${N(1+p.cin/p.cf)},\quad C_{f,approx}=\sqrt{\frac{2C_{in}}{2\pi R_fGBW}}=${N(x.cfDesign*1e12)}\,\mathrm{pF}`),margins(x),
s('Choose two independent capacitor states','Let x = [V−, Vo]ᵀ, initially zero. Cf voltage is V− − Vo, so it is not a third independent state. Rearranging KCL and the amplifier pole gives the state system used by the native matrix exponential.',String.raw`\dot x=\begin{bmatrix}-\frac{1/R_f+A_0C_f/\tau_a}{C_{in}+C_f}&\frac{1/R_f-C_f/\tau_a}{C_{in}+C_f}\\-A_0/\tau_a&-1/\tau_a\end{bmatrix}x+\begin{bmatrix}1/(C_{in}+C_f)\\0\end{bmatrix}I_{ph}`),
s('Check the actual closed-loop corner','The feedback RC corner is a component time constant, not generally the closed-loop −3 dB bandwidth of this second-order response.',String.raw`Z_t(s)=-\frac{A_0R_f}{(1+s\tau_a)[1+sR_f(C_{in}+C_f)]+A_0(1+sR_fC_f)}`,String.raw`f_{RfCf}=${N(x.feedbackPole/1000)}\,\mathrm{kHz},\quad f_{3dB}=${N(x.bandwidth/1000)}\,\mathrm{kHz},\quad\zeta=${N(x.zeta)}`)
], 'The exact circuit decides damping and bandwidth. Treating 1/(2πRfCf) as the closed-loop corner would mix a feedback-network pole with the output response.',{question:'Calculate the suggested feedback capacitance in picofarads.',answer:x.cfDesign*1e12,unit:'pF',hint:'Use the displayed Butterworth approximation, then compare its circuit response.'},{id:'b4',schematic:tiaDrawing(p)})},{symbols:[...symbols,[String.raw`I_{ph},V_-,R_f,C_{in},C_f,NG,Z_t,\zeta`,'Photocurrent (A), summing voltage (V), feedback resistance (Ω), input and feedback capacitances (F), noise gain, transimpedance (Ω), and closed-loop damping ratio.']]}),
L('b5','Two amplifiers share a loop',[{...gbw,value:1e6},k('inner','Inner amplifier noise gain',10,2,40)],'Can a composite amplifier meet crossover and phase-margin targets together?',
'The first amplifier corrects an outer gain-100 loop. The second has a local feedback loop whose noise gain is adjustable. Raising that inner gain increases outer-loop gain but also brings its extra phase lag closer to crossover.',
'At 1 MHz GBW compare inner gains 10 and 30. Then adjust GBW to meet 100 kHz crossover and 45° phase margin together.',p=>{const x=stability(compositeCircuit(p),{input:1e-4}),freqMargin=x.crossover/1000-100,phaseMargin=x.pm-45;return O(x,[
s('Close the inner loop first','Both open-loop amplifiers have the same A(s). The second amplifier’s local noise gain is G2.',String.raw`A(s)=\frac{A_0}{1+s\tau_a},\quad H_2(s)=\frac{A(s)}{1+A(s)/G_2}`,String.raw`G_2=${N(p.inner)},\quad G_{outer}=100`),
s('Form the outer return ratio','The outer divider returns Vout/100 to the first amplifier. Include the closed inner stage rather than multiplying two unmodified open-loop gains.',String.raw`T_{outer}=\frac{A(s)H_2(s)}{100}=\frac{A_0^2/100}{(1+s\tau_a)(1+A_0/G_2+s\tau_a)}`),margins(x),
s('Check both specifications and distinguish bandwidth','This task targets outer-loop crossover, not the closed-loop −3 dB frequency. Positive margins mean the selected model passes both targets.',String.raw`M_f=f_x-100\,\mathrm{kHz},\quad M_{PM}=PM-45^\circ`,String.raw`M_f=${N(freqMargin)}\,\mathrm{kHz},\quad M_{PM}=${N(phaseMargin)}^\circ,\quad f_{3dB}=${N(x.bandwidth/1000)}\,\mathrm{kHz}`)
],freqMargin>=0&&phaseMargin>=0?'This composite model meets both stated targets. The component-level design still needs slew, offset, noise and loading checks.':'At least one target is missed. Increase available GBW or change the inner gain while watching both margins.',{question:'Calculate phase-margin headroom above the 45° target.',answer:phaseMargin,unit:'°',hint:'Subtract 45° from the computed outer-loop phase margin.'},{id:'b5',table:{headers:['Target','Actual','Margin'],rows:[['Crossover ≥100 kHz',x.crossover/1000,freqMargin],['Phase margin ≥45°',x.pm,phaseMargin],['DC voltage gain ≈100',x.dc,x.dc-100]]}})},{symbols:[...symbols,[String.raw`G_2,G_{outer},H_2,M_f,M_{PM}`,'Inner and outer noise gains, closed inner-stage transfer, crossover margin (kHz), and phase-margin headroom (degrees).']]})
]
