export function astable({ra=1e4,rb=1e4,cap=10e-9,supply=5,start=0}={}){
 const low=supply/3,high=2*supply/3,tHigh=Math.LN2*(ra+rb)*cap,tLow=Math.LN2*rb*cap,period=tHigh+tLow,initial=start?low:0,first=(ra+rb)*cap*Math.log((supply-initial)/(supply-high)),events=[],points=[];let time=0,v=initial,on=true
 for(let phase=0;phase<8;phase++){const target=on?supply:0,tau=(on?ra+rb:rb)*cap,threshold=on?high:low,duration=tau*Math.log((v-target)/(threshold-target));for(let n=0;n<51;n++){const t=duration*n/50;points.push({x:(time+t)*1e6,y:target+(v-target)*Math.exp(-t/tau),out:on?supply:0})}time+=duration;v=threshold;events.push({time,v,from:on?'High':'Low',to:on?'Low':'High'});on=!on}
 return{low,high,tHigh,tLow,period,frequency:1/period,duty:tHigh/period,initial,first,events,points}
}
export function monostable({resistance=1e5,cap=10e-9,supply=5,initial=0}={}){const v0=initial*supply,tau=resistance*cap,threshold=2*supply/3,duration=tau*Math.log((supply-v0)/(supply-threshold)),rounded=1.1*tau,at=t=>supply+(v0-supply)*Math.exp(-t/tau);return{v0,tau,threshold,duration,rounded,rounding:(1.1/Math.log(3)-1)*100,at}}
function normal(seed){let x=seed>>>0;const u=()=>{x=(1664525*x+1013904223)>>>0;return(x+.5)/4294967296};return Math.sqrt(-2*Math.log(u()))*Math.cos(2*Math.PI*u())}
export function lockin({signal=1e-6,density=10e-9,enbw=1,phase=0,seed=7}={}){const bandwidth=1e5,carrier=1000,tau=1/(4*enbw),corner=1/(2*Math.PI*tau),angle=phase*Math.PI/180,X=signal*Math.cos(angle),Y=signal*Math.sin(angle),inputNoise=density*Math.sqrt(bandwidth),effective=corner/2*(Math.atan((bandwidth-carrier)/corner)+Math.atan((bandwidth+carrier)/corner)),noise=density*Math.sqrt(effective),snrIn=20*Math.log10(signal/inputNoise),snrOut=20*Math.log10(signal/noise),ripple=signal/Math.hypot(1,4*Math.PI*carrier*tau),measured=X+noise*normal(seed);return{bandwidth,carrier,tau,corner,angle,X,Y,inputNoise,effective,noise,snrIn,snrOut,improvement:snrOut-snrIn,ripple,measured,ci:1.96*noise,settle:t=>X*(-Math.expm1(-t/tau))}}
export function biasCurrent({rise=30,tracking=1,emitter=.22}={}){
 const i0=.05,v0=.65,alpha=-.002,supply=20,theta=2,T0=300,T=T0+rise,vt=1.380649e-23*T/1.602176634e-19,sensor=tracking*rise,bias=2*(v0+alpha*sensor)+2*emitter*i0
 // Two output junctions and emitter resistors; all currents are positive.
 const residual=i=>2*(v0+alpha*rise+vt*Math.log(i/i0)+emitter*i)-bias
 let lo=1e-12,hi=1000;for(let n=0;n<90;n++){const m=Math.sqrt(lo*hi);if(residual(m)>0)hi=m;else lo=m}const current=Math.sqrt(lo*hi),slope=-(alpha*(1-tracking)+(vt/T)*Math.log(current/i0))/(vt/current+emitter),loop=theta*2*supply*slope
 return{i0,v0,alpha,T,vt,sensor,bias,current,slope,loop,residual:residual(current),multiplier:2*(v0+alpha*sensor),tempco:2*alpha*tracking,theta,supply}
}
export function classB({supply=20,load=8,fraction=Math.sqrt(.8),theta=2,ambient=45}={}){
 const peak=supply*fraction,power=peak*peak/(2*load),dc=2*supply*peak/(Math.PI*load),device=dc/2-power/2,efficiency=power/dc,worstPeak=2*supply/Math.PI,worst=supply*supply/(Math.PI**2*load),temperature=ambient+theta*device,worstTemperature=ambient+theta*worst,current=peak/load,stressVoltage=Math.min(peak,supply/2),instant=(supply-stressVoltage)*stressVoltage/load,vceMax=supply+peak,thermalOK=worstTemperature<=125,electricalOK=current<=3&&instant<=15&&vceMax<=60
 return{peak,power,dc,device,efficiency,worstPeak,worst,temperature,worstTemperature,current,instant,vceMax,thermalOK,electricalOK,meets:power>=20-1e-9&&thermalOK&&electricalOK,at:v=>supply*v/(Math.PI*load)-v*v/(4*load),envelope:v=>v>60?0:Math.min(3,15/Math.max(v,1e-9))}
}
export function timerDrawing(p={},mono=false){const {supply=5,ra=1e4,rb=1e4,resistance=1e5,cap=10e-9}=p;return{elements:[{type:'V',id:'VCC',value:supply},{type:'R',id:'RA',value:mono?resistance:ra},...(!mono?[{type:'R',id:'RB',value:rb}]:[]),{type:'C',id:'C1',value:cap},{type:'SW',id:'SD',closed:false}],caption:mono?'Ideal 555 timing path during the pulse: discharge switch open, C1 charging through RA. The upper comparator resets the latch at 2VCC/3. Trigger occurs at t=0 and is released before timeout.':'Ideal 555 timing path during high output: discharge switch open. At 2VCC/3 the latch closes SD; C1 then discharges through RB until VCC/3 resets the phase. Comparator and latch logic are specified by the threshold events.',layout:{w:500,h:300,items:[{el:'VCC',x:50,y:105,dir:'v'},{gnd:[50,125]},{wire:[50,85,50,40]},{wire:[50,40,185,40]},{el:'RA',x:205,y:40,dir:'h'},{wire:[225,40,310,40]},{node:'discharge',x:310,y:40,side:'t'},{wire:[310,40,425,40]},{wire:[425,40,425,145]},{el:'SD',x:425,y:165,dir:'v'},{gnd:[425,185]},...(!mono?[{wire:[310,40,310,85]},{el:'RB',x:310,y:105,dir:'v'},{wire:[310,125,310,155]}]:[{wire:[310,40,310,155]}]),{node:'vc',x:310,y:155,side:'l'},{wire:[310,155,310,185]},{el:'C1',x:310,y:205,dir:'v'},{gnd:[310,225]},{text:'vc → threshold comparators → latch → SD',x:245,y:280}]}}}
