import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {astable,monostable,lockin,biasCurrent,classB,timerDrawing} from './timingAudio.js'
const T=String.raw,timerSource=['TI: xx555 timer datasheet','https://www.ti.com/lit/ds/symlink/ne555.pdf'],lockSource=['Stanford Research Systems: SR830 lock-in basics','https://www.thinksrs.com/downloads/pdfs/manuals/SR830m.pdf']
function L(id,name,knobs,question,intro,attempt,solve,symbols,extra={}){return{id,name,group:'H. Timers, synchronous detection and audio output',knobs,question,intro,try:attempt,solve,symbols,flow:['Define the circuit, state and reference','Derive the timing, noise or power equation','Check the result and model limits'],route:'State equations describe charging and thermal evolution; threshold events change the active circuit. Frequency-domain filtering describes the lock-in output after multiplication. Power integrals describe average heating; instantaneous voltage/current checks address a different limit.',limits:'Behavioral teaching models with explicit thresholds, noise conventions and device limits. No particular timer, amplifier or transistor is certified by these calculations.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const timerSymbols=[[T`V_{CC},v_c,V_L,V_H,R_A,R_B,C`,'Supply and timing-capacitor voltage (V), thresholds VCC/3 and 2VCC/3 (V), timing resistances (Ω), and capacitance (F).'],[T`t,\tau,\dot v_c,t_H,t_L,T_p,f,D`,'Time and RC time constant (s), capacitor-voltage derivative (V/s), high/low durations and period (s), frequency (Hz), and high-output duty fraction.'],[T`t_k^-,t_k^+,v_c(0)`,'Instants immediately before/after a switch event, and initial capacitor voltage (V). The resistive switching path leaves voltage continuous.']]
export const TIMING_AUDIO_LESSONS=[
L('h1','A 555 astable: solve between threshold events',[k('ra','Charging resistance RA',1e4,1000,1e5,'Ω'),k('rb','Charge-discharge resistance RB',1e4,1000,1e5,'Ω'),k('cap','Timing capacitance',10e-9,1e-9,100e-9,'F'),k('supply','Supply voltage',5,3,15,'V'),{...k('start','Initial capacitor state',0,0,1),options:['Uncharged startup','Periodic lower threshold']}],
 'Why does the first high pulse differ from later pulses?',
 'High output opens the discharge switch and charges C through RA+RB. Low output closes it and discharges C through RB. The latch starts high. Ideal thresholds at VCC/3 and 2VCC/3 set exact events, independent of the plotting grid.',
 'Compare uncharged startup with the periodic lower threshold. Change supply and predict which voltages change and which times remain constant.',p=>{const x=astable(p);return O([
 s('Write the two state equations','The capacitor is the only continuous state. Each latch state selects a different resistance and target voltage.',T`\dot v_c=\begin{cases}(V_{CC}-v_c)/[(R_A+R_B)C]&\text{high}\\-v_c/(R_BC)&\text{low}\end{cases}`,T`V_L=${N(x.low)}\,V,\quad V_H=${N(x.high)}\,V,\quad v_c(0)=${N(x.initial)}\,V`),
 s('Integrate the periodic high interval','Start the recurring high phase at VL and stop at VH. Solve the exponential for elapsed time.',T`v_c(t)=V_{CC}+(V_L-V_{CC})e^{-t/[(R_A+R_B)C]},\quad t_H=(R_A+R_B)C\ln2`,T`t_H=${N(x.tHigh*1e6)}\,\mu s`),
 s('Integrate discharge and form the period','Low output discharges from VH to VL. Voltage is continuous at both events; its derivative and output switch immediately.',T`t_L=R_BC\ln2,\quad T_p=t_H+t_L,\quad f=1/T_p,\quad D=t_H/T_p`,T`t_L=${N(x.tLow*1e6)}\,\mu s,\quad f=${N(x.frequency)}\,Hz,\quad D=${N(x.duty*100)}\%`),
 s('Apply the actual startup state','Starting at zero takes longer to reach VH. The first pulse uses its own initial value; each later period contains two latch transitions.',T`t_{H,first}=(R_A+R_B)C\ln\frac{V_{CC}-v_c(0)}{V_{CC}-V_H},\quad v_c(t_k^+)=v_c(t_k^-)`,T`t_{H,first}=${N(x.first*1e6)}\,\mu s,\quad N_{events/period}=2`)
 ],[r('Periodic frequency',x.frequency,'Hz'),r('Periodic high duty',x.duty*100,'%'),r('First high pulse',x.first*1e6,'µs')],[curve('Timing capacitor: exact event endpoints','Time (µs)','Capacitor voltage (V)',x.points),curve('Latch output','Time (µs)','Output voltage (V)',x.points.map(v=>({x:v.x,y:v.out})))],
 'Ideal periodic timing is supply independent because both thresholds scale with supply. Real thresholds, discharge resistance and delays introduce error. The first pulse must use the startup state.',x.frequency,'Hz','Calculate the recurring frequency.','Use 1/[ln2·(RA+2RB)C].',{schematic:timerDrawing(p),table:{headers:['Event','Time (µs)','Capacitor (V)','Latch change'],rows:x.events.slice(0,4).map((e,i)=>[i+1,fmt(e.time*1e6),fmt(e.v),`${e.from} → ${e.to}`])}})},timerSymbols,{sources:[timerSource]}),
L('h2','A 555 monostable: where 1.1 RC comes from',[k('resistance','Timing resistance',1e5,1e4,1e6,'Ω'),k('cap','Timing capacitance',10e-9,1e-9,100e-9,'F'),k('supply','Supply voltage',5,3,15,'V'),k('initial','Initial capacitor / supply ratio',0,0,.3)],
 'How does an incompletely discharged capacitor change pulse width?',
 'At t=0 a brief trigger sets the latch high and opens the discharge path. C charges toward VCC until the upper comparator resets the latch at 2VCC/3. The trigger is released before timeout. Post-timeout discharge is outside this ideal charging calculation.',
 'Set the initial ratio to zero and compare ln3 with 1.1. Then start partly charged and see why the usual zero-state formula no longer applies.',p=>{const x=monostable(p);return O([
 s('Define the initial value and charging equation','The trigger sets the latch; it does not discharge an already charged capacitor.',T`RC\dot v_c+v_c=V_{CC},\quad v_c(0)=v_0`,T`v_0=${N(x.v0)}\,V,\quad RC=${N(x.tau*1000)}\,ms`),
 s('Solve the exponential up to the threshold','Rearrange the exponential using the actual initial voltage.',T`v_c(t)=V_{CC}+(v_0-V_{CC})e^{-t/(RC)},\quad t_p=RC\ln\frac{V_{CC}-v_0}{V_{CC}-2V_{CC}/3}`,T`t_p=${N(x.duration*1000)}\,ms,\quad v_c(t_p)=${N(x.at(x.duration))}\,V`),
 s('Recover the zero-state formula','Only when v0=0 does the logarithm reduce to ln3. The 1.1 factor is rounding, not another physical effect.',T`t_{p,0}=RC\ln3,\quad \epsilon_{round}=100\left(\frac{1.1}{\ln3}-1\right)`,T`\ln3=${N(Math.log(3))},\quad \epsilon_{round}=${N(x.rounding)}\%`),
 s('Separate rounding from initial-state error','A partly charged capacitor can change timing much more than rounding ln3 does.',T`\Delta t_{initial}=t_p-RC\ln3,\quad t_{rounded}=1.1RC`,T`\Delta t_{initial}=${N((x.duration-x.tau*Math.log(3))*1e6)}\,\mu s,\quad t_{rounded}=${N(x.rounded*1000)}\,ms`)
 ],[r('Actual pulse width',x.duration*1000,'ms'),r('Zero-state 1.1 RC estimate',x.rounded*1000,'ms'),r('Rounding error only',x.rounding,'%')],[curve('Charging interval ends at the threshold','Time (ms)','Capacitor voltage (V)',samples(t=>x.at(t/1000),0,x.duration*1000))],
 'State the initial voltage and trigger timing before using 1.1 RC. Held triggers, retrigger behavior, comparator delay and finite post-timeout discharge are not modeled.',x.duration*1000,'ms','Calculate pulse width from the selected initial condition.','Use RC·ln[(VCC−v0)/(VCC/3)].',{schematic:timerDrawing(p,true),table:{headers:['Initial capacitor / supply','Exact pulse width (ms)'],rows:[0,.1,.3].map(initial=>[initial,fmt(monostable({...p,initial}).duration*1000)])}})},[...timerSymbols,[T`v_0,t_p,\epsilon_{round}`,'Initial capacitor voltage (V), one-shot width (s), and percentage rounding error.']],{sources:[timerSource]}),
]
TIMING_AUDIO_LESSONS.push(
L('h3','Lock-in detection: define amplitude, phase and noise bandwidth',[k('signal','Input sine RMS amplitude',1e-6,.1e-6,10e-6,'V'),k('density','Input noise density',10e-9,1e-9,50e-9,'V/√Hz'),k('enbw','Output equivalent noise bandwidth',1,.1,10,'Hz'),k('phase','Signal phase relative to reference',0,-80,80,'°'),k('seed','Stationary output-noise seed',7,1,999,'',1)],
 'How can a narrow measurement recover a signal buried in wideband noise?',
 'The input is √2 Vs cos(ωt+φ), where Vs is RMS amplitude. Multiply by √2 cos(ωt) and low-pass. The reference therefore has unit RMS. Input white noise has one-sided density en over 0–100 kHz; the carrier is 1 kHz.',
 'Compare 1 Hz equivalent noise bandwidth with the RC corner. Change phase: an in-phase channel loses signal even when its noise is unchanged.',p=>{const x=lockin(p);return O([
 s('Multiply before applying a filter transfer','The product identity gives a DC term and a tone at twice the carrier. A single-frequency phasor gain cannot represent this multiplication by itself. A quadrature reference −√2 sinωt gives the stated Y convention.',T`\sqrt2V_s\cos(\omega t+\phi)\sqrt2\cos\omega t=V_s\cos\phi+V_s\cos(2\omega t+\phi)`,T`X=V_s\cos\phi=${N(x.X*1e6)}\,\mu V,\quad Y=V_s\sin\phi=${N(x.Y*1e6)}\,\mu V`),
 s('Relate equivalent noise bandwidth to the RC state','For H(s)=1/(1+sτ), integrate its squared magnitude over positive frequencies. The equivalent rectangular noise bandwidth is not the −3 dB corner.',T`B_N=\int_0^\infty|H(j2\pi f)|^2df=1/(4\tau),\quad f_c=1/(2\pi\tau)=2B_N/\pi`,T`\tau=${N(x.tau)}\,s,\quad f_c=${N(x.corner)}\,Hz`),
 s('Integrate noise with the finite input band retained','The unit-RMS reference shifts the two noise bands into baseband. For source cutoff B and carrier fL, this expression includes their finite edges; it approaches BN when B is much larger than fL and fc.',T`B_{eff}=\frac{f_c}{2}\left[\tan^{-1}\frac{B-f_L}{f_c}+\tan^{-1}\frac{B+f_L}{f_c}\right],\quad\sigma_X=e_n\sqrt{B_{eff}}`,T`B_{eff}=${N(x.effective)}\,Hz,\quad\sigma_X=${N(x.noise*1e9)}\,nV`),
 s('Keep the SNR convention consistent','Compare the same RMS amplitude with rms noise before and after phase-aligned detection. At a phase error the actual X-channel signal is reduced by cosφ.',T`SNR_{in}=20\log_{10}\frac{V_s}{e_n\sqrt B},\quad SNR_{out,aligned}=20\log_{10}\frac{V_s}{\sigma_X}`,T`SNR_{in}=${N(x.snrIn)}\,dB,\quad SNR_{out,aligned}=${N(x.snrOut)}\,dB,\quad\Delta SNR=${N(x.improvement)}\,dB`),
 s('Separate settling, residual carrier and random uncertainty','The averaged baseband state starts at zero: τẏ+y=X. The displayed seeded draw represents one stationary Gaussian output sample with the calculated variance, not a simulated noisy transient. The twice-carrier residual is reported separately.',T`y_{base}(t)=X(1-e^{-t/\tau}),\quad V_{2f,peak}=\frac{V_s}{\sqrt{1+(4\pi f_L\tau)^2}}`,T`X_{draw}=${N(x.measured*1e6)}\,\mu V,\quad1.96\sigma_X=${N(x.ci*1e9)}\,nV,\quad V_{2f,peak}=${N(x.ripple*1e9)}\,nV`)
 ],[r('Expected in-phase output',x.X*1e6,'µV'),r('Output noise',x.noise*1e9,'nV rms'),r('Aligned output SNR',x.snrOut,'dB'),r('Stationary output draw',x.measured*1e6,'µV')],[curve('Averaged baseband settling from zero; 2f ripple excluded','Elapsed time (s)','In-phase output (µV)',samples(t=>x.settle(t)*1e6,0,5*x.tau))],
 'Narrow noise bandwidth buys measurement precision at the cost of settling time. Phase error is a deterministic signal loss. A 1% rms noise ratio is not a guarantee that every individual measurement lies within 1%.',x.noise*1e9,'nV','Calculate stationary output rms noise.','Use en√Beff; BN is its wide-input-band approximation.',{table:{headers:['Quantity','Value','Unit'],rows:[['Input RMS noise',fmt(x.inputNoise*1e6),'µV'],['Noise-equivalent bandwidth',p.enbw,'Hz'],['RC corner',fmt(x.corner),'Hz'],['Expected X',fmt(x.X*1e6),'µV'],['Expected Y',fmt(x.Y*1e6),'µV'],['Approximate 95% noise interval',`±${fmt(x.ci*1e9)}`,'nV']]}})},[[T`V_s,e_n,B,f_L,\omega,\phi,X,Y`,'Input RMS sine amplitude (V), one-sided white-noise density (V/√Hz), 100 kHz cutoff, 1 kHz carrier, angular frequency (rad/s), relative phase, and in-phase/quadrature means (V).'],[T`H,s,\tau,f_c,B_N,B_{eff},\sigma_X,y_{base}`,'Low-pass transfer, Laplace frequency (s⁻¹), RC time constant (s), corner (Hz), equivalent/effective noise bandwidths (Hz), output rms noise (V), and averaged output state (V).']],{sources:[lockSource]}),
L('h4','Bias tracking and thermal feedback are different questions',[k('rise','Output-junction temperature rise',30,0,60,'K'),k('tracking','Bias-sensor temperature tracking',1,0,1),k('emitter','Each emitter resistance',.22,0,1,'Ω')],
 'Does current increasing with temperature necessarily mean runaway?',
 'Two output junctions carry the same positive quiescent current. At 300 K each has 0.65 V at 50 mA. Use the declared local junction law VBE=0.65−0.002ΔT+VT(T)ln(I/50mA). A ratio-one VBE multiplier senses a selectable fraction of the output temperature rise.',
 'Compare an unheated bias sensor with perfect tracking. Remove the emitter resistors and inspect the local thermal feedback criterion, not just the current-versus-temperature slope.',p=>{const x=biasCurrent(p);return O([
 s('State the temperature-dependent junction law','The −2 mV/K slope is an illustrative fixed-current coefficient. VT=kBT/q also varies with absolute temperature. This is a local model over the stated temperature interval.',T`V_{BE}(I,T)=V_0+\alpha\Delta T+V_T(T)\ln(I/I_0)`,T`T=${N(x.T)}\,K,\quad V_T=${N(x.vt*1000)}\,mV,\quad\alpha=-2\,mV/K`),
 s('Build the bias voltage and include emitter headroom','The multiplier ratio is one, so its voltage is twice the sensor junction voltage. Add a fixed 2REI0 allowance to preserve the nominal 50 mA operating point when emitter resistors are present.',T`V_{bias}=2(V_0+\alpha\kappa\Delta T)+2R_EI_0,\quad2V_{BE}(I,T)+2R_EI=V_{bias}`,T`V_{mult}=${N(x.multiplier)}\,V,\quad dV_{mult}/dT=${N(x.tempco*1000)}\,mV/K`),
 s('Solve the nonlinear current balance','The left side increases monotonically with positive current. Solve for I, then substitute back into the voltage equation. Perfect tracking holds I=I0 within this model.',T`V_T\ln(I/I_0)+R_E(I-I_0)=-\alpha(1-\kappa)\Delta T`,T`I=${N(x.current*1000)}\,mA,\quad r_V=${N(x.residual)}\,V`),
 s('Differentiate before assessing thermal feedback','Temperature dependence of VT contributes another term. Emitter resistance reduces current sensitivity. This derivative assumes the bias sensor follows κ times a slow temperature change.',T`\frac{dI}{dT}=-\frac{\alpha(1-\kappa)+(V_T/T)\ln(I/I_0)}{V_T/I+R_E}`,T`dI/dT=${N(x.slope*1000)}\,mA/K`),
 s('Close the incremental heating loop','With ±20 V rails, quiescent total power is approximately 40I. For a shared thermal resistance θ=2 K/W, a local equilibrium is stable only if the incremental thermal gain is below one. This imposed-temperature sweep is not a time-domain runaway simulation.',T`L_\theta=\theta(2V_{CC})dI/dT,\quad L_\theta<1\ \text{for local stability}`,T`L_\theta=${N(x.loop)},\quad\text{criterion: ${x.loop<1?'below unity':'at or above unity'}}`)
 ],[r('Quiescent current',x.current*1000,'mA'),r('Bias multiplier voltage',x.multiplier,'V'),r('Local thermal feedback gain',x.loop)],[{label:'Imposed-temperature current comparison',xLabel:'Output-junction temperature rise (K)',yLabel:'Quiescent current (mA)',traces:[{label:'Unheated bias sensor',points:samples(rise=>biasCurrent({...p,rise,tracking:0}).current*1000,0,60)},{label:'Selected sensor tracking',points:samples(rise=>biasCurrent({...p,rise}).current*1000,0,60)}]}],
 'Current temperature sensitivity alone does not prove runaway. Heating, cooling, sensor coupling and emitter degeneration determine the feedback. Real thermal lag and transistor mismatch can defeat ideal tracking.',x.current*1000,'mA','Solve the quiescent current at the selected temperature.','Use the monotonic log-current voltage balance; κ=1 gives I=I0.',{table:{headers:['Sensor tracking','Current (mA)','Local thermal gain'],rows:[0,.5,1].map(tracking=>{const a=biasCurrent({...p,tracking});return[tracking,fmt(a.current*1000),fmt(a.loop)]})}})},[[T`V_0,I_0,T,\Delta T,V_T,\alpha,I,R_E`,'Reference junction voltage 0.65 V, reference current 50 mA, absolute temperature (K), rise from 300 K, thermal voltage (V), fixed-current coefficient −2 mV/K, bias current (A), and each emitter resistance (Ω).'],[T`\kappa,V_{mult},V_{bias},r_V,\theta,V_{CC},L_\theta`,'Sensor/output temperature-rise ratio, multiplier and total bias voltages (V), voltage residual (V), shared thermal resistance 2 K/W, rail magnitude 20 V, and dimensionless local thermal loop gain.']]),
L('h5','Class-B output: average heat and instantaneous operating limits',[k('supply','Symmetric rail magnitude',20,10,30,'V'),k('load','Resistive load',8,4,16,'Ω'),k('fraction','Output peak / rail magnitude',Math.sqrt(.8),.1,1),k('theta','Each device junction-to-enclosure resistance',2,1,20,'K/W'),k('ambient','Enclosure temperature',45,25,60,'°C')],
 'Why can a lower output level heat the transistors more than full power?',
 'An ideal complementary class-B pair drives a resistor with a sine. Each transistor conducts for half a cycle. Compare cycle-average dissipation with a declared illustrative electrical envelope: 3 A, 60 V and 15 W instantaneous VCE·IC. These are teaching limits, not a manufacturer SOA curve.',
 'Find the worst heating amplitude, then the 20 W design point into 8 Ω. Increase thermal resistance or lower load resistance and see which requirement fails first.',p=>{const x=classB(p);return O([
 s('Integrate output and supply power over the sine cycle','vo=Vm sinϑ and each rail supplies a half-wave current. The load is purely resistive; no reactive phase shift or quiescent bias is included.',T`P_o=V_m^2/(2R_L),\quad P_{DC}=2V_{CC}V_m/(\pi R_L),\quad\eta=\pi V_m/(4V_{CC})`,T`V_m=${N(x.peak)}\,V,\quad P_o=${N(x.power)}\,W,\quad\eta=${N(x.efficiency*100)}\%`),
 s('Assign the power loss equally to the two devices','Each device dissipates half the total loss. Average dissipation is a quadratic in output peak amplitude.',T`P_D=V_{CC}V_m/(\pi R_L)-V_m^2/(4R_L)`,T`P_D=${N(x.device)}\,W\quad\text{per device}`),
 s('Differentiate to locate worst heating','Set dPD/dVm=0. The worst-heating point has 50% efficiency. The number 40.53% is its output power relative to full-scale output power, not its efficiency.',T`V_{m,worst}=2V_{CC}/\pi,\quad P_{D,max}=V_{CC}^2/(\pi^2R_L),\quad\eta_{worst}=1/2`,T`P_{D,max}=${N(x.worst)}\,W,\quad P_o/P_{o,max}=4/\pi^2=${N(4/Math.PI**2)}`),
 s('Budget average junction temperature across the full amplitude range','Treat each device thermal resistance as independent to the stated enclosure temperature. Shared heatsink coupling and thermal transients are omitted. Check worst heating even if the chosen output amplitude runs cooler.',T`T_J=T_A+\theta P_D,\quad T_{J,worst}=T_A+\theta P_{D,max}`,T`T_J=${N(x.temperature)}^\circ C,\quad T_{J,worst}=${N(x.worstTemperature)}^\circ C`),
 s('Check instantaneous electrical stress separately','During conduction VCE=VCC−vo and IC=vo/RL. Off-state voltage reaches VCC+Vm. The maximum instantaneous product occurs at vo=min(Vm,VCC/2). Average heat alone cannot certify SOA.',T`I_{peak}=V_m/R_L,\quad v_* =\min(V_m,V_{CC}/2),\quad p_{inst,max}=(V_{CC}-v_*)v_*/R_L`,T`I_{peak}=${N(x.current)}\,A,\quad V_{CE,max}=${N(x.vceMax)}\,V,\quad p_{inst,max}=${N(x.instant)}\,W`)
 ],[r('Output power',x.power,'W'),r('Chosen-level device heat',x.device,'W/device'),r('Worst-range junction temperature',x.worstTemperature,'°C'),r('Meets stated 20 W design task',x.meets?1:0,'1=yes')],[curve('Per-device average heating vs output peak','Output peak (V)','Average device power (W)',samples(x.at,0,p.supply)),{label:'Conducting load line and illustrative SOA envelope',xLabel:'Collector-emitter voltage (V)',yLabel:'Collector current (A)',traces:[{label:'Conduction trajectory',points:samples(v=>(p.supply-v)/p.load,p.supply-x.peak,p.supply)},{label:'Declared envelope',points:samples(x.envelope,0,60)}]}],
 x.meets?'The selected point delivers at least 20 W and passes the declared electrical and worst-amplitude thermal checks. Real device SOA, reactive loads, headroom and heatsink coupling still require actual device data.':'The selected point misses at least one task condition: 20 W output, 125 °C worst-range junction temperature, or the declared electrical envelope. The table identifies which condition fails.',x.worst,'W','Calculate maximum cycle-average dissipation per device over all amplitudes.','Use VCC²/(π²RL).',{table:{headers:['Task condition','Value','Result'],rows:[['Output ≥20 W',`${fmt(x.power)} W`,x.power>=20-1e-9?'Pass':'Fail'],['Worst junction ≤125 °C',`${fmt(x.worstTemperature)} °C`,x.thermalOK?'Pass':'Fail'],['Peak current ≤3 A',`${fmt(x.current)} A`,x.current<=3?'Pass':'Fail'],['Off-state voltage ≤60 V',`${fmt(x.vceMax)} V`,x.vceMax<=60?'Pass':'Fail'],['Instantaneous power ≤15 W',`${fmt(x.instant)} W`,x.instant<=15?'Pass':'Fail']]}})},[[T`V_{CC},V_m,R_L,\vartheta,P_o,P_{DC},P_D,\eta`,'Rail magnitude and sine peak (V), resistive load (Ω), sine phase (rad), load/supply/per-device average powers (W), and efficiency fraction.'],[T`\theta,T_A,T_J,V_{CE},I_C,v_*`,'Each device junction-to-enclosure resistance (K/W), enclosure/junction temperatures (°C), instantaneous collector-emitter voltage and collector current, and output voltage giving the peak instantaneous product (V).']])
)
