import {receiverNoise,ookSensitivity,photonCountingLimit} from '@ee-labs/photonics'
import {knob as k,step as s,reading as r,curve,samples,texnum as N} from '@ee-labs/lessons/model'
const R=k('resistance','Load resistance',1000,50,10000,'Ω'),B=k('bandwidth','Noise bandwidth',1e9,1e6,2e9,'Hz'),T=k('temperature','Temperature',300,50,500,'K')
const symbols=[['I_p,I_d','Photocurrent and dark current (A).'],['R,T,B','Load resistance (Ω), temperature (K) and one-sided noise bandwidth (Hz).'],['q,k_B','Elementary charge (C) and Boltzmann constant (J/K).'],[String.raw`\sigma`,'RMS noise current (A), the square root of integrated current-noise power density.'],[String.raw`\mathcal R`,'Photodiode responsivity (A/W), optical power converted to photocurrent.']]
function L(id,name,knobs,question,intro,route,limits,tryText,solve,more=[]){return{id,name,group:'B. The optical receiver',knobs,question,intro,route,limits,try:tryText,solve,symbols:[...symbols,...more],flow:['Photons become charge carriers','Shot noise and load thermal noise','Electrical decision or sensitivity budget']}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,plotNote:'Noise densities use A/√Hz; integrated RMS noise uses A. Powers of independent noises add before taking the square root.',practice:{answer,unit,question,hint,reason:conclusion},...extra}}
export const EXTENDED=[
L('b1','Shot noise versus thermal noise',[k('current','Photocurrent',1e-6,1e-9,1e-3,'A'),k('dark','Dark current',1e-9,0,1e-6,'A'),R,T],'Which noise source dominates this photodiode receiver?',
'Carrier arrivals fluctuate even under steady illumination. The load resistor also generates thermal noise. Compare their current-noise densities at the same node before integrating over bandwidth.',
'Use one-sided power spectral densities for independent noise sources. A transient signal solution alone does not describe the ensemble variance.',
'Poisson carrier arrivals without avalanche excess noise, equilibrium resistor, and independent sources. Thermal dominance depends on operating current and circuit design; it is not universal for fibre receivers.',
'Raise photocurrent through the displayed crossover, then increase load resistance.',p=>{const x=receiverNoise(p);return O([
s('Count charge fluctuations','Signal and dark currents both contribute independent carrier-arrival noise.',String.raw`S_{i,shot}=2q(I_p+I_d),\quad i_{shot}=\sqrt{S_{i,shot}}`,String.raw`i_{shot}=${N(x.shotDensity*1e12)}\,\mathrm{pA}/\sqrt{\mathrm{Hz}}`),
s('Refer resistor noise to a parallel current','The resistor’s voltage density 4kBTR becomes current density after division by R².',String.raw`S_{i,thermal}=4k_BT/R,\quad i_{thermal}=\sqrt{4k_BT/R}`,String.raw`i_{thermal}=${N(x.thermalDensity*1e12)}\,\mathrm{pA}/\sqrt{\mathrm{Hz}}`),
s('Solve the crossover','Set the two power densities equal. This threshold is for total signal-plus-dark current.',String.raw`2qI_{total}=4k_BT/R\Rightarrow I_{cross}=2k_BT/(qR)`,String.raw`I_{cross}=${N(x.crossoverCurrent*1e6)}\,\mu\mathrm A`)
],[r('Shot density',x.shotDensity*1e12,'pA/√Hz'),r('Thermal density',x.thermalDensity*1e12,'pA/√Hz'),r('Crossover total current',x.crossoverCurrent*1e6,'μA')],[{label:'Competing noise densities',xLabel:'Photocurrent (μA)',yLabel:'Current density (pA/√Hz)',traces:[{label:'Shot',points:samples(i=>receiverNoise({...p,current:i*1e-6}).shotDensity*1e12,0,200)},{label:'Thermal',points:samples(()=>x.thermalDensity*1e12,0,200)}]}],x.shotPSD>x.thermalPSD?'Carrier shot noise is larger at this operating current.':'Load thermal noise is larger at this operating current.',x.crossoverCurrent*1e6,'μA','Calculate the total-current crossover in microamperes.','Equate the two power spectral densities; do not equate the currents to their square roots.') }),
L('b2','Resistance trades noise for bandwidth',[R,B,T,k('capacitance','Detector capacitance',.1e-12,.02e-12,5e-12,'F')],'Why can a quieter passive receiver also be slower?',
'A larger resistance reduces input current noise, but the same resistance and detector capacitance create a slower pole. A requested noise bandwidth and a circuit’s actual bandwidth are different quantities.',
'Use spectral integration for noise and the RC transfer function for signal bandwidth. The state equation C dv/dt + v/R = i produces the same pole as the phasor route.',
'Passive parallel RC load, white thermal current noise, ideal rectangular post-filter of bandwidth B. The RC-filtered noise is referred to input current by dividing output noise voltage by DC resistance. No amplifier noise is included.',
'Compare 50 Ω, 1 kΩ and 10 kΩ. Inspect both the flat-band budget and the physically RC-filtered noise.',p=>{const x=receiverNoise({...p,current:0});return O([
s('Calculate the flat-band current-noise budget','Integrate a constant one-sided density over the requested rectangular noise bandwidth.',String.raw`\sigma_{flat}^2=(4k_BT/R)B`,String.raw`\sigma_{flat}=${N(x.thermalRms*1e9)}\,\mathrm{nA}`),
s('Find the signal pole','The transimpedance is voltage per input current, with DC magnitude R.',String.raw`Z(s)=\frac R{1+sRC},\quad f_c=\frac1{2\pi RC}`,String.raw`f_c=${N(x.fc/1e6)}\,\mathrm{MHz}`),
s('Integrate through the actual RC response','The effective noise bandwidth below the ideal post-filter cutoff follows by integrating the squared normalized RC magnitude.',String.raw`B_{eff}=\int_0^B\frac{df}{1+(f/f_c)^2}=f_c\tan^{-1}(B/f_c)`,String.raw`\sigma_{filtered}=\sqrt{(4k_BT/R)B_{eff}}=${N(x.filteredThermalRms*1e9)}\,\mathrm{nA}`)
],[r('Flat-band thermal RMS',x.thermalRms*1e9,'nA'),r('RC-filtered thermal RMS',x.filteredThermalRms*1e9,'nA'),r('Signal corner',x.fc/1e6,'MHz')],[curve('Passive receiver frequency response','Frequency (GHz)','Normalized magnitude',samples(f=>1/Math.sqrt(1+(f*1e9/x.fc)**2),0,2))],'Reduced integrated noise can partly reflect reduced signal bandwidth. A transimpedance amplifier changes this trade but adds its own stability and noise constraints.',x.fc/1e6,'MHz','Calculate the passive RC signal corner.','Use 1/(2πRC), then convert hertz to megahertz.') },[['C,f_c','Detector capacitance (F) and passive RC corner (Hz).']]),
L('b3','Optical sensitivity from a decision criterion',[R,B,T,k('Q','Decision Q',6,3,8),k('responsivity','Responsivity',1,.1,1.2,'A/W')],'What average optical power separates zeros and ones by the required noise margin?',
'For equally likely on-off-keyed bits with zero optical power in a zero, the mean power is half the one-level power. The electrical Q criterion compares the current separation to the sum of the two noise standard deviations.',
'Start with the thermal-only estimate, then solve the signal-dependent shot-noise correction. The Gaussian Q-to-BER estimate is a decision model, not a guarantee for a dispersive or jittered link.',
'Independent Gaussian decision noise, equal bit probabilities, zero dark current and an effective rectangular noise bandwidth B. The selected R specifies equivalent thermal current noise; achieving B requires a receiver with adequate signal bandwidth, as B2 demonstrates.',
'Raise resistance from 1 kΩ to 5 kΩ, then reduce bandwidth. Compare the thermal estimate with the shot-inclusive result.',p=>{const x=ookSensitivity(p);return O([
s('Define the two decision levels','The zero current is zero and the one current is the signal separation. Average optical power is I1/(2 responsivity).',String.raw`Q=\frac{I_1-I_0}{\sigma_1+\sigma_0},\quad I_0=0,\quad P_{avg}=I_1/(2\mathcal R)`),
s('Compute the thermal-only estimate','If both noise levels equal σT, then I1 = 2QσT.',String.raw`\sigma_T=\sqrt{4k_BTB/R},\quad P_{thermal}=Q\sigma_T/\mathcal R`,String.raw`P_{thermal}=${N(x.thermalPower)}\,\mathrm W=${N(x.thermalDbm)}\,\mathrm{dBm}`),
s('Include shot noise on the one level','Substitute σ1² = σ0² + 2qBI1 into the Q equation. Squaring and selecting the positive nonzero solution gives this closed form.',String.raw`I_1=2Q\sigma_0+2qBQ^2`,String.raw`I_1=${N(x.oneCurrent)}\,\mathrm A,\quad P_{avg}=${N(x.power)}\,\mathrm W=${N(x.dbm)}\,\mathrm{dBm}`),
s('Substitute back into the original criterion','This checks the solution before any logarithm or rounding.',String.raw`Q_{check}=I_1/(\sigma_0+\sigma_1)`,String.raw`Q_{check}=${N(x.checkQ)}`)
],[r('Thermal estimate',x.thermalDbm,'dBm'),r('Shot-inclusive sensitivity',x.dbm,'dBm'),r('Q check',x.checkQ)],[curve('Sensitivity and resistance','Resistance (Ω)','Required average optical power (dBm)',samples(R=>ookSensitivity({...p,resistance:R}).dbm,50,10000))],'The shot-inclusive result needs slightly more power than the thermal-only estimate. These powers refer to the average over equally likely zeros and ones.',x.thermalDbm,'dBm','Calculate the thermal-only average sensitivity in dBm.','First use QσT / responsivity in watts, then 10 log10(P / 0.001).') },[['Q','Electrical decision separation / sum of noise standard deviations; distinct from resonator Q.'],['I_0,I_1','Mean zero-level and one-level signal currents (A).']]),
L('b4','The photon-counting limit and the practical gap',[k('lambda','Wavelength',1550e-9,800e-9,1700e-9,'m'),k('rate','Bit rate',1e9,1e6,10e9,'bit/s'),k('onePhotons','Mean detected photons in a one',20,10,30),R,B],'What separates an ideal photon counter from the thermal receiver?',
'An ideal on-off photon counter makes an error only when a transmitted one yields zero detected photons. Poisson statistics give the probability of that event. Average energy counts equally likely zeros as well as ones.',
'Use the Poisson zero-count probability for the ideal limit and the Gaussian electrical-noise calculation for the practical receiver. Their assumptions differ and their BER targets must be compared explicitly.',
'Ideal quantum efficiency one, no dark counts or background, perfect timing, zero photons in a zero, and equal bit probabilities. The practical comparison uses Q = 6, 300 K and responsivity 1 A/W. The rounded 20-photon choice gives BER ≈ 1.03×10⁻⁹, close to the Gaussian Q = 6 estimate 9.87×10⁻¹⁰.',
'Double bit rate without changing the photons per one. Then change receiver bandwidth and compare the practical gap.',p=>{const x=photonCountingLimit(p),thermal=ookSensitivity({resistance:p.resistance,bandwidth:p.bandwidth}),gap=thermal.thermalDbm-x.dbm;return O([
s('Calculate the missed-one probability','Only half the bits are ones, so the zero-count probability is weighted by one half.',String.raw`P_e=\tfrac12\Pr(N=0\mid1)=\tfrac12e^{-n_1}`,String.raw`P_e=\tfrac12e^{-${N(p.onePhotons)}}=${N(x.ber)}`),
s('Count average energy per bit','A one has n1 photons on average. With equal probabilities, the average is n1/2 photons per bit.',String.raw`E_{ph}=hc/\lambda,\quad E_{bit}=(n_1/2)E_{ph},\quad P_{avg}=E_{bit}R_b`,String.raw`P_{avg}=${N(x.power)}\,\mathrm W=${N(x.dbm)}\,\mathrm{dBm}`),
s('Compare the explicitly stated receiver models','The gap subtracts two average optical powers in dBm; the result is a ratio in dB.',String.raw`gap=P_{thermal,dBm}-P_{quantum,dBm}`,String.raw`gap=${N(thermal.thermalDbm)}-(${N(x.dbm)})=${N(gap)}\,\mathrm{dB}`)
],[r('Ideal average power',x.dbm,'dBm'),r('Ideal error probability',x.ber),r('Thermal-estimate gap',gap,'dB')],[curve('Missed-one probability','Mean photons in a one','log₁₀(BER)',samples(n=>Math.log10(.5)-n/Math.LN10,10,30))],'The roughly 27.8 dB default gap compares two stated idealized receiver models at nearly equal error probabilities. It is not a universal implementation penalty.',x.dbm,'dBm','Calculate the average photon-counting power in dBm.','Multiply photons per average bit by hc/λ and bit rate, then convert watts to dBm.') },[['n_1,R_b','Mean detected photons in a one and bit rate (bit/s).'],['h,c','Planck constant (J·s) and speed of light (m/s).']]),
]
