// Served paths include dark review apps. Public navigation has its own list.
export const DEPLOYED_APPS = [
  'signal-lab',
  'circuit-lab',
  'control-lab',
  'circuit-elements-lab',
  'power-lab',
  'machines-lab',
  'random-lab',
  'energy-lab',
  'electronics-lab',
  'logic-lab',
  'comms-lab',
  'info-lab',
  'devices-lab',
  'grid-lab',
  'computer-lab',
  'dsp-lab',
  'control-lab-ii',
  'instruments-lab',
  'fields-lab',
  'rf-lab',
  'system-lab',
  'photonics-lab',
]
