// Linear block codes over GF(2): the generator matrix, the parity-check
// matrix, the syndrome and the standard array.
//
// A code here is a subspace of the vectors of `n` bits. Everything this module
// returns is a count over a finite set, so everything is exact. Where a set is
// too large to walk, the function says so in its return value rather than
// sampling it quietly (CORE_SCOPE.md Rule 3).
//
// The reference code is the (7,4) Hamming code, built as the cyclic code of
// x³ + x + 1 so that the polynomial view and the matrix view of it are the same
// code and not two codes with the same parameters (INFORMATION_LAB_PLAN.md §5,
// C2 and C4).

import { CodesError, addVec, allVectors, bitsOf, binomial, identity, matVec, nullSpace, patternsOfWeight, transpose, valueOf, vecMat, weight } from './gf2.js'
import { PRIMITIVE } from './gfm.js'

/** How large a code this module will enumerate. 2^16 codewords is 65 536 walks. */
export const ENUMERATION_LIMIT = 16

/**
 * A code from a systematic generator matrix `[I_k | P]`.
 *
 * @param {number[][]} G     k rows of n bits
 * @param {object} [meta]    `name`, and anything a view wants to carry
 * @returns {{ name, n, k, rate, G, H, systematic }}
 */
export function codeFromGenerator(G, meta = {}) {
  if (!G.length) throw new CodesError('code-empty', 'a code needs at least one generator row')
  const n = G[0].length
  const k = G.length
  const H = nullSpace(G)
  if (H.length !== n - k) throw new CodesError('code-dependent', `${k} generator rows of ${n} bits span only ${n - H.length} dimensions, so the rows are dependent`)
  return { name: meta.name || `(${n},${k})`, ...meta, n, k, rate: k / n, G, H, systematic: isSystematic(G) }
}

/** A code from its parity-check matrix. The generator is a basis of the null space. */
export function codeFromParity(H, meta = {}) {
  const G = nullSpace(H)
  if (!G.length) throw new CodesError('code-empty', 'this parity-check matrix leaves no codeword but the zero word')
  return { ...codeFromGenerator(G, meta), H }
}

const isSystematic = (G) => G.every((row, i) => row.slice(0, G.length).every((b, j) => b === (i === j ? 1 : 0)))

/**
 * The cyclic code of length `n` generated by the polynomial `g`, in systematic
 * form. `g` is an array of bits, highest power first.
 *
 * Systematic encoding shifts the message up by `n − k` places and appends the
 * remainder of that shift on division by `g`, so every codeword is divisible by
 * `g` and the syndrome is the remainder.
 */
export function cyclicCode(n, g, meta = {}) {
  const deg = g.length - 1
  const k = n - deg
  if (k <= 0) throw new CodesError('code-degree', `a generator of degree ${deg} leaves no message bits in ${n}`)
  if (g[0] !== 1 || g[g.length - 1] !== 1) throw new CodesError('code-generator', 'a cyclic generator polynomial has a nonzero constant term and a leading one')
  const G = Array.from({ length: k }, (_, i) => {
    const m = new Array(k).fill(0)
    m[i] = 1
    return cyclicEncode(n, g, m)
  })
  return { ...codeFromGenerator(G, { generator: g, ...meta }), cyclic: true, generatorPoly: g }
}

/** One message, encoded by polynomial division. */
export function cyclicEncode(n, g, message) {
  const deg = g.length - 1
  const shifted = [...message, ...new Array(deg).fill(0)]
  return [...message, ...polyRemainder(shifted, g)]
}

/** The remainder of a bit polynomial on division by `g`, both highest power first. */
export function polyRemainder(a, g) {
  const r = [...a]
  const deg = g.length - 1
  for (let i = 0; i + g.length <= r.length; i++) {
    if (!r[i]) continue
    for (let j = 0; j < g.length; j++) r[i + j] ^= g[j]
  }
  return r.slice(r.length - deg)
}

/**
 * The Hamming code with `r` parity bits, as the cyclic code of a primitive
 * polynomial of degree `r`. Its length is 2^r − 1 and its distance is 3 for
 * every `r`, which `minimumDistance` computes rather than takes on trust.
 */
export function hammingCode(r) {
  const poly = PRIMITIVE[r]
  if (!poly) throw new CodesError('code-hamming', `no primitive polynomial of degree ${r} is tabulated here`)
  const n = 2 ** r - 1
  const g = bitsOf(poly, r + 1)
  return cyclicCode(n, g, { name: `(${n},${n - r}) Hamming`, family: 'hamming', r })
}

/** The single parity check over `k` bits: one extra bit that makes the weight even. */
export function parityCheckCode(k) {
  const G = identity(k).map((row) => [...row, 1])
  return codeFromGenerator(G, { name: `(${k + 1},${k}) parity check`, family: 'parity' })
}

/** The binary Golay code (23,12), from its generator polynomial. */
export function golayCode() {
  return cyclicCode(23, [1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1], { name: '(23,12) Golay', family: 'golay' })
}

/** The repetition code of length `n`: one message bit sent `n` times. */
export function repetitionCode(n) {
  return codeFromGenerator([new Array(n).fill(1)], { name: `(${n},1) repetition`, family: 'repetition' })
}

/** One message as a codeword. */
export function encode(code, message) {
  if (message.length !== code.k) throw new CodesError('code-message', `this code takes ${code.k} message bits, not ${message.length}`)
  return vecMat(message, code.G)
}

/** The message a systematic codeword carries, read off its first k places. */
export function messageOf(code, word) {
  if (!code.systematic) throw new CodesError('code-systematic', 'this generator is not systematic, so the message is not a slice of the codeword')
  return word.slice(0, code.k)
}

/** The syndrome of a received word: `H rᵀ`, which is zero exactly on the codewords. */
export function syndromeOf(code, word) {
  if (word.length !== code.n) throw new CodesError('code-word', `this code has words of ${code.n} bits, not ${word.length}`)
  return matVec(code.H, word)
}

/** Every codeword, in message order. Refuses a code too large to walk. */
export function codewords(code) {
  if (code.k > ENUMERATION_LIMIT)
    throw new CodesError('code-too-large', `this code has 2^${code.k} codewords, and this module enumerates up to 2^${ENUMERATION_LIMIT}`)
  return allVectors(code.k).map((m) => encode(code, m))
}

/**
 * The weight distribution: how many codewords have each weight, from 0 to n.
 * The first entry is always 1, because the zero word is in every linear code.
 */
export function weightDistribution(code) {
  const out = new Array(code.n + 1).fill(0)
  for (const c of codewords(code)) out[weight(c)]++
  return out
}

/**
 * The minimum distance, and how it was found.
 *
 * For a linear code the minimum distance is the smallest nonzero weight, so
 * enumerating the codewords settles it. Above the enumeration limit the same
 * question is asked of the columns of H: the distance is the smallest number of
 * columns that sum to zero. That search is exact up to three columns and stops
 * there, so a large code returns a bound with the reason attached rather than a
 * number it cannot stand behind.
 *
 * @returns {{ d, method: 'weights' | 'columns', bound: boolean, weights: number[] | null }}
 */
export function minimumDistance(code) {
  if (code.k <= ENUMERATION_LIMIT) {
    const weights = weightDistribution(code)
    const d = weights.findIndex((count, w) => w > 0 && count > 0)
    return { d, method: 'weights', bound: false, weights }
  }
  const cols = transpose(code.H)
  const n = cols.length
  for (let i = 0; i < n; i++) if (weight(cols[i]) === 0) return { d: 1, method: 'columns', bound: false, weights: null }
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++) if (cols[i].every((b, x) => b === cols[j][x])) return { d: 2, method: 'columns', bound: false, weights: null }
  for (let i = 0; i < n; i++)
    for (let j = i + 1; j < n; j++) {
      const s = addVec(cols[i], cols[j])
      for (let l = j + 1; l < n; l++) if (s.every((b, x) => b === cols[l][x])) return { d: 3, method: 'columns', bound: false, weights: null }
    }
  return { d: 4, method: 'columns', bound: true, weights: null }
}

/** How many errors a code corrects, from its distance: `t = ⌊(d − 1)/2⌋`. */
export const correctionRadius = (d) => Math.floor((d - 1) / 2)

/** How many errors a code detects: `d − 1`. */
export const detectionRadius = (d) => d - 1

/**
 * The syndrome table: the coset leader for every syndrome, found by walking the
 * error patterns in order of weight.
 *
 * The leader is the lowest-weight error pattern with that syndrome, which is
 * what a maximum-likelihood decoder on a binary symmetric channel below one
 * half chooses. Where two patterns of the same weight share a syndrome the
 * first in counting order is kept, and `ties` counts how often that happened,
 * because a tie is a coset the code cannot correct.
 *
 * @returns {{ table: Map<string, number[]>, ties: number, complete: boolean, cosets: number }}
 */
export function syndromeTable(code) {
  const rows = code.n - code.k
  const cosets = 2 ** rows
  if (rows > 20) throw new CodesError('code-too-large', `this code has 2^${rows} syndromes, and this module tabulates up to 2^20`)
  const table = new Map()
  let ties = 0
  for (let w = 0; w <= code.n && table.size < cosets; w++) {
    for (const e of patternsOfWeight(code.n, w)) {
      const key = valueOf(syndromeOf(code, e))
      if (!table.has(key)) table.set(key, e)
      else if (weight(table.get(key)) === w) ties++
    }
  }
  return { table, ties, complete: table.size === cosets, cosets }
}

/**
 * Decode by the syndrome table: read the syndrome, subtract its coset leader.
 *
 * @returns {{ word, error, message, syndrome, corrected: boolean, weight: number }}
 */
export function decode(code, received, table = null) {
  const st = table || syndromeTable(code)
  const s = syndromeOf(code, received)
  const leader = st.table.get(valueOf(s))
  if (!leader) throw new CodesError('code-syndrome', `syndrome ${s.join('')} is not in this code's table`)
  const word = addVec(received, leader)
  return {
    word,
    error: leader,
    message: code.systematic ? messageOf(code, word) : null,
    syndrome: s,
    corrected: weight(leader) > 0,
    weight: weight(leader),
  }
}

/**
 * The sphere-packing count: how many words each codeword covers within the
 * correction radius, and whether those spheres fill the space exactly.
 *
 * A perfect code is one where they do. The (7,4) Hamming code covers 16 × 8 =
 * 128 words of length 7, which is every one of them.
 */
export function spherePacking(code, d) {
  const t = correctionRadius(d)
  let sphere = 0
  for (let w = 0; w <= t; w++) sphere += binomial(code.n, w)
  const covered = 2 ** code.k * sphere
  const total = 2 ** code.n
  return { t, sphere, covered, total, perfect: covered === total, spare: total - covered }
}

/**
 * The standard array: every word of `n` bits, in a table of 2^(n−k) rows of
 * 2^k columns. The first row is the code, and each later row is the code with
 * one error pattern added to it.
 *
 * Refused above 2^14 words, which is where a table stops being a picture.
 */
export function standardArray(code) {
  if (code.n > 14) throw new CodesError('code-too-large', `a standard array of ${code.n} bits has 2^${code.n} entries, which no pane can draw`)
  const words = codewords(code)
  const st = syndromeTable(code)
  const rows = []
  for (const [syndrome, leader] of st.table) rows.push({ syndrome, leader, weight: weight(leader), words: words.map((c) => addVec(c, leader)) })
  rows.sort((a, b) => a.weight - b.weight || a.syndrome - b.syndrome)
  return rows
}

/**
 * Everything a pane draws about one code, computed once.
 *
 * @returns {{ code, d, t, detect, weights, method, table, packing, words }}
 */
export function describe(code) {
  const { d, method, weights, bound } = minimumDistance(code)
  const small = code.k <= ENUMERATION_LIMIT && code.n - code.k <= 20
  return {
    code,
    n: code.n,
    k: code.k,
    rate: code.rate,
    d,
    bound,
    method,
    weights,
    t: correctionRadius(d),
    detect: detectionRadius(d),
    table: small ? syndromeTable(code) : null,
    packing: small ? spherePacking(code, d) : null,
    words: code.k <= 8 ? codewords(code) : null,
  }
}

/** The Singleton bound: no code of length n and dimension k has distance above n − k + 1. */
export const singletonBound = (n, k) => n - k + 1
