// Vectors and matrices over GF(2), the two-element field.
//
// Addition is exclusive-or and multiplication is the logical AND, so every
// number here is 0 or 1 and every operation is exact. Nothing in this file
// rounds, and no result depends on the order the rows were given in.
//
// A vector is an array of 0 and 1, most significant on the left, which is the
// order a codeword is written in. A matrix is an array of such vectors, one per
// row. The shapes are small by construction: this lab's longest code is 23 bits
// (INFORMATION_LAB_PLAN.md §3), so an array of arrays is the readable choice
// and the cost of it is invisible.

/** A zero matrix of `rows` by `cols`. */
export const zeros = (rows, cols) => Array.from({ length: rows }, () => new Array(cols).fill(0))

/** The identity matrix of order `n`. */
export const identity = (n) => Array.from({ length: n }, (_, i) => Array.from({ length: n }, (_, j) => (i === j ? 1 : 0)))

/** The transpose of `M`. */
export function transpose(M) {
  if (!M.length) return []
  return M[0].map((_, j) => M.map((row) => row[j]))
}

/** The sum of two vectors, which over GF(2) is the exclusive-or of them. */
export function addVec(a, b) {
  if (a.length !== b.length) throw new CodesError('gf2-shape', `a vector of ${a.length} bits cannot be added to one of ${b.length}`)
  return a.map((v, i) => v ^ b[i])
}

/** The inner product of two vectors, modulo two. */
export const dot = (a, b) => a.reduce((acc, v, i) => acc ^ (v & b[i]), 0)

/** The Hamming weight of a vector, which is how many of its bits are 1. */
export const weight = (v) => v.reduce((acc, b) => acc + (b ? 1 : 0), 0)

/** The Hamming distance between two vectors. */
export const distance = (a, b) => weight(addVec(a, b))

/** The product `M v`, with `v` read as a column. */
export function matVec(M, v) {
  return M.map((row) => dot(row, v))
}

/** The product `v M`, with `v` read as a row. */
export function vecMat(v, M) {
  if (!M.length) return []
  return M[0].map((_, j) => v.reduce((acc, b, i) => acc ^ (b & M[i][j]), 0))
}

/** The product of two matrices. */
export function matMul(A, B) {
  return A.map((row) => vecMat(row, B))
}

/** Two matrices side by side, `[A | B]`. */
export const augment = (A, B) => A.map((row, i) => [...row, ...B[i]])

/**
 * Row reduction to reduced row echelon form.
 *
 * @returns {{ rows: number[][], pivots: number[], rank: number }} the reduced
 *   matrix, the column each pivot sits in, and how many there are.
 */
export function rref(M) {
  const rows = M.map((r) => [...r])
  const cols = rows.length ? rows[0].length : 0
  const pivots = []
  let r = 0
  for (let c = 0; c < cols && r < rows.length; c++) {
    let p = r
    while (p < rows.length && rows[p][c] === 0) p++
    if (p === rows.length) continue
    const t = rows[r]
    rows[r] = rows[p]
    rows[p] = t
    for (let i = 0; i < rows.length; i++) {
      if (i !== r && rows[i][c]) rows[i] = addVec(rows[i], rows[r])
    }
    pivots.push(c)
    r++
  }
  return { rows, pivots, rank: pivots.length }
}

/** The rank of `M` over GF(2). */
export const rank = (M) => rref(M).rank

/**
 * A basis of the null space of `M`, as row vectors `x` with `M xᵀ = 0`.
 *
 * The basis has `cols − rank` vectors, one per free column, which is the
 * dimension theorem over any field and is exact over this one.
 */
export function nullSpace(M) {
  const cols = M.length ? M[0].length : 0
  const { rows, pivots } = rref(M)
  const free = []
  for (let c = 0; c < cols; c++) if (!pivots.includes(c)) free.push(c)
  return free.map((f) => {
    const x = new Array(cols).fill(0)
    x[f] = 1
    pivots.forEach((c, i) => {
      x[c] = rows[i][f]
    })
    return x
  })
}

/**
 * `M` in systematic form, `[I_k | P]`, with the column swaps it took.
 *
 * A generator matrix in systematic form puts the message bits into the first
 * `k` positions of the codeword, so the message is readable off the codeword
 * without a decode. `perm` maps a column of the systematic matrix back to the
 * column of `M` it came from, and every result derived from the systematic form
 * is carried back through it.
 *
 * @returns {{ rows, perm, rank }}
 */
export function systematic(M) {
  const cols = M.length ? M[0].length : 0
  const { rows, pivots, rank: rk } = rref(M)
  const kept = rows.slice(0, rk)
  const rest = []
  for (let c = 0; c < cols; c++) if (!pivots.includes(c)) rest.push(c)
  const perm = [...pivots, ...rest]
  return { rows: kept.map((row) => perm.map((c) => row[c])), perm, rank: rk }
}

/**
 * The parity-check matrix of the code generated by `G`.
 *
 * `H` is any matrix whose null space is the code, and the null space of `G`'s
 * own row space gives one. Working through `nullSpace` rather than through the
 * textbook `[Pᵀ | I]` keeps the result right for a `G` that is not systematic
 * and for one whose rows are dependent.
 */
export function parityOf(G) {
  return nullSpace(G)
}

/**
 * The generator matrix of the code checked by `H`, as a basis of its null
 * space. `parityOf(generatorOf(H))` and `H` check the same code.
 */
export function generatorOf(H) {
  return nullSpace(H)
}

/** Every vector of `n` bits, in counting order. Used where a claim says "every". */
export function allVectors(n) {
  const out = []
  for (let i = 0; i < 2 ** n; i++) out.push(bitsOf(i, n))
  return out
}

/** The `n`-bit vector of an integer, most significant bit first. */
export const bitsOf = (value, n) => Array.from({ length: n }, (_, i) => (value >> (n - 1 - i)) & 1)

/** The integer a vector stands for, most significant bit first. */
export const valueOf = (v) => v.reduce((acc, b) => acc * 2 + b, 0)

/** Every vector of `n` bits of weight exactly `w`, in counting order. */
export function patternsOfWeight(n, w) {
  const out = []
  const build = (from, left, acc) => {
    if (left === 0) {
      const v = new Array(n).fill(0)
      for (const i of acc) v[i] = 1
      out.push(v)
      return
    }
    for (let i = from; i <= n - left; i++) build(i + 1, left - 1, [...acc, i])
  }
  build(0, w, [])
  return out
}

/** How many vectors of `n` bits have weight `w`. */
export function binomial(n, w) {
  if (w < 0 || w > n) return 0
  let acc = 1
  for (let i = 0; i < w; i++) acc = (acc * (n - i)) / (i + 1)
  return Math.round(acc)
}

/**
 * The error every function here throws.
 *
 * `code` is a stable word a pane can print and a test can match, in the shape
 * `@ee-labs/network` and `@ee-labs/events` already use.
 */
export class CodesError extends Error {
  constructor(code, message) {
    super(message)
    this.name = 'CodesError'
    this.code = code
  }
}
