import {complex as z} from '@ee-labs/network'
import {n,rect} from './derivationMath.js'
import {loadedRC} from './completionFilters.js'
const step=(title,text,...latex)=>({title,text,latex:latex.map(s=>`&${s}`)})
const row=(label,predicted,measured,unit)=>({label,predicted,measured,unit,tol:1e-7,abs:1e-8})

// Closed 2x2 exponential, independent of the network state extractor/integrator.
export function branchedStep(p,t){
  const a=-1/(p.R1*p.C1),b=-1/p.C1,c=1/p.L1,d=-p.R2/p.L1
  const mean=(a+d)/2,delta2=((a-d)/2)**2+b*c
  let cosine,sine
  if(delta2>1e-16){const delta=Math.sqrt(delta2),e1=Math.exp((mean+delta)*t),e2=Math.exp((mean-delta)*t);cosine=(e1+e2)/2;sine=(e1-e2)/(2*delta)}
  else if(delta2< -1e-16){const delta=Math.sqrt(-delta2),e=Math.exp(mean*t);cosine=e*Math.cos(delta*t);sine=e*Math.sin(delta*t)/delta}
  else {cosine=Math.exp(mean*t);sine=t*cosine}
  const vf=p.E*p.R2/(p.R1+p.R2),ifinal=p.E/(p.R1+p.R2),v=p.v0-vf,i=p.i0-ifinal
  return {v:vf+cosine*v+sine*((a-mean)*v+b*i),i:ifinal+cosine*i+sine*(c*v+(d-mean)*i),a,b,c,d,vf,ifinal}
}
export function loadedComplete(p,t){const a=loadedRC(p),w=2*Math.PI*p.f,forced=a.output[0]*Math.sin(w*t)+a.output[1]*Math.cos(w*t),natural=(p.v0-a.output[1])*Math.exp(-t/a.tau);return {...a,forced,natural,v:forced+natural,i:p.C1*(w*(a.output[0]*Math.cos(w*t)-a.output[1]*Math.sin(w*t))-natural/a.tau)}}
export function capstoneStudy(id,p,x){
  if(id==='g8'){
    const a=branchedStep(p,x.cursor),slope=((p.E-p.v0)/p.R1-p.i0)/p.C1,di=(p.v0-p.R2*p.i0)/p.L1
    return {title:'Circuits I capstone: derive a coupled state model',intro:'Choose x₁ = vC and x₂ = iL, positive into the labeled capacitor and inductor terminals. The source steps to V₁ = u = the source knob. x(0⁻) is the stored state immediately before switching; finite voltages and currents preserve it at 0⁺. A dot means derivative with respect to time.',
      steps:[
        step('Write both circuit laws before arranging a matrix','R₁ feeds a node shared by C₁ and the R₂–L₁ branch. KCL gives capacitor current; KVL down the other branch gives inductor voltage. The two states are coupled because each appears in the other derivative.',String.raw`\frac{u-v_C}{R_1}=C_1\dot v_C+i_L`,String.raw`v_C=R_2i_L+L_1\dot i_L`),
        step('Isolate the derivatives and define every coefficient','The first row has volts per second; the second has amperes per second. The off-diagonal entries therefore have different units. The state vector contains volts and amperes, not two interchangeable numbers.',String.raw`\dot{\boldsymbol x}=\begin{bmatrix}-1/(R_1C_1)&-1/C_1\\1/L_1&-R_2/L_1\end{bmatrix}\boldsymbol x+\begin{bmatrix}1/(R_1C_1)\\0\end{bmatrix}u`,String.raw`A=\begin{bmatrix}${n(a.a)}&${n(a.b)}\\${n(a.c)}&${n(a.d)}\end{bmatrix},\quad\boldsymbol x_0=\begin{bmatrix}${n(p.v0)}\\${n(p.i0)}\end{bmatrix}`),
        step('Predict the initial direction of motion','Substitute the stored state and the new source value into the original circuit laws. These slopes predict whether each trace initially rises or falls before solving the complete response.',String.raw`\dot v_C(0^+)=\frac{(${n(p.E)}-${n(p.v0)})/${n(p.R1)}-${n(p.i0)}}{${n(p.C1)}}=${n(slope)}\,\mathrm{V/s}`,String.raw`\dot i_L(0^+)=\frac{${n(p.v0)}-(${n(p.R2)})(${n(p.i0)})}{${n(p.L1)}}=${n(di)}\,\mathrm{A/s}`),
        step('Find the final state from the physical DC circuit','At a stable DC final state the capacitor is open and the inductor is a wire. The remaining R₁–R₂ divider gives voltage and current. Equivalently set both derivatives to zero.',String.raw`v_{C,\infty}=V_1\frac{R_2}{R_1+R_2}=${n(a.vf)}\,\mathrm V,\qquad i_{L,\infty}=\frac{V_1}{R_1+R_2}=${n(a.ifinal)}\,\mathrm A`),
        step('Use both modes to recover the complete state','Subtract the final state to obtain a homogeneous system. The matrix exponential evolves both initial errors together. In State equations, inspect the extracted matrix and modes; Scope shows the resulting time traces.',String.raw`\boldsymbol x(t)=\boldsymbol x_\infty+e^{At}(\boldsymbol x_0-\boldsymbol x_\infty)`,String.raw`v_C(${n(x.cursor)})=${n(a.v)}\,\mathrm V,\qquad i_L(${n(x.cursor)})=${n(a.i)}\,\mathrm A`),
      ],advantage:'Circuit equations explain each coefficient; the state representation handles both stored quantities and arbitrary initial conditions together. Initial slopes and DC limits are quick independent checks.',limitation:'A single RC time constant cannot describe this coupled second-order circuit. Sinusoidal phasors are not a complete solution to this switched DC problem.',
      checks:[row('capacitor voltage',a.v,x.sol.volt.C1,'V'),row('inductor current',a.i,x.sol.i.L1,'A')],
      practice:[{prompt:'In a fresh trial set vC(0) = 0 and iL(0) = 0, keeping the source and components as shown. Calculate the initial capacitor-voltage slope.',target:p.E/(p.R1*p.C1),unit:'V/s',hint:'At zero stored state all initial R₁ current flows into C₁. Use C₁ dvC/dt = V₁/R₁.'},{prompt:'Form the second state-equation row with state order [vC, iL]. Enter the coefficient multiplying vC in diL/dt.',target:1/p.L1,unit:'A/(V s)',hint:'Isolate the inductor derivative in vC = R2 iL + L1 diL/dt. The coefficient of vC is positive 1/L1.'},{prompt:'Double R₂ in your calculation. What is the new final capacitor voltage?',target:p.E*2*p.R2/(p.R1+2*p.R2),unit:'V',hint:'Use the final DC divider with 2R₂, while the capacitor is open and the inductor is a wire.'}]}
  }
  const a=loadedComplete(p,x.cursor),w=2*Math.PI*p.f,phi=p.phi*Math.PI/180,u0=p.A*Math.sin(phi)
  return {title:'Circuits II capstone: reconcile time, state, Laplace and phasors',intro:'One loaded RC circuit starts with stored voltage v₀ and a sinusoidal source u(t) = A sin(ωt + φ). Lowercase v(t) is an instantaneous voltage. V(s) is its unilateral Laplace transform. The underlined V is a complex peak phasor of only the sinusoidal steady response.',
    steps:[
      step('Start with the physical equation','The R₁ current splits between C₁ and RL. Define τ using the resistance seen by the capacitor and K using the DC divider.',String.raw`C_1\dot v=\frac{u-v}{R_1}-\frac v{R_L}`,String.raw`\tau=(R_1\parallel R_L)C_1=${n(a.tau)}\,\mathrm s,\quad K=\frac{R_L}{R_1+R_L}=${n(a.gain)}`),
      step('Express the same equation as a one-state model','The state is the capacitor voltage. The homogeneous coefficient is −1/τ and the input coefficient is K/τ. The state model retains v₀ and predicts the whole startup.',String.raw`\dot x=-\frac1\tau x+\frac K\tau u,\qquad y=x,\qquad x(0^+)=v_0=${n(p.v0)}\,\mathrm V`),
      step('Transform without dropping the initial term','The derivative transform is sV(s) − v₀. Solve for V(s); the first term is the zero-state response and the second is the zero-input response.',String.raw`(1+s\tau)V(s)=KU(s)+\tau v_0`,String.raw`U(s)=A\frac{\omega\cos\phi+s\sin\phi}{s^2+\omega^2}`,String.raw`V(s)=\frac K{1+s\tau}U(s)+\frac{\tau v_0}{1+s\tau}`),
      step('Use phasors for the part that survives startup','At s = jω, multiply the complex peak input by H. The sine reference means Im(V exp(jωt)) reconstructs the voltage. A phasor does not contain v₀.',String.raw`\underline V=\frac K{1+j\omega\tau}\,A e^{j\phi}=${rect(a.output)}\,\mathrm V`,String.raw`v_{\mathrm{forced}}(t)=\operatorname{Im}\{\underline V e^{j\omega t}\}`),
      step('Restore the natural term to satisfy the initial condition','At t = 0 the forced voltage is the imaginary part of the peak phasor. The difference from v₀ must decay with τ. This complete expression is also the inverse of the Laplace result.',String.raw`v(t)=v_{\mathrm{forced}}(t)+[v_0-\operatorname{Im}\underline V]e^{-t/\tau}`,String.raw`v(${n(x.cursor)})=(${n(a.forced)})+(${n(a.natural)})=${n(a.v)}\,\mathrm V`,String.raw`i_C=C_1\dot v=${n(a.i)}\,\mathrm A`),
      step('Check the start and the scope, then choose the shortest adequate route','At the start, the natural and forced terms must add to v₀. For startup use the differential equation, state or complete Laplace solution. For steady sinusoidal voltage or power use phasors, stating the peak/RMS convention.',String.raw`v(0^+)=v_0,\qquad\dot v(0^+)=\frac{Ku(0)-v_0}{\tau}=${n((a.gain*u0-p.v0)/a.tau)}\,\mathrm{V/s}`),
    ],advantage:'The route depends on the requested quantity. State equations handle stored energy, Laplace exposes poles and input transforms, and phasors give steady sinusoidal amplitude and phase with compact algebra.',limitation:'Compare like quantities: an instantaneous voltage, a transform and a phasor are different representations. Phasors alone cannot reproduce startup; a transfer function alone excludes the initial-state term.',
    checks:[row('complete capacitor voltage',a.v,x.sol.volt.C1,'V'),row('complete capacitor current',a.i,x.sol.i.C1,'A'),row('steady phasor real part',a.output[0],x.ac.volt.C1[0],'V'),row('steady phasor imaginary part',a.output[1],x.ac.volt.C1[1],'V')],
    practice:[{prompt:'Set the source to zero in your calculation. With the displayed initial voltage, what is the capacitor voltage after one time constant?',target:p.v0/Math.E,unit:'V',hint:'This is a zero-input response: v(t) = v₀ exp(−t/τ). At t = τ the exponent is −1.'},{prompt:'For the current sinusoidal drive, calculate the RMS steady output voltage.',target:z.cabs(a.output)/Math.SQRT2,unit:'V',hint:'The phasor uses peak amplitude. Divide its magnitude by √2 to obtain RMS.'},{prompt:'Keep the current drive and components, but start with an uncharged capacitor. Calculate dv/dt at 0⁺.',target:a.gain*u0/a.tau,unit:'V/s',hint:'Use the state equation with x = 0 and u(0) = A sin φ. Convert the phase knob from degrees when using sine.'}]}
}
export function completionCapstones(base,groups){
  const branched=base.find(e=>e.id==='h8'),loaded=base.find(e=>e.id==='k2')
  const common={study:capstoneStudy,claim:{},ghost:undefined,circuitLab:undefined,view:'equations',studyViews:['state','phasor','laplace'],
    lesson:{see:'Start by identifying the requested quantity and the stored initial state. Derive the governing equation, predict the beginning and long-time behavior, then compare the independent calculation with the live circuit.',why:'A complete solution includes definitions, reference directions, initial conditions, units and a check. The method is a choice you should be able to explain. Work through the three practice variants without changing the circuit or revealing the answers first.',try:[{say:'Derive the model and check its coefficients against the State equations view.',reads:[]},{say:'Complete all three independent practice questions in Equations.',reads:[]},{say:'Change an initial condition and explain which parts of the response change.',reads:[]}]},
    headline:{label:'the complete capacitor voltage at the cursor',tag:'v_C',unit:'V',where:null,value:x=>x.sol.volt.C1}}
  const first={...branched,...common,id:'g8',name:'Circuits I capstone: derive and check two coupled states',group:groups[6],prerequisites:['g7','f9','d9'],views:['equations','state','scope','power'],ac:undefined,phasor:undefined,
    params:branched.params.filter(k=>!['A','f','phi'].includes(k.key)).map(k=>({...k,...(k.key==='N'?{unit:'time constants',default:5}:{})})).concat({key:'E',label:'Step V₁',unit:'V',default:6,min:-20,max:20,scale:'linear'}),
    net:p=>{const net=branched.net({...p,A:0,f:100,phi:0});return {...net,elements:net.elements.map(e=>e.id==='V1'?{...e,wave:undefined,value:p.E}:e)}},window:p=>p.N*Math.max(p.R1*p.C1,p.L1/p.R2),cursor:.2,closedHeadline:(p,x)=>branchedStep(p,x.cursor).v}
  const second={...loaded,...common,id:'n1',name:'Circuits II capstone: one circuit, four analysis routes',group:groups[13],prerequisites:['m3','k3','l4','j7'],views:['equations','state','laplace','scope','phasor','bode','acpower'],
    params:[...loaded.params.map(k=>({...k})),{key:'v0',label:'Initial v_C',unit:'V',default:3,min:-20,max:20,scale:'linear'}],net:p=>{const net=loaded.net(p);return {...net,elements:net.elements.map(e=>e.id==='C1'?{...e,x0:p.v0}:e)}},cursor:.1,closedHeadline:(p,x)=>loadedComplete(p,x.cursor).v}
  return [first,second]
}
