import {knob as k,step as s,reading as r,curve,samples,texnum as N} from '@ee-labs/lessons/model'
import {complex} from '@ee-labs/network'
import {cascode,miller,nativeAt,outputStage,railInput,logPoints,millerDrawing} from './architectures.js'
const {cabs,csub}=complex,db=x=>20*Math.log10(x),phase=z=>Math.atan2(z[1],z[0])*180/Math.PI
const tail=k('tail','Input-pair tail current',40e-6,20e-6,80e-6,'A'),eff=k('gmid','Input and cascode gm / ID',15,10,20,'V⁻¹'),cl=k('cl','Output load capacitance',2e-12,.5e-12,10e-12,'F'),supply=k('vdd','Supply voltage',1.8,1.4,2.4,'V')
const symbols=[[String.raw`I_T,I_D,g_m,r_o,g`,'Tail and branch currents (A), transconductance (S), device output resistance (Ω), and g=1/ro (S). Equal branch currents are IT/2.'],[String.raw`V_A,V_{OV},V_T,V_{CM},V_{DD}`,'Early voltage (10 V for cascodes), overdrive (V), threshold magnitude 0.45 V, input common-mode voltage (V) and supply (V).'],[String.raw`C_s,C_L,C_c,s`,'Internal-node capacitance (20 fF for cascodes), output load and compensation capacitances (F); Laplace variable s, with s=j2πf for phasors.'],[String.raw`A(s),T(s),f_u,PM`,'Open-loop voltage gain, unity-feedback return ratio T=A, actual unity crossover |T|=1 (Hz), and phase margin 180°+arg T at that crossing.'],[String.raw`R_{out},V_{pp},P`,'Small-signal output resistance (Ω), single-ended peak-to-peak output window (V), and allocated quiescent power (W).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'C. Amplifier architectures',knobs,question,intro,try:attempt,solve,symbols,flow:['Establish current and headroom','Derive the small-signal or device equations','Compare the result with a stated requirement'],route:'Bias and compliance equations establish whether the operating point is usable. Linear nodal equations give A(s); evaluating s=j2πf gives the phasor response and loop margin. A static output-current curve does not establish closed-loop stability.',limits:'Declared teaching models, not a foundry design. Square-law headroom and current models are explicitly separate from Group A’s charge-based sizing model. No device noise, mismatch, body effect, wiring parasitics or clipping transient is implied. All output swings in this group are single-ended peak-to-peak.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const read=x=>[r('DC gain',db(x.dc),'dB'),r('Actual unity crossover',x.crossover/1e6,'MHz'),r('Unity-feedback phase margin',x.pm,'°'),r('Output window',x.swing,'Vpp'),r('Allocated power',x.power*1e6,'μW')]
const bode=x=>[{...curve('Open-loop gain from the nodal equations','Frequency (Hz)','Gain (dB)',logPoints(f=>db(cabs(x.at(f))))),logX:true},{...curve('Phase of the same transfer','Frequency (Hz)','Phase (°)',logPoints(f=>phase(x.at(f)))),logX:true}]
const checks=x=>({headers:['Requirement','Calculated','Target','Result'],rows:[['DC gain',db(x.dc),60,'dB',db(x.dc)>=60],['Unity crossover',x.crossover/1e6,20,'MHz',x.crossover>=20e6],['Single-ended window',x.swing,1,'Vpp',x.swing>=1],['Allocated power',x.power*1e6,200,'μW',x.power<=200e-6],['Phase margin',x.pm,45,'°',x.pm>=45]].map(([name,value,target,unit,pass])=>[name,N(value)+' '+unit,(name==='Allocated power'?'≤ ':'≥ ')+target+' '+unit,pass?'Meets target':'Below requirement'])})
const auxText=x=>x.aux.crossings.length?x.aux.crossings.map(c=>`${c.direction}: ${N(c.crossover/1e6)} MHz / ${N(c.pm)}°`).join('; '):'No unity crossing in 1 mHz–1 THz; phase margin is undefined'
const check=x=>`Native AC nodal comparison at 1 MHz: relative difference ${(cabs(csub(x.at(1e6),nativeAt(x.net,1e6)))/cabs(x.at(1e6))).toExponential(2)}.`
const comparison=p=>({headers:['Architecture','Gain (dB)','Crossover (MHz)','Window (Vpp)','Power (μW)','PM (°)'],rows:[['Telescopic',cascode({...p,folded:0})],['Folded',cascode({...p,folded:1})],['Miller, default stages',miller({cl:p.cl,vdd:p.vdd})],['Boosted, B0=40',cascode({...p,boost:40})]].map(([label,x])=>[label,...[db(x.dc),x.crossover/1e6,x.swing,x.power*1e6,x.pm].map(N)])})
function cascodeLesson(folded){return L(folded?'c2':'c1',folded?'Fold the input path to reach a different common-mode range':'A telescopic cascode trades headroom for gain',[tail,eff,cl,supply,k('vcm','Input common-mode voltage',folded?.5:.7,0,2.4,'V')],
 'Can this operating point meet gain, speed, swing and power together?',folded?'A PMOS input pair feeds a folded output stack. We retain C1’s output small-signal network to isolate the input-range and current-allocation tradeoff; the fold does not magically create bandwidth.':'Two cascoded output branches meet at the output node. Their resistances are in parallel. Deriving that connection prevents a factor-of-four gain error from entering the architecture comparison.',
 folded?'Compare C1 and C2 at 0 V common mode. Then increase load capacitance and watch the actual unity crossover.':'Change common mode before changing gain. A good AC result cannot rescue an input point outside the declared compliance window.',p=>{const x=cascode({...p,folded});return O([
 s('Convert the current budget to device parameters','Each equal branch carries half the tail current. The selected efficiency fixes gm and the square-law comparison overdrive; Early voltage fixes ro.',String.raw`I_D=I_T/2,\quad g_m=I_D(g_m/I_D),\quad r_o=V_A/I_D,\quad V_{OV}=2/(g_m/I_D)`,String.raw`I_D=${N(p.tail*5e5)}\,\mu\mathrm A,\quad g_m=${N(x.gm*1e6)}\,\mu\mathrm S,\quad r_o=${N(x.ro/1e3)}\,\mathrm{k\Omega}`),
 s('Solve one output branch, then combine both','At DC the internal stack voltage vx obeys (2g+gm)vx=gvo. Substituting into output current gives the branch conductance. Two equal branches double conductance.',String.raw`i_o=g v_o-(g+g_m)v_x,\quad R_{branch}=2r_o+g_mr_o^2,\quad R_{out}=R_{branch}/2`,String.raw`R_{out}=${N(x.rout/1e6)}\,\mathrm{M\Omega},\quad A(0)=g_mR_{out}=${N(x.dc)}`),
 s('Retain internal charge storage before finding crossover','Each internal node has Cs=20 fF. The two identical branch admittances add to the load-capacitor admittance. Solve |A(j2πfu)|=1; gm/(2πCL) is only a comparison estimate.',String.raw`Y_b(s)=\frac{g(g+sC_s)}{2g+g_m+sC_s},\quad A(s)=\frac{g_m}{sC_L+2Y_b(s)}`,String.raw`f_u=${N(x.crossover/1e6)}\,\mathrm{MHz},\quad f_{estimate}=${N(x.estimate/1e6)}\,\mathrm{MHz},\quad PM=${N(x.pm)}^\circ`),
 s('Check the separately declared DC headroom model',folded?'PMOS input drains are held at 0.30 V; the upper tail needs 0.10 V. The output stack reserves two overdrives at either rail. Two tail-current budgets are allocated.':'Input drains are held at 0.30 V and the lower tail needs 0.10 V. NMOS input saturation bounds common mode above by 0.30 V + VT. The output reserves one overdrive above that drain and two below VDD.',folded?String.raw`0\le V_{CM}\le V_{DD}-V_T-V_{OV}-0.1,\quad 2V_{OV}\le V_o\le V_{DD}-2V_{OV},\quad P=2V_{DD}I_T`:String.raw`V_T+V_{OV}+0.1\le V_{CM}\le0.3+V_T,\quad0.3+V_{OV}\le V_o\le V_{DD}-2V_{OV},\quad P=V_{DD}I_T`,String.raw`V_{CM}\in[${N(x.cmMin)},${N(x.cmMax)}]\,\mathrm V,\quad V_o\in[${N(x.outMin)},${N(x.outMax)}]\,\mathrm V`)
 ],[...read(x),r('Input common-mode margin',x.headroom,'V')],bode(x),x.headroom>=0?'The common-mode point fits the declared DC window. Read every target row: gain alone is not the design specification.':'The common-mode point fails the declared DC window. AC values describe the assumed linear network and are not an accepted transistor operating point.',x.rout/1e6,'MΩ','Calculate the two-branch output resistance.','Find 2ro + gm ro², then divide by two.',{check:check(x),table:folded?comparison(p):checks(x),plotNote:'The phasor curve belongs to the explicitly linearized output stack. The comparison shares the selected load, supply and cascode bias; Miller uses its displayed default stage parameters. Targets: 60 dB, 20 MHz, 1 Vpp, at most 200 μW and at least 45°. All rows assume valid bias points. No extra folded-node parasitic is assumed; real folded structures require that additional check.'})})}
export const ARCHITECTURE_LESSONS=[cascodeLesson(0),cascodeLesson(1),
L('c3','Miller compensation separates poles and introduces feedforward',[k('gm1','First-stage transconductance',200e-6,100e-6,500e-6,'S'),k('gm2','Second-stage transconductance',500e-6,250e-6,2e-3,'S'),k('cc','Miller compensation capacitance',1e-12,.5e-12,3e-12,'F'),cl,supply],
 'Why is gm1/(2πCc) insufficient to predict stability?',
 'Two inverting transconductance stages give positive overall gain. A capacitor between their outputs loads the first stage through feedback, but also sends feedforward current directly to the output.',
 'Increase Cc from 1 pF to 3 pF. Compare phase margin with unity crossover, then increase gm2 to move the unwanted zero.',p=>{const x=miller(p);return O([
 s('Name the two node equations','va is the first-stage output and vo the final output. C1=0.1 pF, g1=1/R1 and g2=1/R2. The current allocations give R1=100/gm1 and R2=50/gm2, corresponding to Early voltage 5 V.',String.raw`\begin{aligned}[g_1+s(C_1+C_c)]v_a-sC_cv_o&=-g_{m1}v_i\\(g_{m2}-sC_c)v_a+[g_2+s(C_L+C_c)]v_o&=0\end{aligned}`,String.raw`R_1=${N(x.r1/1e3)}\,\mathrm{k\Omega},\quad R_2=${N(x.r2/1e3)}\,\mathrm{k\Omega}`),
 s('Eliminate the intermediate voltage','The determinant D(s) contains both capacitive states. The numerator changes sign at a positive real s: this is a right-half-plane zero, not an extra stabilizing phase lead.',String.raw`A(s)=\frac{g_{m1}(g_{m2}-sC_c)}{D(s)},\quad D(s)=a_2s^2+a_1s+a_0`,String.raw`a_2=C_1C_L+C_1C_c+C_LC_c,\quad a_1=g_1(C_L+C_c)+g_2(C_1+C_c)+g_{m2}C_c,\quad a_0=g_1g_2`),
 s('Evaluate the actual loop at its unity crossing','Unity voltage feedback makes T=A. The phase-margin calculation uses the full numerator and denominator, including the feedforward zero.',String.raw`f_z=\frac{g_{m2}}{2\pi C_c},\quad |A(j2\pi f_u)|=1,\quad PM=180^\circ+\arg A(j2\pi f_u)`,String.raw`f_z=${N(x.zero/1e6)}\,\mathrm{MHz},\quad f_u=${N(x.crossover/1e6)}\,\mathrm{MHz},\quad PM=${N(x.pm)}^\circ`),
 s('Keep large-signal estimates separate','Input gm/ID=20 gives tail current gm1/10. Second-stage gm/ID=10 gives current gm2/10. A 0.2 V compliance reservation at each output rail sets the illustrative window; slew is a current-limit estimate, not this linear model’s transient.',String.raw`P=V_{DD}(g_{m1}/10+g_{m2}/10),\quad SR_{estimate}=\frac{g_{m1}/10}{C_c},\quad V_{pp}=V_{DD}-0.4`,String.raw`P=${N(x.power*1e6)}\,\mu\mathrm W,\quad SR_{estimate}=${N(x.slew/1e6)}\,\mathrm{V/\mu s}`)
 ],[...read(x),r('gm1/Cc frequency estimate',x.estimate/1e6,'MHz'),r('Right-half-plane zero',x.zero/1e6,'MHz')],bode(x),'Increasing compensation can improve margin while reducing crossover. Check the requirement table after each change; the default is deliberately not guaranteed to pass.',x.zero/1e6,'MHz','Calculate the right-half-plane zero frequency.','Divide gm2 by 2πCc.',{schematic:millerDrawing(p),table:checks(x),check:check(x),symbols:[...symbols,[String.raw`v_a,v_i,C_1,g_1,g_2,a_2,a_1,a_0`,'First-stage and input voltages (V), first-node capacitance (F), stage conductances (S), and coefficients of the displayed second-order determinant.']],sources:[['UC Berkeley EE140: practical Miller compensation','https://www-inst.cs.berkeley.edu/~ee140/sp12/lectures/Lec23w.PracticalCompensation.ee140.s12.ctn.pdf']]})}),
L('c4','Gain boosting adds two loops that need their own checks',[tail,eff,cl,supply,k('boost','Each auxiliary DC gain',40,5,100),k('auxGBW','Each auxiliary gain-bandwidth product',200e6,1e5,1e9,'Hz')],
 'Does higher output resistance still help when the boosters have finite speed?',
 'Each auxiliary amplifier senses its internal stack node and drives that cascode gate in the opposite direction. Both boosters have a declared single-pole response. Their local loops and the overall feedback loop are distinct measurements.',
 'Lower auxiliary gain-bandwidth while holding DC gain fixed. Read both local margins as well as the overall loop margin.',p=>{const x=cascode(p);return O([
 s('State what the auxiliary amplifier senses and drives','For each side, vx is the internal stack voltage and vg its cascode gate. A negative vg response increases the restoring current. The 20 μA extra total current is an explicit auxiliary bias allocation.',String.raw`v_g=-B(s)v_x,\quad B(s)=\frac{B_0}{1+s\tau_b},\quad\tau_b=\frac{B_0}{2\pi GBW_b}`,String.raw`B_0=${N(p.boost)},\quad\tau_b=${N(x.tau*1e9)}\,\mathrm{ns}`),
 s('Recalculate DC resistance before quoting gain','The cascode’s restoring transconductance becomes gm(1+B0), not gmB0 exactly. Both output branches remain in parallel.',String.raw`R_{out}=\frac{2r_o+g_m(1+B_0)r_o^2}{2},\quad A(0)=g_mR_{out}`,String.raw`R_{out}=${N(x.rout/1e6)}\,\mathrm{M\Omega},\quad20\log_{10}A(0)=${N(db(x.dc))}\,\mathrm{dB}`),
 s('Carry the booster pole into the output admittance','Replace static boost by B(s). This expression keeps the internal stack capacitors and gives the same output phasors as the native controlled-source network.',String.raw`Y_b(s)=\frac{g(g+sC_s)}{2g+g_m[1+B(s)]+sC_s},\quad A(s)=\frac{g_m}{sC_L+2Y_b(s)}`,String.raw`f_u=${N(x.crossover/1e6)}\,\mathrm{MHz},\quad PM_{outer}=${N(x.pm)}^\circ`),
 s('Break one auxiliary loop while retaining the other','Let D=2g+gm+sCs and Yo=g+sCL+Yb for the branch with the other booster still closed. Solving the two node equations gives vx/vg. Repeat for the other side; symmetry makes the results equal here.',String.raw`T_b(s)=B(s)\frac{g_m(Y_o-g)}{DY_o-g(g+g_m)}`,x.aux.pm===null?String.raw`\text{No unity crossing: phase margin is undefined}`:String.raw`f_{u,b}=${N(x.aux.crossover/1e6)}\,\mathrm{MHz},\quad PM_n=PM_p=${N(x.aux.pm)}^\circ`)
 ],[...read(x),...(x.aux.pm===null?[]:[r('Smallest auxiliary phase margin',x.aux.pm,'°')])],[...bode(x),{...curve('One booster broken; the other remains closed','Frequency (Hz)','Local return ratio (dB)',logPoints(f=>db(cabs(x.auxAt(f))))),logX:true}], 'The native tests independently break both physical auxiliary sources. All detected crossings are listed. Multiple crossings require a complete Nyquist or closed-pole assessment; a single phase-margin number alone is insufficient. Equal local results come from symmetry.',db(x.dc),'dB','Calculate the boosted DC voltage gain in decibels.','Compute gm times the parallel output resistance, then 20 log10.',{check:check(x),table:{headers:['Loop','Crossings and phase margins','Other loops'],rows:[['Overall',x.crossings.map(c=>`${c.direction}: ${N(c.crossover/1e6)} MHz / ${N(c.pm)}°`).join('; '),'Both boosters closed'],['Lower booster',auxText(x),'Upper booster closed; overall open'],['Upper booster',auxText(x),'Lower booster closed; overall open']]},symbols:[...symbols,[String.raw`B_0,B(s),\tau_b,GBW_b,D,Y_o,T_b`,'Auxiliary DC gain, frequency response, pole time constant (s), gain-bandwidth product (Hz), internal-node denominator (S), remaining output admittance (S), and local return ratio.']]})}),
L('c5','Output topology sets available current near the rails',[k('iq','Quiescent branch current',20e-6,5e-6,100e-6,'A'),supply,k('drive','Signed gate-drive increment',.3,-.4,.4,'V'),k('fraction','Output voltage / supply',.5,.01,.99),{...k('follower','Output connection',0,0,1,'',1),options:['Common-source push-pull','Complementary source followers']}],
 'Why can an output stage deliver more than its idle current yet lose drive near a rail?',
 'A complementary pair has both devices slightly on at rest. Raising the signed drive increases sourcing and reduces sinking. The chosen output voltage is imposed for this static capability measurement; it is not the result of a closed-loop amplifier simulation.',
 'Compare both topologies at output/supply 0.5 and 0.9 with +0.3 V drive. Then reverse drive and move near the lower rail.',p=>{const x=outputStage(p),curves=[0,1].map(follower=>({label:follower?'Source followers':'Common-source',points:samples(fraction=>outputStage({...p,fraction,follower}).current*1e6,.01,.99)}));return O([
 s('Size both devices for the same idle current','The declared strong-inversion law uses |VT|=0.45 V, quiescent overdrive 0.15 V and zero channel-length modulation. Both idle currents share one supply path, so idle power is VDD Iq.',String.raw`\beta=2I_q/V_{OV,q}^2,\quad I_D=\tfrac12\beta V_{OV}^2\quad(V_{DS}\ge V_{OV})`,String.raw`\beta=${N(x.beta)}\,\mathrm{A/V^2},\quad P_q=${N(x.power*1e6)}\,\mu\mathrm W`),
 s('Compute gate voltages and respect the supply rails','clip means clamp to [0,VDD]. For common-source outputs the upper device is PMOS and lower NMOS. Followers instead use an upper NMOS and lower PMOS, whose source voltages both move with the output.',p.follower?String.raw`V_{gn}=clip(V_o+V_T+0.15+u),\quad V_{gp}=clip(V_o-V_T-0.15+u)`:String.raw`V_{gp}=clip(V_{DD}-V_T-0.15-u),\quad V_{gn}=clip(V_T+0.15-u)`,String.raw`V_{g,upper}=${N(x.upperGate)}\,\mathrm V,\quad V_{g,lower}=${N(x.lowerGate)}\,\mathrm V`),
 s('Use the device law in its actual region','Use VSG and VSD magnitudes for PMOS. Below overdrive in drain-source voltage, use the triode expression; nonpositive overdrive means cutoff. Subtract sink current from source current.',String.raw`I_{triode}=\beta(V_{OV}V_{DS}-V_{DS}^2/2),\quad I_o=I_{upper}-I_{lower}`,String.raw`I_o=${N(x.upper.id*1e6)}-(${N(x.lower.id*1e6)})=${N(x.current*1e6)}\,\mu\mathrm A`),
 s('Interpret the window and current separately','The idle compliance window reserves VOV at each rail for common-source, and VT+VOV for followers. At nonzero drive, the current curve gives the available current at the chosen output; the idle window is not a guaranteed loaded swing.',String.raw`V_{pp,CS}=V_{DD}-2V_{OV,q},\quad V_{pp,SF}=V_{DD}-2(V_T+V_{OV,q})`,String.raw`V_{pp,selected}=${N(x.swing)}\,\mathrm V`)
 ],[r('Net source current',x.current*1e6,'μA'),r('Idle current',p.iq*1e6,'μA'),r('Idle compliance window',x.swing,'Vpp')],[{label:'Current capability at the selected drive',xLabel:'Output / supply',yLabel:'Source current (μA)',traces:curves}], 'A positive current can charge a load capacitance or feed a resistive load; a negative current sinks it. This output stage alone has no defined amplifier gain or phase margin.',x.current*1e6,'μA','Calculate net current delivered to the output.','Subtract lower-device current from upper-device current.',{table:{headers:['Device','Current','Operating region'],rows:[['Upper',N(x.upper.id*1e6)+' μA',x.upper.region],['Lower',N(x.lower.id*1e6)+' μA',x.lower.region]]},symbols:[...symbols,[String.raw`I_q,\beta,u,V_{gn},V_{gp},V_{DS},V_{SG},V_{SD}`,'Idle current (A), current factor (A/V²), signed drive (V), NMOS/PMOS gate voltages (V), and device-oriented drain/source/gate voltage differences (V).']]})}),
L('c6','Steer complementary input-pair currents to control gm',[tail,supply,cl,k('vcm','Input common-mode voltage',.9,0,2.4,'V'),{...k('steer','Tail-current control',0,0,1,'',1),options:['Fixed tail commands','Ideal constant-gm bias control']}],
 'Why does simply enabling both input pairs double their combined transconductance?',
 'An NMOS pair loses tail headroom near ground; a PMOS pair loses it near the upper rail. We solve each tail current with the square-law transistor law and source-node headroom. An explicitly ideal bias controller can reduce the shared current command to keep combined gm constant.',
 'At mid-supply compare fixed and controlled commands. In the overlap each controlled tail needs a quarter of its original current, not half, because gm scales with the square root of current.',p=>{const x=railInput(p),points=steer=>samples(vcm=>railInput({...p,vcm,steer}).gm*1e6,0,p.vdd,101);return O([
 s('Define a pair and its tail device','Each nominal tail IT corresponds to input overdrive 0.15 V and tail overdrive 0.10 V. At actual tail current I, each input transistor carries I/2, so its overdrive is sqrt(I/βin).',String.raw`\beta_{in}=I_T/0.15^2,\quad\beta_{tail}=2I_T/0.10^2,\quad g_{m,pair}=\sqrt{\beta_{in}I}`,String.raw`g_{m,target}=\sqrt{\beta_{in}I_T}=${N(x.target*1e6)}\,\mu\mathrm S`),
 s('Solve current with the available source-node voltage','For NMOS the tail drain voltage is VCM−VT−sqrt(I/βin). For PMOS replace VCM by VDD−VCM. Solve I=ItailMOS(VGS, VDS) using the selected command to set tail gate overdrive; zero or negative headroom cuts off current.',String.raw`V_{DS,tail,n}=V_{CM}-V_T-\sqrt{I_n/\beta_{in}},\quad I_n=I_{MOS}(V_T+\sqrt{2I_{cmd}/\beta_{tail}},\max(0,V_{DS,tail,n}))`,String.raw`I_n=${N(x.n.current*1e6)}\,\mu\mathrm A,\quad I_p=${N(x.p.current*1e6)}\,\mu\mathrm A`),
 s('Add transconductances before choosing a current command','Without control, both fully active pairs contribute nominal gm. The ideal controller solves for a common command scale c between zero and one. In full overlap, two sqrt(c) terms must sum to one.',String.raw`g_{m,total}=\sqrt{\beta_{in}I_n}+\sqrt{\beta_{in}I_p},\quad 2\sqrt c=1\Rightarrow c=1/4`,String.raw`c=${N(x.scale)},\quad g_{m,total}=${N(x.gm*1e6)}\,\mu\mathrm S`),
 s('Translate gm into an explicitly limited bandwidth model','For comparison, drive Rout=100 kΩ in parallel with the selected CL. This one-pole stage has A0=gm,total Rout. Its exact unity crossing differs slightly from gm/(2πCL); input-pair parasitic poles are not modeled.',String.raw`A(s)=\frac{g_{m,total}R_{out}}{1+sR_{out}C_L},\quad f_u=\frac{\sqrt{A_0^2-1}}{2\pi R_{out}C_L}\quad(A_0>1)`,String.raw`f_u=${N(x.crossover/1e6)}\,\mathrm{MHz},\quad P_{pairs}=${N(x.power*1e6)}\,\mu\mathrm W`)
 ],[r('Combined transconductance',x.gm*1e6,'μS'),r('One-pole unity crossover',x.crossover/1e6,'MHz'),r('Input-pair power',x.power*1e6,'μW')],[{label:'Input transconductance across common mode',xLabel:'Common mode (V)',yLabel:'gm (μS)',traces:[{label:'Fixed tails',points:points(0)},{label:'Ideal bias control',points:points(1)}]}],p.vcm>p.vdd?'The selected common mode exceeds the supply. The simplified compliance equations do not establish safe beyond-rail operation.':'The steering curve is a solved ideal bias-control target, not an implemented steering transistor network. Bias-loop dynamics, input offset and noise through handover need further design.',x.gm*1e6,'μS','Calculate combined input transconductance.','Add sqrt(βin In) and sqrt(βin Ip).',{table:{headers:['Pair','Tail current','Tail region','Tail headroom'],rows:[['NMOS',x.n],['PMOS',x.p]].map(([label,d])=>[label,N(d.current*1e6)+' μA',d.region,N(d.headroom)+' V'])},symbols:[...symbols,[String.raw`\beta_{in},\beta_{tail},I_{cmd},c,I_n,I_p`,'Input/tail transistor current factors (A/V²), commanded tail current (A), common command scale, and solved NMOS/PMOS tail currents (A).']],sources:[['Analog Devices: input and output rail limitations','https://www.analog.com/en/resources/analog-dialogue/raqs/raq-issue-141.html']]})})
]
