import {knob as k,step as s,reading as r,curve,samples,texnum as N} from '@ee-labs/lessons/model'
import {biasDrawing,bandgap,betaBias,ratioRun,driftRun,BG} from './bias.js'
const R=k('resistance','Bias resistance',10000,5000,50000,'Ω'),K=k('ratio','NMOS size ratio K',4,2,16),W=k('wl','Smaller NMOS width / length',10,5,40),seed=k('seed','Repeatable sample seed',42,1,999,'',1)
const symbols=[[String.raw`I,I_s,g_m,\beta`,'Mirrored branch current (A), auxiliary startup current (A), transconductance (S), and μCox(W/L) (A/V²).'],[String.raw`R,K,V_{OV}`,'Bias resistance (Ω), NMOS size ratio greater than one, and gate overdrive (V).'],[String.raw`T,T_0,U_T`,'Absolute temperature (K), reference temperature 300 K, and thermal voltage kT/q (V).'],[String.raw`V_{BE},\Delta V_{BE},M,N`,'Junction voltage and area-induced voltage difference (V), dimensionless PTAT weight and junction area ratio.'],[String.raw`g,d,\alpha_R`,'Common fractional process shift, local ratio error and resistor fractional temperature coefficient (K⁻¹).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'B. Bias and references',knobs,question,intro,try:attempt,solve,symbols,flow:['Write the bias or charge balance','Substitute device and process values','Check operating points, drift and spread'],route:'DC equations determine possible bias points. Differentiation gives local temperature sensitivity; a parameter ensemble measures spread under explicitly chosen distributions. A phasor analysis needs an established operating point and cannot choose a startup state.',limits:'Generic teaching process. The beta-multiplier uses matched thresholds and the strong-inversion square law, with ideal unity current mirrors and no body effect or channel-length modulation. Tolerances are declared bounded uniform examples, not foundry guarantees.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const stats=(x,label)=>[r(label+' mean',x.mean.value),r('Mean 95% interval lower',x.mean.ci[0]),r('Mean 95% interval upper',x.mean.ci[1]),r('Estimated yield',100*x.yield.value,'%')]
const ensembleTable=x=>({headers:['Statistic','Value','95% interval','Meaning'],rows:[['Mean',N(x.mean.value),x.mean.ci.map(N).join(' to '),'Uncertainty of estimated mean'],['Yield',N(100*x.yield.value)+'%',x.yield.ci.map(v=>N(100*v)+'%').join(' to '),'Wilson interval for pass proportion'],['Sample count',x.count,'—','Independent draws with displayed seed']]})
const samplePlot=x=>({...curve('Repeatable parameter ensemble','Sample','Output / nominal',x.values.slice(0,160).map((y,i)=>({x:i,y}))),stems:true})
export const BIAS_LESSONS=[
L('b1','Matched ratios reject common process shifts',[k('absolute','Absolute tolerance bound',.2,.01,.3),k('match','Ratio mismatch bound',.001,.0001,.01),{...k('mode','Resistor relationship',0,0,1,'',1),options:['Matched pair','Independent absolute errors']},seed],'Why can a resistor ratio be more predictable than either resistor?',
'Two nearby resistors can share a large common process shift. Their ratio cancels that shared factor, leaving local mismatch. Two unrelated resistors do not share the same cancellation.',
'Compare matched and independent resistors using the same seed. Change absolute tolerance while holding mismatch fixed.',p=>{const x=ratioRun(p);return O([
s('Write the two manufacturing models','For the matched pair, R1=R0(1+g) and R2=R0(1+g)(1+d). For the independent case replace the denominator shift g with an independent h. Each error is uniformly distributed within the selected bounds.',String.raw`q_{matched}=\frac{R_2}{R_1}=1+d,\quad q_{independent}=\frac{(1+g)(1+d)}{1+h}`),
s('Translate the ratio into a divider','With R2 below the output node, the fraction of input voltage is q/(1+q). A small ratio error has half as much fractional effect on an equal-resistor divider.',String.raw`V_o/V_i=q/(1+q),\quad\left.\frac{d\ln(V_o/V_i)}{d\ln q}\right|_{q=1}=\frac12`,String.raw`q_{nominal}=1,\quad(V_o/V_i)_{nominal}=0.5`),
s('Measure spread without confusing it with uncertainty','The trace shows individual ratio samples. The table gives confidence intervals for their mean and for yield within ±1% of the nominal ratio; these are not component tolerance limits.',String.raw`\bar q=\frac1n\sum_iq_i,\quad Y=\frac{\#\{|q_i-1|\le0.01\}}n`,String.raw`n=${x.count},\quad\bar q=${N(x.mean.value)},\quad Y=${N(100*x.yield.value)}\%`)
],stats(x,'Ratio'),[samplePlot(x),curve('Divider versus actual ratio','R2/R1','Vout/Vin',samples(q=>q/(1+q),.5,1.8))],p.mode?'Independent absolute errors do not cancel. The nominal divider remains one half, but the individual results spread.':'Common process variation cancels from the ratio exactly in this model. Local mismatch remains.',.5,'','Calculate the nominal equal-resistor divider gain.','Set q = 1 in q/(1 + q).',{table:ensembleTable(x),plotNote:'2048 independent seeded draws. Ratio tolerance is a bound, not a Gaussian sigma. The underlying sampler preserves the declared correlation.'})}),
L('b2','A beta-multiplier sets transconductance',[K,R,W,k('supply','Supply voltage',1.8,1.6,2,'V')],'How does a resistor set gm without an explicit voltage reference?',
'An ideal unity PMOS mirror feeds two NMOS branches. Their gates are common; the larger NMOS has a resistor under its source. Equal current and different gate overdrives establish the resistor drop.',
'Change K and R, then sweep supply. Notice which assumptions make the predicted current supply-independent.',p=>{const x=betaBias(p);return O([
s('Subtract gate-source voltages','M1 has β1=200 μA/V² times W/L; M2 has β2=Kβ1. Equal thresholds cancel and the common gate gives VGS1−VGS2=IR.',String.raw`I=\tfrac12\beta_1V_{OV1}^2=\tfrac12K\beta_1V_{OV2}^2,\quad IR=\sqrt{2I/\beta_1}(1-1/\sqrt K)`),
s('Solve the positive-current branch','Divide only after recognizing that I=0 is also a solution. On the nonzero branch gm1=√(2β1I).',String.raw`g_{m1}=\frac{2(1-1/\sqrt K)}R,\quad I=\frac{g_{m1}^2}{2\beta_1}`,String.raw`\beta_1=${N(x.beta)}\,\mathrm{A/V^2},\quad g_{m1}=${N(x.gm*1e6)}\,\mu\mathrm S,\quad I=${N(x.current*1e6)}\,\mu\mathrm A`),
s('Check voltages before asserting supply independence','The supply is absent from the ideal saturation equation. At this operating point the source resistor and NMOS overdrive require positive headroom. The ideal PMOS mirror is not a supply-headroom model.',String.raw`V_R=IR,\quad V_{OV1}=\sqrt{2I/\beta_1},\quad\left.\partial I/\partial V_{DD}\right|_{ideal}=0`,String.raw`V_R=${N(x.drop)}\,\mathrm V,\quad V_{OV1}=${N(x.overdrive)}\,\mathrm V,\quad V_{DD}=${N(p.supply)}\,\mathrm V`)
],[r('Positive branch current',x.current*1e6,'μA'),r('Transconductance',x.gm*1e6,'μS'),r('Source resistor drop',x.drop,'V')],[curve('Ideal saturated bias versus supply','Supply (V)','Current (μA)',samples(()=>x.current*1e6,1.6,2))],'The resistor sets gm; device current factor then sets current. This algebra does not guarantee startup or operation when real mirror devices run out of headroom.',x.gm*1e6,'μS','Calculate gm of the smaller NMOS.','Use 2(1 − 1/√K)/R.',{schematic:biasDrawing(p),table:{headers:['Branch','Current','Gate overdrive'],rows:[['M1',N(x.current*1e6)+' μA',N(x.overdrive)+' V'],['M2',N(x.current*1e6)+' μA',N(x.overdrive/Math.sqrt(p.ratio))+' V']]}})}),
L('b3','PTAT and CTAT cancel one temperature slope',[k('temperature','Temperature',300,233.15,398.15,'K'),k('n','Junction area ratio',8,2,16),k('m','PTAT multiplier',bandgap().weight,5,40)],'Why does a first-order bandgap still curve with temperature?',
'The junction voltage falls with temperature while the voltage difference between unequal-area junctions rises. A weighted sum can cancel their slopes at 300 K, while the nonlinear junction term remains.',
'Set M to the suggested cancellation weight. Sweep temperature and compare the local slope with the full-range variation.',p=>{const x=bandgap(p),values=samples(t=>bandgap({...p,temperature:t}).reference,233.15,398.15),extrema=[233.15,398.15,...(x.stationaryTemperature>=233.15&&x.stationaryTemperature<=398.15?[x.stationaryTemperature]:[])].map(temperature=>bandgap({...p,temperature}).reference),span=Math.max(...extrema)-Math.min(...extrema),v0=bandgap({...p,temperature:300}).reference;return O([
s('State the temperature law','Use extrapolated gap voltage VG0=1.206 V, VBE(300 K)=0.650 V, saturation-current exponent 4 and PTAT bias current exponent 1. Their difference ηeff=3 enters the logarithmic term.',String.raw`V_{BE}(T)=V_{G0}+(V_{BE0}-V_{G0})T/T_0-3U_T\ln(T/T_0)`,String.raw`V_{BE}=${N(x.vbe)}\,\mathrm V,\quad U_T=kT/q`),
s('Include the area ratio in the PTAT slope','Equal currents and area ratio N give ΔVBE=UT ln N. The factor ln N belongs in its derivative too.',String.raw`\Delta V_{BE}=U_T\ln N,\quad\frac{d\Delta V_{BE}}{dT}=\frac{k}{q}\ln N`,String.raw`\Delta V_{BE}=${N(x.ptat*1000)}\,\mathrm{mV},\quad slope=${N(x.slopePTAT*1e6)}\,\mu\mathrm{V/K}`),
s('Choose a cancellation weight at one temperature','M is fixed after trimming; it is not readjusted at every temperature.',String.raw`V_{ref}=V_{BE}+M\Delta V_{BE},\quad M_{opt}=-\left.\frac{dV_{BE}/dT}{(k/q)\ln N}\right|_{T_0}`,String.raw`M_{opt}=${N(x.optimum)},\quad V_{ref}=${N(x.reference)}\,\mathrm V,\quad dV_{ref}/dT=${N(x.slope*1e6)}\,\mu\mathrm{V/K}`),
s('Measure the remaining curvature','Box temperature coefficient divides the total voltage span by the nominal voltage and temperature span. It is not the local derivative.',String.raw`TC_{box}=\frac{V_{max}-V_{min}}{V_{ref}(T_0)(T_{max}-T_{min})}`,String.raw`\Delta V=${N(span*1000)}\,\mathrm{mV},\quad TC_{box}=${N(span/v0/165*1e6)}\,\mathrm{ppm/K}`)
],[r('Reference',x.reference,'V'),r('Suggested multiplier',x.optimum),r('Full-range variation',span*1000,'mV')],[curve('First-order compensated reference','Temperature (K)','Vref (V)',values),{label:'Contributions to the reference',xLabel:'Temperature (K)',yLabel:'Voltage (V)',traces:[{label:'CTAT: VBE',points:samples(t=>bandgap({...p,temperature:t}).vbe,233.15,398.15)},{label:'Weighted PTAT',points:samples(t=>p.m*bandgap({...p,temperature:t}).ptat,233.15,398.15)}]}],'First-order cancellation removes one slope at the trim temperature. Curvature, resistor-ratio drift, finite beta and amplifier offset still need separate treatment.',x.optimum,'','Calculate the PTAT weight for zero slope at 300 K.','Divide the magnitude of the CTAT slope at 300 K by (k/q) ln N.',{plotNote:'The selected temperature moves the numeric operating point. Both curves use one fixed M across the full range.'})},{sources:[['Analog Devices: Understanding and Applying Voltage References','https://www.analog.com/en/resources/app-notes/an-82f.html']],limits:'Analytic junction-temperature law with PTAT bias, no finite-beta or loading error. The multiplier is ideal and temperature independent. This is a reference-core calculation, not a complete bandgap circuit simulation.'}),
L('b4','Startup must escape a valid zero-current solution',[K,R,W,k('start','Auxiliary startup injection',0,0,100e-9,'A')],'Why is a correct positive-current solution insufficient to guarantee startup?',
'The ideal beta-multiplier also satisfies every DC equation with both branches off. Inject an auxiliary current into the diode-connected M1 branch: M1 then carries I + Is while M2 carries I. This removes the zero-current root while the injection is active.',
'Compare zero startup injection with 5 nA. Read every reported root and the small bias shift caused by leaving injection on.',p=>{const x=betaBias(p);return O([
s('Retain the zero-current branch','The expression before division by √I has two roots. A DC calculation does not supply the circuit’s initial state.',String.raw`F(I)=\sqrt{2I/\beta_1}-\sqrt{2I/(K\beta_1)}-IR=0`,String.raw`I\in\{0,${N(x.current*1e6)}\,\mu\mathrm A\}\quad(I_s=0)`),
s('Model where the startup current enters','Injection adds to the smaller transistor branch only. Consequently its overdrive contains I + Is, while the resistor still carries I.',String.raw`F(I;I_s)=\sqrt{2(I+I_s)/\beta_1}-\sqrt{2I/(K\beta_1)}-IR`,String.raw`F(0;I_s)=\sqrt{2I_s/\beta_1}=${N(x.residual(0))}\,\mathrm V`),
s('Enumerate valid roots instead of selecting one silently','With no injection both roots are listed. Positive injection makes F(0)>0 and leaves one positive root. Solving this scalar equation does not model the startup transient or an automatic shutoff device.',String.raw`F(I_{op};I_s)=0`,String.raw`I_{positive}=${N(x.operating*1e6)}\,\mu\mathrm A,\quad residual=${N(x.residual(x.operating))}\,\mathrm V`)
],[r('Number of nonnegative roots',x.roots.length),r('Positive root',x.operating*1e6,'μA'),r('Injection-induced bias shift',100*(x.operating/x.current-1),'%')],[curve('Gate-voltage balance residual','Mirrored current (μA)','F(I) (V)',samples(i=>x.residual(i*1e-6),0,2*x.operating*1e6))],p.start?'Active startup injection eliminates the zero-current root. A practical startup circuit must turn off after establishing bias; that shutoff and its dynamics are outside this DC model.':'Both roots satisfy the ideal equations. No operating point is selected automatically: initial conditions and a startup path determine whether the real circuit reaches useful bias.',x.roots.length,'','How many nonnegative DC roots remain at this injection?','At Is = 0 retain both the zero and positive roots.',{schematic:biasDrawing(p),table:{headers:['Root','Mirrored current','Interpretation'],rows:x.roots.map((i,j)=>[j+1,N(i*1e6)+' μA',i===0?'Off state; valid DC root':'Positive bias; not a startup guarantee'])}})}),
L('b5','A reference does not erase resistor drift',[k('temperature','Temperature',300,233.15,398.15,'K'),k('tempco','Resistor temperature coefficient',1000,0,2000,'ppm/K'),k('tolerance','Absolute resistor tolerance bound',.2,.01,.3),{...k('mode','Current-setting method',0,0,1,'',1),options:['Beta-multiplier: inverse R squared','Bandgap / resistor: inverse R']},seed],'Which errors remain when a current is derived from a bandgap?',
'The beta-multiplier current depends on the inverse square of resistance. A voltage reference divided by a resistor improves that sensitivity to inverse resistance, but the resistor’s tolerance and temperature coefficient remain.',
'Compare both current-setting methods at 125 °C. Set resistor tempco to zero to isolate the bandgap’s residual curvature.',p=>{const x=driftRun(p),alpha=p.tempco*1e-6,factor=1+alpha*(p.temperature-300),b=bandgap({temperature:p.temperature}),ref0=bandgap().reference,gain=p.mode?b.reference/ref0/factor:1/factor**2,slope=p.mode?b.slope/b.reference-alpha/factor:-2*alpha/factor;return O([
s('Declare temperature and process effects separately','The ensemble varies the resistor at 300 K; the temperature curve holds the nominal process value fixed. This prevents counting a bound as a sigma or hiding one source of error inside another.',String.raw`R(T,e)=R_0(1+e)[1+\alpha_R(T-T_0)],\quad e\sim U[-\epsilon,+\epsilon]`,String.raw`R(T,0)/R_0=${N(factor)}`),
s('Normalize the two current laws','The nominal current cancels from each ratio. Bandgap voltage is evaluated from the same model as B3.',String.raw`\frac{I_\beta(T)}{I_\beta(T_0)}=\left(\frac{R_0}{R(T)}\right)^2,\quad\frac{I_{ref}(T)}{I_{ref}(T_0)}=\frac{V_{ref}(T)}{V_{ref}(T_0)}\frac{R_0}{R(T)}`,String.raw`I(T)/I(T_0)=${N(gain)}`),
s('Differentiate and check finite tolerance endpoints','A local derivative is not a finite ±20% change. The endpoint factors are evaluated without linearization.',String.raw`\alpha_{I\beta}=-2\alpha_R/[1+\alpha_R(T-T_0)],\quad\alpha_{Iref}=V_{ref}'/V_{ref}-\alpha_R/[1+\alpha_R(T-T_0)]`,String.raw`\alpha_I=${N(slope*1e6)}\,\mathrm{ppm/K},\quad I_{min}/I_0=${N((1+p.tolerance)**(p.mode?-1:-2))},\quad I_{max}/I_0=${N((1-p.tolerance)**(p.mode?-1:-2))}`)
],[r('Temperature-only current ratio',gain),r('Local current tempco',slope*1e6,'ppm/K'),...stats(x,'Process current ratio')],[curve('Nominal-process temperature drift','Temperature (K)','Current / current at 300 K',samples(t=>p.mode?bandgap({temperature:t}).reference/ref0/(1+alpha*(t-300)):1/(1+alpha*(t-300))**2,233.15,398.15)),samplePlot(x)],'A bandgap improves the voltage reference. A precision current still requires a suitable resistor, trimming or temperature compensation; it does not inherit voltage-reference drift alone.',slope*1e6,'ppm/K','Calculate the selected current’s local temperature coefficient.','Use the matching derivative, including resistor tempco.',{table:ensembleTable(x),plotNote:'The ensemble varies only resistor process error at 300 K. Yield means current within ±10% of nominal; the table reports its Wilson interval.'})})
]
