import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {complex} from '@ee-labs/network'
import {compensated,nested,gainDb} from './compensation.js'
const T=String.raw,cc=k('cc','Miller capacitance',1e-12,.5e-12,5e-12,'F'),rz=k('rz','Nulling resistance',2000,0,10000,'Ω'),gm2=k('gm2','Second-stage transconductance',500e-6,250e-6,1e-3,'S'),cl=k('cl','Load capacitance',2e-12,1e-12,5e-12,'F')
const matrix=a=>T`\begin{bmatrix}${a.map(row=>row.map(N).join('&')).join(T`\\`)}\end{bmatrix}`
const poly=(values,variable='s')=>values.map((v,i)=>T`(${N(v)})${values.length-i-1?`${variable}^{${values.length-i-1}}`:''}`).join('+')
const complexText=z=>`${fmt(z[0]/(2*Math.PI*1e6))}${z[1]<0?' − ':' + '}${fmt(Math.abs(z[1])/(2*Math.PI*1e6))}j`
const grid=(fn,lo=1e3,hi=1e9)=>Array.from({length:241},(_,i)=>{const x=lo*(hi/lo)**(i/240);return {x,y:fn(x)}})
const source=[['TI: Stability analysis and compensation','https://www.ti.com/lit/sloa020'],['UC Berkeley EE140: Practical compensation','https://www-inst.cs.berkeley.edu/~ee140/sp12/lectures/Lec23w.PracticalCompensation.ee140.s12.ctn.pdf']]
const loopLink=(x,id)=>({app:'control-lab',label:'Inspect this exact loop in Control Lab',patch:{plant:{type:'custom',params:[...Array(3-x.tf.b.length).fill(0),...x.tf.b,...Array(3-x.tf.a.length).fill(0),...x.tf.a]},ctrl:{type:'p',params:[1]},from:{app:'analog-ic-lab',id,label:'Miller compensation loop'}},note:'Transfers the full selected second-order return ratio T(s), including its right-half-plane zero, with unity control. Control Lab then shows the same follower T/(1+T). This link transfers the selected second-order model. The third-order models in E2 and E4 are explored within their lessons.'})
const symbols=[[T`v_i,v_a,v_o,u`,'Incremental input, first-stage and output voltages (V). For a follower vi=u−vo, where u is the reference step.'],[T`g_{m1},g_{m2},g_1,g_2`,'Stage transconductances and output conductances (S). gm1=200 µS, g1=2 µS and g2=10 µS; gm2 is adjustable.'],[T`C_1,C_L,C_c,R_z`,'First-node capacitance 0.1 pF, load and compensation capacitances (F), and series nulling resistance (Ω).'],[T`s,j,f,Y_c,A(s),T(s)`,'Laplace variable (s⁻¹), imaginary unit, frequency (Hz), compensation-branch admittance (S), open-loop amplifier gain and unity-feedback return ratio T=A.'],[T`f_x,PM,z,p,\omega`,'Actual unity crossing (Hz), phase margin (degrees), zero and pole locations (s⁻¹), and angular frequency ω=2πf. A positive real zero is in the right half-plane.'],[T`x,\dot x,\mathbf C,\mathbf G,\mathbf A,\mathbf B,t`,'State vector (V), time derivatives (V/s), capacitance/conductance matrices (F/S), state matrix (s⁻¹), input vector (s⁻¹), and elapsed time (s).'],[T`I_{lim},SR,f_t`,'Declared charging-current limit 20 µA, slew estimate Ilim/Cc (V/s), and dominant-pole frequency estimate gm1/(2πCc). Neither is the exact small-signal unity crossing.']]
const route='Start with KCL to see which current creates the pole or zero. Substitute s=j2πf for phasor gain and phase; that route is efficient for stability margins. Keep the capacitor states to find a step response and initial-condition effects. Both routes describe this same linear circuit; the charging-current slew estimate is a separate large-signal constraint.'
const limits='Linear transconductances with finite output resistances and explicit node capacitances. Ideal unity feedback; no rail clipping, transistor bias drift or current limiting in the plotted small-signal step. The 20 µA slew budget is an estimate for Cc only. Exact nodal poles include C1 and finite output conductances, so textbook pole-splitting and zero-cancellation estimates need not be exact.'
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return {id,name,group:'E. Amplifier compensation',knobs,question,intro,try:attempt,solve,symbols,route,limits,sources:source,flow:['Write the compensation-branch current','Find loop crossover and closed-loop poles','Compare small-signal settling with large-signal limits'],...extra}}
function O(steps,x,conclusion,question,answer,unit,hint,extra={}) {return {steps,readings:[r('Unity crossing',x.crossover/1e6,'MHz'),r('Global phase margin',x.pm,'°'),r('Closed-loop stable',x.stable?1:0,'1=yes'),...(!x.feed&&x.slew?[r('Charging-current slew estimate',x.slew/1e6,'V/µs')]:[])],plots:[{...curve('Return-ratio magnitude','Frequency (Hz)','Magnitude (dB)',grid(f=>gainDb(x.at(f)))),logX:true},{...curve('Return-ratio phase (principal angle)','Frequency (Hz)','Phase (degrees)',grid(f=>{const z=x.at(f);return Math.atan2(z[1],z[0])*180/Math.PI})),logX:true},curve('Linear follower response to a 1 mV step','Time (ns)','Output (mV)',x.response.points.map(p=>({x:p.x*1e9,y:p.y*1000})))],conclusion,practice:{question,answer,unit,hint,reason:conclusion},plotNote:'Gain and phase use the same transfer as the state response. Phase-margin calculations unwrap phase across all unity crossings; the plotted phase uses the principal angle. The step is incremental, begins with every state at zero, and does not include slew limiting.',...extra}}
function commonSteps(x){return [
 s('Name the compensation current and write both KCL rows','Both controlled stage currents point toward ground. Positive va therefore pulls the second-stage output downward. ic is positive from a toward out.',T`i_c=Y_c(s)(v_a-v_o),\quad Y_c(s)=\frac{sC_c}{1+sR_zC_c}`,T`(g_1+sC_1)v_a+i_c=-g_{m1}v_i,\quad(g_2+sC_L)v_o-i_c=-g_{m2}v_a`),
 s('Eliminate the first-stage voltage','Take the determinant of the two KCL rows. The feedthrough current in Cc subtracts from gm2 in the numerator.',T`A(s)=\frac{v_o}{v_i}=\frac{g_{m1}(g_{m2}-Y_c)}{(g_1+sC_1)(g_2+sC_L)+Y_c[g_1+g_2+g_{m2}+s(C_1+C_L)]}`,T`A(s)=\frac{${poly(x.tf.b)}}{${poly(x.tf.a)}}`),
 s('Locate the numerator zero before approximating poles','Multiply numerator and denominator by 1+sRzCc. The finite zero changes side when Rz crosses 1/gm2; equality removes the finite zero.',T`N(s)=g_{m1}[g_{m2}+sC_c(g_{m2}R_z-1)],\quad z=\frac{g_{m2}}{C_c(1-g_{m2}R_z)}`,x.zero===null?T`R_z=1/g_{m2}=${N(x.nulling)}\,\Omega:\quad\text{no finite zero}`:T`z=${N(x.zero)}\,s^{-1},\quad z/(2\pi)=${N(x.zero/(2*Math.PI*1e6))}\,MHz`),
 s('Measure crossover on the complete return ratio','Unity follower feedback gives T=A. Find every |T|=1 crossing, then read the unwrapped phase there. Also check the roots of D+N: a margin alone is not a general stability proof.',T`|T(j2\pi f_x)|=1,\quad PM=180^\circ+\arg T(j2\pi f_x),\quad D(s)+N(s)=0`,T`f_x=${N(x.crossover/1e6)}\,MHz,\quad PM=${N(x.pm)}^\circ,\quad\max\Re(p_{closed})=${N(Math.max(...x.closedPoles.map(z=>z[0])))}\,s^{-1}`)
 ]}
function stateStep(x){return s('Use the same charge balance as a state equation',x.rz?'Use x=[va,vo,vc]ᵀ, where vc is the voltage across Cc from a to its series-resistor junction. The current is (va−vo−vc)/Rz. All three capacitor states start at zero.':'With Rz=0, use the two independent node states x=[va,vo]ᵀ. The voltage across Cc is va−vo, so it is not an independent third state. All capacitor voltages are continuous through the step.',T`\mathbf C\dot x+\mathbf Gx=bv_i,\quad\dot x=\mathbf Ax+\mathbf Bv_i,\quad\mathbf A=-\mathbf C^{-1}\mathbf G,\quad\mathbf B=\mathbf C^{-1}b`,T`\mathbf A=${matrix(x.A)}\,s^{-1},\quad\mathbf B=${matrix(x.B.map(v=>[v]))}\,s^{-1}`)}
const followerStep=x=>s('Close the follower and propagate its initial state','Substitute vi=u−vo. The output selector c is [0,1] or [0,1,0]. Here x(0−)=x(0+)=0, u=0.001 V for t≥0. A dot means derivative per second; exp of a matrix propagates all coupled time constants together.',T`\mathbf A_{cl}=\mathbf A-\mathbf Bc,\quad x(t)=\int_0^t e^{\mathbf A_{cl}(t-\xi)}\mathbf B u\,d\xi,\quad v_o=cx`,T`u=0.001\,V,\quad v_o(${N(x.response.points.at(-1).x*1e9)}\,ns)=${N(x.response.points.at(-1).y*1000)}\,mV`)
const poleTable=x=>({headers:['Quantity','Real / 2π (MHz)','Imaginary / 2π (MHz)'],rows:[...x.poles.map((z,i)=>[`Open pole ${i+1}`,fmt(z[0]/(2*Math.PI*1e6)),fmt(z[1]/(2*Math.PI*1e6))]),...x.closedPoles.map((z,i)=>[`Closed pole ${i+1}`,fmt(z[0]/(2*Math.PI*1e6)),fmt(z[1]/(2*Math.PI*1e6))])]})
function drawing(x){const wire=(...v)=>({wire:v}),ground=(a,b)=>({gnd:[a,b]});return {elements:x.net.elements,caption:'The simulated two-stage circuit. G1 sinks gm1·vi at a; G2 sinks gm2·va at out. The compensation branch connects a to out. Rz is shown only when nonzero; all node voltages are changes from bias.',layout:{w:680,h:310,items:[wire(80,110,270,110),{node:'a',x:190,y:110,labelPos:'t'},wire(400,110,590,110),{node:'out',x:500,y:110,labelPos:'t'},wire(190,110,190,40),wire(190,40,285,40),{el:'Cc',x:305,y:40,dir:'h'},...(x.rz?[wire(325,40,365,40),{el:'Rz',x:385,y:40,dir:'h'},wire(405,40,500,40)]:[wire(325,40,500,40)]),wire(500,40,500,110),...[['G1',80],['R1',175],['C1',270],['G2',400],['R2',495],['CL',590]].flatMap(([id,a])=>[wire(a,110,a,170),{el:id,x:a,y:190,dir:'v'},wire(a,210,a,270),ground(a,270)])]}}}
function nestedDrawing(x){const wire=(...v)=>({wire:v}),ground=(a,b)=>({gnd:[a,b]});return {elements:x.net.elements,caption:'The three-node circuit used by the matrix. G1 sinks gm1·vi; G2 sources gm2·va; G3 sinks gm3·vb. Co connects a to out. Nested mode adds Ci from b to out. Feedforward mode removes Ci and adds Gff sinking 500 µS·va at out. Shunt resistors and capacitors retain their displayed values.',layout:{w:1140,h:420,items:[wire(70,190,280,190),{node:'a',x:175,y:190,labelPos:'t'},wire(420,190,630,190),{node:'b',x:525,y:190,labelPos:'t'},wire(770,190,x.feed?1060:980,190),{node:'out',x:875,y:190,labelPos:'t'},wire(175,190,175,45),wire(175,45,365,45),{el:'Co',x:385,y:45,dir:'h'},wire(405,45,875,45),wire(875,45,875,190),...(x.inner?[wire(525,190,525,115),wire(525,115,665,115),{el:'Ci',x:685,y:115,dir:'h'},wire(705,115,875,115)]:[]),...[['G1',70],['R1',175],['C1',280],['G2',420],['R2',525],['C2',630],['G3',770],['R3',875],['CL',980],...(x.feed?[['Gff',1060]]:[])].flatMap(([id,a])=>[wire(a,190,a,270),{el:id,x:a,y:290,dir:'v',...(id==='G2'?{flip:true}:{})},wire(a,310,a,370),ground(a,370)])]}}}
export const COMPENSATION_LESSONS=[
L('e1','Miller compensation: pole splitting and a right-half-plane zero',[cc,gm2,cl],
 'Why does a compensation capacitor add phase lag through a zero as well as moving poles?',
 'Continue the two-stage amplifier from C3. The compensation branch feeds current forward as well as feeding output changes back. Follow that current through KCL to see why the numerator contains a subtraction.',
 'Double gm2, then double Cc. Compare the exact crossover and margin with the frequency estimate gm1/(2πCc).',p=>{const x=compensated({...p,rz:0});return O([...commonSteps(x),stateStep(x),followerStep(x)],x,
 'A right-half-plane zero raises high-frequency magnitude while adding phase lag. The exact second pole includes C1 and finite conductances; the approximation gm2/CL is useful for intuition but is not the plotted pole.', 'Calculate the right-half-plane zero frequency.',x.zero/(2*Math.PI*1e6),'MHz','Divide gm2 by 2πCc and convert Hz to MHz.',{table:poleTable(x),schematic:drawing(x),handover:loopLink(x,'e1')})}),
L('e2','The nulling resistor moves the compensation zero',[cc,rz,gm2,cl],
 'When does a right-half-plane zero disappear, and when does it become a left-half-plane zero?',
 'Put a resistor in series with Cc. Its current changes the numerator and adds a third state when Rz is nonzero. Compare the textbook cancellation setting with the poles of the complete circuit.',
 'At gm2=500 µS compare Rz=0, 2000, 6000 and 10000 Ω. The 6000 Ω estimate does not exactly cancel the full model’s second pole.',p=>{const x=compensated(p),rows=[0,x.nulling,x.approxCancel,10000].map(rz=>({rz,x:compensated({...p,rz})}));return O([...commonSteps(x),
 s('Distinguish zero removal from an approximate pole cancellation','Rz=1/gm2 removes the s term from the numerator. A larger Rz gives phase lead. Matching the estimate gm2/CL yields the familiar second expression; finite C1 and resistance still move the actual pole.',T`R_{remove}=1/g_{m2},\quad R_{cancel,estimate}=\frac1{g_{m2}}\left(1+\frac{C_L}{C_c}\right)`,T`R_{remove}=${N(x.nulling)}\,\Omega,\quad R_{cancel,estimate}=${N(x.approxCancel)}\,\Omega`),stateStep(x),followerStep(x)],x,
 'Removing the finite zero and canceling a pole are different operations. The exact table includes the extra pole introduced by a nonzero series resistance.', 'Calculate the resistance that removes the finite compensation zero.',x.nulling,'Ω','Take the reciprocal of gm2 in siemens.',{schematic:drawing(x),table:{headers:['Rz (Ω)','Zero / 2π (MHz)','Crossing (MHz)','Margin (°)'],rows:rows.map(({rz,x})=>[fmt(rz),x.zero===null?'No finite zero':fmt(x.zero/(2*Math.PI*1e6)),fmt(x.crossover/1e6),fmt(x.pm)])}})}),
L('e3','Compensation trades bandwidth, margin and charging speed',[cc,gm2,cl],
 'Does a better phase margin always make the amplifier faster?',
 'Compare four compensation capacitors with the same transconductances, load and current budget. Small-signal settling follows the coupled state equations; large-signal charging has a separate current limit.',
 'Compare 0.5, 1, 2 and 5 pF. Find a setting that gives the margin you want, then inspect how much crossover and slew capability it costs.',p=>{const x=compensated({...p,rz:0}),rows=[.5,1,2,5].map(c=>({c,x:compensated({...p,cc:c*1e-12,rz:0})}));const result=O([...commonSteps(x),
 s('Budget the current needed to charge the compensation capacitor','The same current charging more capacitance produces a lower maximum slope. This Ilim/Cc estimate does not clamp the linear step plot and is not a full transistor-level slew simulation.',T`I=C_c\frac{dv_c}{dt},\quad SR_{estimate}=\frac{I_{lim}}{C_c},\quad f_{t,estimate}=\frac{g_{m1}}{2\pi C_c}`,T`SR_{estimate}=\frac{20\times10^{-6}}{${N(p.cc)}}=${N(x.slew/1e6)}\,V/\mu s,\quad f_{t,estimate}=${N(x.estimate/1e6)}\,MHz`),stateStep(x),followerStep(x)],x,
 'More compensation can reduce ringing while lowering bandwidth and charging speed. Compare requirements together rather than maximizing phase margin alone.', 'Calculate the compensation-capacitor slew estimate at the selected capacitance.',x.slew/1e6,'V/µs','Divide 20 µA by Cc, then convert V/s to V/µs.',{schematic:drawing(x),handover:loopLink(x,'e3'),table:{headers:['Cc (pF)','Crossing (MHz)','Margin (°)','Slew estimate (V/µs)'],rows:rows.map(({c,x})=>[c,fmt(x.crossover/1e6),fmt(x.pm),fmt(x.slew/1e6)])}});result.plots.push({label:'The same 1 mV step for four compensation choices',xLabel:'Time (ns)',yLabel:'Output (mV)',traces:rows.map(({c,x})=>({label:`${c} pF`,points:x.response.points.map(p=>({x:p.x*1e9,y:p.y*1000}))}))});return result}),
L('e4','Three stages: nested compensation and feedforward',[
 { ...k('feed','Compensation scheme',0,0,1),options:['Nested Miller capacitors','Outer Miller plus feedforward']},k('outer','Outer compensation capacitance',2e-12,.5e-12,5e-12,'F'),k('inner','Inner compensation capacitance',1e-12,.1e-12,3e-12,'F'),k('gm3','Output transconductance',2e-3,.5e-3,4e-3,'S'),k('cl','Load capacitance',5e-12,2e-12,10e-12,'F')],
 'How do we verify a three-stage loop when an inner compensation path also feeds back?',
 'Use three independent node-voltage states. Compare an inner Miller capacitor with a feedforward transconductance that bypasses the middle stage. Examine actual poles and zeros rather than assuming an ideal cancellation.',
 'Switch schemes at the same load and outer capacitor. Then increase the load. In feedforward mode Ci is removed, so its setting is inactive.',p=>{const x=nested(p),other=nested({...p,feed:1-p.feed}),c=matrix(x.cap.map(row=>row.map(v=>v*1e12))),g=matrix(x.g.map(row=>row.map(v=>v*1e6)));return O([
 s('Define the three stage currents and state order','x=[va,vb,vo]ᵀ. Stage 1 sinks gm1·vi at a; stage 2 sources gm2·va at b; stage 3 sinks gm3·vb at out. Co connects a to out, Ci connects b to out. Feedforward sinks gff·va at out and replaces Ci.',T`\mathbf C\dot x+\mathbf Gx=\begin{bmatrix}-g_{m1}\\0\\0\end{bmatrix}v_i`,T`\mathbf C=${c}\,pF,\quad\mathbf G=${g}\,\mu S`),
 s('Read one row to interpret the matrix','The output row collects capacitor currents leaving out, including cross-node derivatives. The resistor and controlled currents are ordinary algebraic currents. This is KCL, not an additional independent model.',T`-C_o\dot v_a-C_i\dot v_b+(C_L+C_o+C_i)\dot v_o+g_{ff}v_a+g_{m3}v_b+g_3v_o=0`,T`C_i=${N(x.inner*1e12)}\,pF,\quad g_{ff}=${N(x.gff*1e6)}\,\mu S,\quad g_{m3}=${N(x.gm3*1e6)}\,\mu S`),
 s('Convert charge balance into a transfer function','Solve A=−C⁻¹G and B=C⁻¹b. With zero initial state, (sI−A)x=Bvi. A grounded-capacitor realization of these states supplies the transferOf extraction; its transfer is checked against the original circuit phasors.',T`\dot x=\mathbf Ax+\mathbf Bv_i,\quad A_{amp}(s)=[0\;0\;1](sI-\mathbf A)^{-1}\mathbf B`,T`A_{amp}(s)=\frac{${poly(x.tf.b)}}{${poly(x.tf.a)}}`),
 s('Close the global follower and check its poles','The global loop has vi=u−vo. Every closed-loop pole must lie in the left half-plane for this linear follower to settle. The step starts with x(0−)=x(0+)=0 and u=1 mV.',T`\mathbf A_{cl}=\mathbf A-\mathbf B[0\;0\;1],\quad D(s)+N(s)=0`,T`f_x=${N(x.crossover/1e6)}\,MHz,\quad PM=${N(x.pm)}^\circ,\quad\max\Re(p_{cl})=${N(Math.max(...x.closedPoles.map(z=>z[0])))}\,s^{-1}`),
 s('State exactly what the inner-loop check holds fixed','For this local diagnostic ONLY, hold va at AC ground. Co remains an output load. Break gm3, retain Ci, and find its return ratio. It is a bandpass feedback path with rising and falling unity crossings, not the global loop. Feedforward mode has no Ci loop.',T`T_{inner}(s)=\frac{g_{m3}sC_i}{[g_2+s(C_2+C_i)][g_3+s(C_L+C_o+C_i)]-s^2C_i^2}`,x.local.pm===null?T`C_i=0:\quad T_{inner}=0,\quad\text{no inner unity crossing}`:T`f_{x,inner}=${N(x.local.crossover/1e6)}\,MHz,\quad PM_{inner}=${N(x.local.pm)}^\circ`),
 s('Compare the full models, not just a proposed zero location','The pole/zero table comes from the complete three-state transfer. Feedforward can add a useful left-half-plane zero while other zeros and loading remain. The global poles, local loop and step all need review.',T`N(z)=0,\quad D(p)=0`,T`PM_{other\ scheme}=${N(other.pm)}^\circ,\quad f_{x,other}=${N(other.crossover/1e6)}\,MHz`)
 ],x,
 x.stable?'This selected linear follower has left-half-plane closed poles. The conditional inner-loop result helps explain the compensation but does not replace the full-loop stability check.':'This selected follower has a nondecaying closed-loop pole. The rising response is an instability of this linear model; no rail-limited waveform is implied.',
 'Calculate the total output-node capacitance, including both compensation branches.',(x.cl+x.outer+x.inner)*1e12,'pF','Add CL, Co and the active Ci; Ci is zero in feedforward mode.',{schematic:nestedDrawing(x),table:{headers:['Model root','Real + j imaginary, divided by 2π (MHz)'],rows:[...x.poles.map((z,i)=>[`Open pole ${i+1}`,complexText(z)]),...x.zeros.map((z,i)=>[`Zero ${i+1}`,complexText(z)]),...x.closedPoles.map((z,i)=>[`Closed pole ${i+1}`,complexText(z)]),...x.local.crossings.map((c,i)=>[`Inner crossing ${i+1} (${c.direction})`,`${fmt(c.crossover/1e6)} MHz; ${fmt(c.pm)}°`])]}})},
 {symbols:[[T`x,v_a,v_b,v_o,v_i,u`,'States x=[va,vb,vo]ᵀ and input voltages (V). Global follower input is vi=u−vo.'],[T`\mathbf C,\mathbf G,\mathbf A,\mathbf B`,'Capacitance matrix (F), conductance matrix (S), state matrix and input vector (s⁻¹). All matrix rows follow the same state order.'],[T`C_1,C_2,C_L,C_o,C_i`,'First-node 0.2 pF, middle-node 0.5 pF, load, outer and active inner compensation capacitances. Ci=0 in feedforward mode.'],[T`g_1,g_2,g_3,g_{m1},g_{m2},g_{m3},g_{ff}`,'Output conductances 5/20/50 µS; stage transconductances 100/500/adjustable µS; feedforward 500 µS when selected, otherwise zero.'],[T`s,j,f,\dot x,x(0^-),x(0^+)`,'Laplace variable, imaginary unit, frequency (Hz), state derivative per second, state immediately before and after the reference step. Capacitor continuity makes both zero here.'],[T`p,z,PM,T_{inner}`,'Pole and zero locations (s⁻¹), phase margin (degrees) and conditional local return ratio with first-stage voltage clamped.']],limits:'Declared three-stage linear transconductance model. No transistor sizing, slew or rail limit. Feedforward replaces the inner capacitor and bypasses the middle stage with a 500 µS current path; it is not assumed to cancel a pole exactly. The local inner-loop test clamps va; global closed-loop poles determine actual follower stability.'})
]
