import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {preamp,regeneration,schmitt,schmittDrawing,metastability} from './comparators.js'
const T=String.raw,source=['Berkeley EECS 240: Comparators','https://rfic.eecs.berkeley.edu/ee240sp06/pdf/topic15.pdf']
const symbols=[[T`v_{in},v_d,V_0,V_D,V_{OS}`,'Differential input, latch differential state, its initial value, decision threshold, and latch input offset (V).'],[T`t,\tau,\dot v_d,g_m,C`,'Elapsed time (s), regeneration time constant (s), voltage time derivative (V/s), effective regenerative transconductance (S), and effective differential capacitance (F).'],[T`A_p,A_{eff},\sigma_n`,'Preamplifier DC gain, gain available at the sampling instant, and rms input-referred noise (V).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'F. Comparators',knobs,question,intro,try:attempt,solve,symbols,sources:[source],flow:['Define the input, state and decision rule','Calculate the available gain or decision time','Check history, noise and the stated assumptions'],route:'Use input-referred budgets before the decision and a state equation during regeneration. A phasor can describe a linear preamplifier around bias, but cannot determine a latched output, its history, or a metastability event by itself.',limits:'Behavioral comparator models with explicitly defined effective capacitance and transconductance. No transistor PDK, kickback, recovery, device noise dynamics or rail-limited transient is implied.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
export const COMPARATOR_LESSONS=[
L('f1','Preamplification: refer errors through the gain that has settled',[k('gain','Preamplifier DC gain',10,1,50),k('gbw','Preamplifier gain-bandwidth',1e9,1e8,5e9,'Hz'),k('time','Preamplifier acquisition time',2e-9,.1e-9,20e-9,'s')],
 'Does gain ten always divide the latch error by ten?',
 'Compare a bare latch with a one-pole preamplifier that starts at zero and receives a constant differential input. The latch samples the preamplifier after a finite acquisition interval.',
 'Increase gain with acquisition time fixed. Then increase acquisition time. Compare the DC promise with the gain actually available at the sampling instant.',p=>{const x=preamp(p);return O([
 s('Define the stage and the time budget','Assume a fixed gain-bandwidth product. Higher DC gain lowers the one-pole bandwidth. Acquisition time belongs before regeneration and must be budgeted separately.',T`f_p=GBW/A_p,\quad\tau_p=1/(2\pi f_p),\quad H_p(s)=A_p/(1+s\tau_p)`,T`f_p=${N(x.bw/1e6)}\,MHz,\quad\tau_p=${N(x.tau*1e9)}\,ns`),
 s('Solve the preamplifier state from its initial condition','Let vp be its output. Before the input step vp=0, and finite capacitance keeps vp continuous at zero. Divide its step response by the constant input to find the available gain.',T`\tau_p\dot v_p+v_p=A_pv_{in},\quad v_p(0^-)=v_p(0^+)=0,\quad A_{eff}(t)=A_p(1-e^{-t/\tau_p})`,T`A_{eff}(${N(p.time*1e9)}\,ns)=${N(p.gain)}(1-e^{-${N(p.time/x.tau)}})=${N(x.effective)}`),
 s('Refer the latch offset to the external input','Use a signed +5 mV latch offset and an ideal zero-offset preamplifier. The external input must counter that offset through Aeff; the table reports its magnitude.',T`|V_{OS,in}|=|V_{OS,latch}|/A_{eff}`,T`|V_{OS,in}|=0.005/${N(x.effective)}=${N(x.offset*1e6)}\,\mu V,\quad |V_{OS,DC}|=${N(x.dcOffset*1e6)}\,\mu V`),
 s('Combine independent noise on one reference plane','Specify 1 mV rms latch noise at its input and 50 µV rms preamplifier input-referred noise at the observation time. These are given independent sampled noise values, not spectral densities.',T`\sigma_{in}=\sqrt{\sigma_{pre}^2+(\sigma_{latch}/A_{eff})^2}`,T`\sigma_{in}=\sqrt{(50\,\mu V)^2+(1000\,\mu V/${N(x.effective)})^2}=${N(x.noise*1e6)}\,\mu V`),
 s('Account for the preamplifier noise floor','Increasing gain suppresses the latch contribution but does not divide the preamplifier’s own input-referred noise. Short acquisition can prevent higher DC gain from being useful.',T`A_{eff}\to\infty\Rightarrow\sigma_{in}\to\sigma_{pre}`,T`\sigma_{pre}=50\,\mu V,\quad t_{total}=t_{acq}+t_{regen}`)
 ],[r('Available gain',x.effective),r('Input offset magnitude',x.offset*1e6,'µV'),r('Total input noise',x.noise*1e6,'µV'),r('Preamplifier bandwidth',x.bw/1e6,'MHz')],[curve('Gain builds before the latch samples','Acquisition time (ns)','Available gain',samples(t=>x.at(t*1e-9),0,Math.max(p.time,5*x.tau)*1e9))],
 'Use settled gain for an offset or noise budget. A preamplifier can reduce the latch contribution, but it consumes time and adds its own noise.',x.offset*1e6,'µV','Calculate the latch offset referred to the external input.','Divide 5 mV by the available gain, then convert to µV.',{table:{headers:['Configuration','Offset magnitude (µV)','Input noise rms (µV)'],rows:[['Bare latch',5000,1000],['Preamplifier at sample time',fmt(x.offset*1e6),fmt(x.noise*1e6)],['Preamplifier fully settled',fmt(5000/p.gain),fmt(Math.hypot(50,1000/p.gain))]]}})}),
L('f2','Regeneration: an initial difference grows exponentially',[k('gm','Effective regenerative transconductance',.001,.0002,.005,'S'),k('cap','Effective differential capacitance',50e-15,10e-15,200e-15,'F'),k('initial','Initial differential voltage',.001,1e-6,.01,'V')],
 'How long does a tiny initial difference take to become a decision?',
 'The state is the difference between the two latch nodes, vd=v+−v−. Define effective gm and C directly by C·dvd/dt=gm·vd so no hidden factor of two enters the time constant.',
 'Reduce the initial voltage by ten. Predict the added decision time τ ln 10. Then double capacitance and compare all resolution times.',p=>{const x=regeneration(p);return O([
 s('Write the positive-feedback state balance','Regenerative current reinforces the existing difference. A positive gm gives a positive real pole, appropriate during a decision rather than for a stable linear amplifier.',T`C\dot v_d=g_mv_d,\quad \dot v_d=(g_m/C)v_d`,T`\tau=C/g_m=${N(p.cap)}/${N(p.gm)}=${N(x.tau*1e12)}\,ps`),
 s('State exactly what initializes the decision','The input sampling phase creates V0 before regeneration starts. This lesson does not model that sampling phase. The effective capacitor voltage is continuous across its start.',T`v_d(0^-)=v_d(0^+)=V_0,\quad V_0>0`,T`V_0=${N(p.initial*1000)}\,mV,\quad V_D=500\,mV`),
 s('Integrate the differential equation','Divide by vd and integrate from the known initial state to the state at time t. This produces the exponential, with t measured from regeneration enable.',T`\int_{V_0}^{v_d(t)}\frac{dv}{v}=\int_0^t\frac{dt'}\tau\Rightarrow\ln\frac{v_d(t)}{V_0}=t/\tau`,T`v_d(t)=${N(p.initial)}e^{t/${N(x.tau)}}\,V`),
 s('Solve the threshold crossing for time','The decision is declared when the difference first reaches VD. Stop the waveform there: the unsaturated exponential is not a rail model.',T`t_D=\tau\ln(V_D/V_0)`,T`t_D=${N(x.tau*1e12)}\ln(0.5/${N(p.initial)})=${N(x.time*1e12)}\,ps`),
 s('Predict a decade of smaller input','Only the initial difference changes. This logarithmic time penalty explains why the near-zero input region needs a statistical treatment in F4.',T`t_D(V_0/10)-t_D(V_0)=\tau\ln10`,T`\Delta t_D=${N(x.tau*1e12*Math.log(10))}\,ps`)
 ],[r('Regeneration time constant',x.tau*1e12,'ps'),r('Decision time',x.time*1e12,'ps'),r('Added time per input decade',x.tau*1e12*Math.log(10),'ps')],[curve('Regeneration until the decision threshold','Time (ps)','Differential voltage (mV)',samples(t=>x.at(t*1e-12)*1000,0,x.time*1e12))],
 'The state equation, exponential and threshold calculation describe the same decision interval. At exactly zero initial difference the ideal noiseless model never leaves zero; physical noise and mismatch determine a real latch’s behavior.',x.time*1e12,'ps','Calculate the time to reach 500 mV.','Multiply τ by ln(0.5/V0).',{table:{headers:['Initial difference (µV)','Time to 500 mV (ps)'],rows:[1e-6,1e-4,.001].map(initial=>[initial*1e6,fmt(regeneration({...p,initial}).time*1e12)])}})}),
L('f3','Hysteresis: the input alone does not specify the output',[k('beta','Positive-feedback fraction',.1,.02,.4),k('rail','Positive rail magnitude',.5,.2,2,'V'),k('input','Present input voltage',0,-1,1,'V'),{...k('history','Previous output state',0,0,1),options:['High','Low']}],
 'Why can the same input be consistent with two stable outputs?',
 'Use an inverting Schmitt comparator with rails ±Vrail. Its noninverting input receives βvo from a resistor divider; its inverting input receives vin. History selects between consistent rail states.',
 'Keep input at zero and switch the previous state. Then move input beyond a threshold: history can no longer preserve a state that contradicts the comparator input polarity.',p=>{const x=schmitt(p);return O([
 s('Solve the feedback divider','Rg=10 kΩ connects the noninverting input to ground; Rf connects it to output. No input current flows.',T`\beta=\frac{R_g}{R_f+R_g},\quad v_+=\beta v_o,\quad R_f=R_g(1-\beta)/\beta`,T`R_f=${N(1e4*(1-p.beta)/p.beta)}\,\Omega,\quad v_+=${N(p.beta)}v_o`),
 s('Test the high-output assumption','At +Vrail, the comparator can remain high while v+≥vin. A rising input above that threshold must drive the output low.',T`v_o=+V_{rail}\Rightarrow v_{in}\le V_H=\beta V_{rail}`,T`V_H=${N(p.beta)}(${N(p.rail)})=${N(x.threshold)}\,V`),
 s('Test the low-output assumption','At −Vrail, the comparator can remain low while v+≤vin. A falling input below that threshold must drive the output high.',T`v_o=-V_{rail}\Rightarrow v_{in}\ge V_L=-\beta V_{rail}`,T`V_L=${N(-x.threshold)}\,V,\quad\Delta V_H=V_H-V_L=${N(x.width)}\,V`),
 s('Use history to select a physically consistent rail','The native piecewise-linear solver checks the assumed circuit states. Inside the interval, an algebraic balanced linear solution may also exist; it is not a stable memory state.',T`V_L<v_{in}<V_H\Rightarrow\text{both rail states consistent}`,T`v_{in}=${N(p.input)}\,V,\quad v_{o,history}=${N(x.output)}\,V`),
 s('Distinguish total swing from one rail magnitude','The hysteresis width is β times the full output swing. With ±0.5 V rails the swing is 1 V, so β=0.1 gives 100 mV, not 50 mV.',T`\Delta V_H=\beta(V_{OH}-V_{OL})=2\beta V_{rail}`,T`\Delta V_H=${N(x.width*1000)}\,mV`)
 ],[r('Upper threshold',x.threshold*1000,'mV'),r('Lower threshold',-x.threshold*1000,'mV'),r('Hysteresis width',x.width*1000,'mV'),r('Output using history',x.output,'V')],[{label:'Rising and falling input sweeps',xLabel:'Input voltage (V)',yLabel:'Output voltage (V)',traces:[{label:'Rising input, initially high',points:x.rise},{label:'Falling input, initially low',points:x.fall}]}],
 x.refusal,x.width*1000,'mV','Calculate the hysteresis width.','Multiply the full rail-to-rail output swing by β.',{schematic:schmittDrawing(p),table:{headers:['Native solver consistent region','Output (V)','Interpretation'],rows:x.states.map(v=>[v.region,fmt(v.output),v.region==='linear'?'Balanced algebraic state; unstable with positive feedback':'Rail state'])}})}, {symbols:[...symbols,[T`\beta,R_g,R_f,V_{rail},V_H,V_L`,'Feedback divider fraction, ground and feedback resistances (Ω), positive magnitude of symmetric rails (V), and upper/lower input thresholds (V).']]}),
L('f4','Metastability: turn a resolution window into an event rate',[k('tau','Regeneration time constant',20e-12,10e-12,100e-12,'s'),k('time','Available regeneration time',400e-12,50e-12,800e-12,'s'),k('gain','Settled preamplifier gain',1,1,20),k('clock','Independent decision rate',5e9,1e6,10e9,'Hz')],
 'How can a very small unresolved probability still produce frequent events?',
 'Assume independent inputs uniformly distributed over −0.5 to +0.5 V, a settled noiseless preamplifier, and a 0.5 V latch decision threshold. Invert the regeneration law to find the unresolved input interval.',
 'Compare 100, 200 and 400 ps. Then increase preamplifier gain to ten; distinguish the saved regeneration time from the extra acquisition time needed by a real preamplifier.',p=>{const x=metastability(p);return O([
 s('Invert the threshold equation','At the deadline T, initial latch differences below VD exp(−T/τ) have not reached the threshold. Divide by preamplifier gain to refer this interval to the external input.',T`A_p|v_{in}|e^{T/\tau}<V_D\Rightarrow |v_{in}|<V_{min}=\frac{V_D}{A_p}e^{-T/\tau}`,T`V_{min}=\frac{0.5}{${N(p.gain)}}e^{-${N(p.time/p.tau)}}=${N(x.resolution)}\,V`),
 s('Integrate the assumed input distribution','The unresolved interval extends on both sides of zero. For a uniform input over a full width W=1 V, probability is its width divided by W, capped at one.',T`p_u=\min(1,2V_{min}/W),\quad W=1\,V`,T`p_u=\min(1,2(${N(x.resolution)})/1)=${N(x.probability)}`),
 s('Convert a per-decision probability into a rate','Assume independent decisions at fclk. This is an unresolved-decision rate, not automatically a system bit-error rate or a synchronizer MTBF specification.',T`\lambda=f_{clk}p_u,\quad\overline t_{event}=1/\lambda`,T`\lambda=${N(p.clock)}(${N(x.probability)})=${N(x.rate)}\,s^{-1},\quad\overline t_{event}=${N(x.interval)}\,s`),
 s('Translate settled preamplifier gain into time credit','Set the same resolution with and without gain and subtract the required times. F1 explains why acquiring that gain consumes part of the total decision budget.',T`\Delta T=\tau\ln A_p`,T`\Delta T=${N(p.tau*1e12)}\ln(${N(p.gain)})=${N(x.credit*1e12)}\,ps`),
 s('Check the unit scale explicitly','For τ=20 ps, T=400 ps and Ap=1, the input threshold is about one nanovolt. The probability is dimensionless, and the event interval still depends on decision rate.',T`0.5e^{-400/20}=1.03058\times10^{-9}\,V=1.03058\,nV`,T`p_{u,reference}=2.06115\times10^{-9}`)
 ],[r('Input resolution window half-width',x.resolution*1e9,'nV'),r('Unresolved probability',x.probability),r('Unresolved event rate',x.rate,'s⁻¹'),r('Mean event interval',x.interval,'s')],[{...curve('Available time suppresses unresolved events','Regeneration time (ps)','Probability',samples(time=>metastability({...p,time:time*1e-12}).probability,50,800)),logY:true}],
 'The rate depends on the input distribution and the decision frequency as well as the latch. Offset, noise, correlated inputs and downstream error recovery require a richer model before predicting system reliability.',x.rate,'s⁻¹','Calculate the unresolved event rate.','Multiply probability per decision by decisions per second.',{table:{headers:['Time (ps)','Input threshold (V)','Probability','Mean interval (s)'],rows:[100,200,400,800].map(t=>{const y=metastability({...p,time:t*1e-12});return[t,fmt(y.resolution),fmt(y.probability),fmt(y.interval)]})}})}, {symbols:[...symbols,[T`T,W,p_u,f_{clk},\lambda,\overline t_{event}`,'Regeneration deadline (s), full uniform input span (V), unresolved probability, independent decision frequency (Hz), event rate (s⁻¹), and mean interval (s).']]})
]
