import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt as F} from '@ee-labs/lessons/model'
import {outputBias,halfCircuits,feedbackModes,sensors,pairDrawing,modeDrawing} from './differential.js'
import {logPoints} from './architectures.js'
import {complex} from '@ee-labs/network'
const db=z=>20*Math.log10(complex.cabs(z)),unit=(v,u)=>F(v)+' '+u
const commonSymbols=[[String.raw`v_p,v_n,v_{CM},v_D`,'Two output voltages (V), their mean vCM=(vp+vn)/2, and their difference vD=vp−vn. A common change moves both together; a differential change moves them oppositely.'],[String.raw`g_m,r_o,R,C,s`,'Transconductance (S), device output resistance (Ω), the named resistance (Ω), capacitance (F), and Laplace variable s (s⁻¹). For sinusoidal steady state substitute s=j2πf.']]
const source=['Texas Instruments: output common mode and differential swing','https://www.ti.com/document-viewer/lit/html/SSZT192/GUID-00D3D72E-0A2F-480B-BA07-7543D8EA4A26']
function L(id,name,knobs,question,intro,attempt,symbols,solve,extra={}){return{id,name,group:'D. Fully differential amplifiers',question,intro,knobs,try:attempt,symbols:[...commonSymbols,...symbols],solve,sources:[source],flow:['Separate the mean from the difference','Write equations with a stated reference and direction','Compare exact results, approximations and design limits'],route:'Start with nodal equations to see which currents set the result. Symmetry can reduce those equations to independent common and differential modes. State equations retain charge and initial conditions; phasors describe sinusoidal steady state. A phasor curve alone cannot establish a valid DC bias or predict switching charge.',limits:'Declared teaching models, not a foundry design. Matched branches and ideal sensing are assumed unless explicitly stated. Device-region DC checks, incremental dynamics and switched charge calculations have different validity limits; each lesson identifies the model it uses.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const loopLink=(name,x)=>({app:'control-lab',label:`Inspect the ${name}-mode loop in Control Lab`,note:`Transfer the ${name}-mode return ratio T(s), with unity negative feedback. Control Lab then displays the same H(s)=T/(1+T) for that mode; the other mode remains separate under the declared symmetry.`,patch:{plant:{type:'custom',params:[0,0,x.k,...x.tf.a]},ctrl:{type:'p',params:[1]},from:{app:'analog-ic-lab',id:'d3',label:`${name==='common'?'Common':'Differential'}-mode loop`}}})
export const DIFFERENTIAL_LESSONS=[
L('d1','Differential feedback cannot set the output mean',[k('epsilon','Equal current error / branch current',.01,-.1,.1),k('vdd','Supply voltage',1.8,1.4,2.4,'V'),{...k('feedback','Common-mode correction',0,0,1,'',1),options:['Off','On: 100 μS']}],
 'How can the output difference be correct while both outputs drift?',
 'Begin with two identical outputs at half supply. Each contains a PMOS sourcing current and an NMOS sinking current. An equal extra injected current changes their mean. Differential feedback sees only the difference and therefore cannot remove this error.',
 'With correction off, compare 1%, 5% and 10% current error. Then turn correction on. Predict which device loses saturation first for a positive error.',
 [[String.raw`V_B,I_0,\epsilon,\Delta I`,'Target output bias VDD/2 (V), nominal current 20 μA in each device, signed fractional mismatch, and extra current ΔI=εI0 injected into EACH output (A).'],[String.raw`x_p,x_n,x_c,x_d,g,g_c,g_d`,'Increments from bias (V): xp=vp−VB, xn=vn−VB, xc=(xp+xn)/2 and xd=xp−xn. g=1/Rout, common correction gc and differential correction gd=300 μS (all S).'],[String.raw`\beta,\lambda,V_T,V_{OV},I_p,I_n`,'Square-law current factor (A/V²), channel-length modulation (V⁻¹), threshold magnitude 0.45 V, overdrive 0.20 V, and sourcing PMOS / sinking NMOS current magnitudes (A).']],p=>{
 const x=outputBias(p),sweep=fn=>samples(e=>fn(outputBias({...p,epsilon:e})),-.1,.1,101)
 return O([
 s('Identify the two unknown voltages and both feedback paths','Positive ΔI enters each node. The restoring conductance and feedback currents leave it. The differential correction changes sign between outputs; the common correction has the same sign.',String.raw`\begin{aligned}0&=\Delta I-gx_p-\tfrac{g_d}{2}(x_p-x_n)-\tfrac{g_c}{2}(x_p+x_n)\\0&=\Delta I-gx_n+\tfrac{g_d}{2}(x_p-x_n)-\tfrac{g_c}{2}(x_p+x_n)\end{aligned}`,String.raw`R_{out}=500\,\mathrm{k\Omega},\quad g=2\,\mu\mathrm S,\quad\Delta I=${N(x.delta*1e6)}\,\mu\mathrm A`),
 s('Add for the mean; subtract for the difference','Adding cancels differential feedback. Subtracting cancels equal injected currents. Finite output resistance supplies a DC path even with common-mode correction off.',String.raw`\begin{aligned}x_c&=\frac{\Delta I}{g+g_c}=\frac{\Delta I R_{out}}{1+g_cR_{out}}\\(g+g_d)x_d&=0\quad\Rightarrow\quad x_d=0\end{aligned}`,String.raw`\begin{aligned}g_cR_{out}&=${N(x.gc*x.rout)}\\v_{CM,linear}&=${N(x.bias)}+${N(x.linear-x.bias)}=${N(x.linear)}\,\mathrm V\end{aligned}`),
 s('Define the transistor law before trusting that prediction','Both fixed gate overdrives are 0.20 V. Use device-oriented VDS for NMOS and VSD for PMOS. At each supply, β and λ are calibrated to I0 and ro=1 MΩ per device at VB; two conductances in parallel give Rout=500 kΩ.',String.raw`\begin{aligned}I_{sat}(v)&=\tfrac12\beta V_{OV}^2(1+\lambda v),&&v\ge V_{OV}\\I_{triode}(v)&=\beta(V_{OV}v-v^2/2)(1+\lambda v),&&0\le v<V_{OV}\\\lambda&=\frac{1}{2I_0R_{out}-V_B},\quad\beta=\frac{2I_0}{V_{OV}^2(1+\lambda V_B)}\end{aligned}`,String.raw`\lambda=${N(x.lambda)}\,\mathrm{V^{-1}},\quad\beta=${N(x.kn)}\,\mathrm{A/V^2}`),
 s('Solve the actual DC balance and check both regions','The nonlinear solution uses the appropriate law at each device voltage. With symmetric outputs their difference is zero, leaving one scalar current balance. Bisection finds its root within the supply rails.',String.raw`\begin{aligned}0&=I_p(V_{DD}-v_{CM})-I_n(v_{CM})+\Delta I-g_c(v_{CM}-V_B)\\V_{OV}&\le v_{CM}\le V_{DD}-V_{OV}\quad\text{for both devices to saturate}\end{aligned}`,String.raw`v_{CM}=${N(x.vo)}\,\mathrm V,\quad [V_{min},V_{max}]=[${N(x.vov)},${N(p.vdd-x.vov)}]\,\mathrm V`)
 ],[r('Solved output mean',x.vo,'V'),r('Output difference',0,'V'),r('Mean error',x.shift*1e3,'mV'),r('Common-mode DC loop gain',x.gc*x.rout)],
 [{label:'Equal current error moves both outputs',xLabel:'Injected current / nominal branch current',yLabel:'Output mean (V)',traces:[{label:'MOS current balance',points:sweep(a=>a.vo)},{label:'Linear prediction',points:sweep(a=>a.linear),dashed:true},{label:'Upper saturation boundary',points:sweep(()=>p.vdd-.2),dashed:true},{label:'Lower saturation boundary',points:sweep(()=>.2),dashed:true}]}],
 x.inSaturation?'Both devices remain in saturation. The affine channel-length modulation law agrees with the linear bias prediction here. Differential correction holds the difference at zero but does not correct the mean.':'One device has entered triode. The linear extrapolation no longer describes the DC operating point; use the solved MOS currents and region table.',x.linear,'V','Predict output common mode using the linear equation.','Add ΔI/(g+gc) to VDD/2.',
 {table:{headers:['Quantity','Solved value','Meaning'],rows:[['PMOS current',unit(x.p.id*1e6,'μA'),x.p.region],['NMOS current',unit(x.n.id*1e6,'μA'),x.n.region],['Correction leaving each node',unit(x.gc*x.shift*1e6,'μA'),'gc times the mean error'],['DC balance residual',unit(x.residual,'A'),'Sourcing − sinking + injection − correction']]},plotNote:'The dashed linear prediction may leave the rails; it is an extrapolation, not a physical output. Changing supply recalibrates the teaching devices to the same midpoint current and resistance. The correction actuator is ideal and has no separate compliance limit.'})}),
L('d2','Use symmetry to derive exact half-circuits',[k('gm','Each transistor transconductance',200e-6,50e-6,500e-6,'S'),k('rd','Each drain resistance',20e3,5e3,100e3,'Ω'),k('rt','Tail resistance',1e6,10e3,2e6,'Ω'),{...k('ro','Each transistor output resistance',500e3,100e3,2e6,'Ω'),group:'Device'}],
 'When is the half-circuit exact, and where does the approximation enter?',
 'Use D1’s mean and difference coordinates on a symmetric differential pair. Opposite inputs leave the shared source at AC ground. Equal inputs double current in the shared tail, so either half sees twice the physical tail resistance. Both reductions are exact for matched branches.',
 'Reduce tail resistance from 1 MΩ to 10 kΩ. Compare the full circuit, exact half-circuit and large-tail approximation. Then change ro and watch the single-ended rejection ratio.',
 [[String.raw`v_{ip},v_{in},v_s,R_D,R_t,C_L`,'Gate input voltages, shared source voltage (V), each drain resistor, physical tail resistance (Ω), and each drain capacitance CL=2 pF. All are incremental quantities about a valid bias point.'],[String.raw`g_D,g_o,g_t,Y_D`,'Conductances 1/RD, 1/ro, 1/(2Rt) (S), and drain-load admittance YD=gD+sCL (S).'],[String.raw`A_D,A_C,A_{D,SE},CMRR_{SE}`,'Differential-output / differential-input gain, each-output / common-input gain, single-ended differential gain AD/2, and 20 log10 |(AD/2)/AC| in dB.']],p=>{
 const x=halfCircuits(p)
 return O([
 s('Split the excitation before cutting the circuit','Differential excitation is +vid/2 and −vid/2; source-current increments cancel. Common excitation drives both gates by vic; total tail current is twice one branch current. A half-circuit must therefore use 2Rt to preserve the same source voltage.',String.raw`\begin{aligned}v_{ip}&=v_{ic}+v_{id}/2,\quad v_{in}=v_{ic}-v_{id}/2\\v_s&=0\quad(\text{differential})\\v_s&=(2i_s)R_t=i_s(2R_t)\quad(\text{common})\end{aligned}`,String.raw`R_{tail,half}=2(${N(p.rt/1e3)})=${N(2*p.rt/1e3)}\,\mathrm{k\Omega}`),
 s('Solve the differential drain equation','With source at AC ground, gm vi leaves the drain; load and device output conductances both return to ground. Each half’s gain is also the differential-output / differential-input gain because both numerator and denominator double.',String.raw`(g_D+g_o+sC_L)v_o=-g_mv_i,\quad A_D(s)=\frac{-g_m}{g_D+g_o+sC_L}`,String.raw`A_D(0)=\frac{-${N(p.gm*1e6)}}{${N((x.gD+x.go)*1e6)}}=${N(x.ad)}\,\mathrm{V/V}`),
 s('Write both common-mode unknowns explicitly','Unknowns are drain voltage vo and source voltage vs. The first row balances drain current; the second balances source current, including current through 2Rt. Keeping ro preserves the exact result.',String.raw`\begin{bmatrix}Y_D+g_o&-(g_m+g_o)\\-g_o&g_m+g_o+g_t\end{bmatrix}\begin{bmatrix}v_o\\v_s\end{bmatrix}=\begin{bmatrix}-g_mv_i\\g_mv_i\end{bmatrix}`,String.raw`g_t=\frac1{2R_t}=${N(x.gt*1e6)}\,\mu\mathrm S,\quad Y_D=g_D+sC_L`),
 s('Eliminate the source voltage, then compare the shortcut','The numerator is −gm gt after cancellation. The shortcut drops small denominator terms; doubling Rt itself was not an approximation. The table reports the shortcut’s relative error against the exact result.',String.raw`\begin{aligned}A_C(s)&=\frac{-g_mg_t}{Y_D(g_m+g_o+g_t)+g_og_t}\\A_C(0)&=\frac{-g_mR_D}{1+2R_t(g_m+g_o)+g_oR_D}\approx-\frac{R_D}{2R_t}\end{aligned}`,String.raw`A_C(0)=${N(x.ac)},\quad A_{C,approx}=${N(x.approx)},\quad error=${N(100*x.error)}\%`),
 s('Use one consistent CMRR convention','For one output, a differential input vid drives that half by vid/2. Therefore its differential gain is AD/2. Under perfectly symmetric common excitation the DIFFERENTIAL output is zero; this ideal cancellation does not measure real mismatch-limited differential rejection.',String.raw`A_{D,SE}=A_D/2,\quad CMRR_{SE}=20\log_{10}\left|\frac{A_D/2}{A_C}\right|`,String.raw`CMRR_{SE}=20\log_{10}\left|\frac{${N(x.ad/2)}}{${N(x.ac)}}\right|=${N(x.cmrr)}\,\mathrm{dB}`)
 ],[r('Differential gain',x.ad,'V/V'),r('Common-mode gain per output',x.ac,'V/V'),r('Single-ended CMRR',x.cmrr,'dB'),r('Shortcut relative error',x.error*100,'%')],
 [{label:'Phasors from the same two nodal equations',xLabel:'Frequency (Hz)',yLabel:'Gain magnitude (dB)',logX:true,traces:[{label:'Differential output / differential input',points:logPoints(f=>db(x.dm(f)),1e2,1e9)},{label:'One output / common input',points:logPoints(f=>db(x.cm(f)),1e2,1e9)}]},curve('Where the large-tail shortcut becomes useful','Tail resistance (kΩ)','Relative approximation error (%)',samples(rt=>100*halfCircuits({...p,rt:rt*1e3}).error,10,2000))],
 x.error>.05?'The shortcut differs by more than 5% here. Use the exact half-circuit equations; symmetry still makes them identical to the full circuit.':'The shortcut is within 5% here. The exact half-circuit remains available and retains the terms that the shortcut discards.',x.ac,'V/V','Calculate the exact DC common-mode gain per output.','Use −gm RD divided by 1+2Rt(gm+go)+go RD.',{schematic:pairDrawing(x),table:{headers:['Excitation','Output convention','DC gain','Model'],rows:[['Differential','Difference / difference',x.ad,'Full pair = grounded-source half'],['Common','One output / common input',x.ac,'Full pair = exact 2Rt half'],['Common','One output / common input',x.approx,'Large-tail approximation'],['Differential','One output / difference',x.ad/2,'Use this numerator for CMRRSE']]},plotNote:'The curves retain CL=2 pF at each drain. They are incremental responses, not a new DC operating-point calculation. Native nodal tests compare the full pair and both half-circuits over frequency.'})}),
L('d3','Give common and differential feedback separate stability checks',[k('gc','Common-mode correction transconductance',100e-6,50e-6,300e-6,'S'),k('fcm','Common-mode controller pole',10e6,1e6,100e6,'Hz'),k('fdm','Differential controller pole',30e6,2e6,200e6,'Hz'),k('cl','Capacitance at each output',2e-12,.5e-12,10e-12,'F')],
 'Can the output difference settle cleanly while the mean rings?',
 'Return to D1’s 500 kΩ output resistance and add capacitance and finite controller speed. Two equal correction currents control the mean; equal-and-opposite currents control the difference. Symmetry separates this four-state system into two second-order feedback loops.',
 'Lower only the common-mode controller pole from 10 MHz to 1 MHz. Compare both phase margins and both settling curves. Then change output capacitance, which affects both loops.',
 [[String.raw`c,d,a_c,a_d,u_c,u_d`,'Incremental output mean and difference, controller states, and command steps (all V). Physical outputs are 0.9+c±d/2 V. Commands are uc=10 mV and ud=20 mV after t=0.'],[String.raw`\tau_c,\tau_d,\tau_o,\dot{x}(t),x(0^-),x(0^+)`,'Controller pole time constants 1/(2πfp), output time constant Rout CL (s), time derivative of state (V/s), state just before the step and just after. Finite capacitor currents keep these voltage states continuous.'],[String.raw`K,T(s),H(s),f_u,PM`,'DC return ratio gm Rout, open-loop return ratio, closed-loop mode response T/(1+T), actual unity crossing frequency (Hz), and phase margin 180°+arg T at that crossing. Differential correction gd is fixed at 300 μS.'],[String.raw`F,B,x_\infty,e^{Ft}`,'State matrix (s⁻¹), input column (s⁻¹), final state for a constant command (V), and matrix exponential that propagates the initial error. These are defined separately for each mode.']],p=>{
 const x=feedbackModes(p),c=x.cm,d=x.dm,points=fn=>samples(t=>fn(x.state(t*1e-6)),0,x.tEnd*1e6,241)
 return O([
 s('Balance current at each physical output','p and n here denote increments from 0.9 V. Each common actuator injects gc ac; differential actuation injects +gd ad/2 at p and −gd ad/2 at n. Add and subtract the equations to recover c and d.',String.raw`\begin{aligned}C_L\dot p&=-gp+g_ca_c+g_da_d/2\\C_L\dot n&=-gn+g_ca_c-g_da_d/2\\C_L\dot c&=-g\,c+g_ca_c,\quad C_L\dot d=-g\,d+g_da_d\end{aligned}`,String.raw`g=1/R_{out}=2\,\mu\mathrm S,\quad R_{out}C_L=${N(x.rout*p.cl*1e6)}\,\mu\mathrm s`),
 s('Add the controller state instead of hiding its pole','For either mode let y mean c or d, a its controller state, u its command, and gm the corresponding correction transconductance. The controller filters the error u−y. State order is [y,a].',String.raw`\begin{aligned}\tau\dot a&=u-y-a\\\dot x&=Fx+Bu,\quad x=\begin{bmatrix}y\\a\end{bmatrix}\\F&=\begin{bmatrix}-g/C_L&g_m/C_L\\-1/\tau&-1/\tau\end{bmatrix},\quad B=\begin{bmatrix}0\\1/\tau\end{bmatrix}\end{aligned}`,String.raw`\tau_c=${N(c.tau*1e9)}\,\mathrm{ns},\quad\tau_d=${N(d.tau*1e9)}\,\mathrm{ns}`),
 s('Substitute the chosen common-mode parameters','Start from zero incremental states; the command steps to 10 mV at t=0. The matrix entries multiply state voltages to give volts per second. The factor 10⁶ keeps the displayed matrix readable. The differential matrix follows by replacing gc and τc with gd and τd; CL and Rout are shared.',String.raw`\begin{aligned}F_c&=10^6\begin{bmatrix}${N(c.a[0][0]/1e6)}&${N(c.a[0][1]/1e6)}\\${N(c.a[1][0]/1e6)}&${N(c.a[1][1]/1e6)}\end{bmatrix}\,\mathrm{s^{-1}}\\B_c&=10^6\begin{bmatrix}0\\${N(1/c.tau/1e6)}\end{bmatrix}\,\mathrm{s^{-1}}\end{aligned}`,String.raw`\dot x_c(0^+)=B_c(0.010)=\begin{bmatrix}0\\${N(.01/c.tau)}\end{bmatrix}\,\mathrm{V/s}`),
 s('State the initial condition and propagate the step','The outputs and controller capacitors start settled at their bias values, so incremental states are zero before and after the command step. Their derivatives can change immediately. The final state follows from Fx∞+Bu=0, then the matrix exponential gives every intermediate value.',String.raw`\begin{aligned}x(0^-)&=x(0^+)=\begin{bmatrix}0\\0\end{bmatrix},\quad K=g_mR_{out}\\x_\infty&=\frac{u}{1+K}\begin{bmatrix}K\\1\end{bmatrix}\\x(t)&=x_\infty+e^{Ft}[x(0^+)-x_\infty]\end{aligned}`,String.raw`c_\infty=${N(c.steady[0]*1e3)}\,\mathrm{mV},\quad d_\infty=${N(d.steady[0]*1e3)}\,\mathrm{mV}`),
 s('Eliminate states to obtain the same transfer function','Laplace transformation with zero initial increments gives output admittance g+sCL and controller denominator 1+sτ. Closing unity negative feedback adds K to the constant denominator term.',String.raw`\begin{aligned}T(s)&=\frac{K}{(1+sR_{out}C_L)(1+s\tau)}\\H(s)&=\frac{K}{R_{out}C_L\tau s^2+(R_{out}C_L+\tau)s+1+K}\end{aligned}`,String.raw`K_c=${N(c.k)},\quad K_d=${N(d.k)},\quad H_c(0)=${N(c.k/(1+c.k))}`),
 s('Evaluate phasors at the actual unity crossing','Use s=j2πf in each return ratio, solve |T|=1 and read its phase. gm/(2πCL) ignores the controller pole and is only an estimate. The common and differential loops have distinct crossings and margins.',String.raw`|T(j2\pi f_u)|=1,\quad PM=180^\circ+\arg T(j2\pi f_u)`,String.raw`\begin{aligned}f_{u,c}&=${N(c.crossover/1e6)}\,\mathrm{MHz},&PM_c&=${N(c.pm)}^\circ\\f_{u,d}&=${N(d.crossover/1e6)}\,\mathrm{MHz},&PM_d&=${N(d.pm)}^\circ\end{aligned}`)
 ],[r('Common-mode phase margin',c.pm,'°'),r('Differential phase margin',d.pm,'°'),r('Common-mode crossover',c.crossover/1e6,'MHz'),r('Differential crossover',d.crossover/1e6,'MHz')],
 [{label:'Two return ratios, measured separately',xLabel:'Frequency (Hz)',yLabel:'Return ratio magnitude (dB)',logX:true,traces:[{label:'Common mode',points:logPoints(f=>db(c.at(f)),1e3,1e10)},{label:'Differential mode',points:logPoints(f=>db(d.at(f)),1e3,1e10)}]},{label:'State-equation response to both command steps',xLabel:'Time (μs)',yLabel:'Output increment (mV)',traces:[{label:'Mean c: 10 mV command',points:points(z=>1e3*z.c)},{label:'Difference d: 20 mV command',points:points(z=>1e3*z.d)}]},{label:'Reconstruct the two physical outputs',xLabel:'Time (μs)',yLabel:'Output voltage (V)',traces:[{label:'vp = 0.9 + c + d/2',points:points(z=>.9+z.p)},{label:'vn = 0.9 + c − d/2',points:points(z=>.9+z.n)}]}],
 'Both state pairs describe the same physical output nodes. Lower controller bandwidth can reduce phase margin and increase ringing even while the other mode remains well behaved. Positive coefficients make these declared second-order loops stable, but small margin can give poor settling.',c.steady[0]*1e3,'mV','Calculate the final common-mode increment for the 10 mV command.','Multiply 10 mV by Kc/(1+Kc).',
 {schematic:modeDrawing(x),handovers:[loopLink('common',c),loopLink('differential',d)],table:{headers:['Loop','DC return ratio','Actual crossing (MHz)','One-pole estimate (MHz)','Phase margin (°)'],rows:[['Common',c],['Differential',d]].map(([name,m])=>[name,m.k,m.crossover/1e6,m.estimate/1e6,m.pm])},plotNote:'Step responses start from zero incremental state and use the matrix exponential, not a sampled Bode approximation. Native tests compare both output waveforms and break each physical feedback source while leaving the other loop closed. Perfect symmetry is required for separation; mismatch would couple the modes.',limits:'Linear output model at a valid 0.9 V bias, Rout=500 kΩ per output, gd=300 μS, and one controller pole per mode. No slew, clipping, nonlinear sensor, mismatch or extra parasitic poles are included. State transients apply to the stated small steps; loop margins do not prove large-signal recovery.'})}),
L('d4','A common-mode sensor changes the circuit it measures',[{...k('sensor','Sensor to inspect',0,0,2,'',1),options:['Two equal resistors','Two source followers','Reset switched capacitors']},k('rs','Each sensing resistance',100e3,10e3,1e6,'Ω'),k('cs','Each sampling or sensor capacitance',100e-15,20e-15,1e-12,'F'),k('fs','Sampling frequency',100e3,10e3,20e6,'Hz'),k('ud','Unloaded output difference',.1,0,.4,'V')],
 'Which sensor best preserves gain, output swing and settling?',
 'Compare three ways to measure an output mean using D2’s output equivalent: Rout=20 kΩ in parallel with 500 kΩ, CL=2 pF, and an unloaded mean of 0.9 V. A resistive average loads differential signals; a follower adds capacitance and headroom cost; a clocked sampler moves charge.',
 'Compare all three sensors. For switched capacitors, increase clock frequency to 20 MHz and capacitance to 1 pF. Predict whether the held mean equals the cycle-average output mean.',
 [[String.raw`U_p,U_n,R_{out},C_L,R_s,C_s,f_s,h`,'Unloaded Thevenin output voltages 0.9±ud/2 (V), output resistance (Ω), permanent load capacitance (F), each sensing resistance (Ω), each sensor/sample capacitance (F), sampling frequency (Hz) and half-period h=1/(2fs) (s).'],[String.raw`a,r,r_0,b,k,q,m`,'Dimensionless charge-sharing ratio, track and hold exponential factors, pre-track voltage / U, post-kick voltage / U, sampled voltage / U, and cycle-average output voltage / U. These ratios apply independently to either output U.'],[String.raw`\tau_{on},\tau_{off},\overline I,P_{port}`,'Track and hold RC time constants (s), mean current drawn per output (A), and mean power supplied at the two Thevenin output ports (W). Port loading power excludes amplifier quiescent power.'],[String.raw`g_{mf},g_{of},C_g,H_f,V_{GS}`,'Follower transconductance 100 μS, output conductance 2 μS, lumped gate capacitance 50 fF, incremental follower transfer, and illustrative DC gate-source drop 0.65 V.']],p=>{
 const x=sensors(p),q=x.sc,f=x.follower,z=x.resistive,which=['Resistive','Follower','Switched-capacitor'][p.sensor]
 const steps=[s('Start from one shared output-stage model','Replace each output by its unloaded voltage U driving Rout, with CL to ground. This is the DC / incremental output equivalent of D2, not the higher-resistance stage in D1 and D3. The unloaded differential gain remains −gm Rout with gm=200 μS.',String.raw`\begin{aligned}R_{out}&=R_D\parallel r_o,\quad A_{D,0}=-g_mR_{out}\\U_p&=0.9+u_d/2,\quad U_n=0.9-u_d/2\end{aligned}`,String.raw`R_{out}=${N(x.rout/1e3)}\,\mathrm{k\Omega},\quad A_{D,0}=${N(x.ad)},\quad U_p=${N(x.up)}\,\mathrm V,\quad U_n=${N(x.un)}\,\mathrm V`)]
 if(p.sensor===0)steps.push(
 s('Find the midpoint by current balance','Two equal Rs connect the outputs to a high-impedance sense node. Their midpoint draws no DC current. For common excitation both ends move equally; for differential excitation that midpoint is AC ground and each Rs loads its output.',String.raw`\frac{v_p-v_{sense}}{R_s}+\frac{v_n-v_{sense}}{R_s}=0\quad\Rightarrow\quad v_{sense}=\frac{v_p+v_n}{2}`,String.raw`v_{sense}=0.9\,\mathrm V\quad\text{at DC}`),
 s('Include the differential loading','Each differential half sees Rs to AC ground. The unloaded output difference and differential gain therefore share the same voltage-divider loss. Power is dissipated in the two sensing resistors in series.',String.raw`\begin{aligned}v_D&=\frac{u_d}{1+R_{out}/R_s},\quad A_D=\frac{A_{D,0}}{1+R_{out}/R_s}\\P_{port}&=\frac{v_D^2}{2R_s}\end{aligned}`,String.raw`v_D=${N(z.difference)}\,\mathrm V,\quad A_D=${N(z.gain)},\quad P_{port}=${N(z.power*1e9)}\,\mathrm{nW}`),
 s('Check the sensor’s own bandwidth','For this resistor option, the selected Cs is one capacitor from the midpoint to ground. Relative to the actual output mean, the two Rs are in parallel and set the sensing pole. Finite output resistance additionally loads the common-mode output dynamics.',String.raw`\frac{v_{sense}(s)}{v_{CM}(s)}=\frac1{1+sR_sC_s/2},\quad\tau_s=R_sC_s/2`,String.raw`\tau_s=${N(z.sensorTau*1e9)}\,\mathrm{ns}`))
 if(p.sensor===1)steps.push(
 s('Separate gate loading from follower gain','The two gate inputs draw no DC current. Each contributes a declared lumped Cg=50 fF to ground; this is a capacitance estimate, not an exact bootstrapped Cgs network. Each follower source has Cs to ground.',String.raw`\begin{aligned}A_D(0)&=A_{D,0}\\H_f(s)&=\frac{g_{mf}}{g_{mf}+g_{of}+sC_s}\end{aligned}`,String.raw`H_f(0)=${N(f.sensorGain)},\quad f_{p,f}=${N(f.pole/1e6)}\,\mathrm{MHz}`),
 s('Reserve bias headroom before quoting swing','The illustrative NMOS follower requires 0.65 V gate-to-source drop and 0.10 V current-source compliance below its source. Intersect that lower bound with the original output window [0.2,1.6] V. A matching common-mode reference must account for the sensor’s DC level shift.',String.raw`\begin{aligned}V_{out,min}&=\max(0.2,V_{GS}+0.10)=0.75\,\mathrm V\\V_{out,max}&=1.6\,\mathrm V\end{aligned}`,String.raw`[V_{min},V_{max}]=[0.75,1.6]\,\mathrm V,\quad V_{sense,bias}\approx0.9-0.65=0.25\,\mathrm V`),
 s('Account for dynamic and bias costs','The output pole uses CL+Cg even though its DC gain is unchanged. Two follower bias paths are allocated 10 μA each at 1.8 V. That power is a separate supply cost, not current drawn from the output gates.',String.raw`f_{p,out}=\frac1{2\pi R_{out}(C_L+C_g)},\quad P_{bias}=2V_{DD}I_f`,String.raw`f_{p,out}=${N(1/(2*Math.PI*x.rout*(x.cl+f.cgate))/1e6)}\,\mathrm{MHz},\quad P_{bias}=${N(f.power*1e6)}\,\mu\mathrm W`))
 if(p.sensor===2)steps.push(
 s('Define the phases and conserve charge at connection','Before each track phase, both Cs are reset to ground. Connecting one to each output shares its stored charge with CL instantly because the finite output resistance cannot supply an impulse. During track, the driver then recharges CL+Cs toward U.',String.raw`\begin{aligned}a&=\frac{C_L}{C_L+C_s},\quad v(0^+)=a\,v(0^-)\\\tau_{on}&=R_{out}(C_L+C_s),\quad r=e^{-h/\tau_{on}}\\v(h)&=U+[v(0^+)-U]r\end{aligned}`,String.raw`a=${N(q.a)},\quad h=${N(q.half*1e9)}\,\mathrm{ns},\quad\tau_{on}=${N(q.tauOn*1e9)}\,\mathrm{ns}`),
 s('Solve the periodic state, not just the first sample','After track, disconnect both Cs and join their top plates on an isolated hold node; equal capacitances average the captured voltages. Meanwhile each output recovers with CL only. Equating successive pre-track voltages gives the periodic ratios b, k and q.',String.raw`\begin{aligned}r_0&=e^{-h/(R_{out}C_L)},\quad b=\frac{1-rr_0}{1-arr_0}\\k&=ab,\quad q=1+(k-1)r\\v_{hold}&=\frac{qU_p+qU_n}{2}=0.9q\end{aligned}`,String.raw`k=${N(q.kick)},\quad q=${N(q.sample)},\quad v_{hold}=${N(q.held)}\,\mathrm V`),
 s('Use charge per cycle to find real output loading','Each reset discards Cs qU from an output. In periodic steady state the driver must replace that charge every cycle. Average resistor drop is Rout times average current; this determines the cycle-average output ratio m.',String.raw`\begin{aligned}\overline I&=C_sf_sqU,\quad m=1-R_{out}C_sf_sq\\\overline v&=mU,\quad A_{D,mean}=mA_{D,0}\\P_{port}&=f_sC_sq(U_p^2+U_n^2)\end{aligned}`,String.raw`\overline v_{CM}=${N(.9*q.mean)}\,\mathrm V,\quad A_{D,mean}=${N(q.gain)},\quad\overline I_{CM}=${N(q.current*1e6)}\,\mu\mathrm A`),
 s('Check the slow-clock equivalent-resistance approximation','Req≈1/(Cs fs) treats charge loading as a continuous conductance and gives a useful slow-clock estimate. The phase equations remain the calculation when acquisition is incomplete. Seven track time constants leave less than 0.1% of the initial track error.',String.raw`R_{eq}\approx\frac1{C_sf_s},\quad m_{approx}=\frac1{1+R_{out}C_sf_s},\quad h/\tau_{on}\ge7\ \text{for the settling check}`,String.raw`h/\tau_{on}=${N(q.half/q.tauOn)},\quad error_m=${N(100*q.error)}\%`))
 const gain=[z.gain,f.gain,q.gain][p.sensor],plots=p.sensor===2?[{label:'One periodic track–hold cycle',xLabel:'Time (μs)',yLabel:'Voltage (V)',traces:[{label:'Positive output',points:samples(t=>q.wave(x.up,t*1e-6),0,2*q.half*1e6,241)},{label:'Negative output',points:samples(t=>q.wave(x.un,t*1e-6),0,2*q.half*1e6,241)},{label:'Captured mean (valid during hold)',points:[{x:q.half*1e6,y:q.held},{x:2*q.half*1e6,y:q.held}],dashed:true}]}]:[{label:'Sensor choice changes output gain',xLabel:'Each sensing resistance (kΩ)',yLabel:'Differential gain (V/V)',traces:[{label:'Resistive sensor',points:samples(rs=>sensors({...p,rs:rs*1e3}).resistive.gain,10,1000)},{label:'Follower: DC gain',points:[{x:10,y:f.gain},{x:1000,y:f.gain}]},{label:'SC: cycle-mean gain',points:[{x:10,y:q.gain},{x:1000,y:q.gain}],dashed:true}]}]
 const conclusion=p.sensor===2?(q.settled?'Acquisition passes the seven-time-constant check. The held sample and cycle-average output are still different quantities; reset charge creates nonzero loading.':'Incomplete acquisition: use the exact sampled result. The held mean falls below the unloaded mean, and a constant equivalent resistance does not describe the waveform.'):(p.sensor===0?'Equal resistors preserve the common DC mean while reducing differential gain. Increasing Rs reduces loading but slows a capacitive sense node.':(f.margin<0?'The lower output is below follower compliance. The displayed incremental gain assumes a valid bias and is not an accepted operating point at this swing. Reduce the unloaded output difference.':'Followers preserve DC output gain but consume headroom and bias current. Their gate capacitance changes output dynamics; their level shift requires a compatible reference.'))
 return O(steps,[r(p.sensor===2?'Cycle-mean differential gain':'DC differential gain',gain,'V/V'),...(p.sensor===1?[r('Follower headroom margin',f.margin,'V')]:[]),r(p.sensor===1?'Sensor bias estimate':'Selected sensor mean',p.sensor===1?.25:p.sensor===2?q.held:.9,'V'),r('Output-port loading power',p.sensor===0?z.power*1e6:p.sensor===2?q.power*1e6:0,'μW'),...(p.sensor===2?[r('Track time / time constant',q.half/q.tauOn)]:[])],plots,conclusion,gain,'V/V',`Calculate the ${which.toLowerCase()} sensor’s ${p.sensor===2?'cycle-mean':'DC'} differential gain.`,p.sensor===0?'Divide the unloaded gain by 1+Rout/Rs.':p.sensor===1?'Ideal gates draw no DC current, so use the unloaded gain.':'Multiply the unloaded gain by m=1−Rout Cs fs q.',{table:{headers:['Sensor','Output gain','Mean sensing','Main cost'],rows:[['Equal resistors',unit(z.gain,'V/V (DC)'),'Exact mean at DC','Differential loading; midpoint pole'],['Source followers',unit(f.gain,'V/V (DC)'),'Level shift; incremental gain '+F(f.sensorGain),'0.75 V lower bound; 36 μW bias; gate C'],['Reset capacitors',unit(q.gain,'V/V (cycle mean)'),unit(q.held,'V held'),'Charge kick; acquisition; '+unit(q.power*1e6,'μW port loading')]]},plotNote:'Settings remain visible to make the comparison reproducible: Rs affects the resistor option; fs affects the sampler; Cs is the resistor midpoint capacitor, each follower source capacitor, or each sampling capacitor. The switched waveform starts just after the reset/connection kick and ends just before the next kick. The original output compliance window is [0.2,1.6] V; follower limits are separately shown.',limits:'Matched ideal sensors and a linear Thevenin output stage. Follower headroom uses a separate fixed-drop bias estimate. The sampler has ideal zero-resistance switches, instantaneous reset, equal track/hold periods and no charge injection or clock feedthrough. Reset-to-ground is essential to this loading calculation; other SC sensor topologies require their own charge equations.',sources:[['Analog Devices AN-742: switched-capacitor inputs and driver kickback','https://www.analog.com/en/resources/app-notes/an-742.html']]})})
]
