import {TRANSLINEAR_LESSONS} from './translinearLessons.js'
import {COMPARATOR_LESSONS} from './comparatorLessons.js'
import {COMPENSATION_LESSONS} from './compensationLessons.js'
import {ARCHITECTURE_LESSONS} from './architectureLessons.js'
import {DIFFERENTIAL_LESSONS} from './differentialLessons.js'
import {BIAS_LESSONS} from './biasLessons.js'
import {knob as k,step as s,reading as r,curve,samples,texnum as N} from '@ee-labs/lessons/model'
import {PROCESS as P,specific,inversion,atOverdrive,sizeFor,matching,shortChannel} from './models.js'
const source=['EKV model authors: long-channel charge model','https://www.ekvmodel.com/book/04.The%20Long-channel%20MOSFET%20Model/Long_channel_MOSFET_model.html']
const icKnob=k('ic','Inversion coefficient',1,.001,100),eff=k('gmid','Transconductance efficiency',10,5,24,'V⁻¹')
const symbols=[['I_D,g_m','Drain current (A) and its gate-voltage derivative (S).'],['IC,I_S','Inversion coefficient ID/IS and device specific current (A).'],['n,U_T','Slope factor 1.5 and thermal voltage 25.852 mV at 300 K.'],['q_s','Normalized inversion charge; distinct from elementary charge.'],['W,L','Channel width and length (m).'],[String.raw`\mu C_{ox},C_{ox}`,'NMOS process transconductance factor, 200 μA/V², and oxide capacitance density, 8.63 fF/μm².'],['V_{OV}','Gate-source voltage minus zero-body-bias threshold (V).']]
const extras=[[String.raw`V_A,r_o,C_{gs},f_T`,'Early voltage (V), output resistance (Ω), estimated gate-source capacitance (F), and unity-current-gain frequency estimate (Hz).'],[String.raw`A_{VT},A_\beta,\sigma`,'Pair mismatch coefficients 4 mV·μm and 0.01 μm, and standard deviation of the named quantity.'],[String.raw`\gamma,2\phi_F,V_{SB},E_{sat}`,'Body coefficient 0.4 √V, surface-potential parameter 0.6 V, source-body voltage (V), and saturation-field parameter 5 V/μm.'],[String.raw`u,z,g_{mb}`,'Body-adjusted overdrive (V), dimensionless velocity correction u/(Esat L), and body transconductance (S).']]
function L(id,name,knobs,question,intro,tryText,solve,extra={}){return{id,name,group:'A. Devices on a die',knobs,question,intro,try:tryText,solve,symbols:[...symbols,...extras],sources:[source],flow:['Choose inversion and geometry','Calculate current, derivatives and capacitance','Check gain, speed and matching tradeoffs'],route:'Use the charge-based current law for bias and its derivative for small-signal design. Geometry and statistical mismatch add constraints that a nominal transfer function does not describe.',limits:'Generic long-channel saturation model at 300 K, not a foundry PDK. The voltage-charge relation and gm/ID use the same charge model. Earlier plan numbers that mixed this relation with a log-squared interpolation are superseded by the displayed calculation.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,plotNote:'Each curve belongs to the explicitly stated process and model. Ratios simplify design reasoning but do not remove process dependence.',practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const logCurve=(fn)=>Array.from({length:201},(_,i)=>{const x=10**(-3+5*i/200);return{x,y:fn(x)}})
export const EXTENDED=[
L('a1','One consistent law from weak to strong inversion',[icKnob,k('ratio','Width / length',10,1,100)],'How can one charge law span exponential and quadratic current behaviour?',
'Inversion coefficient normalizes drain current to a process-and-geometry scale. A normalized channel charge connects current to gate overdrive continuously through weak, moderate and strong inversion.',
'Compare IC = 0.001, 1 and 100. Look at current, overdrive and the named region.',p=>{const x=inversion(p.ic),Is=specific*p.ratio;return O([
s('Calculate the specific current','The per-square specific current is multiplied by W/L for this device.',String.raw`I_{S,\square}=2n\mu C_{ox}U_T^2,\quad I_S=I_{S,\square}W/L`,String.raw`I_{S,\square}=${N(specific*1e6)}\,\mu\mathrm A,\quad I_S=${N(Is*1e6)}\,\mu\mathrm A`),
s('Find the normalized charge','The positive solution of IC = qs(qs+1) spans both diffusion and drift contributions.',String.raw`IC=q_s(q_s+1),\quad q_s=\frac{\sqrt{1+4IC}-1}{2}`,String.raw`q_s=${N(x.charge)},\quad I_D=IC\,I_S=${N(p.ic*Is*1e6)}\,\mu\mathrm A`),
s('Recover the gate overdrive','When qs is small, ln(qs) dominates; when qs is large, the linear charge term dominates.',String.raw`V_{OV}=nU_T[2q_s+\ln(q_s)]`,String.raw`V_{OV}=${N(x.vov)}\,\mathrm V,\quad S_{weak}=nU_T\ln10=${N(P.n*P.vt*Math.LN10*1000)}\,\mathrm{mV/decade}`)
],[r('Drain current',p.ic*Is*1e6,'μA'),r('Overdrive',x.vov,'V'),r('Specific current / square',specific*1e6,'μA')],[{...curve('Efficiency across inversion','IC','gm/ID (V⁻¹)',logCurve(ic=>inversion(ic).gmid)),logX:true}],`This setting is ${x.region} inversion. Negative gate overdrive does not mean zero current in this model.`,p.ic*Is*1e6,'μA','Calculate drain current in microamperes.','Multiply inversion coefficient by specific current and width/length ratio.') }),
L('a2','Transconductance efficiency has a ceiling',[icKnob,k('vov','Square-law comparison overdrive',.2,.05,.6,'V')],'Why does 2/VOV fail near weak inversion?',
'The square law assumes strong inversion. The continuous charge law has an efficiency ceiling set by thermal voltage and slope factor, so reducing current cannot increase gm/ID without bound.',
'Reduce IC toward 0.001. Then compare both efficiency formulas at 200 mV overdrive.',p=>{const x=inversion(p.ic),v=atOverdrive(p.vov),ceiling=1/(P.n*P.vt),square=2/p.vov;return O([
s('Differentiate the same current law','Use the derivatives of ID = IS qs(qs+1) and VOV = nUT(2qs + ln qs).',String.raw`\frac{dI_D}{dq_s}=I_S(2q_s+1),\quad\frac{dV_{OV}}{dq_s}=nU_T(2+1/q_s)`),
s('Divide to obtain efficiency','The common charge factors cancel, leaving a bounded expression.',String.raw`\frac{g_m}{I_D}=\frac1{nU_T(1+q_s)}=\frac1{nU_T}\frac2{1+\sqrt{1+4IC}}`,String.raw`g_m/I_D=${N(x.gmid)}\,\mathrm{V^{-1}},\quad limit=${N(ceiling)}\,\mathrm{V^{-1}}`),
s('Compare at one common overdrive','Solve the charge-voltage equation before comparing. Mixing overdrive from another interpolation would be inconsistent.',String.raw`(g_m/I_D)_{square}=2/V_{OV},\quad error=\frac{(g_m/I_D)_{square}}{(g_m/I_D)_{charge}}-1`,String.raw`square=${N(square)},\quad charge=${N(v.gmid)}\quad\mathrm{V^{-1}},\quad error=${N(100*(square/v.gmid-1))}\%`)
],[r('Selected efficiency',x.gmid,'V⁻¹'),r('Weak-inversion ceiling',ceiling,'V⁻¹')],[{...curve('Bounded efficiency','IC','gm/ID (V⁻¹)',logCurve(ic=>inversion(ic).gmid)),logX:true}], 'The numerical derivative, bias law and efficiency curve all use the same normalized-charge model.',x.gmid,'V⁻¹','Calculate gm/ID at the selected inversion coefficient.','First find qs, then divide 1 by nUT(1 + qs).') }),
L('a3','Trade current, area, gain and speed',[eff,k('gm','Target transconductance',500e-6,100e-6,2e-3,'S'),k('length','Channel length',1e-6,.18e-6,2e-6,'m')],'What does raising gm/ID buy and what does it cost at fixed gm?',
'Fixing transconductance turns efficiency into a required bias current. The inversion coefficient then gives width/length, while a stated output-resistance and capacitance estimate connects geometry to gain and speed.',
'Compare efficiencies 5, 10 and 20 at 500 μS. Read all four outcomes together.',p=>{const x=sizeFor(p);return O([
s('Use the transconductance target to find current','Efficiency is gm/ID, so the required current follows directly.',String.raw`I_D=g_m/(g_m/I_D)`,String.raw`I_D=${N(x.id*1e6)}\,\mu\mathrm A`),
s('Invert the efficiency relation and size the device','The specific current per square determines the current density at the selected IC.',String.raw`q_s=\frac1{nU_T(g_m/I_D)}-1,\quad IC=q_s(q_s+1),\quad W/L=\frac{I_D}{I_{S,\square}IC}`,String.raw`IC=${N(x.ic)},\quad W/L=${N(x.ratio)},\quad W=${N(x.width*1e6)}\,\mu\mathrm m`),
s('Apply explicitly separate gain and speed estimates','Use Early voltage 10 V per μm of channel length and the strong-inversion Cgs ≈ 2CoxWL/3 estimate. The latter is illustrative away from strong inversion.',String.raw`r_o=V_A/I_D,\quad A_v\simeq g_mr_o,\quad C_{gs}\simeq\tfrac23C_{ox}WL,\quad f_T\simeq g_m/(2\pi C_{gs})`,String.raw`A_v=${N(x.gain)},\quad C_{gs}=${N(x.cgs*1e15)}\,\mathrm{fF},\quad f_T\simeq${N(x.ft/1e6)}\,\mathrm{MHz}`)
],[r('Current',x.id*1e6,'μA'),r('Width',x.width*1e6,'μm'),r('Intrinsic gain estimate',x.gain),r('Capacitance-based fT estimate',x.ft/1e6,'MHz')],[curve('Area cost at fixed gm','gm/ID (V⁻¹)','Width (μm)',samples(g=>sizeFor({...p,gmid:g}).width*1e6,5,24))],'Higher efficiency reduces current but may require more area and capacitance. The displayed fT is a stated capacitance estimate, not a complete RF transistor model.',x.id*1e6,'μA','Calculate current required by the selected gm target.','Divide transconductance by gm/ID, then convert amperes to microamperes.') }),
L('a4','Matching is an area requirement',[k('area','Matched device area',2.5,.25,100,'μm²'),eff,k('target','Target input-offset sigma',1e-3,.1e-3,5e-3,'V')],'How large must a matched pair be for an offset target?',
'Local random mismatch decreases approximately with the square root of device area. Threshold mismatch and current-factor mismatch contribute independently to a pair’s input-referred offset.',
'Multiply area by four and predict the sigma change. Then tighten the target by a factor of two.',p=>{const x=matching(p),required=x.targetArea/p.target**2;return O([
s('Scale the pair-mismatch coefficients','The given coefficients describe the mismatch between a pair; do not add a second √2 factor.',String.raw`\sigma_{\Delta V_T}=A_{VT}/\sqrt{WL},\quad\sigma_{\Delta\beta/\beta}=A_\beta/\sqrt{WL}`,String.raw`\sigma_{\Delta V_T}=${N(x.vth*1000)}\,\mathrm{mV},\quad\sigma_\beta=${N(x.beta*100)}\%`),
s('Refer both contributions to the input','Independent threshold and current-factor errors add in variance.',String.raw`\sigma_{VOS}=\sqrt{\sigma_{\Delta V_T}^2+[\sigma_\beta/(g_m/I_D)]^2}`,String.raw`\sigma_{VOS}=${N(x.offset*1000)}\,\mathrm{mV}`),
s('Solve the area required by the target','Rearrange the variance expression before substituting the target sigma.',String.raw`WL_{required}=\frac{A_{VT}^2+[A_\beta/(g_m/I_D)]^2}{\sigma_{target}^2}`,String.raw`WL_{required}=${N(required)}\,\mu\mathrm{m^2}`)
],[r('Offset sigma',x.offset*1000,'mV'),r('Required area',required,'μm²')],[curve('Area and pair offset','Area (μm²)','Offset sigma (mV)',samples(area=>matching({...p,area}).offset*1000,.25,100))],p.area>=required?'The chosen area meets this statistical sigma target under the declared mismatch model.':'The chosen area misses this statistical sigma target; a nominally correct circuit can still have excessive spread.',required,'μm²','Calculate the area required for the target offset sigma.','Square the coefficients, add their input-referred contributions, and divide by target sigma squared.') },{limits:'Illustrative Pelgrom pair coefficients AVT = 4 mV·μm and Aβ = 1%·μm, independent local Gaussian variations. Declared area range ≥ 0.25 μm². Gradients, systematic layout error and yield tails are not included.'}),
L('a5','Mirror error grows with efficiency',[k('area','Matched device area',2.5,.25,100,'μm²'),eff],'Why can a low-current high-efficiency mirror be more sensitive to threshold mismatch?',
'A threshold difference perturbs current in proportion to gm/ID. Raising efficiency therefore increases the fractional current error caused by the same threshold mismatch.',
'Compare gm/ID = 10 and 20 at 2.5 μm², then increase area to 100 μm².',p=>{const x=matching(p);return O([
s('Linearize the mirror current error','Threshold mismatch changes the effective gate overdrive; current-factor mismatch scales the current directly.',String.raw`\Delta I/I\simeq-(g_m/I_D)\Delta V_T+\Delta\beta/\beta`),
s('Add independent error variances','The sign matters in each sample but drops out when independent variances are added.',String.raw`\sigma_{\Delta I/I}=\sqrt{[(g_m/I_D)\sigma_{\Delta V_T}]^2+\sigma_\beta^2}`,String.raw`\sigma_{\Delta I/I}=${N(100*x.mirror)}\%`),
s('Read the area/efficiency trade','Doubling efficiency doubles only the threshold-related term, while quadrupling area halves both sigmas.',String.raw`\sigma_{\Delta I/I}=\frac{\sqrt{[(g_m/I_D)A_{VT}]^2+A_\beta^2}}{\sqrt{WL}}`,String.raw`\sigma_{threshold\ contribution}=${N(100*p.gmid*x.vth)}\%`)
],[r('Fractional current sigma',100*x.mirror,'%')],[curve('Efficiency and current mismatch','gm/ID (V⁻¹)','Current-error sigma (%)',samples(gmid=>100*matching({...p,gmid}).mirror,5,24))],'The same threshold sigma can be acceptable for a low-efficiency mirror and excessive for a high-efficiency one.',100*x.mirror,'%','Calculate the fractional current-error sigma as a percent.','Add threshold-induced and current-factor error in quadrature.') },{limits:'First-order mismatch propagation with the same pair coefficients and area limits as A4. This is a sigma calculation, not a claim about measured yield or large-mismatch nonlinear tails.'}),
L('a6','Name the short-channel correction',[k('length','Channel length',.18e-6,.18e-6,2e-6,'m'),k('vov','Zero-body overdrive',.3,.15,.6,'V'),k('vsb','Source-body voltage',.5,0,1,'V'),k('velocity','Velocity saturation (0: off, 1: on)',1,0,1,'',1),k('body','Body effect (0: off, 1: on)',0,0,1,'',1),k('clm','Channel-length modulation (0: off, 1: on)',0,0,1,'',1)],'Which simplified device correction changed current and transconductance?',
'This lesson deliberately starts from a strong-inversion square-law comparison and adds labelled corrections one at a time. It makes no claim to be a full short-channel compact model.',
'Compare 0.18 μm and 1 μm with velocity saturation on. Then enable body effect separately.',p=>{const x=shortChannel(p);return O([
s('Shift threshold for reverse body bias','The body effect reduces effective overdrive at fixed gate-source voltage.',String.raw`\Delta V_T=\gamma[\sqrt{2\phi_F+V_{SB}}-\sqrt{2\phi_F}],\quad u=\max(0,V_{OV}-\Delta V_T)`,String.raw`\Delta V_T=${N(x.shift)}\,\mathrm V,\quad u=${N(x.u)}\,\mathrm V`),
s('Apply the declared velocity-saturation correction','Use Esat = 5 V/μm. Turning the toggle off sets z to zero.',String.raw`z=u/(E_{sat}L),\quad I_D=\frac{\mu C_{ox}(W/L)u^2}{2(1+z)}`,String.raw`z=${N(x.z)},\quad I_D/I_{long}=${N(x.ratio)}`),
s('Differentiate the corrected current','The gm correction is not the same as the current correction. Channel-length modulation multiplies both here by 1 + VDS/VA, with VDS fixed at 1 V.',String.raw`\frac{g_m}{g_{m,long}}=\frac{1+z/2}{(1+z)^2},\quad g_{mb}/g_m=\gamma/(2\sqrt{2\phi_F+V_{SB}})`,String.raw`g_m/g_{m,long}=${N(x.gmRatio)},\quad g_{mb}/g_m=${N(x.gmbRatio)},\quad CLM\ factor=${N(x.clmFactor)}`)
],[r('Threshold shift',x.shift*1000,'mV'),r('Velocity current factor',x.ratio),r('gm factor',x.gmRatio),r('Body transconductance ratio',x.gmbRatio)],[curve('Length and velocity correction','Length (μm)','Current / long-channel current',samples(L=>shortChannel({...p,length:L*1e-6}).ratio,.18,2))],'The toggles isolate assumptions. The long-channel charge model in A1–A5 and this illustrative corrected square law must not be mixed as if they were one fitted process model.',x.ratio,'','Calculate the velocity-saturation current factor.','Use 1/(1 + effective overdrive divided by Esat L).') },{limits:'Illustrative strong-inversion corrections, W/L = 1, VDS = 1 V, Esat = 5 V/μm, γ = 0.4 √V, 2φF = 0.6 V and VA = 10 V per μm. No DIBL, mobility degradation or short-channel PDK extraction is claimed.'}),
...BIAS_LESSONS,...ARCHITECTURE_LESSONS,...DIFFERENTIAL_LESSONS,...COMPENSATION_LESSONS,...COMPARATOR_LESSONS
,...TRANSLINEAR_LESSONS
]
