import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {extraElement,extraDrawing,trimPopulation,calibration} from './extraElement.js'
const T=String.raw,knobs=[k('gm','Stage transconductance',200e-6,100e-6,800e-6,'S'),k('rd','Drain load resistance',20000,5000,50000,'Ω'),k('rs','Source driving resistance',10000,2000,50000,'Ω'),k('cap','Gate-drain capacitance',20e-15,5e-15,100e-15,'F')],bits=k('bits','Stored trim resolution',5,3,8,'bits',1),range=k('range','Nominal bipolar trim half-range',.008,.001,.016,'V')
const circuitSymbols=[[T`v_{in},v_g,v_o,g_m,R_S,R_D,C_{gd}`,'Input, gate and output voltages to ground (V), controlled-source transconductance (S), driving and drain resistances (Ω), and gate-drain capacitance (F). RD includes output resistance; supplies and bias are omitted.'],[T`s,j,\omega,f,H,H_0,Z_D,Z_N`,'Laplace variable (s⁻¹), imaginary unit, angular frequency (rad/s), frequency (Hz), voltage transfer vo/vin, transfer with Cgd removed, and two driving-point resistances (Ω) seen by the extra element.'],[T`f_p,f_z,\tau,x,\dot x,t,0^-,0^+`,'Pole-frequency scale (Hz), positive-real-zero frequency scale (Hz, not an AC notch), time constant (s), capacitor state x=vg−vo (V), derivative (V/s), time (s), and instants before/after the input step.']]
const trimSymbols=[[T`u,\sigma_{OS},A,\eta,A_{VT},A_\beta`,'Untrimmed offset (V), its population standard deviation (V), each input-device area (µm²), gm/ID efficiency (V⁻¹), and generic pair coefficients 4 mV·µm and 0.01 µm.'],[T`b,L,R,\Delta,k,c_k,e`,'Integer resolution (bits), number of codes 2ᵇ, nominal bipolar half-range (V), code step (V), integer code, correction voltage (V), and residual offset u−ck (V). R here is a voltage range, not a resistance.'],[T`\Phi,\phi,P,\mathbb E`,'Standard normal cumulative distribution and probability density, probability, and population expectation. All population results assume a zero-mean Gaussian offset and exact noiseless code selection.']]
const eetSource=['Middlebrook: Null Double Injection and the Extra Element Theorem','https://authors.library.caltech.edu/records/2kkth-50y81'],calSource=['Analog Devices: temperature drift in a precision DAC','https://www.analog.com/en/resources/technical-articles/2022/07/16/10/51/understanding-temperature-drift-in-a-precision-digitaltoanalog-converter-dac.html']
function L(id,name,controls,question,intro,attempt,solve,symbols,extra={}){return{id,name,group:'J. Extra-element analysis and stored trim',knobs:controls,question,intro,try:attempt,solve,symbols,flow:['Define the circuit or code convention','Derive and substitute the relevant equations','Compare exact results, approximations and residual limits'],route:'The extra-element theorem, nodal equations, state equation and sinusoidal phasor substitution describe the same linear circuit in J1–J2. Choose the theorem to expose one added element, nodal equations for a direct check, the state equation for startup and phasors for sinusoidal response. J3–J4 instead use a quantizer and an offset/drift model; a transfer function alone cannot describe code selection.',limits:'Explicit teaching models. The circuit has one capacitor and an ideal frequency-independent transconductance. Trim calculations omit code nonlinearity and stochastic measurement noise unless a stated measurement error is selected. Generic mismatch coefficients are not a foundry process guarantee.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const grid=(fn,x)=>{const lo=Math.min(x.pole,x.zero)/100,hi=Math.max(x.pole,x.zero)*100;return Array.from({length:241},(_,i)=>{const f=lo*(hi/lo)**(i/240);return{x:f/1e6,y:fn(f)}})}
export const EXTRA_ELEMENT_LESSONS=[
L('j1','One added capacitor: four routes to the same answer',knobs,
 'How can you restore Cgd without restarting the complete circuit analysis?',
 'Remove Cgd first: no input current flows through RS, so vg=vin and H0=−gmRD. The extra-element theorem restores the capacitor through two port resistances. Keep the controlled source active in both resistance calculations. The direct nodal and state equations below provide independent ways to reach the same response.',
 'Change RS and predict the pole movement. Inspect the small positive output immediately after a positive input step, followed by the negative DC output.',p=>{const x=extraElement(p);return O([
 s('Remove the extra element and solve the simpler circuit','With Cgd open, the gate draws no current. KCL at the output gives vo/RD+gmvg=0.',T`v_g=v_{in},\quad v_o=-g_mR_Dv_g,\quad H_0=-g_mR_D`,T`H_0=-(${N(p.gm)})(${N(p.rd)})=${N(x.gain)}`),
 s('Find ZD with the input voltage source set to zero','Remove Cgd and inject a test current it from out into gate. Then vg=itRS and vo=−itRD(1+gmRS). Dependent sources stay active.',T`Z_D=\frac{v_g-v_o}{i_t}=R_S+R_D+g_mR_SR_D`,T`Z_D=${N(p.rs)}+${N(p.rd)}+(${N(p.gm)})(${N(p.rs)})(${N(p.rd)})=${N(x.zd)}\,\Omega`),
 s('Find ZN by nulling the output with a second injection','Retain the port test current and adjust vin until vo=0. Output KCL gives gmvg=−it; the required vin is −it(RS+1/gm). Nulling the output is not the same as shorting it with an extra source.',T`v_o=0,\quad g_mv_g=-i_t,\quad Z_N=(v_g-v_o)/i_t=-1/g_m`,T`Z_N=${N(x.zn)}\,\Omega`),
 s('Restore the capacitor using its admittance','The open-element form is H=H0(1+ZN/Z)/(1+ZD/Z), with Z=1/(sCgd). The negative numerator resistance produces a positive-real zero.',T`\begin{aligned}H(s)&=H_0\frac{1+sC_{gd}Z_N}{1+sC_{gd}Z_D}=\frac{-g_mR_D+sC_{gd}R_D}{1+sC_{gd}Z_D}\\f_p&=\frac1{2\pi C_{gd}Z_D},\quad f_z=\frac{g_m}{2\pi C_{gd}}\end{aligned}`,T`f_p=${N(x.pole/1e6)}\,MHz,\quad f_z=${N(x.zero/1e6)}\,MHz`),
 s('Write the two nodal equations as a direct check','These are KCL at gate and output, with capacitor current consistently oriented from gate to output in the first row. Solve for vo/vin to obtain the same fraction.',T`\begin{aligned}(v_g-v_{in})/R_S+sC_{gd}(v_g-v_o)&=0\\v_o/R_D+g_mv_g+sC_{gd}(v_o-v_g)&=0\end{aligned}`,T`\tau=C_{gd}Z_D=${N(x.tau*1e9)}\,ns`),
 s('Choose the capacitor voltage as the continuous state','Let x=vg−vo. For an initially uncharged capacitor and a 1 mV input step, x(0−)=x(0+)=0. Both node voltages can jump together while their difference stays continuous.',T`\begin{aligned}\tau\dot x+x&=(1+g_mR_D)v_{in}\\v_o&=\frac{R_D}{Z_D}v_{in}\\&\quad-\frac{R_D(1+g_mR_S)}{Z_D}x\end{aligned}`,T`\begin{aligned}v_o(0^+)&=${N(x.feedthrough)}\,mV\\v_o(\infty)&=${N(x.gain)}\,mV\end{aligned}`),
 s('Read the pole, zero and sinusoidal phase correctly','Set s=j2πf for phasors. The zero is at s=+gm/Cgd, not at j2πfz, so there is no AC notch at fz. The phase is shown on the continuous branch beginning at −180°.',T`s_p=-1/\tau,\quad s_z=+g_m/C_{gd},\quad \angle H(j2\pi f)=-180^\circ-\frac{180^\circ}{\pi}[\tan^{-1}(f/f_z)+\tan^{-1}(f/f_p)]`,T`\angle H(j2\pi f_p)=${N(x.phase(x.pole))}^{\circ}`)
 ],[r('Exact pole frequency',x.pole/1e6,'MHz'),r('Positive-real-zero scale',x.zero/1e6,'MHz'),r('DC voltage gain',x.gain)],[curve('Initially uncharged Cgd: response to a 1 mV step','Time (ns)','Output (mV)',samples(t=>x.step(t*1e-9).output*1000,0,6*x.tau*1e9)),{...curve('Exact response normalized to DC magnitude','Frequency (MHz)','Magnitude relative to DC (dB)',grid(x.db,x)),logX:true},{...curve('Exact continuous phase branch','Frequency (MHz)','Phase (degrees)',grid(x.phase,x)),logX:true}],
 'All four routes agree for this stated circuit. The positive initial response and later negative output reflect its right-half-plane zero. These high-frequency numbers belong to the one-capacitor model, not to a complete physical transistor.',x.pole/1e6,'MHz','Calculate the exact pole-frequency scale.','Use 1/[2πCgd(RS+RD+gmRSRD)].',{schematic:extraDrawing(p),table:{headers:['Quantity','Value','Meaning'],rows:[['ZD',`${fmt(x.zd)} Ω`,'Port resistance with input killed'],['ZN',`${fmt(x.zn)} Ω`,'Port resistance with output nulled'],['Pole',`${fmt(x.pole/1e6)} MHz`,'Negative-real s-plane root'],['Zero',`${fmt(x.zero/1e6)} MHz`,'Positive-real s-plane root; not a notch']]}})},[...circuitSymbols,[T`i_t,Z`,'Test current injected from out into gate (A), and extra-element impedance 1/(sCgd) (Ω).']],{sources:[eetSource]}),
L('j2','Miller pole estimate: measure what it drops',knobs,
 'When is the input-only Miller estimate accurate enough?',
 'The input-only Miller estimate replaces Cgd by Cgd(1+gmRD) to ground at the gate, using the capacitor-free gain. It ignores the drain contribution to the time constant and removes the feedthrough zero. Compare its pole with the exact extra-element result from J1.',
 'Raise RS to 50 kΩ at the default gm and RD. The pole estimate should pass the stated 10% error check, even though the simplified model still omits the zero.',p=>{const x=extraElement(p),cm=p.cap*(1+p.gm*p.rd);return O([
 s('Apply the capacitor-free gain in the Miller estimate','Use H0=−gmRD. The effective gate capacitance is Cgd(1−H0). This is the input-only approximation, not a full two-port equivalence.',T`C_M=C_{gd}(1+g_mR_D),\quad f_M=1/(2\pi R_SC_M)`,T`C_M=${N(cm*1e15)}\,fF,\quad f_M=${N(x.miller/1e6)}\,MHz`),
 s('Compare the exact time constant term by term','The extra-element result retains RD in addition to the input-side Miller term.',T`\begin{aligned}\tau_{exact}&=C_{gd}[R_S(1+g_mR_D)+R_D]\\\tau_M&=C_{gd}R_S(1+g_mR_D)\end{aligned}`,T`\begin{aligned}\tau_{exact}&=${N(x.tau*1e9)}\,ns\\\tau_M&=${N(p.cap*p.rs*(1+p.gm*p.rd)*1e9)}\,ns\end{aligned}`),
 s('Calculate and apply a concrete approximation check','The relative pole overestimate is exactly RD/[RS(1+gmRD)]. At or below 10% this lesson accepts the estimate for pole location only; otherwise it directs you to the exact model.',T`\epsilon_p=f_M/f_p-1=\frac{R_D}{R_S(1+g_mR_D)},\quad\epsilon_p\le0.10`,T`\epsilon_p=${N(x.error*100)}\%\quad\text{(${x.millerOK?'within':'outside'} the 10\% check)}`),
 s('Compare magnitude and phase, not just one frequency','The approximation has no feedthrough zero. Both curves are divided by H0 so their common DC inversion is removed from this comparison.',T`H/H_0=\frac{1-jf/f_z}{1+jf/f_p},\quad H_M/H_0=\frac1{1+jf/f_M}`,T`\angle(H/H_0)|_{f_p}=${N(x.phase(x.pole)+180)}^{\circ},\quad\angle(H_M/H_0)|_{f_p}=${N(-Math.atan(x.pole/x.miller)*180/Math.PI)}^{\circ}`),
 s('Distinguish the pole from the −3 dB point','The zero changes the half-power crossing. Some allowed settings never fall 3 dB below DC because the high-frequency feedthrough is too large.',T`f_{3dB}=\left(f_p^{-2}-2f_z^{-2}\right)^{-1/2}\quad\text{only if }f_z>\sqrt2f_p`,x.cutoff?T`f_{3dB}=${N(x.cutoff/1e6)}\,MHz`:T`f_z\le\sqrt2f_p:\quad\text{no finite half-power crossing}`)
 ],[r('Exact pole',x.pole/1e6,'MHz'),r('Input-only Miller pole',x.miller/1e6,'MHz'),r('Pole overestimate',x.error*100,'%')],[{label:'Normalized magnitude: exact versus input-only Miller',xLabel:'Frequency (MHz)',yLabel:'Magnitude relative to DC (dB)',logX:true,traces:[{label:'Exact',points:grid(x.db,x)},{label:'Miller approximation',points:grid(f=>-10*Math.log10(1+(f/x.miller)**2),x),dashed:true}]},{label:'Phase after removing the common DC inversion',xLabel:'Frequency (MHz)',yLabel:'Additional phase (degrees)',logX:true,traces:[{label:'Exact',points:grid(f=>x.phase(f)+180,x)},{label:'Miller approximation',points:grid(f=>-Math.atan(f/x.miller)*180/Math.PI,x),dashed:true}]}],
 `${x.millerOK?'The pole estimate is within the 10% check.':'The pole estimate exceeds the 10% check; use the exact expression.'} Passing a pole-location check does not validate the missing zero or the high-frequency response.`,x.error*100,'%','Calculate the Miller pole overestimate as a percentage.','Use 100 RD/[RS(1+gmRD)].',{schematic:extraDrawing(p),table:{headers:['Feature','Exact circuit','Input-only Miller'],rows:[['Pole (MHz)',fmt(x.pole/1e6),fmt(x.miller/1e6)],['Zero (MHz)',fmt(x.zero/1e6),'Omitted'],['−3 dB frequency (MHz)',x.cutoff?fmt(x.cutoff/1e6):'No finite crossing',fmt(x.miller/1e6)],['High-frequency gain',fmt(x.feedthrough),'0']]}})},[...circuitSymbols,[T`C_M,f_M,\tau_M,\epsilon_p`,'Input-only Miller capacitance (F), estimated pole frequency (Hz), estimated time constant (s), and fractional pole overestimate.']],{sources:[eetSource]}),
L('j3','Trim quantization: resolution and range are different limits',[k('area','Each input-device area',2.5,.25,100,'µm²'),k('gmid','Input transconductance efficiency',10,5,24,'V⁻¹'),bits,range],
 'How much offset remains after a finite set of correction codes?',
 'Use a symmetric midrise trim DAC: L=2ᵇ levels lie at the centers of bins spanning −R to +R. Thus Δ=2R/L and the largest correction magnitudes are R−Δ/2. An even number of symmetric midrise levels has no zero level. Select the nearest code and subtract its correction from each offset.',
 'Compare five and six bits. Then reduce the range: a smaller code step helps in-range precision but more of the Gaussian population falls outside the range.',p=>{const x=trimPopulation(p),cell=x.cells[x.count/2];return O([
 s('Calculate the untrimmed population spread','Use the same generic pair mismatch model as Group A. Area is in µm² and the stated pair coefficients already describe the pair; do not add another √2 factor.',T`\sigma_{OS}=\sqrt{\frac{A_{VT}^2+(A_\beta/\eta)^2}{A}},\quad u\sim\mathcal N(0,\sigma_{OS}^2)`,T`\sigma_{OS}=${N(x.sigma*1000)}\,mV,\quad3\sigma_{OS}=${N(3*x.sigma*1000)}\,mV`),
 s('Define every code level and its range','Code k runs from 0 to L−1. The endpoints ±R are bin edges, not correction levels. At an exact interior edge, the upper code is chosen.',T`L=2^b,\quad\Delta=2R/L,\quad c_k=-R+(k+1/2)\Delta`,T`L=${x.count},\quad\Delta=${N(x.delta*1000)}\,mV,\quad c_{min,max}=\pm${N((p.range-x.delta/2)*1000)}\,mV`),
 s('State what the familiar quantization estimate assumes','Within the nominal range, nearest-code residual satisfies |e|≤Δ/2. Uniform residual within a bin gives Δ/√12. That is an approximation to the population RMS, not an individual-error bound.',T`e=u-c_{k(u)},\quad e_{uniform,rms}=\Delta/\sqrt{12}`,T`e_{uniform,rms}=${N(x.uniform*1e6)}\,\mu V`),
 s('Calculate the range-overload probability','Here overload means |u|>R, where even the nearest end code leaves more than half a step of error. An end code can also be selected by an in-range offset, so code saturation alone is a different event.',T`P_{outside}=P(|u|>R)=2[1-\Phi(R/\sigma_{OS})]`,T`P_{outside}=${N(x.outside*100)}\%`),
 s('Integrate squared residual over the actual code cells','The two end cells extend to infinity because the DAC clips. For cell bounds ak,bk, use Gaussian probability Pk and first/second moments M1k,M2k. Then sum before taking a square root.',T`\mathbb E[e^2]=\sum_k[M_{2k}-2c_kM_{1k}+c_k^2P_k],\quad M_{nk}=\int_{a_k}^{b_k}u^n p(u)\,du`,T`e_{all,rms}=${N(x.rms*1e6)}\,\mu V,\quad e_{inside,rms}=${N(x.inRms*1e6)}\,\mu V`),
 s('Evaluate the Gaussian moments for one cell','Let za=ak/σ and zb=bk/σ. For the first positive correction cell, substitute its finite boundaries into these closed-form Gaussian integrals.',T`\begin{aligned}P_k&=\Phi(z_b)-\Phi(z_a)\\M_{1k}&=\sigma[\phi(z_a)-\phi(z_b)]\\M_{2k}&=\sigma^2[P_k+z_a\phi(z_a)-z_b\phi(z_b)]\end{aligned}`,T`k=${cell.code},\quad P_k=${N(cell.prob)},\quad M_{2k}-2c_kM_{1k}+c_k^2P_k=${N(cell.power)}\,V^2`),
 s('Check the uniform approximation against the integrated result','Compare Δ/√12 with the conditional RMS for |u|≤R. The lesson flags a relative difference above 5%. Even when that check passes, the total population may be dominated by the tails.',T`\epsilon_q=\left|\frac{\Delta/\sqrt{12}}{\sqrt{\mathbb E[e^2\mid |u|\le R]}}-1\right|`,T`\epsilon_q=${N(x.approxError*100)}\%\quad\text{(${x.approxOK?'within':'outside'} the 5\% check)}`)
 ],[r('Untrimmed offset sigma',x.sigma*1000,'mV'),r('Total population residual',x.rms*1e6,'µV rms'),r('In-range residual',x.inRms*1e6,'µV rms'),r('Outside nominal range',x.outside*100,'%')],[curve('Nearest-code residual: central bins enlarged','Untrimmed offset (mV)','Residual (µV)',x.points)],
 `${x.approxOK?'The uniform in-range RMS estimate passes the 5% check.':'The uniform in-range RMS estimate misses the 5% check; use the integrated result.'} More bits reduce step size at fixed range. More range reduces overload at fixed bits but increases step size. The plot enlarges at most eight central bins; vertical segments indicate code jumps.`,x.delta*1000,'mV','Calculate the correction-code step.','Divide twice the half-range by 2ᵇ.',{table:{headers:['Resolution','Step (µV)','In-range RMS (µV)','All-parts RMS (µV)','Outside range (%)'],rows:[3,4,5,6,7,8].map(bits=>{const v=trimPopulation({...p,bits});return[bits,fmt(v.delta*1e6),fmt(v.inRms*1e6),fmt(v.rms*1e6),fmt(v.outside*100)]})}})},[...trimSymbols,[T`a_k,b_k,z_a,z_b,p(u),P_k,M_{nk},\epsilon_q`,'Bounds of the nearest-code cell (V), those bounds divided by offset sigma, Gaussian offset density (V⁻¹), cell probability, nth offset moment over that cell, and relative error of the uniform in-range RMS estimate.']]),
L('j4','A stored trim code does not track temperature',[k('offset','Actual offset at calibration temperature',.0026,-.012,.012,'V'),k('measurement','Calibration measurement error',0,-.001,.001,'V'),bits,range,k('drift','Untrimmed offset drift',5e-6,-20e-6,20e-6,'V/K'),k('tempco','Correction gain temperature coefficient',100e-6,-.002,.002,'K⁻¹'),k('temperature','Evaluation temperature',85,-40,125,'°C')],
 'After calibrating once, what changes when the circuit heats or cools?',
 'At T0=25°C, measure offset plus the selected measurement error and store one nearest-code correction. The code stays fixed afterward. The analog offset drifts additively; the correction voltage changes with its own fractional gain coefficient. This is a static temperature sweep, not a thermal transient.',
 'Raise offset drift until the ±500 µV task over −40 to 125°C fails. Increase resolution, then reduce drift separately: extra bits cannot remove a temperature-dependent slope.',p=>{const x=calibration(p),q=x.trim;return O([
 s('Select the code using the measured value','The deterministic measurement error can select a different code. Code rounding and clipping follow the same symmetric midrise convention as J3.',T`\begin{aligned}u_m&=u_0+\epsilon_m\\k&=\operatorname{clip}\left(\left\lfloor\frac{u_m+R}{\Delta}\right\rfloor,0,L-1\right)\\c_0&=-R+(k+1/2)\Delta\end{aligned}`,T`\begin{aligned}u_m&=${N((p.offset+p.measurement)*1000)}\,mV\\k&=${q.code}\\c_0&=${N(q.correction*1000)}\,mV\end{aligned}`),
 s('Keep the residual at the calibration temperature','Subtract the selected correction from the actual offset, not from the measurement. One-point calibration does not generally make this exactly zero.',T`e(T_0)=u_0-c_0`,T`e(25^{\circ}C)=${N(p.offset*1000)}-${N(q.correction*1000)}=${N(x.baseline.after*1000)}\,mV`),
 s('Write both temperature laws with their units','α is additive offset drift in V/K. β is fractional correction gain drift in K⁻¹. A temperature difference has the same numerical value in kelvins and degrees Celsius.',T`\begin{aligned}\Delta T&=T-T_0\\u(T)&=u_0+\alpha\Delta T\\c(T)&=c_0(1+\beta\Delta T)\end{aligned}`,T`\begin{aligned}\Delta T&=${N(p.temperature-25)}\,K\\\alpha&=${N(p.drift*1e6)}\,\mu V/K\\\beta&=${N(p.tempco*1e6)}\,ppm/K\end{aligned}`),
 s('Subtract to expose the residual slope','The coefficient c0β has units V/K. It depends on the selected code, so changing the code changes this drift contribution.',T`e(T)=(u_0-c_0)+(\alpha-c_0\beta)\Delta T`,T`\alpha-c_0\beta=${N(x.slope*1e6)}\,\mu V/K,\quad e(${N(p.temperature)}^{\circ}C)=${N(x.selected.after*1e6)}\,\mu V`),
 s('Check the whole temperature interval','The residual is affine in temperature, so maximum absolute error on a closed interval occurs at an endpoint. This is a provable bound for the stated linear drift laws.',T`e_{max}=\max(|e(-40^{\circ}C)|,|e(125^{\circ}C)|),\quad e_{max}\le500\,\mu V`,T`e_{max}=${N(x.worst*1e6)}\,\mu V\quad\text{(${x.passes?'pass':'miss'})}`),
 s('Choose the next design change based on the remaining term','More bits address rounding; more range addresses overload. Reducing measurement error improves the selected code. Temperature tracking or a second calibration parameter is needed to correct a drift slope.',T`\Delta e=e(T)-e(T_0)=(\alpha-c_0\beta)\Delta T`,T`\Delta e=${N(x.increment*1e6)}\,\mu V,\quad |u_m|${q.outside?'>':'\le'}R`)
 ],[r('Stored trim code',q.code),r('Residual at selected temperature',x.selected.after*1e6,'µV'),r('Residual drift',x.slope*1e6,'µV/K'),r('Worst interval residual',x.worst*1e6,'µV')],[{label:'Actual offset and residual after one stored calibration',xLabel:'Temperature (°C)',yLabel:'Offset (mV)',traces:[{label:'Before trim',points:samples(T=>x.at(T).before*1000,-40,125)},{label:'After stored trim',points:samples(T=>x.at(T).after*1000,-40,125)}]},curve('Residual enlarged: same stored code at every temperature','Temperature (°C)','Residual (µV)',samples(T=>x.at(T).after*1e6,-40,125))],
 `${x.passes?'The ±500 µV temperature-interval task passes.':'The ±500 µV temperature-interval task fails.'} ${q.outside?'The measured offset is outside the nominal trim range.':'The measured offset is inside the nominal trim range.'} This sweep includes rounding and a selected fixed measurement error; it excludes random noise, nonlinear temperature behavior and aging.`,x.slope*1e6,'µV/K','Calculate the residual temperature slope.','Subtract correction voltage times its fractional coefficient from untrimmed drift.',{table:{headers:['Temperature (°C)','Before (mV)','Correction (mV)','Residual (µV)'],rows:[-40,25,85,125].map(T=>{const v=x.at(T);return[T,fmt(v.before*1000),fmt(v.correction*1000),fmt(v.after*1e6)]})},related:{app:'mixed-signal-lab',id:'c6',label:'Open Mixed-Signal C6: stored capacitor-weight calibration',note:'Compare this analog correction with a stored digital estimate of DAC weights. The linked lesson opens its own defaults; these are related calibration ideas, not a transfer of this trim circuit or code.'}})},[trimSymbols[1],[T`T,T_0,\Delta T,u_0,u_m,\epsilon_m,c_0,\alpha,\beta,e_{max}`,'Temperature (°C), calibration temperature 25°C, difference (K), actual and measured calibration offsets (V), fixed measurement error (V), stored-code correction at calibration (V), additive drift (V/K), fractional correction coefficient (K⁻¹), and maximum absolute residual over the stated interval (V).']],{sources:[calSource]}),
]
