import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {gmIntegrator,gmBiquad,tuning,ladder,ladderSections,filterHandover,integratorDrawing,ladderDrawing,biquadDrawing,stateStep,loggrid,db} from './integratedFilters.js'
const T=String.raw,source=['Analog Devices: Analog filter design','https://www.analog.com/en/resources/technical-articles/analog-filter-design-demystified.html']
function L(id,name,knobs,question,intro,attempt,solve,symbols,extra={}){return{id,name,group:'H. Integrated filters and tuning',knobs,question,intro,try:attempt,solve,symbols,sources:[source],flow:['Write node-current or state equations','Derive the transfer and frequency response','Measure nonideality, calibration or sensitivity'],route:'KCL, states and transfer functions describe the same linear circuit. Use states and initial conditions for a transient; set s=j2πf for sinusoidal steady state. Calibration statistics and component sensitivities add questions beyond a nominal frequency response.',limits:'Linear transconductors and capacitors with stated output conductance, damping and process models. Transistor headroom, noise and nonlinearity are separate constraints.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const symbols=[[T`g_m,g_{m1},g_{m2},g_d,g_o,R_o,C_1,C_2`,'Transconductances and damping/output conductances (S), output resistance (Ω), and capacitances (F).'],[T`v_{in},v_1,v_2,\dot v_1,\dot v_2,s,j,f,\omega`,'Input and state voltages (V), derivatives (V/s), Laplace variable (s⁻¹), imaginary unit, frequency (Hz), and angular frequency (rad/s).'],[T`H,A,B,\omega_n,Q`,'Input-output transfer, state matrix (s⁻¹), input vector (s⁻¹), denominator natural angular frequency (rad/s), and quality factor.']]
export const INTEGRATED_FILTER_LESSONS=[
L('h1','The gm-C integrator leaks through output resistance',[k('gm','Transconductance',100e-6,20e-6,500e-6,'S'),k('cap','Integrating capacitance',10e-12,2e-12,50e-12,'F'),k('ro','Output resistance',1.5e6,1e5,1e7,'Ω')],
 'When is this a useful integrator rather than a finite-gain amplifier?',
 'A linear transconductor injects gm·vin into C in parallel with Ro. Positive input produces positive current into the capacitor. The normalized step starts with an uncharged capacitor; real output rails are omitted.',
 'Reduce Ro and compare the pole, unity crossing and phase. The ideal gm/(2πC) result approximates the actual crossing only at high DC gain.',p=>{const x=gmIntegrator(p);return O([
 s('Write KCL and identify the stored state','The injected current divides between capacitor current and output-resistance current.',T`C\dot v_o+v_o/R_o=g_mv_{in},\quad v_o(0)=0`,T`\dot v_o=-${N(x.pole)}v_o+${N(x.w)}v_{in}`),
 s('Take the zero-initial-state transfer','Finite Ro moves the ideal integrator pole away from the origin. The capacitor carries no DC current.',T`H(s)=\frac{g_m}{sC+1/R_o},\quad H(0)=g_mR_o,\quad\omega_p=1/(R_oC)`,T`H(0)=${N(x.dc)},\quad f_p=${N(x.pole/(2*Math.PI))}\,Hz`),
 s('Solve the actual unity condition','A positive crossing exists only if gmRo>1. All allowed settings here satisfy that condition.',T`f_u=\frac1{2\pi C}\sqrt{g_m^2-R_o^{-2}},\quad f_{u,ideal}=g_m/(2\pi C)`,T`f_u=${N(x.unity/1e6)}\,MHz,\quad f_{u,ideal}=${N(x.ideal/1e6)}\,MHz`),
 s('Connect phase and bounded step to the same pole','The ideal integration phase is −90°. The leakage pole gives less lag and bounds the DC step response.',T`\angle H(j\omega)=-\tan^{-1}(\omega R_oC),\quad v_o(t)=g_mR_o(1-e^{-t/(R_oC)})\quad(v_{in}=1)`,T`\angle H(j2\pi f_u)=${N(x.phase)}^\circ,\quad\tau=${N(p.ro*p.cap*1e6)}\,\mu s`)
 ],[r('DC voltage gain',x.dc),r('Actual unity frequency',x.unity/1e6,'MHz'),r('Phase at unity',x.phase,'°')],[{...curve('Leakage bounds low-frequency gain','Frequency (Hz)','Magnitude (dB)',loggrid(f=>db(x.at(f)),100,1e9)),logX:true},curve('Zero initial voltage, normalized step','Time / RC','Output / DC gain',samples(u=>x.step(u*p.ro*p.cap)/x.dc,0,5))],
 'One KCL equation gives the state, transfer, phase and step response. Integration is useful above the leakage pole; finite DC gain prevents an indefinite ramp.',x.unity/1e6,'MHz','Calculate the actual unity frequency.','Use √(gm²−1/Ro²)/(2πC).',{schematic:integratorDrawing(p),table:{headers:['Quantity','Value','Unit'],rows:[['Leakage pole',fmt(x.pole/(2*Math.PI)),'Hz'],['Ideal unity',fmt(x.ideal),'Hz'],['Actual unity',fmt(x.unity),'Hz'],['Actual unity phase',fmt(x.phase),'degrees']]}})},[...symbols,[T`C,v_o,\omega_p,\tau,f_u`,'Output capacitance (F), output state (V), leakage-pole angular frequency (rad/s), RC time constant (s), and actual unity frequency (Hz).']]),
L('h2','A gm-C biquad: derive Q from the damping paths',[k('gm1','First transconductance',100e-6,20e-6,500e-6,'S'),k('gm2','Second transconductance',100e-6,20e-6,500e-6,'S'),k('ratio','C2 / C1 ratio',1,.5,2),k('q','Damping-control factor',1,.5,5),k('ro','Each node output resistance',1.5e6,2e5,1e7,'Ω')],
 'Does leakage increase or decrease Q in this topology?',
 'C1=10 pF stores v1. The first transconductor injects gm1(vin−v2) into C1; the second injects gm2v1 into C2. Damping gd=gm2/q and leakage go=1/Ro are explicit. States are x=[v1,v2]ᵀ, with v2 the output.',
 'Increase the damping-control factor toward five, then reduce Ro. Compare ideal and actual Q while retaining the same topology.',p=>{const x=gmBiquad(p);return O([
 s('Write both node equations','Signs follow current injected into each capacitor. Both initial voltages are zero for the step.',T`C_1\dot v_1=g_{m1}(v_{in}-v_2)-g_ov_1,\quad C_2\dot v_2=g_{m2}v_1-(g_d+g_o)v_2`,T`g_d=${N(x.gd*1e6)}\,\mu S,\quad g_o=${N(x.go*1e6)}\,\mu S`),
 s('Write the state equation in column order','Divide each current equation by its capacitance. B multiplies the input; it is not a stored state.',T`\dot x=Ax+Bv_{in},\quad A=\begin{bmatrix}-g_o/C_1&-g_{m1}/C_1\\g_{m2}/C_2&-(g_d+g_o)/C_2\end{bmatrix},\quad B=\begin{bmatrix}g_{m1}/C_1\\0\end{bmatrix}`,T`x(0)=\begin{bmatrix}0\\0\end{bmatrix},\quad C_2=${N(x.c2*1e12)}\,pF`),
 s('Eliminate the first state','Define λ1=go/C1 and λ2=(gd+go)/C2. Keep both leakage terms.',T`H(s)=\frac{b_0}{s^2+a_1s+a_0},\quad b_0=\frac{g_{m1}g_{m2}}{C_1C_2},\quad a_1=\lambda_1+\lambda_2,\quad a_0=b_0+\lambda_1\lambda_2`,T`a_1=${N(x.a[1])}\,s^{-1},\quad a_0=${N(x.a[2])}\,s^{-2},\quad H(0)=${N(x.dc)}`),
 s('Read natural frequency and Q','Natural frequency is √a0, not necessarily the −3 dB corner. Without leakage the stated topology has Q=q√(gm1C2/(gm2C1)).',T`\omega_n=\sqrt{a_0},\quad Q=\sqrt{a_0}/a_1,\quad Q_{ideal}=q\sqrt{g_{m1}C_2/(g_{m2}C_1)}`,T`f_n=${N(x.wn/(2*Math.PI)/1e6)}\,MHz,\quad Q=${N(x.Q)},\quad Q_{ideal}=${N(x.idealQ)},\quad\Delta Q=${N(100*(x.Q/x.idealQ-1))}\%`)
 ],[r('Actual natural frequency',x.wn/(2*Math.PI)/1e6,'MHz'),r('Actual Q',x.Q),r('Ideal Q',x.idealQ),r('DC gain',x.dc)],[{...curve('Actual two-state response','Frequency (Hz)','Magnitude (dB)',loggrid(f=>db(x.at(f)),1e3,1e8)),logX:true},curve('Both initial voltages are zero','Time (µs)','Unit-step output (V)',stateStep(x.A,x.B,1,1,15/x.a[1]).map(v=>({x:v.x*1e6,y:v.y})))],
 'Leakage increases both denominator coefficients. Their ratio determines whether Q rises or falls; it is not a universal finite-gain rule. The state and transfer routes must retain the same current paths.',x.Q,'','Calculate Q from the actual denominator.','Use √a0/a1.',{schematic:biquadDrawing(p),handover:filterHandover([{a:x.a,b:x.b}],'h2',x.wn/(2*Math.PI)),table:{headers:['Model','Natural frequency (MHz)','Q','DC gain'],rows:[['No leakage',fmt(x.ideal/(2*Math.PI)/1e6),fmt(x.idealQ),1],['Finite Ro',fmt(x.wn/(2*Math.PI)/1e6),fmt(x.Q),fmt(x.dc)]]}})},[...symbols,[T`q,\lambda_1,\lambda_2,a_0,a_1,b_0,x(0)`,'Damping control, diagonal decay rates (s⁻¹), constant/linear denominator coefficients (s⁻² and s⁻¹), numerator coefficient (s⁻²), and initial state.']]),
]
INTEGRATED_FILTER_LESSONS.push(
L('h3','Tune a master, then measure the slave that remains',[k('spread','Common process half-range',.2,0,.4),k('mismatch','Local gm and C mismatch half-range',.01,0,.05),k('max','Maximum tuning command',2,1.1,3),k('seed','Process ensemble seed',7,1,999,'',1)],
 'Which errors does a master tuning loop remove, and which does it never observe?',
 'Normalize desired gm/C to one. Common capacitance factor c, common gm factor g and active-RC resistance factor r are independent uniform draws in [1−p,1+p]. Separate local slave gm and C factors vary in [1−m,1+m]. The master senses only ug/c, not those slave mismatches.',
 'Set local mismatch to zero with a wide tuning range. Then restrict the range or restore mismatch, and identify why residual frequency error returns.',p=>{const x=tuning(p);return O([
 s('Use reciprocal component laws before quoting a spread','The exact uncalibrated gm-C ratio is g/c. The RC frequency ratio is 1/(rc), not a linear subtraction except for small perturbations. Uniform half-ranges here are not Gaussian standard deviations.',T`r_{gmC}=g/c,\quad r_{RC}=1/(rc),\quad c,g,r\sim\mathcal U(1-p,1+p)`,T`p=${N(p.spread)},\quad c_{example}=${N(x.c)},\quad g_{example}=${N(x.g)}`),
 s('Define the actual calibration iteration','The command starts at one and is bounded below by 0.5. Update it using the measured normalized master frequency; 128 iterations are used for each ensemble member.',T`u_0=1,\quad u_{k+1}=\operatorname{clip}[u_k+\mu(1-u_kg/c),0.5,u_{max}],\quad\mu=0.5`,T`u_{needed}=c/g=${N(x.needed)},\quad u_{128}=${N(x.command)}`),
 s('Check convergence and command availability','Before clipping, command error multiplies by 1−μg/c on each iteration. Its magnitude is below one throughout the stated range. A limited command cannot reach an unavailable target.',T`e_{k+1}=(1-\mu g/c)e_k,\quad e_k=u_k-c/g`,T`1-\mu g/c=${N(1-.5*x.g/x.c)},\quad N_{clipped}=${x.clipped}\quad\text{of 512}`),
 s('Propagate local mismatch into the slave','Local gm factor dg and capacitance factor dc are not seen by the master. Even if ug/c=1 exactly, the slave retains dg/dc.',T`r_{slave}=\frac{ug\,d_g}{c\,d_c},\quad d_g,d_c\sim\mathcal U(1-m,1+m)`,T`m=${N(p.mismatch)},\quad\overline r_{slave}=${N(x.tuned.mean)},\quad s_r=${N(x.tuned.sd)}`),
 s('Report bias and spread instead of promising perfect tuning','Compare the same 512 process members before and after calibration. RMS error from the target includes both bias and spread; sample standard deviation only measures spread around the sample mean.',T`E_{rms}=\sqrt{\frac1M\sum_i(r_i-1)^2},\quad M=512`,T`E_{before}=${N(x.raw.rms*100)}\%,\quad E_{after}=${N(x.tuned.rms*100)}\%`)
 ],[r('Uncalibrated RMS frequency error',x.raw.rms*100,'%'),r('Tuned slave RMS error',x.tuned.rms*100,'%'),r('Commands outside available range',x.clipped,'of 512')],[curve('Calibration of the c-high, g-low example','Iteration','Master frequency / target',x.history),{label:'Same process members before and after tuning',xLabel:'Ensemble member',yLabel:'Frequency / target',traces:[{label:'Before',points:x.before.slice(0,128).map((y,x)=>({x,y}))},{label:'Tuned slave',points:x.after.slice(0,128).map((y,x)=>({x,y}))}]}],
 'Master tuning cancels measured common variation when command range permits. It cannot cancel unobserved slave mismatch. Finite-resolution control, reference noise and calibration measurement noise would add further error.',x.tuned.rms*100,'%','Calculate RMS slave frequency error from the target across the ensemble.','Use √mean[(r−1)²], then multiply by 100.',{table:{headers:['Frequency model','Mean ratio','Sample SD (%)','RMS target error (%)'],rows:[['Uncalibrated gm-C',x.raw],['Tuned gm-C slave',x.tuned],['Uncalibrated active RC',x.activeRC]].map(([name,a])=>[name,fmt(a.mean),fmt(a.sd*100),fmt(a.rms*100)])}})},[[T`c,g,r,p,m,d_g,d_c`,'Common capacitance, gm and resistance factors, their uniform fractional half-range p, local mismatch half-range m, and separate slave gm/capacitance factors. All are dimensionless.'],[T`u_k,u_{max},\mu,e_k,r_{slave},M,E_{rms},s_r`,'Calibration command at iteration k, upper limit, update gain 0.5, command error, slave frequency ratio, ensemble count 512, RMS target error, and sample standard deviation.']]),
L('h4','An LC ladder and its integrator realization',[k('element','Varied component index',0,0,3,'',1),k('error','Selected fractional component error',.1,-.2,.2)],
 'Which sensitivities survive when an LC ladder is represented by integrator states?',
 'Start with a fourth-order Butterworth ladder at 1 MHz: series L1, shunt C2, series L3, shunt C4, with equal source/load resistance R. Normalize inductor currents as R·i, keep capacitor voltages as states, and normalize output as 2v4 so DC gain is one. A two-biquad cascade has the same nominal transfer.',
 'Choose index 0–3: L1/C2/L3/C4 in the ladder, or the corresponding first/second/third/fourth integrating capacitor in the cascade. These are declared component-error models; equal percentages do not mean every fabrication technology has equal sensitivity.',p=>{const x=ladder(p);return O([
 s('Normalize the physical LC prototype','Use g=[0.765367,1.847759,1.847759,0.765367]. Physical values are L=gR/ω0 and C=g/(Rω0). A component error scales the matching g value by 1+ε.',T`x=[Ri_1,v_2,Ri_3,v_4]^T,\quad g_i'=g_i(1+\epsilon_i),\quad y=2x_4`,T`f_0=1\,MHz,\quad\epsilon_{${p.element+1}}=${N(p.error)},\quad x(0)=0`),
 s('Replace each energy-storage equation by an integrator','These equations include both terminations. Scaling states changes their units, not the transfer. An ideal gm-C state implementation must reproduce these coefficients.',T`\dot x=\omega_0\begin{bmatrix}(-x_1-x_2+v_{in})/g_1'\\(x_1-x_3)/g_2'\\(x_2-x_4)/g_3'\\(x_3-x_4)/g_4'\end{bmatrix}`,T`H(s)=2[0,0,0,1](sI-A)^{-1}B`),
 s('State the equal-response cascade comparison','At nominal values the two unity-DC-gain sections have Q=0.541196 and 1.306563. Each section obeys t1·ż1=ω0(vin−z1/Q−z2), t2·ż2=ω0z1; the four varied factors represent its four capacitor time constants.',T`H_0(s)=\prod_{Q\in\{0.541196,1.306563\}}\frac{\omega_0^2}{s^2+(\omega_0/Q)s+\omega_0^2}`,T`f_{-3dB,ladder}=${N(x.cutoff/1e6)}\,MHz,\quad f_{-3dB,cascade}=${N(x.cascadeCutoff/1e6)}\,MHz`),
 s('Define a local sensitivity with an independent perturbation','For the table, perturb each nominal component by ±0.01%. The selected large perturbation is used only in the plots and response-error readings. Frequency sensitivity is dimensionless; the gain sensitivity is dB per percentage point at 0.5f0.',T`S_i^{f}=\frac{\ln f_c(p_i(1+h))-\ln f_c(p_i(1-h))}{\ln(1+h)-\ln(1-h)},\quad h=10^{-4}`,T`S_{${p.element+1},ladder}^{f}=${N(x.sensitivity[p.element].ladder)},\quad S_{${p.element+1},cascade}^{f}=${N(x.sensitivity[p.element].cascade)}`),
 s('Measure the specified passband error without claiming a universal ranking','Report the maximum absolute dB difference from nominal on a 101-point grid from DC to 0.8f0. The Butterworth prototype has no designed ripple. Other metrics, perturbations and implementation parasitics can change which realization performs better.',T`E_B=\max_{f\in\mathcal G}|20\log_{10}|H(f)|-20\log_{10}|H_0(f)||`,T`E_{B,ladder}=${N(x.ladderError)}\,dB,\quad E_{B,cascade}=${N(x.cascadeError)}\,dB`)
 ],[r('Ladder half-power frequency',x.cutoff/1e6,'MHz'),r('Cascade half-power frequency',x.cascadeCutoff/1e6,'MHz'),r('Sampled ladder passband error',x.ladderError,'dB'),r('Sampled cascade passband error',x.cascadeError,'dB')],[{label:'Same nominal transfer, separately defined component errors',xLabel:'Frequency (Hz)',yLabel:'Magnitude (dB)',logX:true,traces:[{label:'Nominal fourth order',points:loggrid(f=>db(x.nominal.at(f)),1e4,1e7)},{label:'Perturbed ladder',points:loggrid(f=>db(x.actual.at(f)),1e4,1e7)},{label:'Perturbed cascade',points:loggrid(f=>db(x.cascade.at(f)),1e4,1e7)}]}],
 'The ladder-to-integrator state transformation preserves the ideal response. It does not guarantee the lowest sensitivity to every component or every error metric. Compare the specified derivatives and finite perturbation before drawing a design conclusion.',x.cutoff/1e6,'MHz','Find the perturbed ladder half-power frequency.','Solve |H|=|H(0)|/√2 using the full four-state response.',{schematic:ladderDrawing(x.factors),handover:filterHandover(ladderSections(x.factors),'h4'),table:{headers:['Index / ladder component','Ladder frequency S','Cascade frequency S','Ladder dB/% at 0.5f0','Cascade dB/% at 0.5f0'],rows:x.sensitivity.map(a=>[`${a.i}: ${['L1','C2','L3','C4'][a.i]}`,fmt(a.ladder),fmt(a.cascade),fmt(a.ladderDb),fmt(a.cascadeDb)])}})},[...symbols,[T`R,i_1,i_3,x,g_i,\epsilon_i,\omega_0,z_1,z_2,t_1,t_2`,'Equal termination resistance (Ω), inductor currents (A), four normalized voltage states (V), normalized prototype values, fractional component errors, nominal angular frequency (rad/s), cascade states (V), and dimensionless capacitor/time-constant factors.'],[T`f_c,S_i^f,h,\mathcal G,E_B,I`,'Half-power frequency (Hz), logarithmic component sensitivity, small perturbation fraction, stated frequency grid, maximum sampled dB error, and identity matrix.']])
)
