import {bilinear} from '@ee-labs/systems'
import {solveComplex,complex,expm,matVecMul,charPoly,rootsOf} from '@ee-labs/network'
const {cabs,carg,cdiv}=complex
export const loggrid=(fn,lo,hi,n=181)=>Array.from({length:n},(_,i)=>{const x=lo*(hi/lo)**(i/(n-1));return{x,y:fn(x)}})
export const db=z=>20*Math.log10(Math.max(1e-30,cabs(z)))
const R=(id,a,b,value)=>({type:'R',id,nodes:[a,b],value}),C=(id,a,b,value)=>({type:'C',id,nodes:[a,b],value}),G=(id,a,b,p,m,gain)=>({type:'VCCS',id,nodes:[a,b],ctrl:[p,m],gain}),V={type:'V',id:'V1',nodes:['in','gnd'],value:1}
export function gmIntegrator({gm=100e-6,cap=10e-12,ro=1.5e6}={}){const pole=1/(ro*cap),w=gm/cap,dc=gm*ro,unity=dc>1?Math.sqrt(w*w-pole*pole)/(2*Math.PI):null,at=f=>cdiv([gm,0],[1/ro,2*Math.PI*f*cap]);return{gm,cap,ro,pole,w,dc,unity,ideal:w/(2*Math.PI),phase:unity?carg(at(unity))*180/Math.PI:null,at,step:t=>dc*(-Math.expm1(-pole*t)),net:{elements:[V,G('G1','gnd','out','in','gnd',gm),R('Ro','out','gnd',ro),C('C1','out','gnd',cap)]},tf:{b:[w],a:[1,pole]}}}
export function gmBiquad({gm1=100e-6,gm2=100e-6,ratio=1,q=1,ro=1.5e6}={}){const c1=10e-12,c2=c1*ratio,go=1/ro,gd=gm2/q,l1=go/c1,l2=(gd+go)/c2,a=[1,l1+l2,l1*l2+gm1*gm2/(c1*c2)],b=[gm1*gm2/(c1*c2)],wn=Math.sqrt(a[2]),Q=wn/a[1],ideal=Math.sqrt(gm1*gm2/(c1*c2)),idealQ=q*Math.sqrt(gm1*c2/(gm2*c1)),at=f=>cdiv([b[0],0],[a[2]-(2*Math.PI*f)**2,a[1]*2*Math.PI*f]),A=[[-l1,-gm1/c1],[gm2/c2,-l2]],B=[gm1/c1,0],net={elements:[V,C('C1','v1','gnd',c1),C('C2','out','gnd',c2),G('GI','gnd','v1','in','gnd',gm1),G('GF','v1','gnd','out','gnd',gm1),G('G2','gnd','out','v1','gnd',gm2),R('Rd','out','gnd',1/gd),R('Ro1','v1','gnd',ro),R('Ro2','out','gnd',ro)]};return{c1,c2,go,gd,l1,l2,a,b,wn,Q,ideal,idealQ,dc:b[0]/a[2],at,A,B,net}}
export function stateAt(A,B,f){return solveComplex(A.map((row,i)=>row.map((v,j)=>[-v,i===j?2*Math.PI*f:0])),B.map(v=>[v,0]))}
export function stateStep(A,B,output,scale,end,n=201){const aug=A.map((row,i)=>[...row,B[i]]);aug.push(Array(A.length+1).fill(0));const dt=end/(n-1),E=expm(aug.map(row=>row.map(v=>v*dt)));let x=[...Array(A.length).fill(0),1];const points=[];for(let i=0;i<n;i++){points.push({x:i*dt,y:scale*x[output]});x=matVecMul(E,x)}return points}
function rng(seed){let x=seed>>>0;return()=>{x=(1664525*x+1013904223)>>>0;return(x+.5)/4294967296}}
const stats=a=>{const mean=a.reduce((s,x)=>s+x,0)/a.length;return{mean,sd:Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/(a.length-1)),rms:Math.sqrt(a.reduce((s,x)=>s+(x-1)**2,0)/a.length),min:Math.min(...a),max:Math.max(...a)}}
export function tuneCommand(c,g,max=2){let u=1;for(let n=0;n<128;n++)u=Math.max(.5,Math.min(max,u+.5*(1-u*g/c)));return u}
export function tuning({spread=.2,mismatch=.01,max=2,seed=7}={}){const u=rng(seed),before=[],after=[],rc=[];let clipped=0;for(let i=0;i<512;i++){const c=1+spread*(2*u()-1),g=1+spread*(2*u()-1),r=1+spread*(2*u()-1),cg=1+mismatch*(2*u()-1),gg=1+mismatch*(2*u()-1),cmd=tuneCommand(c,g,max);before.push(g*gg/(c*cg));after.push(cmd*g*gg/(c*cg));rc.push(1/(r*c));if(c/g<.5||c/g>max)clipped++}const c=1+spread,g=1-spread,history=[];let cmd=1;for(let i=0;i<31;i++){history.push({x:i,y:cmd*g/c});cmd=Math.max(.5,Math.min(max,cmd+.5*(1-cmd*g/c)))}return{before,after,rc,raw:stats(before),tuned:stats(after),activeRC:stats(rc),clipped,history,c,g,command:tuneCommand(c,g,max),needed:c/g}}
const proto=[.7653668647301795,1.8477590650225735,1.8477590650225735,.7653668647301795],Qs=[.541196100146197,1.306562964876377]
export function ladderState(factors=[1,1,1,1],frequency=1e6){const w=2*Math.PI*frequency,g=proto.map((v,i)=>v*factors[i]),A=[[-w/g[0],-w/g[0],0,0],[w/g[1],0,-w/g[1],0],[0,w/g[2],0,-w/g[2]],[0,0,w/g[3],-w/g[3]]],B=[w/g[0],0,0,0];return{A,B,at:f=>stateAt(A,B,f)[3].map(v=>2*v),g}}
export function cascadeState(factors=[1,1,1,1],frequency=1e6){const w=2*Math.PI*frequency,[a,b,c,d]=factors,A=[[-w/(Qs[0]*a),-w/a,0,0],[w/b,0,0,0],[0,w/c,-w/(Qs[1]*c),-w/c],[0,0,w/d,0]],B=[w/a,0,0,0];return{A,B,at:f=>stateAt(A,B,f)[3],Qs}}
export function halfPower(at,frequency=1e6){const target=cabs(at(0))/Math.SQRT2;let lo=frequency*.05,hi=frequency*10;for(let n=0;n<50;n++){const f=Math.sqrt(lo*hi);if(cabs(at(f))>target)lo=f;else hi=f}return Math.sqrt(lo*hi)}
export function ladder({element=0,error=.1}={}){const factors=[1,1,1,1];factors[element]=1+error;const actual=ladderState(factors),cascade=cascadeState(factors),nominal=ladderState(),cutoff=halfPower(actual.at),cascadeCutoff=halfPower(cascade.at),sensitivity=[];for(let i=0;i<4;i++){const plus=[1,1,1,1],minus=[1,1,1,1];plus[i]+=1e-4;minus[i]-=1e-4;const row={i};for(const [key,make] of [['ladder',ladderState],['cascade',cascadeState]]){const a=make(plus),b=make(minus);row[key]=(Math.log(halfPower(a.at))-Math.log(halfPower(b.at)))/(Math.log(1.0001)-Math.log(.9999));row[key+'Db']=(db(a.at(5e5))-db(b.at(5e5)))/.02}sensitivity.push(row)}const frequencies=Array.from({length:101},(_,i)=>i*8000),deviation=at=>Math.max(...frequencies.map(f=>Math.abs(db(at(f))-db(nominal.at(f)))));return{actual,cascade,nominal,cutoff,cascadeCutoff,sensitivity,ladderError:deviation(actual.at),cascadeError:deviation(cascade.at),factors}}
export function integratorDrawing(p={}){const x=gmIntegrator(p);return{elements:x.net.elements,caption:'G1 injects gm·vin into the output node. Ro models finite transconductor output resistance; C1 stores the output state. This is a linear OTA output model, not a transistor-level OTA.',layout:{w:480,h:230,items:[{el:'V1',x:45,y:105,dir:'v'},{gnd:[45,125]},{node:'in',x:45,y:65,side:'t'},{wire:[45,65,45,85]},{el:'G1',x:170,y:105,dir:'v',flip:true},{gnd:[170,125]},{wire:[170,85,170,45]},{wire:[170,45,380,45]},{node:'out',x:295,y:45,side:'t'},{wire:[280,45,280,85]},{el:'Ro',x:280,y:105,dir:'v'},{gnd:[280,125]},{wire:[380,45,380,85]},{el:'C1',x:380,y:105,dir:'v'},{gnd:[380,125]},{text:'Control current: gm × vin',x:170,y:200}]}}}
export function filterHandover(sections,id,frequency=1e6){const scale=1000,rate=192000,blocks=sections.map(tf=>{const degree=tf.a.length-1,a=tf.a.map((v,i)=>v/scale**i),b=tf.b.map((v,i)=>v/scale**(degree-(tf.b.length-1)+i)),d=bilinear({a,b},rate),bb=[...d.b,0,0].slice(0,3);return{type:'biquad',params:[...bb,d.a[1]??0,d.a[2]??0]}});return{app:'signal-lab',label:'Explore a time-scaled digital copy in Signal Lab',patch:{rate,blocks,sources:[{type:'sine',freq:frequency/scale/4,amp:.1}],zoom:frequency/scale*4,from:{app:'analog-ic-lab',id,label:'Integrated filter: scaled bilinear copy'}},note:'All analog frequencies are divided by 1000 to fit Signal Lab’s sample rate, then each full second-order section is mapped by s=2fs(1−z⁻¹)/(1+z⁻¹). The digital response agrees at the corresponding warped frequency; this is not a same-hertz continuous-time circuit.'}}
export function ladderSections(factors=[1,1,1,1]){const x=ladderState(factors,1/(2*Math.PI)),poles=rootsOf(charPoly(x.A)),pairs=poles.filter(z=>z[1]>1e-7).map(([re,im])=>[1,-2*re,re*re+im*im]),real=poles.filter(z=>Math.abs(z[1])<=1e-7).map(z=>z[0]).sort((a,b)=>a-b);for(let i=0;i<real.length;i+=2)pairs.push([1,-real[i]-real[i+1],real[i]*real[i+1]]);const w=2*Math.PI*1e6;return pairs.map(a=>({a:[1,a[1]*w,a[2]*w*w],b:[a[2]*w*w]}))}
export function ladderNet(factors=[1,1,1,1],frequency=1e6){const w=2*Math.PI*frequency,Rt=1000,g=proto.map((v,i)=>v*factors[i]);return{elements:[V,R('RS','in','a',Rt),{type:'L',id:'L1',nodes:['a','v2'],value:g[0]*Rt/w},C('C2','v2','gnd',g[1]/(Rt*w)),{type:'L',id:'L3',nodes:['v2','out'],value:g[2]*Rt/w},C('C4','out','gnd',g[3]/(Rt*w)),R('RL','out','gnd',Rt)]}}
export function ladderDrawing(factors){return{elements:ladderNet(factors).elements,caption:'The physical LC prototype has 1 kΩ source and load terminations. The four-state equations preserve these paths. Plots normalize the physical output voltage by a factor of two to give unity DC gain.',layout:{w:720,h:260,items:[{el:'V1',x:45,y:160,dir:'v'},{gnd:[45,180]},{wire:[45,140,45,65]},{wire:[45,65,110,65]},{el:'RS',x:130,y:65,dir:'h'},{wire:[150,65,220,65]},{el:'L1',x:240,y:65,dir:'h'},{wire:[260,65,390,65]},{node:'v2',x:305,y:65,side:'t'},{wire:[305,65,305,140]},{el:'C2',x:305,y:160,dir:'v'},{gnd:[305,180]},{el:'L3',x:410,y:65,dir:'h'},{wire:[430,65,640,65]},{node:'out',x:515,y:65,side:'t'},{wire:[515,65,515,140]},{el:'C4',x:515,y:160,dir:'v'},{gnd:[515,180]},{wire:[640,65,640,140]},{el:'RL',x:640,y:160,dir:'v'},{gnd:[640,180]}]}}}
export function biquadDrawing(p){const x=gmBiquad(p),elements=x.net.elements.map(e=>({...e,...(e.id==='GI'?{label:'GI = gm1 × vin'}:e.id==='GF'?{label:'GF = gm1 × v2'}:e.id==='G2'?{label:'G2 = gm2 × v1'}:{})}));return{elements,caption:'Upper node v1: GI injects the input current, GF removes feedback current, and Ro1 leaks charge. Lower node v2: G2 injects gm2·v1 while Rd and Ro2 provide separate damping paths. Current-source control voltages are named beside each source.',layout:{w:900,h:460,items:[{el:'V1',x:45,y:115,dir:'v'},{gnd:[45,135]},{wire:[45,95,45,60]},{node:'in',x:45,y:60,side:'t'},...['GI','C1','Ro1','GF'].flatMap((id,i)=>{const a=150+i*190;return[{wire:[a,40,a,95]},{el:id,x:a,y:115,dir:'v',...(id==='GI'?{flip:true}:{})},{gnd:[a,135]}]}),{wire:[150,40,720,40]},{node:'v1',x:340,y:40,side:'t'},...['G2','C2','Rd','Ro2'].flatMap((id,i)=>{const a=150+i*190;return[{wire:[a,270,a,325]},{el:id,x:a,y:345,dir:'v',...(id==='G2'?{flip:true}:{})},{gnd:[a,365]}]}),{wire:[150,270,720,270]},{node:'v2',x:340,y:270,side:'t'}]}}}
