import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {pairNoise,flicker,budget,noiseDrawing,KB,GAMMA} from './noiseDesign.js'
const T=String.raw,gm=k('gm','Each input-device transconductance',200e-6,100e-6,1600e-6,'S'),ratio=k('ratio','Load / input transconductance ratio',.5,.05,1),temp=k('temp','Absolute temperature',300,250,400,'K')
const symbols=[[T`k_B,T,\gamma,g_m,g_{mL},r`,'Boltzmann constant 1.380649×10⁻²³ J/K, absolute temperature (K), channel thermal-noise factor 2/3, each input-device transconductance (S), each load-device transconductance (S), and ratio r=gmL/gm.'],[T`S_i,S_v,e_n,v_{n,rms},B`,'One-sided current-noise power density (A²/Hz), voltage-noise power density (V²/Hz), amplitude density √Sv (V/√Hz), RMS noise (V), and rectangular noise bandwidth (Hz). Independent source powers add.']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'I. Noise budgets, area and mismatch',knobs,question,intro,try:attempt,solve,symbols,flow:['Define each source and referral point','Add powers and integrate the stated band','Translate the noise target into current and geometry'],route:'Small-signal nodal equations give a transfer from each noise source to the output. Multiply each source power density by the squared transfer magnitude, then sum uncorrelated powers. Integrate over frequency for RMS noise. Statistical device mismatch is a separate static error.',limits:'Generic long-channel teaching process, uncorrelated channel thermal noise with γ=2/3, and explicitly declared flicker constants. No foundry PDK, measured production yield, layout parasitics or full amplifier noise certification is implied.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
export const NOISE_DESIGN_LESSONS=[
L('i1','Trace input-referred noise back to its devices',[gm,ratio,temp,k('gain','First-stage differential voltage gain',100,10,200)],
 'Which devices dominate the input-referred noise power?',
 'Use a symmetric differential equivalent: each branch has gm/2 signal transconductance and a noiseless output resistance R, giving differential gain A1=gmR. Two input devices and two active loads contribute independent channel current noise. An equivalent second-stage input noise is referred through A1.',
 'Reduce first-stage gain and watch the second-stage share grow. Change the load ratio while holding input gm fixed.',p=>{const x=pairNoise(p);return O([
 s('Define one physical device noise source','A long-channel device in saturation contributes one-sided drain-current noise 4kBTγgm. The noise-source gm is the physical device value, not the gm/2 signal coefficient in the differential equivalent.',T`S_{i,M}=4k_BT\gamma g_m`,T`S_{i,M}=${N(4*KB*p.temp*GAMMA*p.gm)}\,A^2/Hz`),
 s('Refer both input-device sources to the differential input','Each source sees R at one output; the differential signal gain is gmR. The R² factors cancel after dividing output power by signal-gain squared.',T`S_{v,in}=\frac{2(4k_BT\gamma g_m)R^2}{(g_mR)^2}=\frac{8k_BT\gamma}{g_m}`,T`S_{v,in}=${N(x.input)}\,V^2/Hz`),
 s('Add the two load devices in power','Their signal referral is still through the input gm. Changing load gm changes the noise numerator.',T`S_{v,L}=\frac{8k_BT\gamma g_{mL}}{g_m^2}=rS_{v,in}`,T`S_{v,L}=${N(x.load)}\,V^2/Hz,\quad e_{n,stage1}=\sqrt{S_{v,in}+S_{v,L}}=${N(x.first*1e9)}\,nV/\sqrt{Hz}`),
 s('Refer the second-stage noise through first-stage gain','Use gm2=500 µS and the same two-device equivalent noise law. Divide amplitude by A1, or power by A1².',T`S_{v,2\to in}=\frac{8k_BT\gamma}{g_{m2}A_1^2}`,T`S_{v,2\to in}=${N(x.second)}\,V^2/Hz,\quad A_1=${N(p.gain)}`),
 s('Sum powers before taking a square root','Each percentage is a share of total noise power. Amplitude densities themselves are not additive.',T`S_{total}=S_{v,in}+S_{v,L}+S_{v,2\to in},\quad e_n=\sqrt{S_{total}},\quad\eta_j=S_j/S_{total}`,T`e_n=${N(x.density*1e9)}\,nV/\sqrt{Hz},\quad\sum_j\eta_j=1`)
 ],[r('Total input-referred density',x.density*1e9,'nV/√Hz'),r('Input-device power share',x.shares[0]*100,'%'),r('Second-stage power share',x.shares[2]*100,'%')],[curve('First-stage gain suppresses referred second-stage noise','First-stage voltage gain','Total density (nV/√Hz)',samples(gain=>pairNoise({...p,gain}).density*1e9,10,200))],
 'A noise budget identifies where a change can help. This equivalent excludes noisy external resistors, flicker, correlations and frequency-dependent gain; those must be added for a complete circuit.',x.density*1e9,'nV/√Hz','Calculate the total input-referred amplitude density.','Add all three power densities, then take a square root.',{schematic:noiseDrawing(p),table:{headers:['Source group','Input-referred power (V²/Hz)','Share (%)'],rows:['Two input devices','Two active loads','Second-stage equivalent'].map((v,i)=>[v,fmt([x.input,x.load,x.second][i]),fmt(x.shares[i]*100)])}})}, {symbols:[...symbols,[T`R,A_1,g_{m2},\eta_j`,'Noiseless output resistance per branch (Ω), first-stage differential gain, second-stage equivalent device transconductance (S), and power fraction of source group j.']]}),
L('i2','Lower noise: specify what stays fixed',[gm,ratio,temp,k('gmid','Fixed transconductance efficiency',10,5,24,'V⁻¹')],
 'Does halving noise cost four times the current, or sixteen times?',
 'For fixed load/input gm ratio, the first-stage thermal power density varies as 1/gm. The current cost depends on the design constraint: preserving gm/ID while resizing devices differs from preserving device geometry in strong inversion. The same fourfold gm increase does not imply the same current in both cases.',
 'Set input gm to 800 µS. Compare the fixed-efficiency current with the fixed-geometry square-law ratio. Then reduce load ratio independently.',p=>{const x=pairNoise(p),gm0=200e-6,m=p.gm/gm0,id=p.gm/p.gmid,base=pairNoise({...p,gm:gm0});return O([
 s('Hold the load ratio fixed for a scaling comparison','This lesson uses the first stage only, so second-stage noise from I1 is excluded. Temperature and load ratio stay fixed along the plotted curve.',T`e_{n,1}^2=\frac{8k_BT\gamma(1+r)}{g_m}`,T`e_{n,1}=${N(x.first*1e9)}\,nV/\sqrt{Hz},\quad e_{n,0}=${N(base.first*1e9)}\,nV/\sqrt{Hz}`),
 s('Square the desired noise reduction','Because amplitude varies as 1/√gm, halving amplitude requires four times gm, not twice gm.',T`e_n/e_{n,0}=\sqrt{g_{m0}/g_m},\quad e_n=e_{n,0}/2\Rightarrow g_m=4g_{m0}`,T`g_m/g_{m0}=${N(m)},\quad e_n/e_{n,0}=${N(1/Math.sqrt(m))}`),
 s('At fixed efficiency, current and geometry scale together','η=gm/ID is held fixed, so inversion level is fixed. Increase W/L along with current; this costs area and capacitance.',T`I_D=g_m/\eta,\quad I_D/I_{D0}=g_m/g_{m0}\quad(\eta\text{ fixed})`,T`I_D=${N(p.gm)}/${N(p.gmid)}=${N(id*1e6)}\,\mu A\text{ per input device},\quad I_{tail}=2I_D`),
 s('At fixed geometry, strong-inversion scaling is different','For ID=βVOV²/2 and gm=βVOV, gm²=2βID. This comparison uses the square law and should not be extended into weak inversion.',T`I_D/I_{D0}=(g_m/g_{m0})^2\quad(\beta\text{ fixed}),\quad g_m\times4\Rightarrow I_D\times16`,T`I_D/I_{D0}=${N(m*m)}\quad\text{for the fixed-geometry comparison}`),
 s('Account for active-load tradeoffs','Lower load gm reduces its noise contribution, but real load current, inversion, compliance and output resistance must still satisfy the bias circuit.',T`S_{v,L}/S_{v,in}=r,\quad I_{tail}=2g_m/\eta`,T`r=${N(p.ratio)},\quad I_{tail}=${N(2*id*1e6)}\,\mu A`)
 ],[r('First-stage density',x.first*1e9,'nV/√Hz'),r('Each input-device current',id*1e6,'µA'),r('Input-pair tail current',2*id*1e6,'µA')],[curve('Thermal noise at fixed temperature and load ratio','Each input gm (µS)','First-stage density (nV/√Hz)',samples(g=>pairNoise({...p,gm:g*1e-6}).first*1e9,100,1600))],
 'State what remains fixed before quoting a noise-versus-power rule. Input-pair current is not total amplifier supply current, and reducing load gm is not free of headroom or speed tradeoffs.',id*1e6,'µA','Calculate current in each input device at the selected efficiency.','Use gm divided by gm/ID.',{table:{headers:['Comparison at selected gm','Current / baseline','What changes'],rows:[['Fixed gm/ID',fmt(m),'W/L, current and capacitance'],['Fixed geometry; square law',fmt(m*m),'Current and overdrive']]}})}, {symbols:[...symbols,[T`g_{m0},I_D,I_{D0},I_{tail},\eta,\beta,V_{OV}`,'Reference gm=200 µS, per-device drain current (A), baseline current (A), input-pair tail current (A), efficiency gm/ID (V⁻¹), square-law coefficient (A/V²), and overdrive (V).']]}),
L('i3','Flicker corner: distinguish area from bandwidth',[k('width','Device width',10,2,80,'µm'),k('length','Device length',1,.25,5,'µm'),gm,temp,k('low','Lower integration frequency',1,.1,100,'Hz'),k('high','Upper integration frequency',1e6,1000,1e6,'Hz')],
 'How does device area change the flicker corner and integrated noise?',
 'Analyze one MOS device referred to its own gate, rather than the loaded pair in I1. Use Sv(f)=4kBTγ/gm+Kf/(CoxWLf), with generic Kf=10⁻²⁵ V²F and Cox=8.63 fF/µm². The corner is where white and flicker powers are equal.',
 'Compare 10×1 µm with 40×2 µm at the same gm. Eight times the area lowers the corner eightfold, which is about 0.903 decade, not a full decade. Then vary the lower band edge.',p=>{const x=flicker(p);return O([
 s('Declare the noise convention and area units','Area is converted from µm² to m² before multiplying by Cox=8.63×10⁻³ F/m². Kf is a generic teaching coefficient, not a measured process value.',T`A=WL,\quad S_w=4k_BT\gamma/g_m,\quad K=K_f/(C_{ox}A)`,T`A=${N(x.area)}\,\mu m^2,\quad S_w=${N(x.white)}\,V^2/Hz,\quad K=${N(x.coefficient)}\,V^2`),
 s('Solve the equality of the two power densities','At the corner, total density is twice the white power, so amplitude is √2 times the white amplitude.',T`K/f_c=S_w\Rightarrow f_c=K/S_w`,T`f_c=${N(x.coefficient)}/${N(x.white)}=${N(x.corner/1000)}\,kHz`),
 s('Check the area scaling at fixed gm','Area scaling alone does not specify a realizable bias redesign. Holding gm means retuning bias/geometry as needed; capacitance and speed change too.',T`f_c\propto A^{-1}\quad(g_m,T\text{ fixed}),\quad\log_{10}8=${N(Math.log10(8))}`,T`f_c(8A)=f_c(A)/8=${N(x.corner/8000)}\,kHz`),
 s('Integrate power over a finite, positive band','A positive lower edge is essential: an ideal 1/f spectrum diverges at zero frequency. The bandwidth is rectangular and no additional transfer function is included.',T`v_{n,rms}^2=\int_{f_L}^{f_H}(S_w+K/f)\,df=S_w(f_H-f_L)+K\ln(f_H/f_L)`,T`P_w=${N(x.thermalPower)}\,V^2,\quad P_f=${N(x.flickerPower)}\,V^2`),
 s('Take the square root after summing both powers','A lower corner does not by itself state total RMS noise: the two band edges are needed.',T`v_{n,rms}=\sqrt{P_w+P_f}`,T`v_{n,rms}=${N(x.rms*1e6)}\,\mu V`)
 ],[r('Device area',x.area,'µm²'),r('Equal-power flicker corner',x.corner/1000,'kHz'),r('Integrated single-device noise',x.rms*1e6,'µV rms')],[{...curve('Single-device gate-referred noise density','Frequency (Hz)','Density (nV/√Hz)',Array.from({length:161},(_,i)=>{const f=p.low*(p.high/p.low)**(i/160);return{x:f,y:x.density(f)*1e9}})),logX:true,logY:true}],
 'Area lowers this model’s flicker contribution, while white noise is set by gm and temperature. Real process coefficients, capacitances and gain shaping are additional design inputs.',x.corner/1000,'kHz','Calculate the equal-power flicker corner.','Divide Kf/(CoxWL) by 4kBTγ/gm.',{table:{headers:['Noise term','Integrated power (V²)','Share (%)'],rows:[['White',fmt(x.thermalPower),fmt(100*x.thermalPower/x.rms**2)],['Flicker',fmt(x.flickerPower),fmt(100*x.flickerPower/x.rms**2)]]}})}, {symbols:[...symbols,[T`W,L,A,C_{ox},K_f,K,f_c,f_L,f_H,P_w,P_f`,'Width and length (m in equations), area (m²), oxide capacitance density (F/m²), flicker coefficient (V²F), area-normalized coefficient (V²), equal-power corner (Hz), integration edges (Hz), and integrated white/flicker powers (V²).']],sources:[['Analog Devices: understanding 1/f noise','https://www.analog.com/en/resources/analog-dialogue/articles/understanding-and-eliminating-1-f-noise.html']]}),
L('i4','Size an input pair from noise and mismatch budgets',[k('target','First-stage thermal density target',5e-9,3e-9,20e-9,'V/√Hz'),ratio,temp,k('gmid','Input transconductance efficiency',20,5,24,'V⁻¹'),k('length','Input channel length',1e-6,1e-6,5e-6,'m'),k('offsetLimit','Allowed one-sigma input offset',.2e-3,.1e-3,3e-3,'V')],
 'Can the same input devices meet both thermal-noise and mismatch targets?',
 'First solve the loaded-pair thermal-noise target for gm. Then use the consistent charge-based sizing law from Group A to obtain current, W/L, and area. Finally compare the independent pair-offset model against a one-sigma budget. These are two different error mechanisms.',
 'Compare gm/ID=20 and 10 at the same noise target. Increase length until the offset target also passes; the price includes more area and capacitance.',p=>{const x=budget(p),d=x.device;return O([
 s('Solve the thermal-noise inequality for minimum gm','This target covers the loaded first stage only, with the selected load ratio. It excludes the second stage, flicker and external resistors.',T`e_{target}^2\ge\frac{8k_BT\gamma(1+r)}{g_m}\Rightarrow g_{m,min}=\frac{8k_BT\gamma(1+r)}{e_{target}^2}`,T`g_{m,min}=${N(x.gm*1000)}\,mS`),
 s('Translate transconductance into current','The chosen efficiency must stay below 1/(nUT). Here n=1.5 and UT=25.852 mV define the 300 K sizing process; the noise-temperature knob changes noise only, not the sizing process parameters.',T`I_D=g_m/\eta,\quad I_{tail}=2I_D`,T`I_D=${N(d.id*1e6)}\,\mu A,\quad I_{tail}=${N(2*d.id*1e6)}\,\mu A`),
 s('Use the same charge law to obtain geometry','The charge-based model gives qs=1/(nUTη)−1, IC=qs(qs+1), and IS,square=2nµCoxUT². Thus W/L is set by current and inversion.',T`q_s=\frac1{nU_T\eta}-1,\quad IC=q_s(q_s+1),\quad W/L=I_D/(I_{S,\square}IC)`,T`IC=${N(d.ic)},\quad W/L=${N(d.ratio)},\quad W=${N(d.width*1e6)}\,\mu m,\quad A=${N(x.area)}\,\mu m^2`),
 s('Check mismatch independently of thermal noise','Use generic pair coefficients AVT=4 mV·µm and Aβ=0.01 µm. This first-order sigma is not a deterministic maximum or a yield estimate.',T`\sigma_{OS}^2=\frac{A_{VT}^2+(A_\beta/\eta)^2}{A},\quad A_{required}=\frac{A_{VT}^2+(A_\beta/\eta)^2}{\sigma_{limit}^2}`,T`\sigma_{OS}=${N(x.match.offset*1000)}\,mV,\quad A_{required}=${N(x.requiredArea)}\,\mu m^2`),
 s('Keep bandwidth and the design verdict explicit','A flat first-stage density over a 1 MHz rectangular band integrates to en√B. Increasing length at fixed W/L preserves the bias calculation but increases area and capacitance.',T`v_{n,rms}=e_{target}\sqrt{10^6},\quad\text{pass if }\sigma_{OS}\le\sigma_{limit}`,T`v_{n,rms}=${N(x.rms*1e6)}\,\mu V,\quad\sigma_{limit}=${N(p.offsetLimit*1000)}\,mV`)
 ],[r('Required input gm',x.gm*1000,'mS'),r('Each input-device current',d.id*1e6,'µA'),r('One-sigma input offset',x.match.offset*1000,'mV'),r('Each input-device area',x.area,'µm²')],[curve('Length improves mismatch at fixed W/L','Channel length (µm)','Offset sigma (mV)',samples(length=>budget({...p,length:length*1e-6}).match.offset*1000,1,5))],
 x.passes?'Both stated targets pass in these models. Total supply current, flicker noise, bandwidth, headroom and layout still need their own checks.':'The thermal target determines gm, but the selected geometry misses the offset-sigma target. Increase area and recheck the associated capacitance and speed.',d.id*1e6,'µA','Calculate drain current in each input device.','Divide required gm by the selected gm/ID.',{table:{headers:['Requirement','Calculated','Limit','Result'],rows:[['First-stage thermal density',`${fmt(p.target*1e9)} nV/√Hz`,`${fmt(p.target*1e9)} nV/√Hz`,'Met by sizing'],['Pair offset sigma',`${fmt(x.match.offset*1000)} mV`,`${fmt(p.offsetLimit*1000)} mV`,x.passes?'Pass':'Miss']]}})}, {symbols:[...symbols,[T`\eta,I_D,I_{tail},n,U_T,q_s,IC,I_{S,\square},\mu C_{ox}`,'Efficiency gm/ID (V⁻¹), input-device and tail currents (A), slope factor, fixed sizing thermal voltage (V), normalized charge and inversion coefficient, specific current per square (A), and process transconductance factor 200 µA/V².'],[T`W,L,A,A_{VT},A_\beta,\sigma_{OS},\sigma_{limit},e_{target}`,'Device width/length (m), per-device area (µm² in mismatch equation), pair coefficients (V·µm and µm), predicted and allowed offset sigma (V), and first-stage thermal amplitude-density target (V/√Hz).']]}),
]
