import {PROCESS,sizeFor,matching} from './models.js'
export const KB=1.380649e-23,GAMMA=2/3
export function pairNoise({gm=200e-6,ratio=.5,temp=300,gain=100,gm2=500e-6}={}){const input=8*KB*temp*GAMMA/gm,load=input*ratio,second=8*KB*temp*GAMMA/gm2/gain**2,total=input+load+second;return{gm,ratio,temp,gain,gm2,input,load,second,total,density:Math.sqrt(total),first:Math.sqrt(input+load),shares:[input,load,second].map(v=>v/total)}}
// Explicit differential signal model: each branch has gm/2 signal drive.
// Uncorrelated drain-current noises use each physical device's gm.
export function noiseNet(p={}){const x=pairNoise(p),R=x.gain/x.gm;return{elements:[{type:'V',id:'V1',nodes:['in','gnd'],value:1},{type:'VCCS',id:'G1',nodes:['gnd','p'],ctrl:['in','gnd'],gain:x.gm/2},{type:'VCCS',id:'G2',nodes:['n','gnd'],ctrl:['in','gnd'],gain:x.gm/2},{type:'R',id:'Rp',nodes:['p','gnd'],value:R},{type:'R',id:'Rn',nodes:['n','gnd'],value:R}],sources:[['M1','p',x.gm],['M2','n',x.gm],['M3','p',x.gm*x.ratio],['M4','n',x.gm*x.ratio]].map(([id,node,gm])=>({id,nodes:[node,'gnd'],psd:()=>4*KB*x.temp*GAMMA*gm}))}}
export function noiseDrawing(p={}){const net=noiseNet(p),wire=(...v)=>({wire:v}),gnd=(x,y)=>({gnd:[x,y]});return{elements:net.elements,caption:'Differential small-signal equivalent. G1 and G2 each have gm/2 signal transconductance. Rp and Rn represent noiseless output resistance. Independent M1–M4 channel noise is added analytically; supplies, bias and second stage are omitted.',layout:{w:700,h:230,items:[{el:'V1',x:60,y:130,dir:'v'},gnd(60,150),wire(60,110,60,65),{node:'in',x:60,y:65,labelPos:'t'},{el:'G1',x:220,y:130,dir:'v',flip:true},gnd(220,150),wire(220,110,220,65),wire(220,65,330,65),{node:'p',x:330,y:65,labelPos:'t'},wire(330,65,330,110),{el:'Rp',x:330,y:130,dir:'v'},gnd(330,150),{el:'G2',x:470,y:130,dir:'v'},gnd(470,150),wire(470,110,470,65),wire(470,65,580,65),{node:'n',x:580,y:65,labelPos:'t'},wire(580,65,580,110),{el:'Rn',x:580,y:130,dir:'v'},gnd(580,150)]}}}
export function flicker({width=10,length=1,gm=200e-6,temp=300,low=1,high=1e6}={}){const area=width*length,kf=1e-25,cox=PROCESS.cox,white=4*KB*temp*GAMMA/gm,coefficient=kf/(cox*area*1e-12),corner=coefficient/white,thermalPower=white*(high-low),flickerPower=coefficient*Math.log(high/low);return{area,kf,cox,white,coefficient,corner,thermalPower,flickerPower,rms:Math.sqrt(thermalPower+flickerPower),density:f=>Math.sqrt(white+coefficient/f)}}
export function budget({target=5e-9,ratio=.5,temp=300,gmid=20,length=1e-6,offsetLimit=1e-3}={}){const gm=8*KB*temp*GAMMA*(1+ratio)/target**2,device=sizeFor({gm,gmid,length}),area=device.area*1e12,match=area>=.25?matching({area,gmid}):null,requiredArea=(PROCESS.avt**2+(PROCESS.abeta/gmid)**2)/offsetLimit**2;return{gm,device,area,match,requiredArea,passes:!!match&&match.offset<=offsetLimit,rms:target*Math.sqrt(1e6)}}
