import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {VT,translinear,bipolar,mosPair,pairLimits,gilbert,vga} from './translinear.js'
const T=String.raw,source=['Analog Devices: Multiplier application guide','https://www.analog.com/media/en/training-seminars/design-handbooks/ADI_Multiplier_Applications_Guide.pdf']
const symbols=[[T`V_T,k_B,T,q,I_S,V_{BE}`,'Thermal voltage kBT/q=25.852 mV at 300 K, Boltzmann constant, temperature (K), elementary charge (C), saturation current (A), and base-emitter voltage (V).'],[T`I_1,I_2,I_3,I_4,I_{tail},v_d`,'Positive branch currents and pair tail current (A), and differential input voltage (V).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'G. Translinear circuits and multipliers',knobs,question,intro,try:attempt,solve,symbols,sources:[source],flow:['Start from the device current law','Derive the product or steering relation','Measure linearity, gain and unwanted output terms'],route:'Use nonlinear current laws and KVL for bias and multiplication. A small-signal tangent describes only a neighborhood of that point. Multiplication creates new frequencies, so a single-frequency phasor ratio cannot describe the whole output spectrum.',limits:'Matched forward-active exponential junctions at 300 K unless mismatch is explicitly varied. Base currents, Early effect, headroom and device dynamics are omitted; these are behavioral circuit relations, not a fabricated IC model.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
export const TRANSLINEAR_LESSONS=[
L('g1','KVL around junctions becomes a current product',[k('i1','Branch current I1',100e-6,1e-6,1e-3,'A'),k('i2','Branch current I2',50e-6,1e-6,1e-3,'A'),k('i3','Branch current I3',20e-6,1e-6,1e-3,'A'),k('mismatch','I4 saturation-current mismatch',0,-.05,.05)],
 'Which current products follow from the direction of the junctions around the loop?',
 'Specify the loop orientation before multiplying currents: VBE1+VBE3=VBE2+VBE4. Currents I1, I2 and I3 are imposed; the fourth junction adjusts to satisfy KVL. The positive-current controls span three decades.',
 'Double I1 or I3, then double I2. Predict how I4 changes. Add a 1% saturation-current mismatch to junction four and see why equal temperature alone is insufficient.',p=>{const x=translinear(p);return O([
 s('Name the exponential model and its domain','Use IC=IS exp(VBE/VT), which neglects the diode −1 term when IC≫IS and omits base current. All branches share temperature; IS=10⁻¹⁵ A except the explicit fourth-branch mismatch.',T`V_{BE,k}=V_T\ln(I_k/I_{S,k}),\quad V_T=k_BT/q`,T`V_T=${N(VT*1000)}\,mV,\quad I_{S,4}=10^{-15}(1+${N(p.mismatch)})\,A`),
 s('Write KVL with the specified junction orientation','Branches one and three contribute in one direction; branches two and four contribute in the opposite direction. Reversing the chosen pair changes the product equation.',T`V_{BE,1}+V_{BE,3}-V_{BE,2}-V_{BE,4}=0`,T`\ln\frac{I_1I_3}{I_{S,1}I_{S,3}}=\ln\frac{I_2I_4}{I_{S,2}I_{S,4}}`),
 s('Exponentiate and isolate the unknown current','Equal temperature cancels VT. Equal saturation currents cancel only in the matched case; keep the ratio visible when mismatch is enabled.',T`I_4=\frac{I_1I_3}{I_2}\frac{I_{S,2}I_{S,4}}{I_{S,1}I_{S,3}}`,T`I_4=\frac{${N(p.i1*1e6)}\cdot${N(p.i3*1e6)}}{${N(p.i2*1e6)}}(1+${N(p.mismatch)})=${N(x.i4*1e6)}\,\mu A`),
 s('Substitute back into voltage KVL','Compute all four logarithmic voltages, not merely the product a second time. A near-zero voltage residual confirms the loop orientation and current solution.',T`r_V=V_{BE,1}+V_{BE,3}-V_{BE,2}-V_{BE,4}`,T`r_V=${N(x.residual)}\,V,\quad I_{4,matched}=${N(x.ideal*1e6)}\,\mu A`)
 ],[r('Solved I4',x.i4*1e6,'µA'),r('Matched-law I4',x.ideal*1e6,'µA'),r('Current error from mismatch',x.error,'%')],[{...curve('Three decades of imposed current','I1 (A)','I4 (A)',Array.from({length:121},(_,i)=>{const i1=10**(-6+i/40);return{x:i1,y:translinear({...p,i1}).i4}})),logX:true,logY:true}],
 'The product relation is exact within the declared exponential model and loop orientation. Matching, temperature equality and adequate transistor headroom determine how closely a physical circuit follows it.',x.i4*1e6,'µA','Solve for the fourth current.','Multiply I1 by I3, divide by I2, then include the saturation-current ratio.',{table:{headers:['Junction','Current (µA)','VBE (V)'],rows:[p.i1,p.i2,p.i3,x.i4].map((i,k)=>[k+1,fmt(i*1e6),fmt(x.voltages[k])])}})}),
L('g2','Differential pairs: quantify the useful linear interval',[k('error','Allowed fractional gain compression',.01,.001,.1),k('overdrive','MOS zero-input overdrive',.2,.1,.4,'V')],
 'How far can each pair move before its nonlinear steering differs from its tangent?',
 'Compare a bipolar pair’s tanh law with a long-channel square-law MOS pair. Both use ideal fixed tail current. Normalize output as differential current divided by tail current, so their input ranges can be compared fairly.',
 'Compare 1% and 5% compression. Then double MOS overdrive. Distinguish a finite full-steering point from a bipolar pair that only approaches full steering asymptotically.',p=>{const x=pairLimits(p);return O([
 s('Write the bipolar law and its tangent','Matched exponential branches give an exact tanh steering law within the forward-active model. The derivative at zero is 1/(2VT).',T`\Delta I/I_{tail}=\tanh(v_d/(2V_T)),\quad (\Delta I/I_{tail})_{lin}=v_d/(2V_T)`,T`2V_T=${N(2*VT*1000)}\,mV`),
 s('Derive the MOS steering law from square-law branches','VOV is each branch’s overdrive at zero differential input. Tail-current conservation fixes the average overdrive as the input separates the branches.',T`\Delta I/I_{tail}=\frac{v_d}{V_{OV}}\sqrt{1-\frac{v_d^2}{4V_{OV}^2}},\quad |v_d|\le\sqrt2V_{OV}`,T`|v_{full,MOS}|=\sqrt2(${N(p.overdrive)})=${N(x.mosFull*1000)}\,mV`),
 s('Define compression relative to the small-signal tangent','Compression is one minus actual response divided by its tangent at the same nonzero input. Solve the bipolar equation numerically; the MOS equation can be inverted directly.',T`\epsilon_B=1-\tanh(u)/u,\quad u=v_d/(2V_T),\quad v_{MOS}=2V_{OV}\sqrt{1-(1-\epsilon)^2}`,T`\epsilon=${N(p.error)},\quad v_B=${N(x.bjt*1000)}\,mV,\quad v_{MOS}=${N(x.mos*1000)}\,mV`),
 s('Avoid inventing a finite bipolar full-steering voltage','Tanh approaches one only at infinite argument. Report a stated 99% steering level for the bipolar pair and the exact cutoff boundary of the ideal square-law MOS pair.',T`v_{99,B}=2V_T\operatorname{atanh}(0.99)`,T`v_{99,B}=${N(x.bjt99*1000)}\,mV,\quad v_{MOS}/v_B=${N(x.mos/x.bjt)}`)
 ],[r('Bipolar linearity limit',x.bjt*1000,'mV'),r('MOS linearity limit',x.mos*1000,'mV'),r('MOS full steering',x.mosFull*1000,'mV'),r('Bipolar 99% steering',x.bjt99*1000,'mV')],[{label:'Normalized current steering',xLabel:'Differential input (mV)',yLabel:'Differential / tail current',traces:[{label:'Bipolar',points:samples(v=>bipolar(v/1000),-500,500)},{label:'MOS square law',points:samples(v=>mosPair(v/1000,p.overdrive),-500,500)}]}],
 'A larger linear input range is a tradeoff, not a universal device advantage: the zero-input transconductance per tail current differs. This comparison excludes short-channel behavior and finite voltage headroom.',x.mos*1000,'mV','Calculate the MOS input limit for the selected compression.','Use 2VOV√[1−(1−ε)²].',{table:{headers:['Compression (%)','Bipolar limit (mV)','MOS limit (mV)'],rows:[.01,.05].map(error=>{const y=pairLimits({...p,error});return[error*100,fmt(y.bjt*1000),fmt(y.mos*1000)]})}})}, {symbols:[...symbols,[T`V_{OV},\Delta I,\epsilon,u`,'Each MOS branch’s zero-input overdrive (V), differential branch current (A), fractional compression from the tangent, and normalized bipolar input vd/(2VT).']]}),
L('g3','Gilbert cell: wanted sidebands and carrier leakage',[k('signal','Signal peak',.001,.0001,.02,'V'),k('lo','LO sine peak',.2,.01,.5,'V'),k('mismatch','Normalized branch imbalance',.01,0,.05),{...k('hard','Carrier drive model',1,0,1),options:['Finite tanh steering','Hard-switched limit']}],
 'Where do sum and difference tones come from, and what sets carrier feedthrough?',
 'Use a 1 kHz input and a 10 kHz carrier with a 1 mA tail and 1 kΩ differential transimpedance. A normalized imbalance adds a DC term before carrier steering, so its physical meaning is explicit.',
 'Set imbalance to zero, then 1%. Switch between hard commutation and finite LO drive. Increase signal amplitude to see the lower pair depart from its tangent.',p=>{const x=gilbert(p);return O([
 s('Write both steering operations','The lower pair converts the signal through tanh. The upper switching quad multiplies it by either tanh of the LO or the hard-switched sign limit. The imbalance δ is a fraction of tail current.',T`v_o=RI_{tail}[\tanh(v_s/(2V_T))+\delta]m(t)`,T`RI_{tail}=1\,V,\quad\delta=${N(p.mismatch)},\quad m(t)=${p.hard?T`\operatorname{sgn}(\sin\omega_Lt)`:T`\tanh(v_L/(2V_T))`}`),
 s('Use the carrier fundamental to derive conversion gain','A unit square wave has fundamental peak 4/π. Multiplying it by a sine gives one-half that coefficient in each first-order sideband. Higher odd carrier harmonics generate further tone pairs.',T`m(t)=\frac4\pi[\sin\omega_Lt+\tfrac13\sin3\omega_Lt+\cdots],\quad G_{conv,norm}=2/\pi`,T`2/\pi=${N(x.ideal)},\quad20\log_{10}(2/\pi)=${N(20*Math.log10(x.ideal))}\,dB`),
 s('Keep the signal-pair gain separate from normalized conversion','The small-signal voltage gain before commutation is RI_tail/(2VT). The 2/π factor is relative to that gain, not the total input-to-output voltage gain.',T`G_s=RI_{tail}/(2V_T),\quad V_{side,ideal}=(2/\pi)G_sV_s`,T`G_s=${N(x.signalGain)},\quad V_{side,ideal}=${N(x.ideal*x.signalGain*p.signal*1000)}\,mV`),
 s('Measure coherent output tones from the nonlinear waveform','Use 8192 midpoint samples over 4 ms, containing integer cycles of both inputs. Project the waveform onto sine and cosine at each tone; the reported amplitude is peak.',T`V_k=\frac2M\left|\sum_{n=0}^{M-1}v_o[n]e^{-j2\pi k(n+1/2)/M}\right|`,T`V_{9k}=${N(x.lower*1000)}\,mV,\quad V_{11k}=${N(x.upper*1000)}\,mV,\quad G_{conv,norm}=${N(x.conversion)}`),
 s('Trace imbalance into a carrier tone','The DC imbalance is multiplied by the carrier. In the hard limit, its fundamental is 4RI_tail δ/π; finite LO drive changes that coefficient.',T`V_{LO,hard}=4RI_{tail}|\delta|/\pi`,T`V_{LO,measured}=${N(x.feed*1000)}\,mV,\quad V_{LO,hard}=${N(x.expectedFeed*1000)}\,mV`)
 ],[r('Normalized conversion gain',x.conversion),r('Normalized conversion gain',x.conversionDb,'dB'),r('Lower sideband',x.lower*1000,'mV peak'),r('Carrier feedthrough',x.feed*1000,'mV peak')],[{...curve('Coherent output tones','Frequency (kHz)','Voltage (mV peak)',x.tones.map(p=>({x:p.x,y:p.y*1000}))),stems:true},curve('First carrier periods of the computed output','Time (µs)','Output (mV)',x.output.slice(0,500).map((y,n)=>({x:(n+.5)*4000/x.count,y:y*1000})))],
 'Hard carrier commutation gives the 2/π sideband factor only for a sufficiently linear signal pair. Finite LO drive, signal compression and imbalance are separate effects; inspect them one at a time.',x.lower*1000,'mV','Find the lower-sideband peak amplitude.','Use the coherent waveform projection; compare with (2/π)GsVs in the hard, small-signal limit.',{handover:{app:'signal-lab',label:'Compare an ideal sine multiplier in Signal Lab',patch:{rate:192000,sources:[{type:'sine',freq:1000,amp:x.signalGain*p.signal}],blocks:[{type:'ringmod',params:[10000]}],from:{app:'analog-ic-lab',id:'g3',label:'Linear sine-multiplier comparison'}},note:'This comparison uses the signal-pair tangent and a unit sine carrier: each sideband has gain Gs/2. It does not transfer the nonlinear tanh, hard switching, or imbalance. Compare its two tones with the Gilbert waveform here.'},table:{headers:['Tone (kHz)','Role','Peak voltage (mV)'],rows:[[9,'Difference',x.lower],[10,'Carrier leakage',x.feed],[11,'Sum',x.upper]].map(([f,role,v])=>[f,role,fmt(v*1000)])}})}, {symbols:[...symbols,[T`R,v_s,v_L,m(t),\delta,G_s,M,k`,'Differential transimpedance 1 kΩ, signal and carrier voltages (V), normalized carrier steering, fractional tail-current imbalance, signal-pair tangent gain, sample count 8192, and coherent tone-bin index.']]}),
L('g4','Current-ratio gain and a decibel-linear control law',[k('control','Control current',.001,.0001,.01,'A'),k('reference','Reference current',.001,.0005,.002,'A'),k('limit','Available control-path current',.005,.001,.01,'A')],
 'Why is exponential voltage control linear in decibels, and what clips that range?',
 'Use an ideal translinear current-ratio gain cell, iout/isignal=Icontrol/Ireference. Convert a control-junction voltage difference into that ratio, then add an explicit available-current limit.',
 'Compare 0.1 mA and 1 mA control at a 1 mA reference. Raise control above its available-current limit and distinguish the requested decibel gain from the delivered gain.',p=>{const x=vga(p);return O([
 s('State the current-ratio gain law','This is a current-gain cell with fixed reference current, not a lone differential pair with a bounded steering fraction. A current conveyor or translinear loop supplies the ratio.',T`G_i=i_{out}/i_{signal}=I_c/I_r`,T`G_{requested}=${N(p.control)}/${N(p.reference)}=${N(x.demand)}`),
 s('Subtract two exponential junction voltages','Equal saturation currents and temperature cancel in the voltage difference. Exponentiating recovers the current ratio.',T`\Delta V=V_T\ln(I_c/I_r),\quad G_{requested}=e^{\Delta V/V_T}`,T`\Delta V=${N(x.rawDelta*1000)}\,mV`),
 s('Convert amplitude gain to decibels','Use 20 log10 for a current amplitude ratio on the same reference basis. The slope is constant in dB per control volt before limiting.',T`G_{dB}=20\log_{10}G=\frac{20}{\ln10}\frac{\Delta V}{V_T}`,T`G_{dB,requested}=${N(x.idealDb)}\,dB,\quad\frac{dG_{dB}}{d\Delta V}=${N(20/(Math.log(10)*VT))}\,dB/V`),
 s('Apply the declared current availability before claiming range','The ideal exponential law can demand more current than the control path provides. The model clips control current at Imax; real compliance and signal swing add further limits.',T`G_{actual}=\min(I_c,I_{max})/I_r`,T`G_{actual}=${N(x.realized)},\quad G_{dB,actual}=${N(x.gainDb)}\,dB`)
 ],[r('Requested current gain',x.demand),r('Actual current gain',x.realized),r('Actual gain',x.gainDb,'dB'),r('Control voltage difference',x.rawDelta*1000,'mV')],[curve('The decibel line stops at the current limit','Control voltage difference (mV)','Actual gain (dB)',samples(v=>20*Math.log10(x.at(v/1000)),-100,100))],
 x.limited?'The requested gain exceeds the declared current availability. A linear decibel control law does not remove current or voltage-compliance limits.':'The control current is within the declared availability. A tenfold current ratio gives 20 dB; actual device mismatch, headroom and bandwidth remain separate design constraints.',x.gainDb,'dB','Calculate the actual gain in decibels.','Limit the current first, divide by the reference, then take 20 log10.',{table:{headers:['Control current (mA)','Requested gain (dB)','Delivered gain (dB)'],rows:[.0001,.001,.01].map(control=>{const y=vga({...p,control});return[control*1000,fmt(y.idealDb),fmt(y.gainDb)]})}})}, {symbols:[...symbols,[T`I_c,I_r,I_{max},G_i,\Delta V`,'Control, reference, and available current (A), current amplitude gain, and matched junction-voltage difference (V).']]})
]
