import {noiseFloorDbm,KT0_DBM_HZ} from '@ee-labs/rf'
import {systemBudget,chainSpectrum,phaseEnsemble,CUBIC_BACKOFF} from './budgetModels.js'
import {L,O,k,s,r,curve,samples,N,fmt,gain,band,table} from './lessonSupport.js'
export const NOISE_LINEARITY=[
L('b1','Thermal noise needs a bandwidth',[band],'What does −174 dBm/Hz become over a real channel?',
'The familiar thermal floor is a power density. A receiver integrates it over its noise-equivalent bandwidth, so a power in dBm must always carry a bandwidth.',
'Increase bandwidth tenfold. Predict the change before reading the result.',p=>{const power=1.380649e-23*290*p.bandwidth,floor=noiseFloorDbm(p.bandwidth);return O([
s('Start with the density','A matched 290 K source provides kT0 watts of available noise per hertz.',String.raw`N_0=kT_0`,String.raw`N_{0,dBm/Hz}=10\log_{10}(kT_0/10^{-3})=${N(KT0_DBM_HZ)}`),
s('Integrate the band','A rectangular equivalent noise bandwidth makes the integral a multiplication.',String.raw`N=N_0B=kT_0B`,String.raw`N=${N(power)}\,\mathrm W`),
s('Convert power to dBm','Bandwidth must be in hertz inside the numerical logarithm.',String.raw`N_{dBm}=N_{0,dBm/Hz}+10\log_{10}(B/1\,\mathrm{Hz})`,String.raw`N_{dBm}=${N(KT0_DBM_HZ)}+${N(10*Math.log10(p.bandwidth))}=${N(floor)}`)
],[r('Input thermal floor',floor,'dBm')],[curve('Bandwidth penalty','Bandwidth (MHz)','Thermal floor (dBm)',samples(B=>noiseFloorDbm(B*1e6),.01,20))],'Ten times the bandwidth raises integrated thermal power by 10 dB.',floor,'dBm','Calculate the integrated thermal floor.','Add 10 log10(B in Hz) to the density in dBm/Hz.') }),
L('b2','Friis and first-stage noise',[gain],'Which stage contributes the most input-referred added noise?',
'To compare noise added at different positions, refer each contribution back through all the gain before it. The sum is linear even though the final noise figure is reported in decibels.',
'Raise LNA gain and watch the later stages’ shares shrink.',p=>{const c=systemBudget(p);return O([
s('Undo the decibels','Compute each preceding gain product before summing noise factors.',String.raw`G_i=10^{G_{i,dB}/10},\quad F_i=10^{NF_i/10},\quad g_i=\prod_{j<i}G_j`),
s('Refer each stage to the input','The first one is the source’s own thermal noise. Each extra term is the stage’s added noise.',String.raw`F_{total}=1+\sum_i\frac{F_i-1}{g_i}`,String.raw`F_{total}=1+${c.blocks.map(b=>N(b.fTerm)).join('+')}=${N(c.f)}`),
s('Report the total and shares','Shares divide each excess-noise term by total excess, excluding the baseline one.',String.raw`NF=10\log_{10}F_{total},\quad share_i=\frac{(F_i-1)/g_i}{F_{total}-1}`,String.raw`NF=${N(c.nfDb)}\,\mathrm{dB}`)
],[r('Noise figure',c.nfDb,'dB')],[curve('Noise figure versus LNA gain','LNA gain (dB)','Cascade NF (dB)',samples(g=>systemBudget({gain:g}).nfDb,5,30))],'Gain ahead of a noisy block reduces its input-referred contribution. A noisy first block cannot be repaired by gain after it.',c.nfDb,'dB','Calculate the cascade noise figure.','Sum the displayed linear excess terms and the baseline one, then take 10 log10.',{table:table(c)}) }),
L('b3','Move the LNA before the filter',[k('first','LNA first (0: no, 1: yes)',0,0,1,'',1)],'What do you gain and lose by placing amplification before preselection?',
'Moving the LNA changes which gains precede every noise and distortion source. Total small-signal gain stays the same, but sensitivity and blocker tolerance change.',
'Toggle the LNA position and compare both budgets, not only noise figure.',p=>{const a=systemBudget(),b=systemBudget({first:1}),c=p.first?b:a;return O([
s('Check the unchanged total gain','Multiplying the same scalar stage gains in another order leaves the product unchanged.',String.raw`G_{total}=\prod_iG_i`,String.raw`G_{total,dB}=${N(c.gainDb)}`),
s('Recompute the noise terms in the new order','The LNA before the lossy filter shields the input-referred budget from part of the filter’s noise.',String.raw`F_{total}=1+\sum_i(F_i-1)/g_i`,String.raw`NF_{filter\ first}=${N(a.nfDb)},\quad NF_{LNA\ first}=${N(b.nfDb)}\quad\mathrm{dB}`),
s('Recompute distortion at the same input plane','Preselection loss previously attenuated blockers before they reached the LNA.',String.raw`\frac1{IIP3_{total}}=\sum_i\frac{g_i}{IIP3_i}`,String.raw`IIP3_{filter\ first}=${N(a.iip3Dbm)},\quad IIP3_{LNA\ first}=${N(b.iip3Dbm)}\quad\mathrm{dBm}`)
],[r('Selected noise figure',c.nfDb,'dB'),r('Selected input IP3',c.iip3Dbm,'dBm')],[],'Putting the LNA first improves the noise budget but exposes it to stronger out-of-band signals before filtering.',a.nfDb-b.nfDb,'dB','Calculate the noise-figure improvement from moving the LNA first.','Subtract the LNA-first NF from the filter-first NF.',{table:table(c)}) }),
L('b4','More gain has a cost',[gain],'Why can additional front-end gain improve sensitivity but reduce linearity?',
'More LNA gain suppresses later input-referred noise. It also sends larger signals into the mixer and IF stages, reducing their distortion headroom referred to the antenna.',
'Compare 15 dB and 25 dB LNA gain. Inspect the two trends on separate axes.',p=>{const c=systemBudget(p);return O([
s('Calculate the noise benefit','Following-stage noise is divided by preceding gain.',String.raw`F_{total}=1+\sum_i(F_i-1)/g_i`,String.raw`NF=${N(c.nfDb)}\,\mathrm{dB}`),
s('Calculate the distortion penalty','Following-stage reciprocal intercepts are multiplied by preceding gain.',String.raw`IIP3_{total}^{-1}=\sum_i g_i/IIP3_i`,String.raw`IIP3=${N(c.iip3Dbm)}\,\mathrm{dBm}`),
s('Compare two concrete settings','The signs matter: a lower NF helps, while a lower input intercept hurts.',String.raw`\Delta NF=NF_{25}-NF_{15},\quad\Delta IIP3=IIP3_{25}-IIP3_{15}`,String.raw`\Delta NF=${N(systemBudget({gain:25}).nfDb-systemBudget().nfDb)},\quad\Delta IIP3=${N(systemBudget({gain:25}).iip3Dbm-systemBudget().iip3Dbm)}\quad\mathrm{dB}`)
],[r('Noise figure',c.nfDb,'dB'),r('Input IP3',c.iip3Dbm,'dBm')],[curve('Noise benefit','LNA gain (dB)','NF (dB)',samples(g=>systemBudget({gain:g}).nfDb,5,30)),curve('Linearity cost','LNA gain (dB)','Input IP3 (dBm)',samples(g=>systemBudget({gain:g}).iip3Dbm,5,30))],'Gain is a design tradeoff across multiple requirements, not a quantity to maximize by itself.',c.iip3Dbm,'dBm','Calculate the input IP3 at the selected gain.','Use the reciprocal linear-power sum before converting to dBm.',{table:table(c)}) }),
L('b5','Sensitivity is a noise floor plus a requirement',[gain,band,k('snr','Required SNR',10,0,30,'dB')],'How weak a signal can this receiver accept under the stated criterion?',
'Sensitivity combines the input-referred receiver floor with the SNR required by the detector or demodulator. Required SNR is an input to this budget; modulation and coding determine its meaning.',
'Change required SNR independently of bandwidth and LNA gain.',p=>{const c=systemBudget(p);return O([
s('Find source noise in the channel','Use the equivalent noise bandwidth, not an unspecified spectrum width.',String.raw`N_{source,dBm}=10\log_{10}(kT_0B/10^{-3})`,String.raw`N_{source,dBm}=${N(noiseFloorDbm(p.bandwidth))}`),
s('Include the receiver’s SNR degradation','Noise figure raises the input-referred floor.',String.raw`N_{in,dBm}=N_{source,dBm}+NF`,String.raw`N_{in,dBm}=${N(c.floor)}`),
s('Add the detection requirement','This sum is an input signal power, not an output power.',String.raw`P_{min,dBm}=N_{in,dBm}+SNR_{required,dB}`,String.raw`P_{min,dBm}=${N(c.floor)}+${N(p.snr)}=${N(c.sensitivity)}`)
],[r('Input-referred floor',c.floor,'dBm'),r('Sensitivity',c.sensitivity,'dBm')],[curve('SNR requirement sets sensitivity','Required SNR (dB)','Sensitivity (dBm)',samples(snr=>c.floor+snr,0,30))],'A sensitivity specification is incomplete without bandwidth, receiver NF, and a detection criterion.',c.sensitivity,'dBm','Calculate the required input signal power.','Add the required SNR in dB to the input-referred noise floor.') }),
L('c1','Products that fall into the channel',[k('f1','First tone',100e6,80e6,120e6,'Hz'),k('spacing','Tone spacing',1e6,.1e6,5e6,'Hz'),k('width','Channel width',5e6,1e6,20e6,'Hz')],'Why are third-order products especially troublesome near a wanted signal?',
'A cubic response generates near-band intermodulation as well as far-away harmonics. The two products closest to the input pair are difficult to filter without also rejecting the wanted tones.',
'Widen tone spacing and watch the near-band pair leave the selected channel.',p=>{const f2=p.f1+p.spacing,center=(p.f1+f2)/2,products=[['Lower IM3',2*p.f1-f2],['Upper IM3',2*f2-p.f1],['Sum cubic 2f1 + f2',2*p.f1+f2],['Sum cubic 2f2 + f1',2*f2+p.f1]];return O([
s('Write the two-tone input','The same amplitude is applied to both tones; phase is zero for this example.',String.raw`x(t)=A\cos(2\pi f_1t)+A\cos(2\pi f_2t)`),
s('Expand the cubic term','Products with coefficients 2 and 1 produce both frequency sums and differences.',String.raw`y=a_1x+a_3x^3\Rightarrow 2f_1\pm f_2,\quad2f_2\pm f_1`,String.raw`f_{IM3,low}=${N((p.f1-p.spacing)/1e6)}\,\mathrm{MHz},\quad f_{IM3,high}=${N((p.f1+2*p.spacing)/1e6)}\,\mathrm{MHz}`),
s('Compare with channel boundaries','The channel is centred between the two tones.',String.raw`f_c=(f_1+f_2)/2,\quad |f_{product}-f_c|\le B/2`,String.raw`f_c=${N(center/1e6)}\,\mathrm{MHz},\quad B=${N(p.width/1e6)}\,\mathrm{MHz}`)
],[],[], 'A linear phasor model preserves input frequencies; the cubic model is needed to predict these new frequencies.',(p.f1-p.spacing)/1e6,'MHz','Calculate the lower third-order intermodulation frequency.','Use 2f1 − f2.',{table:{headers:['Product','Frequency (MHz)','Inside channel'],rows:products.map(([name,f])=>[name,f/1e6,Math.abs(f-center)<=p.width/2?'Yes':'No'])}}) },{symbols:[['f_1,f_2,f_c,B','Input frequencies, channel centre and channel width (Hz).'],['a_1,a_3,A','Linear gain, cubic coefficient and equal per-tone input amplitude.']]}),
L('c2','Extract IP3 from a measured spectrum',[gain,k('pin','Input per tone',-55,-65,-25,'dBm')],'Does the intercept inferred from the output FFT match the cascade budget?',
'Two coherent tones pass through every stage’s memoryless cubic law. The FFT measures the fundamental and near-band third-order product; their separation yields an extrapolated intercept.',
'Raise input drive in 5 dB steps. The inferred intercept is nearly constant only while the cubic weak-signal approximation holds.',p=>{const x=chainSpectrum(p);return O([
s('Measure powers at a common output plane','The FFT bins are coherent: fundamentals at 25 and 40, IM3 at 10 and 55. Each sinusoid’s peak voltage A gives power A²/(2·50 Ω).',String.raw`P=A_{pk}^2/(2R_0),\quad\Delta=P_{fund,dBm}-P_{IM3,dBm}`,String.raw`\Delta=${N(x.fundamental)}-(${N(x.im3)})=${N(x.gap)}\,\mathrm{dB}`),
s('Extrapolate the unequal slopes','The fundamental rises one dB per dB of input; weak third-order power rises three.',String.raw`OIP3=P_{fund}+\Delta/2,\quad IIP3_{est}=P_{in}+\Delta/2`,x.guard==='declined'?String.raw`\text{Intercept estimate declined: less than 3 dB backoff}`:String.raw`IIP3_{est}=${N(x.estimatedInputIp3)}\,\mathrm{dBm}`),
s('Compare with the small-signal budget','The difference should tend toward zero as input drive is reduced. It is not forced to zero by construction of the FFT.',String.raw`error=IIP3_{est}-IIP3_{budget}`,x.guard==='declined'?String.raw`\text{Reduce drive before comparing small-signal intercepts}`:String.raw`error=${N(x.estimatedInputIp3-x.budget.iip3Dbm)}\,\mathrm{dB}`)
],[...(x.guard==='declined'?[]:[r('FFT input IP3 estimate',x.estimatedInputIp3,'dBm')]),r('Budget input IP3',x.budget.iip3Dbm,'dBm')],[{...curve('Output FFT lines','Coherent frequency bin','Line power (dBm)',x.bins.map(b=>({x:b.bin,y:b.power}))),stems:true}],`Extrapolation status: ${x.guard}. The FFT includes higher-order products generated when cubic stages are cascaded.`,x.gap,'dB','Calculate the measured fundamental-to-IM3 power gap.','Subtract the measured IM3 power in dBm from the measured fundamental power in dBm.',{table:{headers:['FFT bin','Output power (dBm)'],rows:x.bins.map(b=>[b.bin,b.power])}}) }),
L('c3','Cascade intercepts at one reference plane',[gain],'Which stage dominates the chain’s third-order distortion?',
'A stage following gain reaches its own nonlinear limit at a lower antenna input power. Refer every reciprocal intercept back to the same chain input before summing.',
'Raise LNA gain and inspect the mixer’s share.',p=>{const c=systemBudget(p);return O([
s('Convert each intercept to linear power','The calculation uses milliwatts so its inverse terms have units of inverse milliwatts.',String.raw`A_i=10^{IIP3_{i,dBm}/10}\,\mathrm{mW}`),
s('Align the distortion amplitudes','The worst-case weak-cubic rule assumes all stage IM3 phasors align at the output.',String.raw`A_{total}^{-1}=\sum_i g_i/A_i`,String.raw`A_{total}^{-1}=${c.blocks.filter(b=>b.ip3Term).map(b=>N(b.ip3Term)).join('+')}\quad\mathrm{mW^{-1}}`),
s('Invert and calculate each share','Ideal passive blocks make no third-order product in this model, so their inverse-intercept contribution is zero.',String.raw`IIP3_{dBm}=10\log_{10}(A_{total}/1\,\mathrm{mW}),\quad share_i=\frac{g_i/A_i}{\sum_jg_j/A_j}`,String.raw`IIP3=${N(c.iip3Dbm)}\,\mathrm{dBm}`)
],[r('Input IP3',c.iip3Dbm,'dBm'),r('Output IP3',c.oip3Dbm,'dBm')],[],'A later stage can dominate despite a higher stand-alone intercept, because preceding gain increases its drive.',c.iip3Dbm,'dBm','Calculate the cascade input IP3.','Invert the sum of reciprocal-power contributions before converting to dBm.',{table:table(c)}) }),
L('c4','Distortion phases change the answer',[gain,k('seed','Ensemble seed',42,1,1000,'',1),k('runs','Independent phase realizations',2000,500,10000,'',1)],'How does coherent worst-case distortion compare with random phases?',
'Stage distortion products are phasors. Their amplitudes add in the aligned worst case. Independent uniform phases have a known mean squared magnitude, but individual realizations can fall on either side of that mean.',
'Change the seed, then increase ensemble size. Compare the measured mean product power and its confidence interval with the analytic power sum.',p=>{const x=phaseEnsemble(p);return O([
s('Form each input-referred distortion amplitude','Use ai = preceding gain divided by stage intercept in milliwatts.',String.raw`a_i=g_i/A_i,\quad a_{total}=\left|\sum_i a_ie^{j\phi_i}\right|`),
s('Separate aligned and mean-power rules','For independent uniform phases the cross terms average to zero. This does not order every individual realization relative to the mean.',String.raw`a_{aligned}=\sum_i a_i,\quad\mathbb E[a_{total}^2]=\sum_i a_i^2`,String.raw`IIP3_{aligned}=${N(x.aligned)},\quad IIP3_{power}=${N(x.power)}\quad\mathrm{dBm}`),
s('Check a seeded ensemble with uncertainty','The mean squared amplitude has an approximate 95% confidence interval. A median intercept is a different statistic from an intercept derived from mean power.',String.raw`\overline{a^2}=\frac1M\sum_{m=1}^M a_m^2`,String.raw`\overline{a^2}=${N(x.estimate.value)},\quad95\%\ CI=[${N(x.estimate.ci[0])},${N(x.estimate.ci[1])}]`)
],[r('Aligned worst-case IP3',x.aligned,'dBm'),r('Mean-power equivalent IP3',x.power,'dBm'),r('Sample median IP3',x.median,'dBm')],[curve('Random-phase intercept distribution','Sorted percentile (%)','Input IP3 (dBm)',x.intercepts.filter((_,i)=>i%Math.ceil(p.runs/200)===0).map((v,i)=>({x:100*i*Math.ceil(p.runs/200)/(p.runs-1),y:v})))],`The central 90% sample interval is ${fmt(x.p05)} to ${fmt(x.p95)} dBm. A particular random-phase result need not exceed the mean-power equivalent intercept.`,x.expected,'mW⁻²','Calculate the expected squared distortion amplitude from the stage terms.','Sum the squares of the input-referred amplitudes; do not square their sum.',{table:{headers:['Quantity','Squared amplitude (mW⁻²)'],rows:[['Analytic expectation',x.expected],['Measured mean',x.estimate.value],['95% lower bound',x.estimate.ci[0]],['95% upper bound',x.estimate.ci[1]]]}}) }),
L('c5','Know where the cubic budget stops',[gain,k('pin','Input per tone',-35,-65,-10,'dBm')],'How close is the selected drive to the model’s compression boundary?',
'An intercept is an extrapolation, not an achievable output level. A memoryless compressive cubic supplies a related single-tone 1 dB compression estimate that can guard the weak-signal budget.',
'Increase drive toward the displayed compression estimate and watch the status move from accepted to warning to declined.',p=>{const c=systemBudget(p),headroom=c.p1-p.pin,status=headroom<3?'declined':headroom<10?'warning':'accepted';return O([
s('Relate amplitude compression to the cubic coefficient','One dB less fundamental amplitude means the gain has fallen to 10^(−1/20) of its small-signal value.',String.raw`P_{1dB}/IIP3=1-10^{-1/20}`),
s('Convert the ratio to a power difference','This relation belongs to a single equivalent weak cubic, not every commercial amplifier.',String.raw`P_{1dB,dBm}=IIP3_{dBm}+10\log_{10}(1-10^{-1/20})`,String.raw`P_{1dB,dBm}=${N(c.iip3Dbm)}-${N(CUBIC_BACKOFF)}=${N(c.p1)}`),
s('Apply the declared extrapolation guard','At least 10 dB of backoff is accepted; 3–10 dB warns; below 3 dB declines an IP3-based prediction. Actual two-tone compression can differ.',String.raw`H=P_{1dB}-P_{in}`,String.raw`H=${N(headroom)}\,\mathrm{dB}\quad\text{${status}}`)
],[r('Equivalent single-tone P1dB',c.p1,'dBm'),r('Backoff',headroom,'dB')],[],`Status: ${status}. The displayed threshold guards the budget and is not a transistor-level compression simulation.`,headroom,'dB','Calculate the input backoff from the estimated compression point.','Subtract the selected input drive from the estimated P1dB.') }),
]
