import {noiseFloorDbm} from '@ee-labs/rf'
import {systemBudget,linkBudget} from './budgetModels.js'
import {L,O,k,s,r,curve,samples,N,gain,band,table} from './lessonSupport.js'
const rangePlot=c=>({label:'Signal, IM3 and noise at the output',xLabel:'Input per tone (dBm)',yLabel:'Output power (dBm)',traces:[{label:'Fundamental, slope 1',points:samples(p=>p+c.gainDb,c.floor,c.p1)},{label:'IM3, slope 3',points:samples(p=>3*p-2*c.iip3Dbm+c.gainDb,c.floor,c.p1)},{label:'Integrated noise floor',points:samples(()=>c.floor+c.gainDb,c.floor,c.p1)}]})
const freq=k('frequency','RF frequency',2.4e9,.1e9,12e9,'Hz'),distance=k('distance','Distance',100,10,1e5,'m'),linkBand=k('bandwidth','Noise bandwidth',20e6,1e5,40e6,'Hz')
const linkSymbols=[['P_t,P_r','Transmitted and received powers, in dBm when used in the decibel sum.'],['G_t,G_r','Antenna gains in dBi in the link sum.'],[String.raw`\lambda,d,L`,'Wavelength (m), path distance (m) and extra path loss (dB).'],['NF,B','Receiver noise figure (dB) and equivalent noise bandwidth (Hz).'],['C/N_0,E_b/N_0','Carrier-to-noise-density ratio (dB-Hz) and energy-per-bit to noise-density ratio (dB).'],['R_b,C','Information bit rate and ideal AWGN capacity (bit/s).']]
const linkExtra={symbols:linkSymbols,flow:['Transmit power and antenna gain','Free-space spreading and stated extra loss','Receive gain, noise floor and detection requirement'],route:'Calculate power density and receiving aperture in linear units, or add the corresponding decibel line items. The two routes describe the same ideal far-field link.',limits:'Far-field aligned antennas in free space, with extra losses stated separately. Receiver noise figure defaults to 6 dB and source temperature to 290 K. This is not a multipath, fading or antenna near-field simulation.'}
export const RANGE_LINK=[
...['d1','d2','d3'].map(id=>L(id,{d1:'Find the spurious-free range',d2:'Two different dynamic-range limits',d3:'Bandwidth changes both range and sensitivity'}[id],[gain,band],{d1:'Where does the third-order product first rise above the noise?',d2:'How do distortion-free range and compression-limited range differ?',d3:'What do you lose when the channel becomes one hundred times wider?'}[id],
'The fundamental and intermodulation product rise at different slopes, while integrated noise stays fixed for a selected bandwidth. Their intersection sets a distortion criterion; compression sets a different upper limit.',
'Compare 200 kHz and 20 MHz. Inspect both dynamic-range definitions and the output-plane intersection.',p=>{const c=systemBudget(p),cross=(c.floor+2*c.iip3Dbm)/3,a=systemBudget({gain:p.gain,bandwidth:2e5}),b=systemBudget({gain:p.gain,bandwidth:20e6});return O([
s('Place all three lines on the same output plane','The input-referred floor includes the cascade NF. Adding gain puts every line at the output.',String.raw`P_{fund}=P_{in}+G,\quad P_{IM3}=3P_{in}-2IIP3+G,\quad N_{out}=N_{in}+G`,String.raw`N_{in}=${N(c.floor)}\,\mathrm{dBm},\quad G=${N(c.gainDb)}\,\mathrm{dB}`),
s('Solve the IM3/noise intersection','Cancel the common gain and solve for the input per-tone crossing. SFDR is the distance above the input-referred noise floor, using a 0 dB signal/noise lower criterion.',String.raw`3P_{cross}-2IIP3=N_{in},\quad SFDR=P_{cross}-N_{in}=\frac23(IIP3-N_{in})`,String.raw`P_{cross}=${N(cross)}\,\mathrm{dBm},\quad SFDR=${N(c.sfdr)}\,\mathrm{dB}`),
s('Compare the compression-based criterion','The equivalent cubic single-tone P1dB supplies a separate upper boundary.',String.raw`DR_{compression}=P_{1dB}-N_{in}`,String.raw`DR_{compression}=${N(c.p1)}-(${N(c.floor)})=${N(c.linearRange)}\,\mathrm{dB}`),
...(id==='d3'?[s('Change only the channel bandwidth','One hundred times the bandwidth raises the floor by 20 dB and lowers SFDR by two thirds of that.',String.raw`\Delta N=10\log_{10}(B_2/B_1),\quad\Delta SFDR=-\tfrac23\Delta N`,String.raw`\Delta N=${N(b.floor-a.floor)},\quad\Delta SFDR=${N(b.sfdr-a.sfdr)}\quad\mathrm{dB}`)]:[])
],[r('SFDR',c.sfdr,'dB'),r('Compression-limited range',c.linearRange,'dB'),r('Input crossing',cross,'dBm')],[rangePlot(c)],'The two ranges answer different questions. A required signal SNR above zero narrows the usable interval further; weak-cubic extrapolation also needs its backoff guard.',id==='d3'?b.sfdr-a.sfdr:id==='d2'?c.linearRange:c.sfdr,'dB',id==='d3'?'Calculate the SFDR change from 200 kHz to 20 MHz.':id==='d2'?'Calculate the compression-limited range.':'Calculate the spurious-free dynamic range.',id==='d3'?'Use −2/3 times the noise-floor change.':id==='d2'?'Subtract the input-referred floor from P1dB.':'Use two thirds of the input IP3 minus the floor.') })),
L('d4','Add the converter noise budget',[k('bits','Resolution',12,4,16,'bits',1),k('sampleRate','Sample rate',100e6,50e6,250e6,'Hz'),linkBand,k('fullscale','Full-scale sine power',10,-10,15,'dBm')],'How does oversampling change an ideal ADC’s in-band noise floor?',
'Ideal uniform quantization noise spreads over the Nyquist band under the usual uncorrelated-error assumption. A narrower digital channel retains only part of that noise.',
'Add one bit, then double sample rate at fixed channel bandwidth. Compare the different improvements.',p=>{if(p.bandwidth>p.sampleRate/2)throw Error('The noise bandwidth must not exceed the Nyquist band, fs/2.');const snr=6.02*p.bits+1.76,osr=p.sampleRate/(2*p.bandwidth),pg=10*Math.log10(osr),floor=p.fullscale-snr-pg;return O([
s('Use the full-scale sine reference','The familiar expression compares full-scale sinusoidal power with ideal uniform quantization noise.',String.raw`SNR_{Nyquist}\simeq6.02N+1.76`,String.raw`SNR_{Nyquist}=${N(snr)}\,\mathrm{dB}`),
s('Keep only the in-band fraction','For white quantization noise, the retained fraction is B/(fs/2).',String.raw`OSR=f_s/(2B),\quad PG=10\log_{10}(OSR)`,String.raw`OSR=${N(osr)},\quad PG=${N(pg)}\,\mathrm{dB}`),
s('Refer noise to the ADC input power scale','Subtract the in-band SNR from the full-scale reference power.',String.raw`N_{ADC,dBm}=P_{FS,dBm}-SNR_{Nyquist}-PG`,String.raw`N_{ADC,dBm}=${N(p.fullscale)}-${N(snr)}-${N(pg)}=${N(floor)}`)
],[r('Nyquist SNR',snr,'dB'),r('Processing gain',pg,'dB'),r('In-band ADC floor',floor,'dBm')],[curve('Resolution and ideal noise','Bits','In-band floor (dBm)',samples(n=>p.fullscale-6.02*n-1.76-pg,4,16,13))],'This ideal floor excludes thermal noise, aperture jitter, distortion and correlated quantization error. Full-scale power must refer to the same input impedance as the receiver budget.',floor,'dBm','Calculate the ADC in-band noise floor.','Subtract both ideal SNR and processing gain from full-scale power.') },{symbols:[['N,f_s,B','Bit depth, sample rate (Hz), and in-band noise bandwidth (Hz).'],['P_{FS},OSR,PG','Full-scale sinusoidal power, oversampling ratio and processing gain (dB).']],limits:'Ideal uniform quantizer, full-scale sine, white uncorrelated quantization error and ideal in-band filtering. Bandwidth must be no greater than fs/2.'}),
L('e1','Free-space spreading',[freq,distance],'How much power is lost to geometric spreading?',
'The free-space path factor combines spherical spreading with a receiving isotropic antenna’s effective aperture. It depends on both separation and wavelength.',
'Double distance and then double frequency. Compare the decibel penalties.',p=>{const x=linkBudget(p);return O([
s('Calculate wavelength','Use metres and hertz with the speed of light.',String.raw`\lambda=c/f`,String.raw`\lambda=${N(x.lambda)}\,\mathrm m`),
s('Form the spreading power ratio','The ideal path loss is the reciprocal of the isotropic path power gain.',String.raw`L_{FS}=(4\pi d/\lambda)^2`,String.raw`L_{FS}=${N(10**(x.fspl/10))}`),
s('Convert the squared ratio to decibels','The square explains why the coefficient is 20 rather than 10.',String.raw`L_{FS,dB}=20\log_{10}(4\pi d/\lambda)`,String.raw`L_{FS,dB}=${N(x.fspl)}`)
],[r('Wavelength',x.lambda,'m'),r('Free-space loss',x.fspl,'dB')],[curve('Distance penalty','Distance (m)','Free-space loss (dB)',samples(d=>linkBudget({...p,distance:d}).fspl,10,1000))],'Doubling either distance or frequency adds 6.0206 dB of free-space loss at fixed antenna gains.',x.fspl,'dB','Calculate free-space loss.','Use distance and wavelength in the same units.') },linkExtra),
...['e2','e3'].map(id=>L(id,id==='e2'?'The complete link as a sum':'Recover a link with negative margin',[freq,{...distance,value:id==='e2'?100:1000},k('tx','Transmit power',20,0,40,'dBm'),k('gt','Transmit antenna gain',2,0,20,'dBi'),k('gr','Receive antenna gain',2,0,20,'dBi'),linkBand,k('loss','Extra losses',0,0,20,'dB'),k('snr','Required SNR',20,0,30,'dB')],id==='e2'?'Does the received signal clear the noise requirement?':'Which design change is enough to close the failed link?',
'Received power is a sum of signed decibel terms. Comparing it with receiver noise and required SNR turns that power into a design margin.',
'Try one remedy at a time: more transmit power, more antenna gain, or less bandwidth. Compare the physical cost outside this ideal budget.',p=>{const x=linkBudget(p);let running=0;const rows=x.items.map(([name,value])=>{running+=value;return[name,value,running]});return O([
s('Sum the propagation path','Antenna gain adds and path loss subtracts. Both gains use the isotropic reference.',String.raw`P_r=P_t+G_t+G_r-L_{FS}-L_{extra}`,String.raw`P_r=${x.items.map(([,v])=>`(${N(v)})`).join('+')}=${N(x.received)}\,\mathrm{dBm}`),
s('Find the receiver’s input-referred noise','This example uses a stated 6 dB receiver NF, independent of the reference six-stage chain.',String.raw`N_{in}=10\log_{10}(kT_0B/10^{-3})+NF`,String.raw`N_{in}=${N(x.floor)}\,\mathrm{dBm}`),
s('Calculate margin above the requirement','Zero margin just meets the stated criterion and leaves no fading or implementation reserve.',String.raw`SNR=P_r-N_{in},\quad M=SNR-SNR_{required}`,String.raw`SNR=${N(x.snr)}\,\mathrm{dB},\quad M=${N(x.margin)}\,\mathrm{dB}`)
],[r('Received power',x.received,'dBm'),r('Receiver SNR',x.snr,'dB'),r('Link margin',x.margin,'dB')],[{kind:'waterfall',label:'Link budget: each gain or loss moves the running power',rows}],x.margin>=0?'The ideal link meets the stated requirement. Real links usually reserve additional margin.':`The ideal link misses the requirement by ${N(-x.margin)} dB. Any remedy must recover at least this deficit.`,x.margin,'dB','Calculate the link margin.','Subtract the noise floor and required SNR from received power.',{table:{headers:['Line item','Signed change (dB; first row dBm)','Running power (dBm)'],rows}}) },linkExtra)),
L('e4','From received power to energy per bit',[freq,distance,linkBand,k('rate','Information bit rate',1e6,1e5,100e6,'bit/s')],'How do C/N0, Eb/N0 and channel capacity answer different questions?',
'Noise density removes bandwidth from the carrier comparison. Dividing signal power by information bit rate gives energy per bit; Shannon capacity supplies an ideal upper bound for a band-limited Gaussian-noise channel.',
'Change information bit rate without changing received power, then widen noise bandwidth.',p=>{const x=linkBudget(p);return O([
s('Remove the bandwidth from the noise floor','C/N0 uses a power divided by a power-per-hertz density, which is why its decibel unit is dB-Hz.',String.raw`C/N_0=P_{r,dBm}-N_{0,dBm/Hz}`,String.raw`C/N_0=${N(x.cn0)}\,\mathrm{dB\!\cdot\!Hz}`),
s('Allocate received energy per information bit','Use information bit rate consistently; coded symbol rate would describe a different energy reference.',String.raw`E_b/N_0=C/N_0-10\log_{10}(R_b/1\,\mathrm{Hz})`,String.raw`E_b/N_0=${N(x.ebn0)}\,\mathrm{dB}`),
s('Calculate the ideal Gaussian-channel bound','The logarithm takes the linear SNR, not its decibel value.',String.raw`C=B\log_2(1+10^{SNR_{dB}/10})`,String.raw`C=${N(x.capacity/1e6)}\,\mathrm{Mbit/s}`)
],[r('C/N0',x.cn0,'dB-Hz'),r('Eb/N0',x.ebn0,'dB'),r('Ideal capacity',x.capacity/1e6,'Mbit/s')],[curve('Energy allocated per bit','Information bit rate (Mbit/s)','Eb/N0 (dB)',samples(rate=>linkBudget({...p,rate:rate*1e6}).ebn0,.1,100))],'Capacity is an ideal upper bound. Actual BER needs a modulation, coding and receiver model; Eb/N0 alone does not specify it.',x.ebn0,'dB','Calculate Eb/N0 for the selected information bit rate.','Subtract 10 log10(bit rate) from C/N0.') },linkExtra),
L('f1','Which block consumes the power?',[], 'Do the noise, distortion and power budgets have the same dominant stage?',
'DC power adds directly, while noise and distortion refer through preceding gain in opposite ways. Therefore each budget can be dominated by a different stage.',
'Compare the three largest shares in the table and explain why they belong to different blocks.',()=>{const c=systemBudget(),largest=key=>c.blocks.reduce((a,b)=>a[key]>b[key]?a:b);return O([
s('Sum the named DC loads','Passive blocks have zero assigned DC draw in this model; support circuitry is outside this subtotal.',String.raw`P_{DC,total}=\sum_iP_{DC,i}`,String.raw`P_{DC,total}=33+45+60=${N(c.powerMw)}\,\mathrm{mW}`),
s('Normalize each power share','Each percentage uses the total DC power, not total RF gain.',String.raw`share_{P,i}=P_{DC,i}/P_{DC,total}`,String.raw`share_{IF}=60/${N(c.powerMw)}=${N(60/c.powerMw)}`),
s('Compare differently weighted budgets','Noise and distortion use their own denominators and reference-plane weights.',String.raw`share_{N,i}\propto(F_i-1)/g_i,\quad share_{IM3,i}\propto g_i/IIP3_i`)
],[r('DC subtotal',c.powerMw,'mW')],[],`Largest noise share: ${largest('noiseShare').name}; largest distortion share: ${largest('ip3Share').name}; largest power share: ${largest('powerShare').name}.`,100*60/c.powerMw,'%','Calculate the IF amplifier’s fraction of total DC power.','Divide 60 mW by the 138 mW subtotal, then multiply by 100.',{table:table(c)}) }),
L('f2','Reciprocal mixing from a strong blocker',[gain,band,k('blocker','Input blocker power',-30,-80,-10,'dBm'),k('phaseNoise','LO SSB phase noise at blocker offset',-117,-150,-90,'dBc/Hz')],'Can LO phase noise raise the wanted-channel noise above the receiver’s thermal floor?',
'A strong off-channel blocker mixes with local-oscillator phase noise. Its power scales the noise skirt that folds into the wanted channel.',
'Reduce the blocker by 10 dB or improve phase noise by 10 dB. Compare their equal effect in this approximation.',p=>{const c=systemBudget(p),relative=p.phaseNoise+10*Math.log10(p.bandwidth),noise=p.blocker+relative,excess=noise-c.floor,total=10*Math.log10(10**(noise/10)+10**(c.floor/10));return O([
s('Integrate the relevant LO noise skirt','The supplied SSB phase-noise density is assumed approximately constant across the wanted channel at the blocker offset.',String.raw`L_{band,dBc}=L_{SSB,dBc/Hz}+10\log_{10}(B/1\,\mathrm{Hz})`,String.raw`L_{band}=${N(relative)}\,\mathrm{dBc}`),
s('Scale by blocker power','Both blocker and resulting reciprocal-mixing noise are referred to the receiver input.',String.raw`N_{recip,dBm}=P_{blocker,dBm}+L_{band,dBc}`,String.raw`N_{recip}=${N(noise)}\,\mathrm{dBm}`),
s('Add independent noise powers','Decibel powers cannot be added directly.',String.raw`N_{total,dBm}=10\log_{10}(10^{N_{thermal}/10}+10^{N_{recip}/10})`,String.raw`N_{total}=${N(total)}\,\mathrm{dBm}`)
],[r('Reciprocal-mixing noise',noise,'dBm'),r('Above thermal floor',excess,'dB'),r('Combined noise',total,'dBm')],[curve('Blocker-driven noise','Input blocker (dBm)','Input-referred noise (dBm)',samples(b=>b+relative,-80,-10))],'Filtering the blocker before the mixer or improving the LO noise skirt can help; more downstream gain cannot restore the lost SNR.',noise,'dBm','Calculate input-referred reciprocal-mixing noise.','Add blocker power, LO noise density and 10 log10(B).') }),
L('f3','Meet three system requirements',[
k('targetSensitivity','Maximum acceptable sensitivity',-105,-120,-80,'dBm'),k('targetSfdr','Minimum SFDR',70,50,90,'dB'),k('targetPower','Maximum DC power',150,50,300,'mW'),
...[[ 'lna','LNA',15,1.5,-5,33],['mixer','Mixer',8,8,5,45],['ifamp','IF amplifier',22,10,20,60]].flatMap(([id,name,g,nf,ip,power])=>[k(id+'Gain',name+' gain',g,0,30,'dB'),k(id+'Nf',name+' noise figure',nf,.5,15,'dB'),k(id+'Ip3',name+' input IP3',ip,-15,35,'dBm'),k(id+'Power',name+' DC power',power,1,120,'mW')].map(item=>({...item,group:name})))
],'Can one set of three active blocks meet sensitivity, SFDR and power limits together?',
'Choose specifications for the LNA, mixer and IF amplifier while the passive filters stay fixed. A valid design needs nonnegative margin against all three requirements, not just the most visible one.',
'Start with the feasible reference design. Lower one block’s power or change its gain and inspect all three margins.',p=>{const c=systemBudget(p),m=[p.targetSensitivity-c.sensitivity,c.sfdr-p.targetSfdr,p.targetPower-c.powerMw];return O([
s('Evaluate noise and sensitivity','This capstone uses a 200 kHz noise bandwidth and a 10 dB required SNR.',String.raw`P_{min}=10\log_{10}(kT_0B/10^{-3})+NF+10\,\mathrm{dB}`,String.raw`P_{min}=${N(c.sensitivity)}\,\mathrm{dBm}`),
s('Evaluate distortion-free range and DC consumption','Use the aligned weak-cubic IP3 budget and sum the assigned active-block power.',String.raw`SFDR=\tfrac23(IIP3-N_{in}),\quad P_{DC}=\sum_iP_{DC,i}`,String.raw`SFDR=${N(c.sfdr)}\,\mathrm{dB},\quad P_{DC}=${N(c.powerMw)}\,\mathrm{mW}`),
s('Turn every requirement into a margin','A lower sensitivity power and lower DC power are better; a larger SFDR is better. Set the subtraction order accordingly.',String.raw`M_S=S_{max}-S,\quad M_D=SFDR-D_{min},\quad M_P=P_{max}-P_{DC}`,String.raw`M_S=${N(m[0])}\,\mathrm{dB},\quad M_D=${N(m[1])}\,\mathrm{dB},\quad M_P=${N(m[2])}\,\mathrm{mW}`)
],[r('Sensitivity margin',m[0],'dB'),r('SFDR margin',m[1],'dB'),r('Power margin',m[2],'mW')],[],m.every(v=>v>=0)?'This specification set meets all three stated budget targets. Circuit implementation, bandwidth and stability still need verification.':'At least one target is missed. Identify its dominant contributing block before changing specifications.',m[0],'dB','Calculate the sensitivity margin.','Subtract achieved sensitivity from the maximum allowed sensitivity.',{table:table(c)}) },{limits:'Block specifications are independently adjustable requirements, not a claim that arbitrary gain/NF/IP3/power combinations exist in one physical device. The exercise finishes a budget; a circuit design must establish realizability.'}),
]
