import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {pll,linearStep,acquisition,detector,phaseNoise,clockBudget,db,logpoints,loopDrawing} from './clocks.js'
const T=String.raw
const source=['Analog Devices: PLL fundamentals','https://www.analog.com/en/resources/analog-dialogue/articles/phase-locked-loop-pll-fundamentals.html'],jitterSource=['Analog Devices MT-008: Phase noise to jitter','https://www.analog.com/media/en/training-seminars/tutorials/MT-008.pdf']
const symbols=[[T`\phi_r,\phi_d,e,\phi_o,N`,'Reference, divided VCO, error e=φr−φd, and output phases (rad); integer divider N=100 with φd=φo/N.'],[T`I_{CP},K_d,K_v,K`,'Charge-pump current (A), detector gain Icp/(2π) (A/rad), VCO gain (rad/s/V), and K=KdKv/N. VCO gain in Hz/V is multiplied by 2π before use.'],[T`R,C_1,C_2,Z(s),T(s)`,'Series loop-filter resistor (Ω), main and shunt capacitances (F), impedance (Ω), and dimensionless return ratio.'],[T`\omega_n,\zeta,t,s,j`,'Natural angular frequency (rad/s), damping ratio, elapsed time (s), Laplace variable (s⁻¹), and imaginary unit. A dot means derivative with respect to seconds.']]
const knobs=[k('current','Charge-pump current',100e-6,20e-6,200e-6,'A'),k('resistance','Loop-filter resistance',6324.555320336759,2000,10000,'Ω')]
function L(id,name,ks,question,intro,attempt,solve,extra={}){return{id,name,group:'F. Clocks and phase-locked loops',knobs:ks,question,intro,try:attempt,solve,symbols,sources:[source],flow:['Define phase, frequency and the detector model','Derive the loop or noise equation','Compare the result with acquisition or converter requirements'],route:'Use the phase-domain transfer function and phasors for small deviations around lock. Use state equations for transients and actual edge events for acquisition outside that approximation. Integrating a noise spectrum is a separate statistical calculation, with its own bandwidth and independence assumptions.',limits:'Ideal charge pump and VCO, N=100, C1=1 nF, VCO gain 100 MHz/V unless varied explicitly. No reset delay, dead zone, current mismatch, control-voltage rails, divider noise or device-specific tuning curve.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
export const clockLink=x=>({app:'control-lab',label:'Inspect this exact PLL loop in Control Lab',patch:{plant:{type:x.a.length===4?'custom3':'custom',params:[...Array((x.a.length===4?4:3)-x.b.length).fill(0),...x.b,...x.a]},ctrl:{type:'p',params:[1]},from:{app:'mixed-signal-lab',id:'f3',label:'Charge-pump PLL return ratio'}},note:'Carries the complete return-ratio coefficients, including the third-order denominator when C2 is present. Unity control closes the same divided-phase feedback loop.'})
export const CLOCK_LESSONS=[
L('f1','The phase-frequency detector: pulses first, gain second',[k('phase','Phase difference on one cycle branch',1,-7,7,'rad'),k('current','Charge-pump current',100e-6,20e-6,200e-6,'A')],
 'Where does Icp/(2π) come from, and when is a phase number insufficient?',
 'A reference edge sets UP; a divided-clock edge sets DOWN. When both are set, an ideal reset clears both. On a selected equal-frequency cycle branch, their separation determines the charge-pump pulse width.',
 'Try ±π and then approach ±2π. Go beyond one cycle: the lesson withdraws the single-pulse calculation because edge history is needed.',p=>{const x=detector(p);return O([
 s('Define the edge ordering and sign','Positive phase error means the reference leads, producing a positive current pulse until the divided VCO catches up. Negative error produces a negative pulse.',T`i_{CP}=I_{CP}(UP-DOWN),\quad e=\phi_r-\phi_d`,T`I_{CP}=${N(p.current*1e6)}\,\mu A,\quad e=${N(p.phase)}\,rad`),
 s('Convert edge separation to a fraction of one period','A full period corresponds to 2π rad. This equation assumes the selected two edges belong to one branch and |e|≤2π.',T`\Delta t/T_{ref}=|e|/(2\pi),\quad |e|\le2\pi`,T`|e|/(2\pi)=${N(Math.abs(p.phase)/(2*Math.PI))}`),
 s('Average the rectangular charge pulse','Pulse area is charge. Divide by the reference period to obtain average current, then differentiate with respect to phase to obtain detector gain.',T`Q=I_{CP}\Delta t\operatorname{sgn}(e),\quad\bar i=Q/T_{ref}=K_de,\quad K_d=I_{CP}/(2\pi)`,T`K_d=${N(p.current/(2*Math.PI))}\,A/rad,\quad K_de=${N(x.linear*1e6)}\,\mu A`),
 s('Keep the model boundary visible','A current pump cannot average more than its on-current. Beyond one cycle, a clipped line is only a bound, not a unique detector characteristic: UP/DOWN history and frequency ordering matter.',T`|\bar i|\le I_{CP}`,x.inside?T`\bar i=${N(x.average*1e6)}\,\mu A`:T`\text{Outside the selected one-cycle branch}`),
 s('Choose the next analysis route','F2 averages these pulses around lock. F4 retains the UP/DOWN state and computes the next actual edge, so acquisition is not inferred by clipping a phase curve.',T`\text{edge events}\longrightarrow\text{charge}\longrightarrow\text{filter voltage}\longrightarrow\text{next VCO edge}`,T`\text{Reset rule: }UP=DOWN=1\Rightarrow UP=DOWN=0`)
 ],[r('Detector gain',p.current/(2*Math.PI),'A/rad'),r('Unbounded linear prediction',x.linear*1e6,'µA'),r('Current magnitude bound',p.current*1e6,'µA')],[...(x.inside?[curve('Selected cycle pair: rectangular pulse','Time / reference period','Charge-pump current (µA)',x.points)]:[]),curve('Average current on the admitted branch only','Phase error (rad)','Average current (µA)',samples(e=>p.current*e/(2*Math.PI)*1e6,-2*Math.PI,2*Math.PI))],
 x.inside?'On this selected equal-frequency branch the pulse area gives a linear average. This does not turn a phase-frequency detector into a globally memoryless component.':'The selected phase lies outside the one-cycle branch. No pulse waveform or claimed average is provided; use the edge-driven acquisition model in F4.',p.current/(2*Math.PI),'A/rad','Calculate the local detector gain.','Divide the charge-pump current by 2π.',{table:{headers:['Error on branch (rad)','Pulse fraction','Average current (µA)'],rows:[-Math.PI,0,Math.PI].map(e=>[fmt(e),fmt(Math.abs(e)/(2*Math.PI)),fmt(p.current*e/(2*Math.PI)*1e6)])}})}),
L('f2','Charge pump and loop filter: derive two state equations',knobs,
 'How do current, capacitance and resistance set the PLL dynamics?',
 'The main loop filter is a series R–C1 branch to ground. Its capacitor voltage is continuous; the resistor voltage can jump with current. Derive the averaged loop and inspect a small 1 kHz reference-frequency step.',
 'Compare R near 3.162 kΩ and 6.325 kΩ. Inspect the response rather than borrowing a no-zero second-order overshoot formula.',p=>{const x=linearStep(p,1000),rows=[.5,.70710678,1].map(z=>({z,x:linearStep({...p,resistance:2*z/Math.sqrt(x.K*x.cap)},1000)}));return O([
 s('Translate VCO gain into angular units','VCO gain is given in Hz/V. Phase integration requires radians per second per volt. The divider reduces the effect at the detector by N.',T`K_d=I_{CP}/(2\pi),\quad K_v=2\pi(10^8),\quad K=K_dK_v/N`,T`K=${N(x.K)},\quad N=100`),
 s('Write the two physical states','e is detector phase error and vc is capacitor voltage. A reference-frequency step adds Δωr to the phase-error derivative. Start locked, with both deviation states zero.',T`\dot v_c=K_de/C_1,\quad v_{ctrl}=v_c+RK_de,\quad\dot e=\Delta\omega_r-(K_v/N)v_{ctrl}`,T`e(0)=v_c(0)=0,\quad\Delta\omega_r=2\pi(1000)\,rad/s`),
 s('Eliminate capacitor voltage to identify poles','Differentiating the phase equation gives a homogeneous second-order equation after the step. Initial derivative is Δωr. Compare its coefficients with s²+2ζωns+ωn².',T`\ddot e+KR\dot e+(K/C_1)e=0,\quad\omega_n=\sqrt{K/C_1},\quad\zeta=\frac R2\sqrt{KC_1}`,T`\omega_n=${N(x.wn)}\,rad/s,\quad f_n=${N(x.wn/(2*Math.PI*1000))}\,kHz,\quad\zeta=${N(x.zeta)}`),
 s('Keep the zero in the closed-loop response','The series resistor contributes a zero. Divided output phase and frequency deviations follow the same closed-loop transfer H=T/(1+T). A critically damped denominator therefore does not guarantee a monotone output step.',T`T(s)=\frac{K(1+sRC_1)}{C_1s^2},\quad H(s)=\frac{2\zeta\omega_ns+\omega_n^2}{s^2+2\zeta\omega_ns+\omega_n^2}`,T`f_z=1/(2\pi RC_1)=${N(x.zero/1000)}\,kHz`),
 s('Measure the response of these exact states','The matrix exponential advances normalized states [e,(Kv/N)vc/ωn]. The plotted frequency is at the divided VCO; multiply its deviation by N for output frequency.',T`\Delta f_d=(K_v/N)(v_c+RK_de)/(2\pi),\quad\Delta f_o=N\Delta f_d`,T`\max |e|=${N(x.peak)}\,rad,\quad M_p=${N(x.overshoot)}\%`)
 ],[r('Natural frequency',x.wn/(2*Math.PI*1000),'kHz'),r('Damping ratio',x.zeta),r('Frequency-step overshoot',x.overshoot,'%')],[{label:'Same 1 kHz reference step at three dampings',xLabel:'Time (µs)',yLabel:'Divided VCO frequency change (kHz)',traces:rows.map(({z,x})=>({label:`ζ = ${fmt(z)}`,points:x.points.map(p=>({x:p.x*1e6,y:p.frequency/1000}))}))},curve('Selected loop phase error','Time (µs)','Error (rad)',x.points.map(p=>({x:p.x*1e6,y:p.error})))],
 'The resistor adds damping and a zero at the same time. Read the transient from the full transfer function or its state equations; a denominator-only overshoot rule misses that zero.',x.wn/(2*Math.PI*1000),'kHz','Calculate natural frequency in kHz.','Take √(K/C1), divide by 2π, then by 1000.',{schematic:loopDrawing(x),table:{headers:['Damping ζ','Required R (Ω)','Output overshoot (%)'],rows:rows.map(({z,x})=>[fmt(z),fmt(x.resistance),fmt(x.overshoot)])}})}),
]
CLOCK_LESSONS.push(
L('f3','PLL margins: retain the extra loop-filter pole',[...knobs,k('extra','Shunt capacitance / main capacitance',.1,0,.3)],
 'How much phase margin does a second loop-filter capacitor cost?',
 'Place C2 directly from the charge-pump output to ground, in parallel with the series R–C1 branch. Derive the exact impedance and send the complete return ratio to Control Lab.',
 'Set C2/C1 to zero, then 0.1 and 0.3. Compare the crossover shift as well as margin; the extra pole does not leave crossover fixed.',p=>{const x=pll(p),baseline=pll({...p,extra:0});return O([
 s('Add admittances at the charge-pump node','C2 is in parallel with the entire series branch, not simply added to C1. Invert the sum of admittances.',T`Z(s)=\left[sC_2+\frac{sC_1}{1+sRC_1}\right]^{-1}=\frac{1+sRC_1}{s(C_1+C_2)+s^2RC_1C_2}`,T`C_1=1\,nF,\quad C_2=${N(x.c2*1e9)}\,nF`),
 s('Multiply detector, filter, VCO integrator and divider','The VCO contributes another factor 1/s. A nonzero C2 therefore makes the open-loop denominator third order.',T`T(s)=\frac{K(1+sRC_1)}{s^2(C_1+C_2)+s^3RC_1C_2}`,T`K=${N(x.K)},\quad RC_1C_2=${N(x.resistance*x.cap*x.c2)}`),
 s('Locate the zero and additional pole','The extra pole uses C1+C2 in its numerator. A shortcut that uses 1/(RC2) neglects the C2/C1 correction.',T`f_z=\frac1{2\pi RC_1},\quad f_{p,extra}=\frac{C_1+C_2}{2\pi RC_1C_2}`,x.pole?T`f_z=${N(x.zero/1000)}\,kHz,\quad f_{p,extra}=${N(x.pole/1000)}\,kHz`:T`C_2=0\Rightarrow\text{no finite extra pole}`),
 s('Solve the unity-gain crossing before measuring margin','Evaluate T(j2πf), solve |T|=1, and read its continuous phase. Confirm all closed-loop roots lie in the left half-plane.',T`|T(j2\pi f_u)|=1,\quad PM=180^\circ+\arg T(j2\pi f_u)`,T`f_u=${N(x.crossover/1000)}\,kHz,\quad PM=${N(x.pm)}^\circ,\quad PM_{C_2=0}=${N(baseline.pm)}^\circ`),
 s('Carry the same polynomial into Control Lab','The handover selects the third-order custom plant when needed and unity proportional control. No pole is discarded to fit a lower-order receiver.',T`H(s)=T(s)/(1+T(s)),\quad D_{closed}(s)=D_T(s)+N_T(s)`,T`\text{Closed-loop order}=${x.poles.length},\quad\text{all poles left half-plane: }\text{${x.stable?'yes':'no'}}`)
 ],[r('Unity crossing',x.crossover/1000,'kHz'),r('Phase margin',x.pm,'°'),r('Margin change',x.pm-baseline.pm,'°')],[{label:'Return-ratio magnitude',xLabel:'Frequency (Hz)',yLabel:'Magnitude (dB)',logX:true,traces:[{label:'C2 = 0',points:logpoints(f=>db(baseline.at(f)),1e3,1e7)},{label:'Selected C2',points:logpoints(f=>db(x.at(f)),1e3,1e7)}]}],
 'The extra capacitor reduces high-frequency pump ripple in a real loop but also changes stability. Compare the complete loop and verify its closed poles before selecting a bandwidth.',x.pm,'°','Calculate phase margin from the unity-crossing phase.','Add 180° to the return-ratio phase at |T|=1.',{schematic:loopDrawing(x),handover:clockLink(x),table:{headers:['Closed-loop pole','Real part (s⁻¹)','Imaginary part (s⁻¹)'],rows:x.poles.map((z,i)=>[i+1,fmt(z[0]),fmt(z[1])])}})}),
L('f4','Acquisition: compare linear phase error with actual edge events',[k('step','Reference-frequency step',1e5,1e3,2e6,'Hz'),k('resistance','Loop-filter resistance',6324.555320336759,3162.2776601683795,10000,'Ω')],
 'What happens when the linear prediction leaves its selected phase branch?',
 'Start with a 1 MHz reference and a 100 MHz VCO, divided by 100. Step the reference frequency at t=0. Compare the averaged two-state model with a stateful UP/DOWN detector and charge-pump pulses.',
 'Compare a 10 kHz step with 100 kHz and 1 MHz. Watch capacitor voltage and phase error as pulse widths change. Crossing 2π warns about the approximation; it is not a proven hardware lock-range boundary.',p=>{const a=linearStep(p,p.step),x=acquisition(p,p.step),critical=pll({...p,resistance:6324.555320336759}),guard=critical.wn*Math.E;return O([
 s('Define the initial lock and the new edge schedule','Only frequency changes at t=0; there is no phase step. All phases start at zero, UP and DOWN are cleared, and the capacitor deviation is zero.',T`\phi_r(t)=2\pi(f_r+\Delta f_r)t,\quad\phi_d(0)=v_c(0)=0,\quad UP=DOWN=0`,T`f_r=1\,MHz,\quad\Delta f_r=${N(p.step/1000)}\,kHz`),
 s('Predict the error with the linear states','The general damping response is computed from F2. For ζ=1 only, e(t)=Δωr t exp(−ωnt), which peaks at 1/ωn. The 2π branch guard then gives Δfr=exp(1)ωn in Hz.',T`e_{\zeta=1}(t)=\Delta\omega_rte^{-\omega_nt},\quad e_{max}=\frac{\Delta\omega_r}{\mathrm{e}\omega_n}`,T`e_{max,selected}=${N(a.peak)}\,rad,\quad\Delta f_{guard,\zeta=1}=${N(guard/1000)}\,kHz`),
 s('Retain the actual detector state','A reference edge sets UP and a divided VCO edge sets DOWN. Reset both as soon as both are set. Each segment has constant pump current, so capacitor voltage changes linearly.',T`i=I_{CP}(UP-DOWN),\quad\dot v_c=i/C_1,\quad v_{ctrl}=v_c+Ri`,T`I_{CP}=100\,\mu A,\quad C_1=1\,nF,\quad R=${N(p.resistance)}\,\Omega`),
 s('Solve the next VCO edge from phase, not a clipped gain','Between events, divided phase is quadratic because capacitor voltage is linear. Solve for the next multiple of 2π and advance to whichever comes first: reference edge or VCO edge.',T`\phi_d(t+h)=\phi_d(t)+2\pi[f_r+k_v(v_c+Ri)/N]h+\frac{\pi k_vi}{NC_1}h^2`,T`k_v=10^8\,Hz/V,\quad\text{processed edges}=${x.events}`),
 s('Interpret the finite observation','The stateful detector keeps running beyond the branch guard. An unwrapped residual near 2π times an integer records whole-cycle slips; its modulo-2π residual describes final edge alignment. This is evidence for this run, not a proof of acquisition for arbitrary initial conditions or a rail-limited physical VCO.',T`e_{edge}(t)=\phi_r(t)-\phi_d(t),\quad e_{wrapped}=\operatorname{atan2}(\sin e,\cos e)`,T`\max|e_{edge}|=${N(x.peak)}\,rad,\quad e_{wrapped}(t_{end})=${N(x.wrapped)}\,rad`)
 ],[r('Linear peak phase error',a.peak,'rad'),r('Edge-model peak phase error',x.peak,'rad'),r('Final phase error modulo 2π',x.wrapped,'rad')],[{label:'Two descriptions of the same reference step',xLabel:'Time (µs)',yLabel:'Unwrapped phase error (rad)',traces:[{label:'Linear averaged loop',points:a.points.map(p=>({x:p.x*1e6,y:p.error}))},{label:'Edge-driven PFD',points:x.points.map(p=>({x:p.x*1e6,y:p.error}))}]},curve('Continuous capacitor voltage through acquisition','Time (µs)','Capacitor voltage change (V)',x.points.map(p=>({x:p.x*1e6,y:p.voltage})))],
 a.peak>2*Math.PI?'The linear prediction exceeds the selected 2π phase branch. Use the edge-driven result for this acquisition model; the branch warning alone does not establish loss of physical lock.':'The linear prediction remains within the selected 2π branch. Compare it with the actual edge model: being inside the branch does not guarantee pulse averaging is accurate.',a.peak,'rad','Find the peak magnitude of the linear phase-error prediction.','For ζ=1 use Δω/(exp(1)ωn); otherwise use the selected state response.',{schematic:loopDrawing(x),table:{headers:['Model','Peak |phase error| (rad)','Final error (rad)'],rows:[['Linear averaged',fmt(a.peak),fmt(a.points.at(-1).error)],['Edge-driven pump',fmt(x.peak),fmt(x.finalError)]]}})}, {symbols:[...symbols,[T`k_v,h,UP,DOWN,\Delta f_r`,'VCO gain in Hz/V, segment duration (s), detector state bits, and reference-frequency step (Hz). Roman e in the peak formula is Euler’s number, distinct from phase error e(t).']]})
)
CLOCK_LESSONS.push(
L('f5','From phase-noise density to RMS time jitter',[k('level','SSB noise at 1 MHz offset',-120,-140,-100,'dBc/Hz'),k('low','Integration lower offset',1e4,1e3,1e5,'Hz'),k('high','Integration upper offset',1e7,1e6,2e7,'Hz'),k('carrier','Carrier frequency',1e8,1e7,1e9,'Hz')],
 'Why does phase noise require an integration band before it becomes jitter?',
 'Assume a pure 1/f² single-sideband phase-noise skirt between the chosen offsets. Convert decibels to a linear density, integrate both sidebands, and divide RMS phase by carrier angular frequency.',
 'Raise the lower integration bound by ten. Then double carrier frequency while keeping the phase-noise curve unchanged. Predict the effect on time jitter.',p=>{const x=phaseNoise(p);return O([
 s('Convert the SSB density to a linear ratio per hertz','L(f) is specified relative to carrier power in a 1 Hz bandwidth. Use 10, not 20, in the power conversion.',T`\ell(f)=10^{L_0/10}(f_0/f)^2=c/f^2`,T`c=10^{${N(p.level)}/10}(10^6)^2=${N(x.c)}`),
 s('Count both noise sidebands under the small-phase approximation','The one-sided phase PSD Sφ(f) is twice the linear SSB density. Integrate over positive offsets only, with the factor two already included.',T`S_\phi(f)=2\ell(f),\quad\sigma_\phi^2=2\int_{f_L}^{f_H}\ell(f)df`,T`f_L=${N(p.low)}\,Hz,\quad f_H=${N(p.high)}\,Hz`),
 s('Integrate the stated power law exactly','The integral of f⁻² is −1/f. Retain both endpoints; the upper endpoint is small but not zero.',T`\sigma_\phi^2=2c(1/f_L-1/f_H)`,T`\sigma_\phi^2=2(${N(x.c)})(1/${N(p.low)}-1/${N(p.high)})=${N(x.variance)}\,rad^2`),
 s('Convert phase deviation into timing deviation','For a carrier cos(2πfct+φ), a small phase displacement is equivalent to time displacement φ/(2πfc). Take the square root before dividing.',T`\sigma_\phi=\sqrt{\sigma_\phi^2},\quad\sigma_t=\sigma_\phi/(2\pi f_c)`,T`\sigma_\phi=${N(x.rms)}\,rad,\quad\sigma_t=${N(x.jitter*1e12)}\,ps`),
 s('State what this number excludes','The result describes integrated random phase noise within the chosen band. Discrete spurs, other slopes, AM noise and cycle-to-cycle jitter are different specifications.',T`\sigma_t^2(f_L,f_H)=\frac{2c(1/f_L-1/f_H)}{(2\pi f_c)^2}`,T`\sigma_\phi=${N(x.rms*180/Math.PI)}^\circ\ rms`)
 ],[r('Integrated phase variance',x.variance,'rad²'),r('RMS phase',x.rms,'rad'),r('RMS time jitter',x.jitter*1e12,'ps')],[{...curve('Specified SSB phase-noise skirt','Offset frequency (Hz)','SSB phase noise (dBc/Hz)',logpoints(f=>10*Math.log10(x.at(f)),p.low,p.high)),logX:true}],
 'Always report the carrier and integration band with a jitter value. Lower-frequency noise can dominate a 1/f² integral, so changing the lower bound changes the result substantially.',x.jitter*1e12,'ps','Calculate RMS time jitter.','Square-root the phase variance and divide by 2π times carrier frequency.',{table:{headers:['Lower offset (Hz)','Upper offset (Hz)','Phase variance (rad²)','Time jitter (ps)'],rows:[p.low,p.low*2,p.low*5].map(low=>{const y=phaseNoise({...p,low});return[fmt(low),fmt(p.high),fmt(y.variance),fmt(y.jitter*1e12)]})}})}, {sources:[jitterSource],symbols:[[T`L_0,\ell(f),S_\phi(f),f_0,c`,'SSB phase-noise level (dBc/Hz), linear SSB power density (Hz⁻¹), one-sided phase density (rad²/Hz), 1 MHz anchor offset, and its power-law coefficient.'],[T`f_L,f_H,f_c,\sigma_\phi^2,\sigma_\phi,\sigma_t`,'Lower/upper integration offsets and carrier frequency (Hz), phase variance (rad²), RMS phase (rad), and RMS time jitter (s).']]}),
L('f6','Clock noise meets converter SNR',[k('bandwidth','PLL natural frequency',5e4,1e4,3e5,'Hz'),k('input','ADC input sine frequency',1e7,1e6,5e7,'Hz'),k('reference','Reference SSB white phase-noise floor',-150,-170,-130,'dBc/Hz')],
 'Which noise source wins when PLL bandwidth changes?',
 'Combine independent white reference phase noise with the 1/f² free-running VCO noise from F5. Keep divider N=100 and carrier 100 MHz fixed; vary natural frequency at fixed ζ=1/√2 in the phase-domain design.',
 'Sweep natural frequency with the default reference noise, then raise that noise floor. Compare reference and VCO contributions before calculating converter SNR.',p=>{const x=clockBudget(p),bare=phaseNoise();return O([
 s('Identify where each noise enters the loop','Reference phase passes through N·T/(1+T) to the output. VCO phase disturbance passes through 1/(1+T). The N² factor matters when comparing noise powers.',T`H_r=N\frac{T}{1+T},\quad H_v=\frac1{1+T}`,T`N=100,\quad f_n=${N(p.bandwidth/1000)}\,kHz,\quad\zeta=1/\sqrt2`),
 s('Sum independent output phase-noise densities','Reference noise is white at the selected SSB level. VCO noise is −120 dBc/Hz at 1 MHz with a 1/f² slope. Both are converted to one-sided phase PSDs.',T`S_{out}=2|H_r|^2\ell_r+2|H_v|^2\ell_v`,T`\ell_r=10^{${N(p.reference)}/10}\,Hz^{-1}`),
 s('Integrate before converting to jitter','Integrate 10 kHz through 10 MHz using Simpson quadrature on log frequency with its Jacobian df=f dln f. Components add as variances, not as RMS amplitudes.',T`\sigma_{out}^2=\sigma_r^2+\sigma_v^2=\int_{10^4}^{10^7}S_{out}(f)df`,T`\sigma_r^2=${N(x.vr)}\,rad^2,\quad\sigma_v^2=${N(x.vv)}\,rad^2,\quad\sigma_t=${N(x.jitter*1e12)}\,ps`),
 s('Translate timing noise into the sampled sine error','For small independent timing error, differentiate the input sine. Mean signal and slope powers both contain amplitude squared over two, so amplitude cancels.',T`\delta v\simeq\dot v\delta t,\quad SNR_j=-20\log_{10}(2\pi f_{in}\sigma_t)`,T`2\pi f_{in}\sigma_t=${N(2*Math.PI*p.input*x.jitter)},\quad SNR_j=${N(x.snr)}\,dB`),
 s('Use equivalent bits as a comparison ceiling','Invert the ideal full-scale-sine quantization relation. This is a jitter-only equivalent-bit ceiling, not measured ADC ENOB: converter noise and distortion would reduce total performance.',T`N_{equiv}=(SNR_j-1.76)/6.02`,T`N_{equiv}=${N(x.bits)},\quad\sigma_{t,free\ VCO}=${N(bare.jitter*1e12)}\,ps`)
 ],[r('Integrated clock jitter',x.jitter*1e12,'ps'),r('Jitter-limited sine SNR',x.snr,'dB'),r('Jitter-only equivalent-bit ceiling',x.bits,'bits')],[{label:'Independent output phase-noise contributions',xLabel:'Offset (Hz)',yLabel:'Phase PSD (rad²/Hz)',logX:true,logY:true,traces:[{label:'Reference through loop',points:logpoints(f=>x.density(f).ref,1e4,1e7)},{label:'VCO through loop',points:logpoints(f=>x.density(f).vco,1e4,1e7)}]},{...curve('Bandwidth tradeoff with the selected source spectra','Natural frequency (Hz)','Integrated jitter (ps)',logpoints(bandwidth=>clockBudget({...p,bandwidth}).jitter*1e12,1e4,3e5,41)),logX:true}],
 'A wider loop suppresses more low-offset VCO noise but admits more multiplied reference noise. The best bandwidth depends on both source spectra and the integration band; a single jitter number cannot choose it.',x.snr,'dB','Calculate the jitter-only SNR of the selected ADC sine.','Use −20 log10(2π fin σt), with σt in seconds.',{table:{headers:['Natural frequency (kHz)','Clock jitter (ps)','Sine SNR (dB)'],rows:[10,50,100,300].map(f=>{const y=clockBudget({...p,bandwidth:f*1000});return[f,fmt(y.jitter*1e12),fmt(y.snr)]})}})}, {sources:[source,jitterSource],symbols:[...symbols,[T`H_r,H_v,\ell_r,\ell_v,S_{out},\sigma_t,f_{in},N_{equiv}`,'Reference/output and VCO/output phase gains, SSB noise densities (Hz⁻¹), output phase PSD (rad²/Hz), RMS time jitter (s), ADC sine frequency (Hz), and jitter-only equivalent-bit ceiling.']]})
)
