import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt as F} from '@ee-labs/lessons/model'
import {chargeDAC,sar,arrayErrors,mismatchStats,flash,pipeline,calibrateWeights,dacDrawing} from './converters.js'
const bits=k('bits','Resolution',12,4,12,'bits',1),seed=k('seed','Repeatable sample seed',42,1,999,'',1),sigma=k('sigma','Unit-capacitor fractional sigma',.00316,.0001,.02),fraction=k('fraction','Input / reference',.63,0,1),ref=k('vref','Reference voltage',1,.5,2.5,'V')
const symbols=[[String.raw`N,L,k,b_i,V_{ref},V_{DAC}`,'Resolution (bits), L=2ᴺ code levels, integer code k, bit i (zero is least significant), reference voltage (V) and DAC voltage (V).'],[String.raw`C_u,C_i,C_d,C_b,Q`,'Unit, bit, dummy and bridge capacitances (F); charge on the named floating conductor (C).'],[String.raw`LSB,INL,DNL`,'One ideal code step Vref/2ᴺ; integral and differential nonlinearity (LSB). Each lesson states its endpoint/reference convention.'],[String.raw`\sigma_u,\sigma_m,M`,'Unit-capacitor fractional mismatch standard deviation, single weight-measurement noise (LSB), and number of independent measurements averaged.']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'C. Converter decisions and static errors',knobs,question,intro,try:attempt,solve,symbols,flow:['Write charge balance or the decision rule','Follow the actual code and residue','Measure the error using a named convention'],route:'Charge equations establish DAC levels. A clocked recurrence follows SAR or pipeline decisions. Static transfer levels give INL/DNL; an ensemble estimates manufacturing spread under its declared distribution. Phasors cannot replace a nonlinear code decision.',limits:'Ideal settled switches and comparisons unless an offset is explicitly selected. No settling, thermal noise or aperture jitter is included here. Random errors are reproducible teaching distributions, not fabrication guarantees. Group D treats dynamic errors separately.',sources:[['Analog Devices: ADC and DAC architectures and error definitions','https://www.analog.com/en/resources/technical-articles/types-of-adcs-and-dacs.html']],...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const errorPlots=x=>[curve('Endpoint-referenced integral error','Code','INL (LSB)',x.inl),{...curve('Adjacent step error','Transition to code','DNL (LSB)',x.dnl),stems:true}]
export const CONVERTER_LESSONS=[
L('c1','A floating capacitor array turns bits into voltage',[bits,k('unit','Unit capacitance',20e-15,10e-15,100e-15,'F'),k('code','Requested DAC code',2730,0,4095,'',1),ref,{...k('split','Capacitor arrangement',0,0,1,'',1),options:['Binary array','Split high / low banks']},{...k('phase','Displayed switch phase',1,0,1,'',1),options:['Reset to zero','Apply code']}],
 'Where do the binary weights come from, and what does splitting the array save?',
 'Reset every capacitor to zero voltage, release the common top conductor, then drive each bottom plate to zero or Vref. The top conductor cannot gain net charge, so its voltage moves. A split array adds a second floating conductor and a bridge capacitor.',
 'Switch between binary and split at the same code, then select reset. Reduce resolution: the requested code is limited to the selected converter’s largest code.',p=>{const x=chargeDAC(p),binary=chargeDAC({...p,split:0}),split=chargeDAC({...p,split:1}),H=2**x.high,A=2**x.low;return O([
 s('Count every physical capacitor','A binary array has weighted capacitors 1,2,…,2ᴺ⁻¹ units plus one unit dummy. The split array has no high-bank dummy: its one dummy belongs to the low bank. Let m and n be high/low bit counts, m+n=N.',String.raw`C_{binary}=2^NC_u,\quad C_H=(2^m-1)C_u,\quad C_L=2^nC_u,\quad C_b=\frac{2^n}{2^n-1}C_u`,String.raw`m=${x.high},\ n=${x.low},\quad C_b=${N(x.bridge/1e-15)}\,\mathrm{fF}`),
 s('Write conservation at both floating conductors','SH and SL are sums of capacitance times driven bottom-plate voltage for their banks. Both initial top-node charges are zero. The binary case has one equation: ΣCi(Vo−Vbi)=0.',String.raw`\begin{aligned}(C_H+C_b)V_o-C_bV_l&=S_H\\-C_bV_o+(C_L+C_b)V_l&=S_L\end{aligned}`,String.raw`S_H=\sum_H C_i b_iV_{ref},\quad S_L=\sum_L C_i b_iV_{ref}`),
 s('Eliminate the low-bank node','The bridge attenuates the low-bank contribution by 1/2ⁿ and contributes one unit to the output-node effective capacitance. The high-bank sum plus that unit is exactly 2ᵐCu.',String.raw`\alpha=\frac{C_b}{C_L+C_b}=\frac1{2^n},\quad V_o=\frac{S_H+\alpha S_L}{C_H+\alpha C_L}=V_{ref}\frac{k}{2^N}`,String.raw`k=${x.code},\quad V_o=${N(x.out)}\,\mathrm V\quad\text{in the selected phase}`),
 s('Include the bridge in the area comparison','For this one-dummy topology, the total is (2ᵐ+2ⁿ−1)Cu plus the bridge. Reset still gives zero output even if a nonzero code is waiting in the control.',String.raw`C_{split}=(2^m+2^n-1)C_u+C_b`,String.raw`C_{binary}=${N(binary.total/1e-12)}\,\mathrm{pF},\quad C_{split}=${N(split.total/1e-12)}\,\mathrm{pF}`)
 ],[r('Selected output',x.out,'V'),r('Selected total capacitance',x.total/1e-12,'pF'),r('Binary / split capacitance',binary.total/split.total)],[curve('Ideal settled DAC levels','Code','Voltage (V)',Array.from({length:Math.min(257,2**p.bits)},(_,i)=>{const code=Math.round(i*(2**p.bits-1)/(Math.min(257,2**p.bits)-1));return{x:code,y:p.phase?p.vref*code/2**p.bits:0}}))], 'The native charge projector solves the displayed conductor equations. The saving depends on the exact dummy placement; counting two dummies would describe a different transfer.',x.out,'V','Calculate the output voltage for the displayed phase and effective code.','Reset gives zero. The code phase gives Vref k/2ᴺ.',{schematic:dacDrawing(p),table:{headers:['Conductor check','Computed residual','Expected'],rows:[['Output-node charge',x.qout.toExponential(2)+' C','0 C'],...(p.split?[['Low-node charge',x.qlow.toExponential(2)+' C','0 C']]:[]),['Effective output capacitance',p.split?`${H} Cu`:`${2**p.bits} Cu`,'Used in charge equation'],['Low-bank attenuation',p.split?`1/${A}`:'No low bank','Topology-dependent']]},symbols:[...symbols,[String.raw`m,n,C_H,C_L,V_l,S_H,S_L,\alpha`,'High/low bank bit counts, summed bank capacitances including only the stated low dummy (F), low top-node voltage (V), bottom-drive charge sums (C), and bridge attenuation.']]})}),
L('c2','Follow every SAR trial and comparator decision',[bits,fraction,ref,k('clock','Decision clock',20e6,5e6,50e6,'Hz')],
 'What exactly halves during a successive-approximation conversion?',
 'The SAR tries the largest remaining binary weight, compares the trial DAC voltage with the held input, and keeps or clears that bit. The trial weight halves each clock. The signed comparator difference need not halve or even shrink monotonically.',
 'Move the input slightly across a code boundary. Follow the first changed decision and compare the final residue with one LSB.',p=>{const x=sar(p),first=x.rows[0],native=chargeDAC({bits:p.bits,code:x.code,vref:p.vref,split:1});return O([
 s('Establish the sample and acquisition budget','The input is held during all N comparisons. This teaching timing allocates two additional clocks for acquisition; it does not derive settling from a switch resistance.',String.raw`V_{in}=qV_{ref},\quad LSB=V_{ref}/2^N,\quad f_s=\frac{f_{clock}}{N+2}`,String.raw`V_{in}=${N(x.vin)}\,\mathrm V,\quad f_s=${N(x.rate/1e6)}\,\mathrm{MS/s}`),
 s('Try the highest unresolved bit','Start with accepted code k=0. At bit index i, form kt=k+2ⁱ and compute its DAC voltage using C1’s charge-derived weights.',String.raw`k_t=k+2^i,\quad V_t=V_{ref}k_t/2^N,\quad e_t=V_{in}-V_t`,String.raw`i=${first.bit},\quad k_t=${first.trial},\quad V_t=${N(first.test)}\,\mathrm V,\quad e_t=${N(first.comparison)}\,\mathrm V`),
 s('Keep or clear, then move to the next bit','Keep the trial if et≥0; equality selects the higher code. Otherwise retain the previous accepted code. The table records the comparator difference before each decision and the accepted-code residue after it.',String.raw`k_{next}=\begin{cases}k_t&e_t\ge0\\k&e_t<0\end{cases},\quad i_{next}=i-1,\quad r=V_{in}-V_{DAC}(k_{next})`),
 s('Interpret the final quantization error','For an ideal unsaturated unipolar conversion, the final output code is floor(2ᴺq). The upper endpoint clips to 2ᴺ−1. Final residue is below one LSB except at the exact upper endpoint, where it equals one LSB.',String.raw`k_{final}=\min(2^N-1,\lfloor 2^Nq\rfloor),\quad r_{final}=V_{in}-V_{ref}k_{final}/2^N`,String.raw`k_{final}=${x.code},\quad r_{final}=${N(x.residue)}\,\mathrm V`)
 ],[r('Final code',x.code),r('Final residue',x.residue,'V'),r('Clocks per conversion',x.clocks),r('Conversion rate',x.rate/1e6,'MS/s')],[curve('Signed difference seen by each comparator trial','Decision','Input − trial DAC (V)',x.rows.map((q,i)=>({x:i+1,y:q.comparison})))],'Read the trial and accepted-code columns separately. A cleared bit changes the accepted residue differently from the signed trial difference.',x.code,'','Calculate the final ideal SAR code.','Multiply input/reference by 2ᴺ, round down, and limit to the maximum code.',{check:`Native split-array voltage at the final code: ${native.out.toPrecision(7)} V.`,table:{headers:['Clock / bit','Trial code','Trial voltage','Input − trial','Decision','Accepted code','Residue'],rows:x.rows.map((q,i)=>[`${i+3} / b${q.bit}`,q.trial,F(q.test)+' V',F(q.comparison)+' V',q.keep?'Keep':'Clear',q.code,F(q.residue)+' V'])},symbols:[...symbols,[String.raw`q,f_{clock},f_s,k_t,e_t,r`,'Input/reference ratio, decision clock and conversion rate (Hz), trial code, signed input-minus-trial voltage (V), and accepted-code residue (V).']]})}),
L('c3','Capacitor mismatch becomes code-dependent step error',[bits,sigma,seed],
 'How does a small unit mismatch become a large error at a major carry?',
 'A 2ⁱ-unit capacitor is the sum of independent unit errors, so its absolute sigma grows as √2ⁱ. At a major carry the most significant capacitor turns on while all lower capacitors turn off. Their errors therefore combine rather than average away.',
 'Compare resolution 8 and 12 at the same unit sigma. Change the seed to distinguish one array’s INL curve from the population estimate.',p=>{const x=arrayErrors(p),m=mismatchStats(p),Lcode=2**p.bits;return O([
 s('Specify the manufacturing model','Each unit has mean Cu and Gaussian standard deviation σuCu. Independent weighted-capacitor sums are drawn directly from their resulting normal distributions. The dummy is independent too; no systematic gradient is included.',String.raw`C_i/C_u=2^i+\sigma_u\sqrt{2^i}\,z_i,\quad z_i\sim\mathcal N(0,1)`),
 s('Choose endpoint-referenced INL and DNL','Normalize measured DAC levels between code 0 and code L−1. This removes endpoint gain and offset. z(k) is the resulting code-equivalent level, not a digital converter output.',String.raw`z(k)=(L-1)\frac{V(k)-V(0)}{V(L-1)-V(0)},\quad INL(k)=z(k)-k,\quad DNL(k)=z(k)-z(k-1)-1`,String.raw`\max|INL|=${N(x.worstINL)}\,\mathrm{LSB},\quad\max|DNL|=${N(x.worstDNL)}\,\mathrm{LSB}`),
 s('Estimate the major-carry spread, then measure it across arrays','For small independent errors, the familiar estimate neglects the small endpoint-normalization correction. A seeded 2048-array run computes the exact normalized major-carry DNL. Its spread interval is propagated from the sample-variance estimator.',String.raw`\sigma_{DNL,estimate}\simeq\sigma_u\sqrt{2^N-1}`,String.raw`\sigma_{estimate}=${N(m.estimate)}\,\mathrm{LSB},\quad\widehat\sigma=${N(m.sd)}\,\mathrm{LSB}`),
 s('Turn a three-sigma target into an area requirement','Require the estimated three-sigma major-carry DNL to fit 0.5 LSB. Under the stated mismatch-versus-area law σu∝1/√area, squared sigma ratio gives the needed relative unit area. This does not guarantee worst-code yield across an entire converter.',String.raw`\sigma_{u,required}=\frac{0.5}{3\sqrt{2^N-1}},\quad\frac{Area_{required}}{Area_{now}}=\left(\frac{\sigma_u}{\sigma_{u,required}}\right)^2`,String.raw`\sigma_{u,required}=${N(m.requiredSigma)},\quad Area_{ratio}=${N(m.area)}`)
 ],[r('Estimated major-carry sigma',m.estimate,'LSB'),r('Sample major-carry sigma',m.sd,'LSB'),r('Required relative unit area',m.area)],errorPlots(x),'The single-array curves and the population spread answer different questions. The half-LSB criterion here concerns the major carry; it is not a guarantee of all-code INL, DNL or missing-code performance.',m.area,'','Calculate relative unit area for the three-sigma half-LSB target.','Square the ratio of present unit sigma to required unit sigma.',{table:{headers:['Population statistic','Estimate','95% interval','Samples'],rows:[['DNL mean',F(m.mean.value)+' LSB',m.mean.ci.map(v=>v.toFixed(5)).join(' to '),m.count],['DNL standard deviation',F(m.sd)+' LSB',m.sdCI.map(v=>v.toFixed(5)).join(' to '),m.count],['|Major-carry DNL| ≤ 0.5 LSB',F(100*m.yield.value)+'%',m.yield.ci.map(v=>(100*v).toFixed(2)+'%').join(' to '),m.count]]},plotNote:`All ${Lcode} code levels are evaluated for the displayed array. DNL transition k refers to the step from k−1 to k.`})}),
L('c4','Flash comparator bubbles make the encoder part of the model',[{...bits,value:6,min:4,max:8},k('sigma','Comparator offset sigma',.25,0,1.5,'LSB'),seed,{...fraction,value:.4},{...k('encoder','Thermometer encoder policy',0,0,1,'',1),options:['Count asserted comparators','Highest asserted physical index']}],
 'What happens when neighboring comparators switch out of order?',
 'Each physical comparator has an independent Gaussian offset added to its nominal ladder threshold. We preserve those identities. Count-of-ones and highest-index encoders can produce different codes from the same bubbled thermometer pattern.',
 'Raise offset sigma to 1.5 LSB and switch encoder policy. Watch missing codes and the physical comparator states near the selected input.',p=>{const x=flash(p),Lcode=2**p.bits,center=Math.floor(p.fraction*Lcode),start=Math.max(0,Math.min(Lcode-10,center-5));return O([
 s('Build the ladder and perturb physical thresholds','N bits require 2ᴺ−1 comparators. Comparator j has nominal threshold j/2ᴺ of the reference. Offset is specified in nominal LSB and can put thresholds out of order or outside the input range.',String.raw`t_j=\frac{j+o_j}{2^N},\quad o_j\sim\mathcal N(0,\sigma_{offset}^2),\quad b_j=\mathbf1[q\ge t_j]`,String.raw`N_{comparators}=${Lcode-1},\quad\text{adjacent threshold inversions}=${x.inversions}`),
 s('Apply the selected encoder without reordering comparators','Count-of-ones sums all asserted bits. Highest-index returns the largest asserted physical index, or zero when none is asserted. A hole in the thermometer word affects these policies differently.',String.raw`k_{count}=\sum_j b_j,\quad k_{highest}=\max(\{j:b_j=1\}\cup\{0\})`,String.raw`k_{selected}=${x.code},\quad k_{ideal}=${x.ideal}`),
 s('Measure each code’s actual input interval','Partition [0,1] at every physical threshold voltage and apply the selected encoder inside each interval. Voltage breakpoints are sorted only for integration; comparator indices and encoder behavior are unchanged.',String.raw`w_k=\int_0^1\mathbf1[k(q)=k],dq,\quad DNL_k=2^Nw_k-1`,String.raw`\sum_k w_k=1,\quad\text{zero-width codes}=${x.missing}`),
 s('State the INL reference explicitly','For these monotonic encoders, cumulative code widths give transition positions. The fixed full-scale endpoints 0 and 1 define the reference; this includes offset effects and differs from C3’s measured-DAC endpoint fit.',String.raw`t_k^{encoded}=\sum_{j=0}^{k-1}w_j,\quad INL_k=2^Nt_k^{encoded}-k`,String.raw`\max|INL|=${N(x.worstINL)}\,\mathrm{LSB}`)
 ],[r('Encoded output',x.code),r('Ideal output',x.ideal),r('Missing codes',x.missing),r('Maximum transition INL magnitude',x.worstINL,'LSB')],errorPlots(x),'Threshold disorder is not repaired by renaming comparators. This lesson makes the encoder rule visible; real bubble-correction logic needs its own specified behavior.',Lcode-1,'','How many comparators are required at the selected resolution?','A full flash uses 2ᴺ−1 internal thresholds.',{table:{headers:['Physical comparator','Nominal / Vref','Actual / Vref','Asserted'],rows:x.thresholds.slice(start,start+10).map((t,i)=>[start+i+1,F((start+i+1)/Lcode),F(t),x.thermometer[start+i]?'1':'0'])},plotNote:'The table shows up to ten comparators around the selected input in their original physical order. The plots integrate all comparators and all codes.',symbols:[...symbols,[String.raw`t_j,o_j,q,w_k,b_j`,'Threshold/reference ratio, comparator offset in nominal LSB, input/reference ratio, fraction of full input range assigned to code k, and asserted comparator state.']]})}),
L('c5','Pipeline redundancy corrects decisions while residues stay in range',[k('stages','Redundant 1.5-bit stages',10,1,10,'',1),k('fraction','Bipolar input / reference',.3,-1,1),k('offset','Common comparator-threshold shift / reference',.15,-.3,.3)],
 'How can an imperfect early decision still produce the correct final code?',
 'Each redundant stage chooses −1, 0 or +1 and passes twice its input minus that decision to the next stage. A two-bit backend quantizes the final residue. Digital combination weights every stage decision and propagates carries.',
 'Compare offsets 0, +0.25 and +0.30. Sweep input and inspect residue limits before trusting the reconstructed code.',p=>{const x=pipeline(p);return O([
 s('Write the three decisions and the residue recurrence','Voltages are normalized to Vref; each stage input should be in [−1,+1]. Both comparator thresholds receive the displayed shift o. The stage’s two comparator bits represent three decisions, not 1.5 independent information bits.',String.raw`d_i=\begin{cases}-1&x_i<-1/4+o\\0&-1/4+o\le x_i<1/4+o\\1&x_i\ge1/4+o\end{cases},\quad x_{i+1}=2x_i-d_i`,String.raw`x_1=${N(p.fraction)},\quad d_1=${x.rows[0].d},\quad x_2=${N(x.rows[0].residue)}`),
 s('Check why the quarter-reference offset bound matters','Immediately below the upper decision threshold, the middle branch gives residue 1/2+2o; immediately above the lower threshold it gives −1/2+2o. Requiring both to stay in [−1,+1] yields |o|≤1/4. The outer branches impose the same bound.',String.raw`-1\le-1/2+2o,\quad1/2+2o\le1\quad\Rightarrow\quad |o|\le1/4`,String.raw`|o|=${N(Math.abs(p.offset))},\quad\text{all selected residues within range: }${x.valid?'yes':'no'}`),
 s('Include the backend when counting resolution','S one-bit-effective redundant stages followed by a two-bit backend provide S+2 bits. The backend uses four uniform lower-edge levels over [−1,+1], clipping the exact upper endpoint to its largest code.',String.raw`b=clip_{0..3}(\lfloor2(x_{S+1}+1)\rfloor),\quad\widehat x_{S+1}=-1+b/2,\quad N=S+2`,String.raw`S=${p.stages},\quad b=${x.backend},\quad N=${x.bits}`),
 s('Combine weighted decisions, including carries','Unroll the recurrence: x1=Σdi/2ⁱ+xS+1/2ˢ. Replacing only the last residue by its backend level gives the full-scale code below. It can agree with the ideal quantizer even when individual di values change.',String.raw`k=2^{S+1}+\sum_{i=1}^{S}d_i2^{S+1-i}-2+b`,String.raw`k=${x.code},\quad k_{ideal}=${x.ideal},\quad\widehat x_1=${N(x.reconstructed)}`)
 ],[r('Effective resolution',x.bits,'bits'),r('Reconstructed code',x.code),r('Ideal code',x.ideal),r('Code error',x.code-x.ideal,'LSB')],[{label:'First-stage residue over the input range',xLabel:'Input / reference',yLabel:'Residue / reference',traces:[{label:'Selected threshold shift',points:samples(fraction=>pipeline({...p,stages:1,fraction}).rows[0].residue,-1,1,257)},{label:'Zero shift',points:samples(fraction=>pipeline({...p,stages:1,fraction,offset:0}).rows[0].residue,-1,1,257)}]}],!x.valid?'A residue exceeds the next stage’s range. The clipped code is shown to expose the failure; redundancy does not guarantee correction here.':x.guard?'All selected residues fit, and the threshold shift is inside the full-range redundancy bound.':'This input happens to keep residues in range, but the shift exceeds the full-range bound. Other inputs can fail.',x.code,'','Combine the stage decisions and backend into the final code.','Use the signed weighted sum; the backend contributes −2+b.',{table:{headers:['Stage','Input / Vref','Decision','Residue / Vref','Range check'],rows:x.rows.map(q=>[q.stage,F(q.input),q.d,F(q.residue),Math.abs(q.residue)<=1+1e-12?'Within ±1':'Outside ±1'])},symbols:[...symbols,[String.raw`S,x_i,d_i,o,b,\widehat x_i`,'Number of redundant stages, normalized stage input, signed stage decision, normalized comparator shift, two-bit backend code, and reconstructed normalized input.']],sources:[['Analog Devices: understanding pipelined ADCs','https://www.analog.com/en/resources/technical-articles/understanding-pipelined-adcs.html']]})}),
L('c6','Calibrate the voltage represented by a capacitor code',[bits,sigma,seed,k('measurement','Single weight-measurement noise sigma',.05,0,.25,'LSB'),k('averages','Independent measurements per weight',16,1,256,'',1)],
 'What can a stored weight calibration correct, and what information is still lost?',
 'The actual DAC weights differ from ideal powers of two. A calibration measures each weight and stores it, allowing a digital code to be reported as an estimated physical voltage. This is a calibrated level estimate; the capacitor array itself and its code spacing remain unchanged.',
 'Set measurement noise to zero, then raise it. Increase averages from 1 to 16 and compare the same seeded error realization. The estimate error should shrink by four.',p=>{const x=calibrateWeights(p),Lcode=2**p.bits;return O([
 s('Express actual weights in nominal LSB','The physical weight wi is Ci divided by all capacitance, including the dummy. A code’s actual voltage in nominal LSB is the sum of its asserted physical weights times 2ᴺ.',String.raw`w_i=\frac{C_i}{C_d+\sum_j C_j},\quad y(k)=2^N\sum_i b_i(k)w_i`,String.raw`y(2^N-1)=${N(x.weights.reduce((a,b)=>a+b,0)*Lcode)}\,\mathrm{LSB}`),
 s('Model the measurement rather than declaring perfect calibration','Each stored weight is an independent unbiased Gaussian measurement. Averaging M independent observations reduces its standard deviation to σm/√M. A shared reference error would not average away and is excluded here.',String.raw`\widehat W_i=2^Nw_i+\epsilon_i,\quad\epsilon_i\sim\mathcal N(0,\sigma_m^2/M)`,String.raw`\sigma_{stored}=${N(x.sd)}\,\mathrm{LSB}`),
 s('Compare uncalibrated and calibrated level estimates','Before calibration the reported level is simply integer k. Afterwards it is the sum of stored weights. The displayed error is estimated voltage minus actual DAC voltage; it is not a new physical transfer curve or repaired ADC code bin.',String.raw`e_{before}(k)=k-y(k),\quad e_{after}(k)=\sum_i b_i(k)\widehat W_i-y(k)=\sum_i b_i(k)\epsilon_i`,String.raw`\max|e_{before}|=${N(x.worstBefore)}\,\mathrm{LSB},\quad\max|e_{after}|=${N(x.worstAfter)}\,\mathrm{LSB}`),
 s('Carry the measurement uncertainty into the estimate','For h asserted bits, independent errors give sigma σm√(h/M). The ±1.96σ interval is pointwise over repeated calibrations, not a simultaneous bound on the maximum of the whole plotted curve.',String.raw`\sigma_e(k)=\sigma_m\sqrt{h(k)/M},\quad h(2^N-1)=N`,String.raw`95\%\text{ pointwise interval at all-ones code: }\pm${N(x.allOn95)}\,\mathrm{LSB}`)
 ],[r('Largest uncalibrated estimate error',x.worstBefore,'LSB'),r('Largest calibrated estimate error',x.worstAfter,'LSB'),r('All-ones pointwise 95% half-width',x.allOn95,'LSB')],[{label:'Estimated level minus actual physical level',xLabel:'Code',yLabel:'Voltage estimate error (LSB)',traces:[{label:'Ideal binary interpretation',points:x.before},{label:'Stored measured weights',points:x.after}]}],'Weight calibration can improve the voltage assigned to a known code. It does not create missing ADC information or change the DAC’s physical DNL; those require additional analog or conversion design.',x.allOn95,'LSB','Calculate the all-ones code’s pointwise 95% uncertainty half-width.','Use 1.96 σm √(N/M).',{table:{headers:['Bit','Ideal weight (LSB)','Actual weight (LSB)','Stored weight (LSB)'],rows:x.weights.map((w,i)=>[i,2**i,F(w*Lcode),F(x.measured[i])])},symbols:[...symbols,[String.raw`w_i,\widehat W_i,y(k),\epsilon_i,e(k),h(k)`,'Physical fractional capacitor weight, stored weight in nominal LSB, actual code level in LSB, stored-weight measurement error, reported-level error, and asserted-bit count.']]})})
]
