import {ZERO_DRIFT_LESSONS} from './zeroDriftLessons.js'
import {CLOCK_LESSONS} from './clockLessons.js'
import {NOISE_SHAPING_LESSONS} from './noiseShapingLessons.js'
import {CONVERTER_LESSONS} from './converterLessons.js'
import {DYNAMIC_LESSONS} from './dynamicLessons.js'
import {SC_LESSONS} from './scLessons.js'
import {knob as k,step as s,reading as r,curve,samples,texnum as N} from '@ee-labs/lessons/model'
import {K,COX,acquisition,chargeShare,injection,thermal,bottomPlate,jitter,rcSchematic,shareSchematic,bottomSchematic} from './models.js'
const cap=k('capacitance','Sampling capacitance',1e-12,.1e-12,10e-12,'F'),bits=k('bits','Resolution',12,8,16,'bits',1),res=k('resistance','Switch on-resistance',1000,100,10000,'Ω')
const symbols=[[String.raw`V_{in},V_H`,'Input and held capacitor voltage (V), measured to the indicated reference.'],[String.raw`C_s,R_{on},\tau`,'Sampling capacitance (F), closed-switch resistance (Ω), and acquisition time constant Ron Cs (s).'],[String.raw`t,t_{acq},N`,'Time (s), acquisition duration (s), and integer resolution in bits.'],[String.raw`Q,k_B,T`,'Electric charge (C), Boltzmann constant 1.380649×10⁻²³ J/K, and absolute temperature (K).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'A. A capacitor remembers a voltage',knobs,question,intro,try:attempt,solve,symbols,flow:['Identify the switch phase and stored state','Conserve charge or solve its change with time','Compare the residual error with a stated resolution'],route:'Use charge conservation across an ideal switch event, and state equations during a finite-resistance phase. A phasor describes the continuously tracking RC response, but cannot alone represent opening a switch or sampling jitter.',limits:'Lumped, idealized sampling circuits. Each lesson names the resistance, charge, noise or timing effect it includes. These are foundations for converter design, not complete ADC/DAC implementations.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,plotNote:'Predict the effect of a setting before changing it. Voltage errors are signed where charge direction is known; rms noise and settling bounds are magnitudes.',practice:{answer,unit,question,hint,reason:conclusion},...extra}}
export const EXTENDED=[
L('a1','Acquire before you hold',[res,cap,bits,k('time','Acquisition duration',9e-9,.1e-9,1e-6,'s')],'How long must the switch stay closed for a full-scale step to settle?',
'The held capacitor voltage is the state. It begins at zero and approaches a 1 V input through the closed switch. Opening the ideal switch freezes that state at the acquisition time.',
'At Ron = 1 kΩ and Cs = 1 pF, compare 10 and 12 bits. Add one time constant and predict the remaining-error factor.',p=>{const x=acquisition(p);return O([
s('Write current balance while tracking','The resistor current charges the capacitor. The initial value VH(0⁻)=0 also equals VH(0⁺) because this finite-resistance connection cannot create an impulse of capacitor current.',String.raw`C_s\dot V_H=(V_{in}-V_H)/R_{on},\quad V_H(0^+)=0,\quad\tau=R_{on}C_s`,String.raw`\tau=${N(x.tau*1e9)}\,\mathrm{ns}`),
s('Solve the state equation and stop at the opening time','For a constant 1 V input, the derivative decays exponentially. During ideal hold, the derivative becomes zero.',String.raw`V_H(t)=V_{in}(1-e^{-t/\tau}),\quad e(t)=V_{in}-V_H(t)=V_{in}e^{-t/\tau}`,String.raw`V_H(t_{acq})=${N(x.held)}\,\mathrm V,\quad e(t_{acq})=${N(x.error)}\,\mathrm V`),
s('Require less than half an LSB','A full-scale step must leave less than VFS/2^(N+1) error. Taking natural logs converts the exponential bound to a time bound.',String.raw`e^{-t_{acq}/\tau}\le2^{-(N+1)}\Rightarrow t_{acq}\ge(N+1)\ln2\,\tau`,String.raw`t_{required}=${N(x.required*1e9)}\,\mathrm{ns},\quad e_{limit}=${N(x.limit*1e6)}\,\mu\mathrm V`)
],[r('Time constant',x.tau*1e9,'ns'),r('Required acquisition',x.required*1e9,'ns'),r('Remaining error',x.error*1e6,'μV')],[curve('Tracking a 1 V step','Time / τ','Held voltage (V)',samples(t=>1-Math.exp(-t),0,12))],x.error<=x.limit?'The selected acquisition time meets the half-LSB settling bound. Extending time by one τ multiplies the remaining error by e⁻¹.':'The switch opens too early for this resolution. Shortening time by one τ multiplies the remaining error by e, making it larger.',x.required*1e9,'ns','Calculate the required acquisition duration.','Multiply (N+1) ln(2) by Ron Cs.',{schematic:rcSchematic(p)})}),
L('a2','Charge sharing changes the initial condition',[k('c1','First capacitor',1e-12,.1e-12,10e-12,'F'),k('c2','Second capacitor',1e-12,.1e-12,10e-12,'F'),k('v1','First initial voltage',1,0,2,'V'),k('v2','Second initial voltage',0,0,2,'V'),k('resistance','Connection resistance',1,1,1000,'Ω')],'Where does the missing energy go when two capacitors share charge?',
'Two isolated capacitor top plates are connected. The ideal switch calculation projects the two initial voltages onto one shared voltage by conserving charge. A finite resistor resolves the same event in time and dissipates the missing energy.',
'Start with two 1 pF capacitors at 1 V and 0 V. Change connection resistance and identify which final quantities stay fixed.',p=>{const x=chargeShare(p);return O([
s('Record charge immediately before connection','Capacitances multiply their own initial voltages. A common reference is essential when adding charge.',String.raw`Q_{before}=C_1V_1(0^-)+C_2V_2(0^-)`,String.raw`Q_{before}=${N(x.charge*1e12)}\,\mathrm{pC}`),
s('Impose one voltage after the ideal event','Charge is conserved while the two node voltages become equal. This instantaneous projection is distinct from finite-R continuity.',String.raw`(C_1+C_2)V_f=Q_{before}\Rightarrow V_f=\frac{C_1V_1+C_2V_2}{C_1+C_2}`,String.raw`V_f=${N(x.voltage)}\,\mathrm V`),
s('Account for the energy difference','The charge constraint does not conserve capacitor energy. With finite R, integrate i²R over the redistribution transient.',String.raw`W_i=\tfrac12C_1V_1^2+\tfrac12C_2V_2^2,\quad W_f=\tfrac12(C_1+C_2)V_f^2,\quad W_R=W_i-W_f`,String.raw`W_i=${N(x.initial*1e12)},\quad W_f=${N(x.final*1e12)},\quad W_R=${N(x.loss*1e12)}\quad\mathrm{pJ}`),
s('Resolve the switch event with finite resistance','Subtract the two capacitor current equations. Their voltage difference decays with the series-equivalent capacitance.',String.raw`\Delta V(t)=(V_1-V_2)e^{-t/\tau_d},\quad\tau_d=R\frac{C_1C_2}{C_1+C_2}`,String.raw`\tau_d=${N(x.tau*1e12)}\,\mathrm{ps}`)
],[r('Shared voltage',x.voltage,'V'),r('Dissipated energy',x.loss*1e12,'pJ'),r('Redistribution time constant',x.tau*1e12,'ps')],[{label:'Finite-R redistribution',xLabel:'Time / τd',yLabel:'Capacitor voltage (V)',traces:[{label:'C1',points:samples(t=>x.at(t*x.tau).v1,0,12)},{label:'C2',points:samples(t=>x.at(t*x.tau).v2,0,12)}]}], 'Resistance changes the transient duration but not the final shared voltage or total loss. An ideal zero-duration jump hides the dissipation mechanism; it does not establish energy conservation.',x.voltage,'V','Calculate the final common voltage.','Add initial charges and divide by total capacitance.',{schematic:shareSchematic(p)})},{symbols:[...symbols,[String.raw`C_1,C_2,V_1,V_2,V_f`,'Capacitances (F), initial node voltages (V), and final common voltage (V).'],[String.raw`W_i,W_f,W_R,\tau_d`,'Initial and final stored energy and dissipated energy (J), and differential-mode time constant (s).']]}),
L('a3','Opening a MOS switch leaves a pedestal',[cap,k('width','Switch width',1e-6,.2e-6,10e-6,'m'),k('vin','Sampled input',0,0,1,'V'),k('dummy','Half-width dummy (0 off, 1 on)',0,0,1,'',1),k('mismatch','Dummy charge mismatch',0,-.2,.2)],'How much of the switch-opening error comes from channel charge and clock coupling?',
'An NMOS channel contains negative mobile charge. When the switch opens, an assumed half of that charge reaches the sampling capacitor. A falling clock also couples through an overlap capacitance. A dummy switch can cancel one modeled contribution without canceling the other.',
'Enable the dummy at zero mismatch, then add 10% mismatch. Explain the residual feedthrough even with ideal channel cancellation.',p=>{const x=injection(p);return O([
s('Estimate the channel-charge magnitude','Use L = 0.18 μm, Cox = 8.63 fF/μm², Vclk = 1.8 V and threshold 0.45 V. This is a strong-inversion charge estimate.',String.raw`|Q_{ch}|=WLC_{ox}(V_{clk}-V_{in}-V_T)`,String.raw`|Q_{ch}|=${N(x.q*1e15)}\,\mathrm{fC}`),
s('Assign the charge reaching the held node','The partition fraction α is assumed 0.5. Negative electron charge causes a negative voltage step.',String.raw`\Delta V_{ch}=-\alpha|Q_{ch}|/C_s`,String.raw`\Delta V_{ch}=${N(x.channel*1e3)}\,\mathrm{mV}`),
s('Add clock feedthrough and the optional dummy contribution','Cov = 0.2 fF couples a −1.8 V clock edge. The half-width dummy model returns +0.5Qch(1+ε) when enabled.',String.raw`\Delta V_{ft}=C_{ov}\Delta V_{clk}/C_s,\quad\Delta V_d=d\frac{0.5|Q_{ch}|(1+\epsilon)}{C_s}`,String.raw`\Delta V_{ft}=${N(x.feed*1e3)}\,\mathrm{mV},\quad\Delta V_d=${N(x.dummy*1e3)}\,\mathrm{mV}`),
s('Compare the signed pedestal with a 12-bit, 1 V range','One LSB is 1/4096 V. The dummy only cancels the modeled channel term under matched charge and partition assumptions.',String.raw`\Delta V=\Delta V_{ch}+\Delta V_{ft}+\Delta V_d,\quad error_{LSB}=\Delta V/(1/4096)`,String.raw`\Delta V=${N(x.total*1e3)}\,\mathrm{mV}=${N(x.total/x.lsb)}\,\mathrm{LSB}`)
],[r('Total pedestal',x.total*1e3,'mV'),r('Pedestal',x.total/x.lsb,'LSB')],[curve('Input-dependent pedestal','Input voltage (V)','Error (mV)',samples(vin=>injection({...p,vin}).total*1e3,0,1))], 'Charge partition, clock slope, signal level and parasitics matter. The dummy is an explicit ideal cancellation model; it is not a general claim that a half-width switch halves the physical error.',x.total*1e3,'mV','Calculate the signed total pedestal.','Add the channel, dummy and feedthrough steps with their signs.',{schematic:rcSchematic(p),table:{headers:['Contribution','Signed step (mV)'],rows:[['Channel injection',x.channel*1000],['Clock feedthrough',x.feed*1000],['Dummy compensation',x.dummy*1000]]}})},{symbols:[...symbols,[String.raw`W,L,C_{ox},V_T`,'Switch width and length (m), oxide capacitance density (F/m²), and threshold voltage (V).'],[String.raw`\alpha,C_{ov},d,\epsilon`,'Channel partition fraction 0.5, clock overlap capacitance 0.2 fF, dummy enable 0/1, and fractional dummy mismatch.']]}),
L('a4','Why sampled thermal noise is kT/C',[cap,res,k('temperature','Absolute temperature',300,250,400,'K'),bits],'Why does lowering switch resistance fail to lower the fully settled thermal noise?',
'A smaller switch resistance lowers its white noise density but widens the tracking bandwidth by the same factor. The integrated capacitor noise therefore depends on temperature and capacitance after a sufficiently long track phase.',
'Change resistance by a factor of ten. Then change capacitance by a factor of four and predict the rms noise.',p=>{const x=thermal(p);return O([
s('Write the one-sided tracking noise spectrum','The switch resistance has thermal voltage density 4kTR. The RC magnitude squared filters that density.',String.raw`S_v(f)=\frac{4k_BTR_{on}}{1+(2\pi fR_{on}C_s)^2}`,String.raw`f_c=\frac1{2\pi R_{on}C_s}=${N(x.fc/1e6)}\,\mathrm{MHz}`),
s('Integrate over all positive frequencies','With u = 2πfRonCs, the integral of 1/(1+u²) from zero to infinity is π/2. Resistance cancels.',String.raw`\sigma_v^2=\int_0^\infty S_v(f)df=\frac{2k_BT}{\pi C_s}\frac\pi2=\frac{k_BT}{C_s}`,String.raw`\sigma_v=${N(x.rms*1e6)}\,\mu\mathrm V`),
s('Translate an explicitly chosen signal reference into a capacitance bound','Use a 1 V rms sine for this comparison, not a 1 V peak-to-peak ADC range. Require this one noise contribution to reach 6.02N+1.76 dB.',String.raw`SNR=20\log_{10}(1\,\mathrm{V_{rms}}/\sigma_v),\quad C_{min}=\frac{k_BT}{(1\,\mathrm V)^2}10^{(6.02N+1.76)/10}`,String.raw`SNR=${N(x.snr)}\,\mathrm{dB},\quad C_{min}=${N(x.minC*1e12)}\,\mathrm{pF}`)
],[r('Thermal noise',x.rms*1e6,'μV rms'),r('SNR for 1 V rms signal',x.snr,'dB'),r('Required capacitance',x.minC*1e12,'pF')],[curve('Accumulated noise versus integration bandwidth','Upper frequency / fc','Fraction of kT/C',samples(u=>2/Math.PI*Math.atan(u),0,20))], 'Reducing Ron helps acquisition time, but does not reduce the settled kT/C variance. The capacitance target assigns the entire noise allowance to sampling noise; a complete converter needs margin for other terms.',x.rms*1e6,'μV','Calculate the rms sampled thermal noise.','Take the square root of kBT/Cs and convert to microvolts.',{schematic:rcSchematic(p)})}),
L('a5','The order of opening switches matters',[cap,k('vin','Input voltage',.5,0,1,'V'),{...k('order','Opening order',1,0,1,'',1),options:['Input switch first','Bottom plate switch first']},{...k('phase','Switch phase',2,0,2,'',1),options:['0: Track','1: First switch opens','2: Both switches open']}],'How does opening the grounded bottom-plate switch first remove signal-dependent charge injection?',
'The sampling capacitor has a switch from its top plate to the input and a switch from its bottom plate to ground. During tracking its differential voltage is Vin. Opening the grounded switch first makes its turn-off overdrive independent of Vin.',
'Compare both opening orders while sweeping Vin. Step through phases 0, 1 and 2 and distinguish a constant pedestal from distortion.',p=>{const x=bottomPlate(p),normal=injection({vin:p.vin,capacitance:p.capacitance,overlap:0}).q,constant=injection({vin:0,capacitance:p.capacitance,overlap:0}).q;return O([
s('Define the held state and the first opening event','The state is the capacitor differential voltage VH=Vtop−Vbottom. During tracking Vtop=Vin and Vbottom=0.',String.raw`V_H(0^-)=V_{top}-V_{bottom}=V_{in}`,String.raw`V_H(0^-)=${N(p.vin)}\,\mathrm V`),
s('Compare signal-dependent and fixed charge magnitudes','Input-first opening uses Vclk−Vin−VT. Ground-switch opening uses Vclk−VT, so its charge has no input term.',String.raw`|Q_{input}|=WLC_{ox}(V_{clk}-V_{in}-V_T),\quad |Q_{ground}|=WLC_{ox}(V_{clk}-V_T)`,String.raw`|Q_{input}|=${N(normal*1e15)},\quad |Q_{ground}|=${N(constant*1e15)}\quad\mathrm{fC}`),
s('Follow the sign into the differential voltage','For input-first opening, negative top-plate charge lowers VH. For bottom-first opening, negative bottom-plate charge raises VH. Once one plate floats, opening the other ideal switch cannot change the stored differential voltage.',String.raw`\Delta V_{H,input}=-\frac{\alpha|Q_{input}|}{C_s},\quad\Delta V_{H,bottom}=+\frac{\alpha|Q_{ground}|}{C_s}`,String.raw`\Delta V_H(phase\ ${p.phase})=${N(x.error*1e3)}\,\mathrm{mV},\quad V_H=${N(x.held)}\,\mathrm V`)
],[r('Phase',p.phase),r('Differential pedestal',x.error*1e3,'mV'),r('Held differential voltage',x.held,'V')],[{label:'Switch order and distortion',xLabel:'Input voltage (V)',yLabel:'Differential error (mV)',traces:[{label:'Input first',points:samples(vin=>bottomPlate({...p,vin,order:0}).error*1000,0,1)},{label:'Bottom plate first',points:samples(vin=>bottomPlate({...p,vin,order:1}).error*1000,0,1)}]}], 'Bottom-plate-first switching makes the ideal pedestal independent of input; it does not make every voltage error zero. Plate parasitics, clock overlap and incomplete settling reintroduce error in physical circuits.',x.held,'V','Calculate the held differential voltage at the selected phase.','Add the signed differential pedestal to Vin.',{schematic:bottomSchematic(p),table:{headers:['Phase','Input first','Bottom plate first'],rows:[['0: tracking','Both closed; VH = Vin','Both closed; VH = Vin'],['1: first opening','Input opens; signal-dependent negative pedestal','Ground opens; fixed positive differential pedestal'],['2: second opening','Ground opens; ideal differential charge holds','Input opens; ideal differential charge holds']]}})},{symbols:[...symbols,[String.raw`V_{top},V_{bottom},\alpha`,'Top and bottom plate voltages (V); assumed charge partition fraction α = 0.5.'],[String.raw`W,L,C_{ox},V_{clk},V_T`,'Fixed switch width 1 μm, length 0.18 μm, oxide density 8.63 fF/μm², clock high 1.8 V and threshold 0.45 V.']]}),
L('a6','Timing uncertainty becomes voltage noise',[k('frequency','Input sine frequency',10e6,.1e6,20e6,'Hz'),k('sigma','Rms aperture jitter',1e-12,.1e-12,100e-12,'s'),bits,k('seed','Random seed',42,1,1000,'',1)],'Why does the same clock become inadequate as input frequency rises?',
'The sampler observes a 1 V peak sine at 160 MS/s. Each sample gets an independent Gaussian time error. The error is the actual sine value at the displaced time minus the value at the intended time.',
'Increase input frequency by ten and predict the SNR loss. Change the seed to distinguish a repeatable model result from finite-record variation.',p=>{const x=jitter(p),w=2*Math.PI*p.frequency;return O([
s('Convert time error to voltage error','For sufficiently small ωδt, use the derivative at each sample. High slopes magnify the same timing error.',String.raw`e_v[n]=\sin(\omega(t_n+\delta t_n))-\sin(\omega t_n)\simeq\omega\cos(\omega t_n)\delta t_n`,String.raw`\omega\sigma_t=${N(w*p.sigma)}\ll1`),
s('Average error power over sine phase','The mean squared cosine is 1/2. Signal power is also 1/2 V² for the 1 V peak sine, so amplitude cancels from SNR.',String.raw`\sigma_e^2\simeq\omega^2\sigma_t^2/2,\quad SNR_{jitter}=-20\log_{10}(2\pi f\sigma_t)`,String.raw`SNR_{jitter}=${N(x.snr)}\,\mathrm{dB}`),
s('Measure a seeded time record','The simulation evaluates the displaced sine directly, not the derivative approximation. Its 8192 squared errors provide a mean-power estimate and an approximate normal confidence interval.',String.raw`\widehat P_e=\frac1M\sum_{n=0}^{M-1}e_v[n]^2,\quad\widehat{SNR}=10\log_{10}(0.5/\widehat P_e)`,String.raw`\widehat{SNR}=${N(x.measured)}\,\mathrm{dB},\quad95\%\ CI\simeq[${N(x.ci[0])},${N(x.ci[1])}]\,\mathrm{dB}`),
s('Solve the jitter allowance for a resolution target','Use the ideal full-scale-sine quantization SNR as a comparison target. Assigning it all to jitter leaves no margin for other noise.',String.raw`\sigma_{t,max}=\frac{10^{-(6.02N+1.76)/20}}{2\pi f}`,String.raw`\sigma_{t,max}=${N(x.required*1e12)}\,\mathrm{ps}`)
],[r('Analytic jitter SNR',x.snr,'dB'),r('Measured SNR',x.measured,'dB'),r('Jitter allowance',x.required*1e12,'ps')],[curve('First 128 timing-induced errors','Sample index','Voltage error (μV)',x.record)], 'The analytic curve describes the ensemble; the finite record fluctuates with seed. Clock phase-noise correlation, signal-independent ADC noise and quantization are omitted here.',x.required*1e12,'ps','Calculate the maximum rms jitter for the selected resolution target.','Convert the target dB ratio to an amplitude ratio and divide by 2πf.')},{symbols:[...symbols,[String.raw`f,\omega,t_n,\delta t_n,\sigma_t`,'Input frequency (Hz), angular frequency 2πf (rad/s), intended sample time (s), random time error (s) and its rms value (s).'],[String.raw`e_v[n],M,\widehat P_e`,'Voltage error at sample n (V), record length 8192, and estimated mean-square error (V²).']]}),
...SC_LESSONS,...CONVERTER_LESSONS,...DYNAMIC_LESSONS,...NOISE_SHAPING_LESSONS,...CLOCK_LESSONS
,...ZERO_DRIFT_LESSONS
]
