import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {quantizationRecord,bandPower,spectrum,shapedPower,noiseExperiment,modulator,decimation,ntfPower,RECORD,TONE_BIN} from './noiseShaping.js'
const T=String.raw,osr=k('osr','Oversampling ratio',64,8,256,'',1),amp=k('amplitude','Input sine peak',.5,.1,.9,'V'),seed={...k('seed','Noise-model seed',42,1,999,'',1),group:'Record'}
const sources=[['Analog Devices: Sigma-Delta ADCs Tutorial','https://www.analog.com/en/resources/technical-articles/sigmadelta-adcs-tutorial.html'],['Analog Devices: Using Sigma-Delta Converters','https://www.analog.com/en/resources/analog-dialogue/articles/using-sigma-delta-converters-1.html']]
const commonSymbols=[[T`n,M,f_s,f,B,OSR`,'Integer sample index, record length M=16384, sample rate (Hz), frequency (Hz), retained band edge B=fs/(2·OSR), and oversampling ratio. Plots use normalized frequency f/fs unless Hz is shown.'],[T`A,N,L,\ell,\nu,\sigma_e^2,K`,'Sine peak (V), quantizer resolution (bits), level count L=2^N, shaping order ℓ, normalized frequency ν=f/fs, quantizer-error variance (V²), and a final sample/bin index as specified in each equation.'],[T`u[n],y[n],e[n],\Delta,P`,'Input, quantized output and quantizer error (V); quantizer step (V), and mean-square voltage power (V²). “Power” here assumes no particular load resistance.'],[T`U,Y,E,X_1,X_2`,'Z transforms of u, y, quantizer error e, and the integrator states. E denotes the transform of an error signal, not a voltage-source name.'],[T`z,z^{-1},Q,NTF,STF`,'Discrete-time transform variable; one-sample delay; nonlinear quantizer; noise and signal transfer functions of the additive-error representation. z⁻¹ is a delay, not division by time.'],[T`x_1[n],x_2[n],v[n],x[-1]`,'Updated integrator states (V), quantizer input (V), and states immediately before retained sample zero. These may be nonzero after warm-up; E5 instead resets them to zero. Discrete updates replace a continuous derivative.'],[T`P_{model},P_{record},SNDR`,'Noise power predicted under white independent quantizer-error assumptions; measured finite-record in-band error power; signal-to-error ratio including distortion (dB).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}) {return {id,name,group:'E. Noise shaping',knobs,question,intro,try:attempt,solve,symbols:commonSymbols,sources,route:'Use the sample-by-sample state equations to run the nonlinear quantizer. Use the z transform to derive how an additive quantizer error reaches the output. Evaluate z=exp(j2πf/fs) to inspect the frequency response. Only after declaring a statistical model for that error can the transfer predict a noise power; a transfer function alone cannot predict idle tones or overload.',limits:'Ideal sampled-data behavioral models with declared update order. No switched-capacitor settling, comparator delay, DAC mismatch, jitter or analog thermal noise. White independent quantizer error is an approximation, tested against the actual finite record rather than imposed on it.',flow:['Name the states, quantizer and sampling convention','Derive the signal and error paths','Measure the actual record and compare the assumptions'],...extra}}
function O(steps,readings,plots,conclusion,question,answer,unit,hint,extra={}){return {steps,readings,plots,conclusion,practice:{question,answer,unit,hint,reason:conclusion},...extra}}
const points=(values,count=256)=>Array.from({length:Math.min(count,values.length)},(_,i)=>{const n=Math.floor(i*(values.length-1)/(Math.min(count,values.length)-1));return {x:n,y:values[n]}})
const powerPoints=x=>{const out=[];for(let i=1;i<x.powers.length;i+=8){let best=i;for(let j=i;j<Math.min(i+8,x.powers.length);j++)if(x.powers[j]>x.powers[best])best=j;out.push({x:best*x.df,y:10*Math.log10(Math.max(1e-16,x.powers[best]))})}return out}
const spectrumPlot=(a,b,label='Actual error versus the independent-noise record')=>({label,xLabel:'Normalized frequency f/fs',yLabel:'Bin power (dB relative to 1 V²)',logX:true,traces:[{label:'Actual quantizer error path',points:powerPoints(a)},{label:'Independent white-error model',points:powerPoints(b)}]})
const plotNote='Spectra use the complete rectangular-window record, with DC retained in power sums. The graph shows the strongest bin in each group of eight and floors only displayed powers at −160 dB relative to 1 V². Numerical metrics use every bin, with no display floor. A single periodogram has substantial statistical variation.'
const rowsTable=x=>({headers:['n','u (V)','Previous y (V)','Updated x1 (V)','Updated x2 (V)','y (V)'],rows:x.rows.map(z=>[z.n,fmt(z.u),fmt(z.old),fmt(z.x1),x.order===2?fmt(z.x2):'Unused',z.y])})
function recurrence(order){return order===1?T`x_1[n]=x_1[n-1]+u[n]-y[n-1],\quad v[n]=x_1[n],\quad y[n]=Q(v[n])`:T`x_1[n]=x_1[n-1]+u[n]-y[n-1],\quad x_2[n]=x_2[n-1]+x_1[n]-y[n-1],\quad y[n]=Q(x_2[n])`}
function loopSteps(x,p,order){const first=x.actual.rows[1];return [
 s('Declare the state update and quantizer levels','Q(v)=+1 V for v≥0, otherwise −1 V. Both feedback paths use the PREVIOUS output. In second order, x2 uses the newly updated x1. States and previous output are zero before warm-up sample −M. Run −M through −1, then retain 0 through M−1 without resetting. The numerical example uses retained sample 1.',recurrence(order),first?T`n=1:\quad u=${N(first.u)}\,V,\quad y[0]=${N(first.old)}\,V,\quad x_1[1]=${N(first.x1)}\,V,\quad y[1]=${first.y}\,V`:T`\text{State guard reached during warm-up; no steady record}`),
 ...(first?[s('Substitute one complete retained-sample update','These starting values are the states left after warm-up and retained sample zero, immediately before retained sample one. They are not newly reset. Keep the previous output fixed while updating both states.',T`x_1[1]=x_1[0]+u[1]-y[0]`,T`x_1[1]=${N(first.before1)}+(${N(first.u)})-(${N(first.old)})=${N(first.x1)}\,V`),s(order===2?'Update the second state, then quantize':'Quantize the updated first state',order===2?'Use the new first-state value in the second accumulation. The sign of the updated second state selects the next DAC output.':'The sign of the updated first state selects the next DAC output. Only after this decision does the feedback value change.',order===2?T`x_2[1]=x_2[0]+x_1[1]-y[0],\quad y[1]=Q(x_2[1])`:T`y[1]=Q(x_1[1])`,order===2?T`x_2[1]=${N(first.before2)}+(${N(first.x1)})-(${N(first.old)})=${N(first.x2)}\,V,\quad y[1]=${first.y}\,V`:T`y[1]=Q(${N(first.x1)}\,V)=${first.y}\,V`)]:[]),
 s('Introduce quantizer error as an exact bookkeeping identity','Define e=y−v. This identity is exact for the nonlinear simulation. It does not say that e is white, uniform or independent. Zero-initial-condition z transforms describe the linear input/error paths.',T`y[n]=v[n]+e[n],\quad D=1-z^{-1}`,order===1?T`DX_1=U-z^{-1}Y,\quad Y=X_1+E\Rightarrow Y=U+DE`:T`DX_1=U-z^{-1}Y,\quad DX_2=X_1-z^{-1}Y,\quad Y=X_2+E\Rightarrow Y=U+D^2E`),
 s('Identify the two transfer functions','For this declared update timing, the signal path is unity. The error path has a zero at DC; its order determines how strongly low-frequency error is attenuated.',T`STF(z)=1,\quad NTF(z)=(1-z^{-1})^{${order}},\quad |NTF(e^{j2\pi f/f_s})|^2=[2\sin(\pi f/f_s)]^{${2*order}}`,T`|NTF(B)|^2=[2\sin(\pi/(2\cdot${p.osr}))]^{${2*order}}=${N(ntfPower(order,.5/p.osr))}`),
 s('Add a statistical assumption before integrating noise','The model replaces e with independent uniform noise of step Δ=2 V, variance Δ²/12. With a one-sided PSD, integrate 2σe²/fs times |NTF|² from 0 to B. Numerical integration retains the exact sine.',T`P_{model}=\frac{\Delta^2}{6}\int_0^{1/(2OSR)}[2\sin(\pi\nu)]^{${2*order}}d\nu`,T`\Delta=2\,V,\quad P_{model}=${N(x.model.exact)}\,V^2`),
 s('Derive the oversampling slope and compare the actual record','For large OSR, sin(πν)≈πν. A doubled OSR divides the model power by 2^(2ℓ+1). Measure y−u in the actual bitstream record independently; the quantizer error can be correlated or have a different variance.',T`P_{model}\approx\frac{\Delta^2\pi^{${2*order}}}{12(${2*order+1})OSR^{${2*order+1}}},\quad SNDR=10\log_{10}\frac{A^2/2}{P}`,T`P_{approx}=${N(x.model.approx)}\,V^2,\quad SNDR_{model}=${N(x.predicted)}\,dB,\quad\Delta SNDR_{doubling}\approx${N(x.model.gainPerDoubling)}\,dB`)
 ]}
function loopOutput(p,order){const x=noiseExperiment({...p,order}),rows=[16,32,64,128].map(o=>{const m=shapedPower(order,o);return [o,fmt(m.exact),fmt(10*Math.log10(p.amplitude**2/(2*m.exact))),x.actual.complete?fmt(bandPower(x.actual.error,o,'hann').power):'Guard reached']});return O(loopSteps(x,p,order),[r('White-error model ratio',x.predicted,'dB'),...(x.measured?[r('Actual in-band signal/error',x.measuredRatio,'dB')]:[]),r('Largest observed state',x.actual.maxState,'V'),r('Model improvement per OSR doubling',x.model.gainPerDoubling,'dB')],
 [...(x.measured?[spectrumPlot(x.measured,x.white),curve('Actual first integrator, first 256 retained samples','Sample n','State x1 (V)',x.actual.state1.slice(0,256).map((y,x)=>({x,y})))]:[]),{...curve('Noise transfer magnitude squared','Normalized frequency f/fs','Magnitude squared',samples(f=>ntfPower(order,f),0,.5)),logX:false}],
 x.actual.complete?'The bitstream and additive-error path obey the same recurrence, but a white uniform error distribution is an additional assumption. Differences between measured and predicted noise are meaningful; no curve is rescaled to force agreement.':'The nonlinear run exceeded the declared state limit before a complete record was obtained. A white-noise ratio remains a conditional calculation and is not an achieved converter performance.',
 'Calculate the predicted dB improvement when OSR doubles in the large-OSR model.',x.model.gainPerDoubling,'dB',`Compute 10 log10(2^${2*order+1}).`,{plotNote:`${plotNote.replace('rectangular-window','Hann-window, power-normalized')} Hann tapering limits endpoint leakage from high-frequency shaped noise. Bin sums estimate window-weighted power; no mean subtraction or tone removal is applied to y−u. The coherent input makes ${TONE_BIN} cycles in ${RECORD} samples; its tone remains inside the retained band throughout the OSR range. Actual in-band error includes DC and distortion.`,table:{headers:['OSR','Model power (V²)','Model ratio (dB)','Actual error power (V²)'],rows}})}
export const NOISE_SHAPING_LESSONS=[
L('e1','Quantization error is a waveform before it is a noise model',[
 k('bits','Quantizer resolution',4,2,8,'bits',1),{...k('kind','Input record',0,0,1),options:['Slow ramp','Seeded busy input']},seed],
 'When is replacing quantization error with independent white noise a useful approximation?',
 'Compute every quantized sample first. Then construct a separate independent uniform-noise record with the same nominal variance. The slow ramp exposes structure that a variance-only model cannot describe.',
 'Compare slow ramp with seeded busy input. Look at adjacent-sample correlation and the spectrum, not only total error power.',p=>{const x=quantizationRecord(p),actual=spectrum(x.error),white=spectrum(x.white);return O([
 s('Define the quantizer grid and its rounding rule','The allowed input span is −1 to +1 V. Codes correspond to interval centers. Floor chooses the interval; the highest and lowest indices are clipped to the code range.',T`L=2^N,\quad\Delta=2/L,\quad k=\operatorname{clip}(\lfloor(u+1)/\Delta\rfloor,0,L-1),\quad y=-1+(k+1/2)\Delta`,T`L=${2**p.bits},\quad\Delta=${N(x.delta)}\,V`),
 s('Calculate a real sample and its error','Use the first input sample from the selected deterministic ramp or seeded uniform input. The error is the quantized result minus that input.',T`e[n]=Q(u[n])-u[n]`,T`u[0]=${N(x.input[0])}\,V,\quad y[0]=${N(x.output[0])}\,V,\quad e[0]=${N(x.error[0])}\,V`),
 s('Derive the uniform-noise variance as a separate hypothesis','A uniform random variable on [−Δ/2,Δ/2] has this mean-square value. A deterministic error sequence is not made random merely by having a similar power.',T`P_{model}=\frac1\Delta\int_{-\Delta/2}^{\Delta/2}e^2de=\frac{\Delta^2}{12}`,T`P_{model}=${N(x.delta)}^2/12=${N(x.modelPower)}\,V^2`),
 s('Measure the actual finite record','Compute mean-square error without removing its DC value. Adjacent-sample correlation uses mean-subtracted errors and diagnoses structure the scalar power misses.',T`P_{record}=\frac1M\sum_{n=0}^{M-1}e[n]^2,\quad\rho_1=\frac{\sum_{n=1}^{M-1}(e[n]-\bar e)(e[n-1]-\bar e)}{(M-1)\sigma_e^2}`,T`P_{record}=${N(x.power)}\,V^2,\quad P_{independent\ record}=${N(x.whitePower)}\,V^2,\quad\rho_1=${N(x.lag)}`),
 s('Inspect where the error power lies','A rectangular-window FFT resolves repeatable structure. The ramp is one finite ramp, so endpoint discontinuity can also spread power; the seeded busy input helps decorrelate quantization from adjacent samples.',T`P_{record}=\sum_k P_k,\quad P_k=PSD_k\Delta f`,T`M=${RECORD},\quad\Delta f/f_s=1/${RECORD}`)
 ],[r('Quantizer step',x.delta,'V'),r('Actual total error power',x.power,'V²'),r('Uniform model power',x.modelPower,'V²'),r('Adjacent-error correlation',x.lag)],[curve('Actual error across the record','Sample n','Error (V)',points(x.error,1024)),spectrumPlot(actual,white)],
 'Similar total power does not imply a white spectrum. The ramp and busy input exercise the same quantizer; only the input sequence changes. Subsequent noise-shaping predictions must state which error assumptions they use.', 'Calculate the uniform-error model variance.',x.modelPower,'V²','Square the quantizer step, then divide by 12.',{plotNote,table:{headers:['Sample','Input (V)','Quantized (V)','Error (V)'],rows:x.input.slice(0,8).map((u,i)=>[i,fmt(u),fmt(x.output[i]),fmt(x.error[i])])}})}),
L('e2','Oversampling lowers in-band noise under a stated model',[k('bits','Quantizer resolution',4,2,8,'bits',1),osr,{...k('kind','Input record',1,0,1),options:['Slow ramp','Seeded busy input']},seed],
 'How much resolution does oversampling alone buy?',
 'Keep the quantizer and full-band error power fixed, then retain a smaller fraction of the Nyquist band. Compare the white-error prediction with integration of the actual error spectrum from E1.',
 'Compare OSR 16, 32, 64 and 128. Switch to the ramp and see whether its structured error follows the smooth white-noise prediction.',p=>{const x=quantizationRecord(p),measured=bandPower(x.error,p.osr),white=bandPower(x.white,p.osr),model=x.modelPower/p.osr,improvement=10*Math.log10(p.osr);return O([
 s('Define oversampling by the retained signal band','OSR is the sample rate divided by twice the desired signal bandwidth. The positive-frequency retained interval is 0 through fs/(2OSR).',T`OSR=\frac{f_s}{2B},\quad B/f_s=\frac1{2OSR}`,T`B/f_s=1/(2\cdot${p.osr})=${N(.5/p.osr)}`),
 s('Spread the model variance over the Nyquist band','The one-sided white PSD is 2Ptotal/fs. Integrate it over B. This is an ideal brick-wall retention calculation, not an implemented anti-alias or decimation filter.',T`S_e(f)=\frac{2}{f_s}\frac{\Delta^2}{12},\quad P_{band}=\int_0^B S_e(f)df=\frac{\Delta^2}{12OSR}`,T`P_{band}=${N(x.delta)}^2/(12\cdot${p.osr})=${N(model)}\,V^2`),
 s('Convert power reduction to dB and equivalent bits','For a fixed signal, power divided by two gains 3.0103 dB. One ideal ADC bit corresponds to 6.0206 dB, so doubling OSR gains half a bit under this model.',T`\Delta SNR=10\log_{10}(OSR),\quad\Delta N=\tfrac12\log_2(OSR)`,T`\Delta SNR=${N(improvement)}\,dB,\quad\Delta N=${N(.5*Math.log2(p.osr))}\,bits`),
 s('Integrate the measured error bins independently','Include DC and all bins whose centers lie in the retained band. Finite bin spacing and realization variation mean this need not equal the continuous integral exactly. Correlated error can deviate systematically.',T`K=\left\lfloor\frac M{2OSR}\right\rfloor,\quad P_{record,band}=\sum_{k=0}^{K}P_k`,T`K=${measured.last},\quad P_{actual,band}=${N(measured.power)}\,V^2,\quad P_{white,band}=${N(white.power)}\,V^2`)
 ],[r('White-model in-band error',model,'V²'),r('Actual in-band error',measured.power,'V²'),r('Model SNR improvement',improvement,'dB'),r('Model equivalent-bit gain',.5*Math.log2(p.osr),'bits')],[spectrumPlot(measured,white),{...curve('White model: power falls as 1/OSR','OSR','In-band power (V²)',samples(o=>x.modelPower/o,1,256)),logX:true,logY:true}],
 'Oversampling alone gives only half a bit per doubling under the white-error model. The actual error record can contain tones; reducing bandwidth does not guarantee that those tones fall outside it.', 'Calculate the predicted equivalent-bit gain at the selected OSR.',.5*Math.log2(p.osr),'bits','Take half of log base 2 of OSR.',{plotNote,table:{headers:['OSR','White-model power (V²)','Actual power (V²)'],rows:[16,32,64,128].map(o=>[o,fmt(x.modelPower/o),fmt(bandPower(x.error,o).power)])}})}),
L('e3','First-order feedback shapes quantizer error',[{...amp,value:1,max:1},osr,seed],
 'How does one integrator create a zero in the noise path at DC?',
 'Run a one-bit loop sample by sample, then eliminate its state algebraically. The same timing that produces the bitstream gives NTF=1−z⁻¹. Compare its actual in-band error with a separately generated white-error model.',
 'Double OSR while keeping the input amplitude fixed. Expect about 9 dB per doubling from the model; inspect whether the deterministic bitstream follows it.',p=>loopOutput(p,1)),
L('e4','Second-order shaping: two states and stronger assumptions',[amp,osr,seed],
 'What does a second integrator change besides the low-frequency noise slope?',
 'The second state accumulates the updated first state minus the previous DAC output. Derive NTF=(1−z⁻¹)² for this explicit loop, then inspect the actual state excursions and spectrum.',
 'Compare 0.1, 0.5 and 0.9 V peak. A white-error prediction does not tell you whether the internal states remain small or the bitstream develops structure.',p=>{const x=loopOutput(p,2),actual=modulator({order:2,amplitude:p.amplitude});if(actual.complete)x.plots.push(curve('Second integrator, first 256 retained samples','Sample n','State x2 (V)',actual.state2.slice(0,256).map((y,x)=>({x,y}))));return x}),
L('e5','Overload: watch the nonlinear states, not a linear noise curve',[
 k('amplitude','Input magnitude',.8,.1,1.2,'V'),{...k('kind','Input waveform',0,0,1),options:['Constant DC','Coherent sine']},k('length','Observation length',4096,1024,16384,'samples',1)],
 'What evidence shows that this particular one-bit loop has overloaded?',
 'Start both states at zero and apply the selected input. Stop at the first state magnitude above 100 V in this normalized behavioral model. The flag is an explicit observation limit, not a physical rail or a universal delta-sigma stability theorem.',
 'With DC input compare 0.6, 0.7, 0.8 and 1.1 V. Values above 0.7 V are not automatically unstable. Above the ±1 V DAC range, constant input cannot be balanced by any bit pattern.',p=>{const x=modulator({order:2,amplitude:p.amplitude,dc:!p.kind,n:p.length,bin:13,warm:false}),first=x.rows[0],rows=[.6,.7,.8,1.1].map(amplitude=>({amplitude,x:modulator({order:2,amplitude,dc:!p.kind,n:p.length,bin:13,warm:false})}));return O([
 s('Begin from a fully defined state','The first sample uses previous output zero, which is an initialization value, not a third DAC level. Every subsequent DAC output is +1 or −1 V.',T`x_1[-1]=x_2[-1]=y[-1]=0,\quad Q(v)=\begin{cases}+1&v\ge0\\-1&v<0\end{cases}`,recurrence(2)),
 s('Work through the first update','First accumulate input minus previous output. Then update the second state with the new first state minus that same previous output. Only then quantize.',T`x_1[0]=u[0],\quad x_2[0]=x_1[0],\quad y[0]=Q(x_2[0])`,T`u[0]=${N(first.u)}\,V,\quad x_1[0]=${N(first.x1)}\,V,\quad x_2[0]=${N(first.x2)}\,V,\quad y[0]=${first.y}\,V`),
 s('Derive a necessary average balance','Sum the first-state recurrence. A bounded state requires the long-term average output to track the average input. The one-bit DAC cannot produce an average outside [−1,+1] V.',T`x_1[K]-x_1[-1]=\sum_{n=0}^{K}(u[n]-y[n-1]),\quad |\overline y|\le1\,V`,T`\overline y_{observed}=${N(x.mean)}\,V,\quad\max_n(|x_1|,|x_2|)=${N(x.maxState)}\,V`),
 s('Explain what the finite observation proves','For constant u>1 V, each first-state increment is at least u−1 after the initial sample, so unbounded growth follows algebraically. A sine with zero mean is not covered by that proof; inspect its state trajectory instead.',T`u_{DC}>1\Rightarrow x_1[n]-x_1[n-1]\ge u_{DC}-1>0`,x.stop===null?T`\text{No guard crossing in }${p.length}\text{ samples}`:T`\text{First state-limit crossing at }n=${x.stop}`),
 s('Keep the stop condition separate from clipping','The simulation records the crossing sample and stops. It does not clamp the state or fabricate a recovered waveform. A run that stays below the limit has only passed this finite observation.',T`n_{stop}=\min\{n:\max(|x_1[n]|,|x_2[n]|)>100\,V\}`,T`\text{Retained samples}=${x.output.length},\quad\text{longest identical-output run}=${x.longest}`)
 ],[r('Largest observed state',x.maxState,'V'),r('Samples simulated',x.output.length),r('Observed output mean',x.mean,'V'),r('Longest same-symbol run',x.longest,'samples')],[{label:'States from zero initialization; curve ends at the guard',xLabel:'Sample n',yLabel:'Integrator state (V)',traces:[{label:'x1',points:points(x.state1,1024)},{label:'x2',points:points(x.state2,1024)}]},curve('First 128 DAC outputs','Sample n','Output (V)',x.output.slice(0,128).map((y,x)=>({x,y})))],
 x.stop===null?'No guard crossing occurred in this finite record. That is not a proof of bounded behavior for every input or initial state. The 0.7-full-scale rule is not universal.':'The state limit was crossed and simulation stopped. A linearized white-noise SNR is not reported as achieved performance for this run.',
 'What is the largest average voltage that the ±1 V DAC can produce?',1,'V','An average cannot exceed the largest available output level.',{table:{headers:['Input magnitude (V)','Largest state (V)','Observation'],rows:rows.map(({amplitude,x})=>[amplitude,fmt(x.maxState),x.stop===null?`${p.length} samples below guard`:`Guard at n=${x.stop}`])}})},
 {limits:'This exact second-order recurrence, zero initialization, and the selected finite record only. A 100 V state guard bounds computation and is not a hardware rail. No hard-coded 0.7-full-scale stability boundary. A DC input above the DAC magnitude has a mathematical overload proof; other inputs require separate analysis.'}),
L('e6','Decimation: remove noise before discarding samples',[
 k('ratio','Decimation ratio',64,8,128,'',1),k('clock','Input sample rate',1e6,.5e6,4e6,'Hz'),k('edge','Passband edge / output rate',.2,.05,.45),{...k('correct','Droop correction',1,0,1),options:['No corrector','Three-tap edge corrector']}],
 'What does a sinc³ decimator preserve, and what does it attenuate along with the noise?',
 'Run the actual second-order bitstream through three normalized moving averages before downsampling. Measure passband droop, then apply an explicitly defined three-tap FIR corrector at the output rate.',
 'Compare correction off and on at a 0.2-output-rate band edge. Move the band edge toward Nyquist and inspect the remaining interior ripple: matching one edge does not flatten the entire passband.',p=>{const x=decimation(p),fsout=x.rate,half=x.halfEdgeGain;return O([
 s('Filter first, then reduce the sample rate','Each stage averages R high-rate samples, with zeros in its delay line before sample zero. Three cascaded stages form sinc³. Keep samples R−1, 2R−1, and so on after filtering.',T`H(z)=\left[\frac{1-z^{-R}}{R(1-z^{-1})}\right]^3,\quad f_{out}=f_s/R`,T`R=${p.ratio},\quad f_{out}=${N(p.clock)}/${p.ratio}=${N(fsout)}\,Hz`),
 s('Evaluate the actual frequency response','The first zero is fs/R. The output Nyquist frequency is fs/(2R), where the sinc³ droop is close to 11.76 dB for large R. That Nyquist edge is not a sensible flat-passband assumption.',T`|H(f)|=\left|\frac{\sin(\pi Rf/f_s)}{R\sin(\pi f/f_s)}\right|^3`,T`f_{null,1}=${N(x.firstNull)}\,Hz,\quad L(f_{out}/2)=${N(x.nyquistLoss)}\,dB`),
 s('Calculate droop at the chosen usable band edge','The edge fraction b is relative to the OUTPUT sample rate. Choosing b<0.5 leaves a transition band before output Nyquist.',T`B=b f_{out},\quad L(B)=-20\log_{10}|H(B)|`,T`b=${N(p.edge)},\quad B=${N(p.edge*fsout)}\,Hz,\quad |H(B)|=${N(x.target)},\quad L(B)=${N(x.edgeLoss)}\,dB`),
 s('Design a finite corrector and state what it matches','At the output rate use coefficients [−a,1+2a,−a]. Its zero-phase gain is 1+2a(1−cos Ω), with one output-sample delay. Choose a to make the total edge gain one; DC is already one.',T`F(e^{j\Omega})=e^{-j\Omega}[1+2a(1-\cos\Omega)],\quad a=\frac{1/|H(B)|-1}{2[1-\cos(2\pi b)]}`,T`a=${N(x.a)},\quad [h_0,h_1,h_2]=[${N(-x.a)},${N(1+2*x.a)},${N(-x.a)}]`),
 s('Check the rest of the band and the added delay','The corrector does not recover information lost to aliasing. It can increase out-of-band noise and leaves residual interior ripple. Compare the measured decimated waveform with the same transfer gain and group delay.',T`D_{sinc}=3(R-1)/2\text{ input samples},\quad D_{total}=D_{sinc}+R\text{ with correction}`,T`D_{selected}=${N(x.delay)}\text{ input samples},\quad |HF|(B/2)=${N(half)},\quad e_{rms,record}=${N(x.rms)}\,V`)
 ],[r('Output sample rate',fsout,'samples/s'),r('Uncorrected edge loss',x.edgeLoss,'dB'),r('Selected half-edge gain',half),r('Waveform residual RMS',x.rms*1e6,'µV')],[{label:'Droop and the finite corrector',xLabel:'Frequency / output sample rate',yLabel:'Gain (dB)',traces:[{label:'Sinc³',points:samples(f=>20*Math.log10(Math.max(1e-15,Math.abs(Math.sin(Math.PI*f)/(p.ratio*Math.sin(Math.PI*f/p.ratio)))**3)),.00001,.5)},{label:p.correct?'Sinc³ plus corrector':'Selected: sinc³',points:samples(f=>20*Math.log10(Math.max(1e-15,x.gain(f/p.ratio))),0,.5)}]},
 {label:'Actual decimated bitstream versus gain-and-delay prediction',xLabel:'Output sample index',yLabel:'Voltage (V)',traces:[{label:'Actual filtered output',points:x.output.slice(8,136).map((y,i)=>({x:i+8,y}))},{label:'Predicted sine',points:x.expected.slice(8,136).map((y,i)=>({x:i+8,y}))}]}],
 'Sinc³ is a useful decimation example, not a universal requirement for every second-order modulator. Its stopband and transition band must fit the application. One short corrector matches DC and one edge, not every frequency.',
 'Calculate the output sample rate.',fsout,'samples/s','Divide input sample rate by the integer decimation ratio.',{plotNote:'The waveform begins after eight output samples to exclude FIR startup. The actual second-order loop starts from zero, produces a 13-cycle sine record over 512R input samples, and is filtered before decimation. The residual includes shaped quantization error; it is not a claimed ADC ENOB.',table:{headers:['Frequency','Uncorrected gain','Selected gain'],rows:[['DC',1,1],['B/2',fmt(Math.abs(Math.sin(Math.PI*p.edge/2)/(p.ratio*Math.sin(Math.PI*p.edge/(2*p.ratio))))**3),fmt(half)],['B',fmt(x.target),fmt(x.spanGain)]]}})},
 {symbols:[[T`R,f_s,f_{out},b,B`,'Integer decimation ratio; input and output sample rates (Hz); passband-edge fraction of output rate; physical band edge (Hz).'],[T`z,z^{-1},H(z),F(z),\Omega`,'High-rate delay variable for H, output-rate delay variable for F; three-stage moving-average transfer; corrector transfer; output-rate angular frequency (radians/sample). The two rates are explicitly different.'],[T`a,h_0,h_1,h_2,D`,'Dimensionless corrector coefficient, three FIR taps, and group delay measured in input samples.'],[T`u[n],y[n],e_{rms}`,'Desired sine and actual one-bit output of the E4 recurrence (V); RMS difference of the decimated output from its gain-and-delay prediction (V).']],limits:'Three moving averages implemented as floating-point FIRs with zero initial delay lines, followed by downsampling and an optional three-tap FIR. This is mathematically equivalent to normalized sinc³ without finite-word-length CIC overflow. No universal sinc order requirement or perfect one-stage equalization is claimed.'})
]
