import {knob as k,step as s,reading as r,curve,samples,texnum as N} from '@ee-labs/lessons/model'
import {phaseDrawing,transferCharge,scCoefficients,integrator,sampleResponse,continuousComparison,scTolerance,scBiquad,biquadResponse,hz,signalHandover} from './sc.js'
const clock=k('fs','Sample clock',1e6,48000,2e6,'Hz'),ratio=k('ratio','Sampling / feedback capacitance',.1,.01,.5),voltage=k('vin','Sampled input voltage',.1,-.2,.2,'V')
const phase={...k('phase','Displayed switch phase',1,0,1,'',1),options:['φ1: sample input','φ2: transfer charge']}
const symbols=[[String.raw`C_s,C_f,C_p,Q`,'Sampling, feedback and parasitic capacitances (F), and plate charge (C).'],[String.raw`f_s,T_s,n,z`,'Sample rate (Hz), period 1/fs (s), integer sample index, and discrete-time transform variable. A delay of one sample is z⁻¹.'],[String.raw`u[n],y[n],r`,'Input and output samples (V); r=Cs/Cf is dimensionless. y[0] is the initial held output.'],[String.raw`\phi_1,\phi_2,A_0`,'Nonoverlapping sample and transfer phases; dimensionless settled amplifier gain.'],[String.raw`f,f_0,Q_f,\Omega`,'Test frequency and pole natural frequency (Hz), filter quality factor, and discrete angular frequency 2πf/fs (rad/sample).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'B. Switched-capacitor circuits',knobs,question,intro,try:attempt,solve,symbols,flow:['Track capacitor plates across both phases','Conserve charge to obtain a sample update','Compare the exact sampled response with approximations'],sources:[['Analog Devices: A Filter Primer','https://www.analog.com/en/resources/technical-articles/a-filter-primer.html']],route:'Use charge equations at each switch event to obtain the state update. Its z transform gives the exact sampled frequency response. A continuous equivalent resistance is useful only when the input changes slowly relative to the clock.',limits:'Ideal nonoverlapping switching with full settling in each phase. Charge is conserved on floating conductors; driven nodes and amplifier outputs can supply charge. Switch resistance, noise, injection and slew are excluded here and are introduced separately in Group A or later groups.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
const stems=(label,points)=>({...curve(label,'Sample index n','Output (V)',points),stems:true})
const responsePlot=(tf,fs)=>({...curve('Exact sampled magnitude','Frequency (Hz)','Magnitude (dB)',Array.from({length:161},(_,i)=>{const f=fs*10**(-4+i/160*Math.log10(4900));return{x:f,y:20*Math.log10(Math.max(1e-12,Math.hypot(...hz(tf,f,fs))))}})),logX:true})
const phaseTable=(vin,prior,after,cs,cf)=>({headers:['Phase boundary','Cs positive plate','Cs negative plate','Output','Charge retained at sum'],rows:[['End φ1',N(vin)+' V','Ground: 0 V',N(prior)+' V',N(-cf*prior)+' C on Cf'],['Connect φ2','Ground: 0 V','Join virtual-ground sum',N(after)+' V',N(-cs*vin-cf*prior)+' C total'],['End φ2','Ground: 0 V','Sum: 0 V',N(after)+' V','Same total; ideal input draws no charge']]})
export const SC_LESSONS=[
L('b1','A clock and capacitor carry an average current',[clock,k('cs','Switched capacitance',1e-12,.1e-12,10e-12,'F'),k('delta','Voltage difference',1,-2,2,'V'),k('capTolerance','Absolute capacitor tolerance bound',.2,.001,.3),k('clockTolerance','Clock tolerance bound',.001,0,.01),k('seed','Repeatable sample seed',42,1,999,'',1)],'When can a switched capacitor stand in for a resistor?',
'In phase 1 a capacitor charges to V1; in phase 2 it is connected to V2. The receiving source takes the charge difference once per cycle. Average current is proportional to voltage difference, even though instantaneous current arrives in pulses.',
'Double the clock and predict equivalent resistance. Then compare a 20% absolute capacitor tolerance with a 0.1% assumption.',p=>{const charge=p.cs*p.delta,current=charge*p.fs,req=1/(p.cs*p.fs),x=scTolerance(p);return O([
s('Account for one complete charge transfer','Take V2=0 and V1=ΔV. The stored charge changes from CsV1 to CsV2, so the charge delivered to V2 is positive when V1>V2.',String.raw`\Delta Q=C_s(V_1-V_2)=C_s\Delta V`,String.raw`\Delta Q=${N(charge)}\,\mathrm C`),
s('Average over the clock period','One transfer occurs per period. Req is the ratio of voltage difference to average current; this constitutive coefficient remains defined at zero applied voltage.',String.raw`I_{avg}=\Delta Q f_s=C_s\Delta V f_s,\quad R_{eq}=1/(C_sf_s)`,String.raw`I_{avg}=${N(current*1e6)}\,\mu\mathrm A,\quad R_{eq}=${N(req/1e6)}\,\mathrm{M\Omega}`),
s('Keep absolute accuracy separate from matching','Absolute equivalent resistance depends on absolute capacitance and clock rate. A matched capacitor ratio can be accurate without either capacitor being accurate in farads.',String.raw`R_{eq}/R_{eq0}=\frac1{(1+e_C)(1+e_f)},\quad\delta R/R\simeq-e_C-e_f`,String.raw`\overline{R/R_0}=${N(x.mean.value)},\quad95\%\ mean\ interval=[${x.mean.ci.map(N).join(',')}]`)
],[r('Equivalent resistance',req/1e6,'MΩ'),r('Average delivered current',current*1e6,'μA'),r('Estimated ±1% resistance yield',100*x.yield.value,'%')],[curve('Equivalent resistance versus clock','Clock (Hz)','Resistance (MΩ)',samples(fs=>1/(p.cs*fs)/1e6,48000,2e6))],'The average resistor analogy is useful; it does not make an absolute capacitor accurate to its matching tolerance or describe the within-cycle current pulses.',req/1e6,'MΩ','Calculate equivalent resistance in megohms.','Take 1/(Cs fs), then divide by one million.',{table:{headers:['Ensemble measure','Estimate','95% interval'],rows:[['Mean R/R0',N(x.mean.value),x.mean.ci.map(N).join(' to ')],['Yield within ±1%',N(100*x.yield.value)+'%',x.yield.ci.map(v=>N(100*v)+'%').join(' to ')],['Independent draws',x.count,'Bounded uniform C and clock errors']]}})}),
L('b2','Charge balance becomes an exact integrator',[clock,ratio,voltage,phase,k('prior','Initial output y[0]',0,-1,1,'V')],'How do capacitor charges become a difference equation and H(z)?',
'The positive Cs plate samples the input while its negative plate is grounded. For transfer, ground the positive plate and connect the negative plate to the virtual-ground summing node. Cf remains between that node and the output. This plate reversal gives a positive output increment.',
'Change the initial output and input separately. The response preserves the initial offset and adds the same increment each cycle.',p=>{const cf=10e-12,cs=p.ratio*cf,event=transferCharge({cs,cf,vin:p.vin,prior:p.prior}),x=integrator(p),points=sampleResponse({...x,input:p.vin}).map(q=>({...q,y:q.y+p.prior}));return O([
s('Label the charges before switching','Cf contributes −Cf y[n−1] at sum. The Cs plate about to join sum carries −Cs u[n−1]. Grounding its opposite plate does not allow charge into the amplifier input.',String.raw`Q_{sum}^{before}=-C_fy[n-1]-C_su[n-1]`),
s('Conserve summing-conductor charge','At the end of transfer both Cs plates are at zero, and Cf carries the retained sum charge. The charge projection solves the voltage constraint and this equation together.',String.raw`-C_fy[n]=-C_fy[n-1]-C_su[n-1],\quad y[n]=y[n-1]+r\,u[n-1]`,String.raw`y[1]=${N(p.prior)}+${N(p.ratio)}(${N(p.vin)})=${N(event.voltages.out)}\,\mathrm V`),
s('Take the z transform with zero initial state','The transfer function describes the zero-state response. A nonzero y[0] is an additional initial-condition response, visible in the sample trace.',String.raw`Y(z)=z^{-1}Y(z)+rz^{-1}U(z),\quad H(z)=\frac{r}{z-1}`),
s('Find unity gain on the unit circle','For z=exp(jΩ), |z−1|=2sin(Ω/2). The continuous estimate replaces sin(Ω/2) with Ω/2.',String.raw`f_u=\frac{f_s}{\pi}\sin^{-1}(r/2),\quad f_{u,cont}=rf_s/(2\pi)`,String.raw`f_u=${N(x.unity/1000)}\,\mathrm{kHz},\quad f_{u,cont}=${N(x.continuous/1000)}\,\mathrm{kHz}`)
],[r('Next output',event.voltages.out,'V'),r('Exact unity-gain frequency',x.unity/1000,'kHz'),r('Continuous estimate',x.continuous/1000,'kHz')],[stems('Charge-derived output samples',points),responsePlot(x.tf,p.fs)],'The event equation, stored state and z-domain filter describe the same settled samples. H(z) alone omits a nonzero initial output.',event.voltages.out,'V','Calculate the output after the first transfer.','Add r times the first input sample to y[0].',{schematic:phaseDrawing(p),table:phaseTable(p.vin,p.prior,event.voltages.out,cs,cf),handover:signalHandover(x.tf,p.fs,'b2',x.unity),plotNote:'The sample trace is exact for ideal phase settling. It does not interpolate the amplifier’s waveform between phases.'})}),
L('b3','Measure where the continuous approximation breaks',[clock,ratio,k('perCycle','Samples per input cycle',20,3,100)],'How much error hides in the equivalent-resistor approximation?',
'The exact integrator is evaluated at z=exp(jωTs), while the continuous approximation uses s=jω. Their magnitude and phase differences depend on samples per input cycle.',
'Compare 20, 10 and 5 samples per cycle. Observe the continuous-model handover disappear below 20.',p=>{const x=continuousComparison(p.perCycle),f=p.fs/p.perCycle,tf=integrator(p).tf;return O([
s('Use the same physical frequency in both domains','The continuous approximation has Hc(s)=rfs/s. Its low-frequency slope agrees with the exact sampled integrator.',String.raw`H_d(e^{j\Omega})=\frac r{e^{j\Omega}-1},\quad H_c(j\omega)=\frac{rf_s}{j\omega},\quad\Omega=\omega/f_s`),
s('Factor the sample delay explicitly','The factor exp(jΩ/2) produces half a sample of additional phase lag relative to the continuous integrator.',String.raw`e^{j\Omega}-1=2j\sin(\Omega/2)e^{j\Omega/2},\quad\frac{|H_d|}{|H_c|}=\frac{\Omega/2}{\sin(\Omega/2)}`,String.raw`magnitude\ error=${N(100*(x.ratio-1))}\%,\quad extra\ lag=${N(x.lag)}^\circ`),
s('Apply a stated approximation boundary','The handover requires at least 20 samples per cycle at the inspected frequency. This is a teaching accuracy boundary, not a claim of equivalence at all frequencies.',String.raw`f_s/f\ge20,\quad f=${N(f)}\,\mathrm{Hz}`,String.raw`f_s/f=${N(p.perCycle)}\quad\text{${x.allowed?'continuous comparison allowed':'use the exact sampled model'}}`)
],[r('Magnitude error',100*(x.ratio-1),'%'),r('Additional phase lag',x.lag,'°'),r('Inspected frequency',f,'Hz')],[curve('Magnitude approximation error','Samples per cycle','Error (%)',samples(n=>100*(continuousComparison(n).ratio-1),3,100)),curve('Additional sampled phase lag','Samples per cycle','Lag (°)',samples(n=>continuousComparison(n).lag,3,100))],x.allowed?'The stated approximation boundary is met at this frequency. The exact z-domain response remains the reference.':'Fewer than 20 samples per cycle: the continuous handover is withheld. Continue with the exact sampled equations.',100*(x.ratio-1),'%','Calculate continuous-model magnitude error.','Evaluate (π/N)/sin(π/N) − 1, then multiply by 100.',{handover:x.allowed?{app:'control-lab',label:'Inspect the permitted continuous approximation',patch:{plant:{type:'custom',params:[0,0,p.ratio*p.fs,0,1,0]},ctrl:{type:'p',params:[1]},from:{app:'mixed-signal-lab',id:'b3',label:'Low-frequency integrator approximation'}},note:`Hc(s)=r fs/s approximates the sampled integrator near ${N(f)} Hz. Control Lab closes this plant with unity feedback; that closed loop is not the SC integrator itself.`}:undefined,table:{headers:['Samples/cycle','Magnitude error','Extra phase lag','Continuous handover'],rows:[5,10,20,50,100].map(n=>{const a=continuousComparison(n);return[n,N(100*(a.ratio-1))+'%',N(a.lag)+'°',a.allowed?'Allowed':'Withheld']})}})}),
L('b4','Test which parasitic charge reaches the summing node',[ratio,voltage,phase,k('top','Sampling-plate parasitic',.1e-12,0,1e-12,'F'),k('bottom','Grounded-plate parasitic',.1e-12,0,1e-12,'F'),{...k('sensitive','Plate switching arrangement',0,0,1,'',1),options:['Reverse plates: insensitive','Transfer sampled plate: sensitive']}],'What does “parasitic-insensitive” mean at each switching phase?',
'In the insensitive arrangement the sampled plate and its parasitic are grounded during transfer. The plate joining sum was grounded during sampling. In the sensitive arrangement the sampled plate joins sum and carries its parasitic charge with it; the output increment also changes sign.',
'Vary the two parasitics independently. Switch arrangements and predict both the sign and magnitude of the output increment.',p=>{const cf=10e-12,cs=p.ratio*cf,x=scCoefficients({...p,cs,cf}),event=transferCharge({...p,cs,cf,vin:p.vin}),ideal=p.sensitive?-p.ratio:p.ratio;return O([
s('Identify the actual receiving plate','Charge on a parasitic matters only if the plate carrying it joins the isolated summing conductor. A voltage constraint by itself does not remove charge; the driven grounding path supplies the required redistribution.',String.raw`Q_{Cp,initial}=C_pV_{plate,initial}`),
s('Write both sum-charge equations','For reverse-plate transfer the joining plate’s parasitic begins and ends at zero. For sampled-plate transfer the top parasitic joins sum with charge CpTop u.',String.raw`\Delta y_{insensitive}=\frac{C_s}{C_f}u,\quad\Delta y_{sensitive}=-\frac{C_s+C_{p,top}}{C_f}u`),
s('Solve the same capacitor projection with parasitics present','The native charge solver includes each parasitic separately, conserves charge at sum and enforces ideal virtual ground. Coefficients are read from unit-input and unit-prior-state solves.',String.raw`y[n]=a\,y[n-1]+b\,u[n-1]`,String.raw`a=${N(x.a)},\quad b=${N(x.b)},\quad\Delta y=${N(event.voltages.out)}\,\mathrm V,\quad b/b_{ideal}-1=${N(100*(x.b/ideal-1))}\%`)
],[r('Input coefficient b',x.b),r('State retention a',x.a),r('Parasitic gain error',100*(x.b/ideal-1),'%')],[curve('Effect of sampled-plate parasitic','CpTop (pF)','Input coefficient b',samples(top=>scCoefficients({...p,cs,cf,top:top*1e-12}).b,0,1))],'Insensitivity is a property of the named topology, ideal virtual ground and full settling. It does not eliminate switch injection, finite-gain errors or settling time.',x.b,'','Calculate the input coefficient including the selected parasitics.','Use +Cs/Cf for reverse-plate transfer or −(Cs+CpTop)/Cf for sampled-plate transfer.',{schematic:phaseDrawing(p),table:{headers:['Parasitic','Before transfer','During transfer','Effect on ideal input coefficient'],rows:[['CpTop','Charged to input',p.sensitive?'Joins sum':'Grounded through driven path',p.sensitive?'Adds to sampled charge':'Does not join sum'],['CpBottom','Both terminals grounded',p.sensitive?'Remains grounded':'Joins virtual ground','Zero initial and final plate voltage']]}})}),
L('b5','Design the biquad in the z plane',[clock,k('normalized','Target natural frequency / clock',.05,.01,.15),k('q','Target quality factor',2,.6,5),{...k('exact','Coefficient design',1,0,1,'',1),options:['Continuous small-step approximation','Exact pole matching']}],'Why should a sampled two-integrator loop be designed in z?',
'Two stored outputs form the discrete state. The second update uses the new first state, so its coefficients contain the within-cycle update order. Matching this exact update to the desired poles avoids treating a finite sample interval as infinitesimal.',
'Compare exact and approximate designs at f0/fs = 0.05 and Q = 2. Increase normalized frequency and watch the approximation error.',p=>{const target=p.normalized*p.fs,x=scBiquad({...p,frequency:target}),fn=x.frequency/target-1,qe=x.q/p.q-1;return O([
s('Map the target poles into z','For the specified underdamped continuous pole pair, z=exp(sTs). This matches pole natural frequency and damping; it does not specify every possible numerator shape.',String.raw`s_{1,2}=-\omega_0/(2Q_f)\pm j\omega_0\sqrt{1-1/(4Q_f^2)},\quad z_{1,2}=e^{s_{1,2}/f_s}`,String.raw`D_{target}(z)=z^2${x.targetA1<0?'-':'+'}${N(Math.abs(x.targetA1))}z+${N(x.targetA2)}`),
s('Write the phase-ordered state updates','x1 and x2 are held integrator outputs in volts; u is the prior input sample. Output y equals x2. The second equation uses x1[n], not x1[n−1].',String.raw`x_1[n]=x_1[n-1]+K_4(u[n-1]-x_2[n-1]),\quad x_2[n]=\frac{x_2[n-1]+K_5x_1[n]}{1+K_6}`),
s('Read the denominator and match coefficients','If Dtarget=z²+a1z+a2, matching gives K6=1/a2−1 and K4K5=(1+a1+a2)/a2. The comparison instead uses K6=ω0Ts/Q and K4K5=(ω0Ts)².',String.raw`D(z)=z^2-\frac{2+K_6-K_4K_5}{1+K_6}z+\frac1{1+K_6},\quad H(z)=\frac{[K_4K_5/(1+K_6)]z}{D(z)}`,String.raw`K_6=${N(x.k6)},\quad K_4K_5=${N(x.product)},\quad K_4=K_5=${N(x.k4)}`),
s('Recover physical pole parameters from the realized filter','Invert the map using s=fs log z on the principal underdamped branch. f0 is the pole natural frequency, not necessarily the magnitude peak or −3 dB corner.',String.raw`f_{0,realized}=|s|/(2\pi),\quad Q_{realized}=|s|/(-2\Re s)`,String.raw`f_{0,realized}=${N(x.frequency/1000)}\,\mathrm{kHz},\quad Q_{realized}=${N(x.q)}`)
],[r('Realized natural frequency',x.frequency/1000,'kHz'),r('Realized Q',x.q),r('Frequency error',100*fn,'%'),r('Q error',100*qe,'%')],[{kind:'zplane',label:'Realized poles and zero on the z plane',poles:[-1,1].map(sign=>[x.radius*Math.cos(x.angle),sign*x.radius*Math.sin(x.angle)]),zeros:[[0,0]],sampleRate:p.fs,markerFreq:target},responsePlot(x.tf,p.fs),stems('Two-state response to a 0.1 V input',biquadResponse(x))],p.exact?'Exact matching recovers the specified pole frequency and Q. The numerator follows this particular two-state structure.':'The continuous coefficient estimate changes the realized poles at a finite sample interval. The exact update reveals the resulting frequency and Q errors.',x.product,'','Calculate the required K4K5 product for the selected design.','Use the matching equation for the exact design or (2πf0/fs)² for the approximate one.',{handover:signalHandover(x.tf,p.fs,'b5',target),table:{headers:['State matrix row','Coefficient of prior x1','Coefficient of prior x2','Coefficient of prior input'],rows:x.A.map((row,i)=>['x'+(i+1),...row.map(N),N(x.B[i])])},plotNote:'This is an explicit ideal discrete two-integrator model. No transistor-level settling or switch waveform is inferred from the state samples.'})}),
L('b6','Derive finite-gain leakage for this topology',[clock,ratio,voltage,k('gain','Settled amplifier gain A0',100,100,10000)],'How does finite virtual-ground error change the retained charge?',
'The same reverse-plate topology as B2 now has Vsum=−Vout/A0. Cf remains connected during sampling, so its initial charge also includes that nonzero summing voltage. Keeping both initial and final charges is essential: a generic leakage formula from another switching topology need not apply.',
'Compare gains 100, 1000 and 10000. Increase Cs/Cf and watch the pole move farther from one.',p=>{const x=integrator(p),ideal=integrator({...p,gain:Infinity}),z=hz(x.tf,ideal.unity,p.fs),err=Math.hypot(...z)-1;return O([
s('Include the prior finite-gain state','Cf was held in feedback before transfer, so its initial sum-plate charge is −Cf(1+1/A0)y[n−1]. The joining Cs plate carries −Cs u[n−1].',String.raw`Q_{before}=-C_f(1+1/A_0)y[n-1]-C_su[n-1]`),
s('Conserve charge with nonzero final summing voltage','After transfer Cs contributes −Cs y[n]/A0, and Cf contributes −Cf(1+1/A0)y[n]. Equating this total to Qbefore gives the exact settled update for this topology.',String.raw`(A_0+1+r)y[n]=(A_0+1)y[n-1]+rA_0u[n-1]`),
s('Read the pole and DC gain','Write y[n]=a y[n−1]+b u[n−1]. The pole is a and the finite DC gain is b/(1−a). These coefficients are independently recovered from the native charge projection.',String.raw`a=\frac{A_0+1}{A_0+1+r},\quad b=\frac{rA_0}{A_0+1+r},\quad H(z)=\frac b{z-a},\quad H(1)=A_0`,String.raw`a=${N(x.a)},\quad b=${N(x.b)},\quad H(1)=${N(x.dc)}`),
s('Compare at the ideal filter’s unity-gain frequency','The ideal response is exactly one there. Evaluate the finite-gain filter at that same frequency rather than substituting a generic first-order percentage.',String.raw`\epsilon=|H(e^{j2\pi f_{u,ideal}/f_s})|-1`,String.raw`f_{u,ideal}=${N(ideal.unity/1000)}\,\mathrm{kHz},\quad\epsilon=${N(100*err)}\%`)
],[r('Retained-state pole',x.a),r('Finite DC gain',x.dc),r('Gain error at ideal unity frequency',100*err,'%')],[{kind:'zplane',label:'Finite-gain integrator pole',poles:[[x.a,0]],zeros:[],sampleRate:p.fs,markerFreq:ideal.unity},responsePlot(x.tf,p.fs),stems('Finite-gain output samples',sampleResponse({...x,input:p.vin,count:100}))],'Leakage is real, but its coefficient must come from the actual phase connections. For this continuously connected feedback capacitor, the DC gain is A0; coefficients from another switching arrangement cannot be reused without checking its charge balance.',x.dc,'','Calculate the finite DC gain of this topology.','Evaluate b/(1−a); simplify before substituting.',{schematic:phaseDrawing(p),handover:signalHandover(x.tf,p.fs,'b6',ideal.unity),table:{headers:['Amplifier gain','Pole a','Input coefficient b','DC gain'],rows:[100,1000,10000].map(gain=>{const a=integrator({...p,gain});return[gain,N(a.a),N(a.b),N(a.dc)]})}})})
]
