import {knob as k,step as s,reading as r,curve,samples,texnum as N,fmt} from '@ee-labs/lessons/model'
import {KB,chopper,injection,autozero,noisePaths,cds,chopperDrawing,autozeroDrawing} from './zeroDrift.js'
const T=String.raw,source=['Analog Devices: To chop or auto-zero','https://www.analog.com/en/resources/technical-articles/to-chop-or-auto-zero-that-is-the-question.html'],tutorial=['Analog Devices MT-055: Zero-drift amplifiers','https://www.analog.com/media/en/training-seminars/tutorials/mt-055.pdf']
const symbols=[[T`v_{in},V_{OS},A,m(t),y(t)`,'Input and amplifier offset (V), instantaneous amplifier gain, ideal chopper polarity ±1, and filtered output state (V).'],[T`f_{ch},T_{ch},R,C,\tau,t,\dot y`,'Chopper rate (Hz), period (s), filter resistance (Ω), capacitance (F), time constant RC (s), elapsed time (s), and state derivative (V/s).'],[T`k_B,T,\sigma`,'Boltzmann constant 1.380649×10⁻²³ J/K, temperature 300 K, and the stated rms noise (V).']]
function L(id,name,knobs,question,intro,attempt,solve,extra={}){return{id,name,group:'G. Chopping, auto-zero and correlated sampling',knobs,question,intro,try:attempt,solve,symbols,sources:[source,tutorial],flow:['Track the switch phase or sampled state','Derive the update and its initial condition','Separate bias, ripple and random noise'],route:'Use switch-phase equations and state continuity for chopping transients. Use charge conservation for injection and sampling events. A z-domain transfer describes sampled differences, while phase-noise and alias sums describe statistical power; these routes answer different parts of the same measurement problem.',limits:'Ideal behavioral switches and explicitly stated linear storage/recovery paths. No transistor switch waveform, dead time, charge partition, finite amplifier settling or sampled-noise correlation is implied unless introduced in that lesson.',...extra}}
function O(steps,readings,plots,conclusion,answer,unit,question,hint,extra={}){return{steps,readings,plots,conclusion,practice:{answer,unit,question,hint,reason:conclusion},...extra}}
export const ZERO_DRIFT_LESSONS=[
L('g1','Follow both choppers and the filter state',[k('gain','Instantaneous amplifier gain',1000,100,1000),k('offset','Amplifier input offset',.001,0,.002,'V'),k('clock','Chopping frequency',1e5,2e4,5e5,'Hz'),k('corner','Output low-pass corner',1000,100,5000,'Hz'),{...k('start','Filter initial condition',1,0,1),options:['Uncharged output','Periodic steady state']}],
 'Why is the desired signal restored while the amplifier offset becomes ripple?',
 'Two synchronized ideal differential crossbar switches either pass or reverse polarity. The first precedes an instantaneous gain stage; the second follows it. Between switch events, the output low-pass capacitor obeys its RC state equation.',
 'Compare the two initial conditions. Increase the filter corner until the usual high-chop-frequency ripple approximation becomes less accurate. The exact phase propagation remains valid.',p=>{const x=chopper(p);return O([
 s('Apply the first switch, amplifier and second switch in order','The input is a constant 10 µV. Offset is introduced inside the amplifier after the first chopper. Multiplying twice by the same polarity restores the signal because m²=1.',T`v_1=mv_{in},\quad v_2=A(v_1+V_{OS}),\quad v_3=mv_2=Av_{in}+AV_{OS}m`,T`Av_{in}=${N(x.dc*1000)}\,mV,\quad AV_{OS}=${N(x.amp)}\,V`),
 s('Write the state equation within each switch phase','The amplifier and switches are algebraic in this model. Only the low-pass capacitor carries state. Each half-period holds v3 constant, so integrate the RC equation exactly.',T`\tau\dot y+y=v_3,\quad y(t+h)=v_3+[y(t)-v_3]e^{-h/\tau}`,T`\tau=1/(2\pi f_c)=${N(x.tau*1e6)}\,\mu s,\quad h=T_{ch}/2=${N(x.period*5e5)}\,\mu s`),
 s('Preserve the capacitor voltage at a switch event','The chopper reverses v3 instantly but provides no impulse current through a finite filter resistor. Therefore y remains continuous, and its derivative changes.',T`y(t_k^+)=y(t_k^-),\quad a=e^{-T_{ch}/(2\tau)}`,T`a=${N(x.a)},\quad y(0)=${N(x.initial)}\,V`),
 s('Solve the periodic boundary condition','In steady state the ripple alternates between −P and +P around A·vin. Apply the half-period update and solve P=U+(−P−U)a.',T`P=AV_{OS}\frac{1-a}{1+a}=AV_{OS}\tanh(T_{ch}/(4\tau))`,T`P=${N(x.peak*1000)}\,mV,\quad\overline y=Av_{in}=${N(x.dc*1000)}\,mV`),
 s('Keep ripple peak and fundamental amplitude distinct','The offset square wave has fundamental peak 4AVOS/π. The low-pass attenuates it at fch; its exact transfer contains √[1+(fch/fc)²]. Higher harmonics also contribute to the waveform peak.',T`V_{1} =\frac{4AV_{OS}/\pi}{\sqrt{1+(f_{ch}/f_c)^2}},\quad V_{1,approx}=\frac{4AV_{OS}}\pi\frac{f_c}{f_{ch}}`,T`V_1=${N(x.fundamental*1000)}\,mV,\quad V_{1,approx}=${N(x.approx*1000)}\,mV`)
 ],[r('Desired DC output',x.dc*1000,'mV'),r('Periodic ripple peak',x.peak*1000,'mV'),r('Ripple fundamental peak',x.fundamental*1000,'mV')],[curve('Output capacitor over eight switching periods','Time (µs)','Output (mV)',x.points.map(v=>({x:v.x,y:v.y*1000}))),curve('Second chopper restores signal and switches the offset','Time (µs)','Before low-pass (V)',x.points.map(v=>({x:v.x,y:v.demod})))],
 'Ideal synchronous chopping translates internal offset to the chopping harmonics, while the desired DC signal returns to baseband. Residual DC is zero only for this ideal symmetry; startup, ripple peak and harmonic amplitude are distinct quantities.',x.fundamental*1000,'mV','Calculate the first-harmonic ripple peak.','Multiply the square-wave fundamental by the exact low-pass magnitude.',{schematic:chopperDrawing,table:{headers:['Phase','Input switch output (µV)','Amplifier output (V)','Demodulated (V)','Filter at phase end (mV)'],rows:x.phases.slice(0,4).map(v=>[v.m>0?'Straight':'Crossed',fmt(v.pre*1e6),fmt(v.amplifier),fmt(v.demod),fmt(v.after*1000)])}})}),
L('g2','Charge mismatch: an edge jump is not a DC offset',[k('charge','Net unmatched charge per cycle',1e-15,-5e-15,5e-15,'C'),k('cap','Output-node capacitance',1e-12,.5e-12,10e-12,'F'),k('resistance','Recovery resistance',1e6,1e5,1e7,'Ω'),k('clock','Injection repetition rate',1e5,2e4,5e5,'Hz')],
 'What happens to a charge-injection mismatch after the edge?',
 'Place one net charge impulse per cycle onto an output node with capacitance C and a recovery resistor R to its nominal level. The cancelling portion of the switch-charge pair is omitted; Q is the signed unmatched remainder. Use gain 1000 to refer output errors to the input.',
 'Compare the immediate Q/C jump with the cycle average. Increase capacitance and then resistance separately; they do not have the same effect on the average error.',p=>{const x=injection(p);return O([
 s('Conserve charge through the impulse','A finite injected charge changes capacitor voltage instantly. The resistor cannot absorb an impulse of charge over zero duration.',T`C[v(0^+)-v(0^-)]=Q,\quad\Delta v=Q/C`,T`\Delta v=${N(p.charge)}/${N(p.cap)}=${N(x.jump*1000)}\,mV`),
 s('Propagate the recovery between impulses','The state is deviation from the nominal output level. With no injected current between edges, the resistor discharges that deviation exponentially.',T`\dot v=-v/(RC),\quad v(t)=v(0^+)e^{-t/\tau},\quad\tau=RC`,T`\tau=${N(x.tau*1e6)}\,\mu s,\quad T=${N(x.T*1e6)}\,\mu s`),
 s('Solve for the periodic before- and after-edge states','The next impulse adds Q/C to the surviving value from the previous period. Solve that recurrence before drawing a steady-state trace.',T`v_+=v_+e^{-T/\tau}+Q/C,\quad v_+=\frac{Q/C}{1-e^{-T/\tau}},\quad v_-=v_+e^{-T/\tau}`,T`v_+=${N(x.after*1000)}\,mV,\quad v_-=${N(x.before*1000)}\,mV`),
 s('Integrate one period to find the DC component','Average the decaying waveform. Charge balance also gives mean resistor current Qfs, so the mean voltage is Q R fs. It is not generally Q/C.',T`\overline v=\frac1T\int_0^T v_+e^{-t/\tau}dt=QRf_s`,T`\overline v=${N(x.mean*1e6)}\,\mu V,\quad\overline v/A=${N(x.inputMean*1e9)}\,nV`),
 s('Refer the edge and average to the input separately','At gain 1000, a 1 mV output jump corresponds to 1 µV at the input at that instant. Recovery determines its average and its harmonic content.',T`\Delta v_{in}=Q/(AC),\quad\overline v_{in}=QRf_s/A`,T`\Delta v_{in}=${N(x.inputJump*1e6)}\,\mu V,\quad A=1000`)
 ],[r('Instantaneous output jump',x.jump*1000,'mV'),r('Mean output error',x.mean*1e6,'µV'),r('Mean input-referred error',x.inputMean*1e9,'nV')],[curve('Periodic error from just after one impulse to before the next','Time after impulse (µs)','Output error (mV)',samples(t=>x.at(t*1e-6)*1000,0,x.T*1e6))],
 'Charge divided by capacitance predicts the edge discontinuity. To predict DC offset, also specify how the node recovers and how often impulses occur. Different output and sampling topologies can have different averages for the same Q/C.',x.mean*1e6,'µV','Calculate the cycle-average output error.','Multiply signed charge by recovery resistance and repetition frequency.',{table:{headers:['Quantity','Output (µV)','Input-referred (µV)'],rows:[['Edge jump',fmt(x.jump*1e6),fmt(x.inputJump*1e6)],['After-edge state',fmt(x.after*1e6),fmt(x.after*1000)],['Cycle average',fmt(x.mean*1e6),fmt(x.inputMean*1e6)]]}})}, {symbols:[[T`Q,C,R,f_s,T,\tau,A,v_+,v_-`,'Net signed charge per cycle (C), node capacitance (F), recovery resistance (Ω), repetition rate (Hz), period (s), recovery time constant (s), gain 1000, and voltages just after/before an impulse (V).']]}),
L('g3','Auto-zero: acquire an offset, then hold a noisy estimate',[k('cap','Storage capacitance',1e-12,.5e-12,20e-12,'F'),k('acquire','Offset acquisition duration',10e-9,1e-9,100e-9,'s'),k('hold','Hold duration',10e-6,1e-6,100e-6,'s'),k('leak','Storage leakage current',100e-15,0,1e-12,'A'),k('seed','Ensemble seed',7,1,999,'',1)],
 'Which part of the offset remains, and what noise did sampling add?',
 'For one calibration event, initialize the storage capacitor to zero, then connect it through a 1 kΩ switch to a constant 1 mV amplifier-offset voltage. Open the switch, hold the estimate, and subtract it with unity correction gain. Repeated trials below are independent repetitions of this same initial condition.',
 'Increase capacitance: thermal noise falls, but the same acquisition time may leave more settling error. Then vary hold time to isolate leakage droop.',p=>{const x=autozero(p);return O([
 s('Define the acquisition state and its initial value','Let vc be the stored offset estimate. During acquisition it approaches VOS through the switch resistance. The capacitor begins uncharged in this single-event experiment.',T`R_{on}C\dot v_c+v_c=V_{OS},\quad v_c(0)=0`,T`R_{on}=1000\,\Omega,\quad V_{OS}=1\,mV,\quad\tau=${N(x.tau*1e9)}\,ns`),
 s('Solve the remaining deterministic settling error','At acquisition end the switch opens. With no charge injection in this lesson, the storage voltage is continuous across that event.',T`a=e^{-t_a/\tau},\quad v_c(t_a)=V_{OS}(1-a),\quad e_{settle}=V_{OS}a`,T`a=${N(x.a)},\quad e_{settle}=${N(x.settle*1e6)}\,\mu V`),
 s('Include the noise accumulated during finite acquisition','The resistor’s thermal noise charges the capacitor. Starting from zero noise variance, the RC variance approaches kT/C with a doubled exponent because variance is a squared quantity.',T`\sigma_c^2=(k_BT/C)(1-e^{-2t_a/\tau})`,T`\sigma_c=${N(x.sigma*1e6)}\,\mu V,\quad\sqrt{k_BT/C}=${N(x.steadyNoise*1e6)}\,\mu V`),
 s('Propagate leakage during hold','Positive leakage removes charge from the stored estimate, so subtracting that smaller estimate leaves a positive residual. This is deterministic droop, separate from the sampled noise.',T`\Delta v_{leak}=I_Lt_h/C,\quad e_{mean}=V_{OS}a+I_Lt_h/C`,T`\Delta v_{leak}=${N(x.droop*1e6)}\,\mu V,\quad e_{mean}=${N(x.residual*1e6)}\,\mu V`),
 s('Compare a seeded ensemble with the predicted distribution','Draw 4096 independent Gaussian samples of stored thermal noise. Subtract the noisy estimate from the offset; the sign of noise reverses, but its variance is unchanged.',T`e=e_{mean}-n_c,\quad n_c\sim\mathcal N(0,\sigma_c^2)`,T`\bar e_{record}=${N(x.mean*1e6)}\,\mu V,\quad s_{record}=${N(x.sd*1e6)}\,\mu V`)
 ],[r('Mean residual after hold',x.residual*1e6,'µV'),r('Sampled thermal noise',x.sigma*1e6,'µV rms'),r('Ensemble standard deviation',x.sd*1e6,'µV')],[curve('Independent calibration trials at the same initial condition','Trial','Residual offset (µV)',x.draws.slice(0,200).map((v,i)=>({x:i,y:v*1e6})))],
 'Auto-zeroing subtracts an estimate of offset. Settling and leakage create mean error, while sampling creates random error. The kT/C result describes a sufficiently settled sample; short acquisition reduces noise only by also failing to acquire the offset fully.',x.sigma*1e6,'µV','Calculate thermal noise after the selected acquisition interval.','Use √[(kT/C)(1−exp(−2ta/τ))].',{schematic:autozeroDrawing(p),table:{headers:['Contribution','Mean (µV)','RMS random component (µV)'],rows:[['Incomplete acquisition',fmt(x.settle*1e6),0],['Hold leakage',fmt(x.droop*1e6),0],['Sampled thermal noise',0,fmt(x.sigma*1e6)]]}})}, {symbols:[[T`v_c,V_{OS},R_{on},C,\tau,t_a,t_h,I_L`,'Stored correction and 1 mV offset (V), switch resistance 1 kΩ, capacitance (F), acquisition time constant (s), acquisition/hold durations (s), and leakage removing charge (A).'],[T`a,k_B,T,\sigma_c,n_c,e`,'Remaining settling fraction, Boltzmann constant, 300 K temperature, sampled rms noise (V), one stored-noise draw (V), and residual input offset (V).']]})
,
L('g4','Compare noise folding with chopper translation',[k('clock','Sampling or chopping frequency',1e5,2e4,5e5,'Hz'),k('ratio','Noise bandwidth / clock rate',10,1,20,'',1),k('density','Input white-noise density',10e-9,1e-9,50e-9,'V/√Hz')],
 'Why can sampling a wideband correction signal increase its baseband noise?',
 'Compare two explicitly defined paths driven by the same flat, band-limited noise: ideal samples followed by a zero-order hold, and multiplication by a ±1 square wave. These are path-level, time-averaged noise spectra; they are not a complete auto-zero amplifier noise budget.',
 'Increase the source bandwidth while holding its density fixed. Sampling adds more aliases; chopping redistributes noise with harmonic weights whose total approaches one.',p=>{const bandwidth=p.ratio*p.clock,args={...p,bandwidth},f=.01*p.clock,x=noisePaths(args,f);return O([
 s('Define the source spectrum and observation frequency','Use a two-sided power spectral density S0 inside ±B, zero outside. The displayed amplitude density is the usual one-sided density en, so S0=en²/2. Ratios are unchanged by that convention.',T`S_n(f)=\begin{cases}e_n^2/2,&|f|<B\\0,&|f|\ge B\end{cases},\quad B=qf_s`,T`B=${N(bandwidth)}\,Hz,\quad f_o=0.01f_s=${N(f)}\,Hz`),
 s('Count the aliases landing at the observation frequency','Every integer k satisfying |fo+kfs|<B contributes the same power. Uncorrelated spectral bands add as power, not voltage amplitude.',T`N_a=\sum_{k\in\mathbb Z}\mathbf1_{|f_o+kf_s|<B},\quad S_{sample}(f_o)=N_a S_0`,T`N_a=${x.count},\quad e_{sample}=${N(p.density*Math.sqrt(x.count)*1e9)}\,nV/\sqrt{Hz}`),
 s('Include the hold aperture','Holding each sample for a full period multiplies the time-averaged spectrum by sinc². Define sinc explicitly to avoid the two common conventions.',T`\operatorname{sinc}(u)=\sin(u)/u,\quad e_{held}=e_n\sqrt{N_a}|\operatorname{sinc}(\pi f_o/f_s)|`,T`e_{held}=${N(x.sampled*1e9)}\,nV/\sqrt{Hz},\quad 10\log_{10}(N_a\operatorname{sinc}^2(\pi f_o/f_s))=${N(10*Math.log10(x.fold))}\,dB`),
 s('Weight the translated bands for a chopper','A unit square wave has only odd harmonics. Its complex Fourier coefficients have squared magnitude 4/(πk)². Shift the source spectrum by each signed harmonic and add the weighted powers.',T`S_{ch}(f_o)=\sum_{k\;odd}\frac{4}{\pi^2k^2}S_n(f_o-kf_{ch})`,T`\sum_{|f_o-kf_{ch}|<B,\;k\;odd}\frac4{\pi^2k^2}=${N(x.chop)},\quad e_{ch}=${N(x.chopped*1e9)}\,nV/\sqrt{Hz}`),
 s('Interpret the result within the model','As B grows without bound, the chopper weights sum to one: ideal multiplication by ±1 preserves total instantaneous noise power. Real chopping adds switching artifacts; a complete auto-zero circuit also has direct noise and correlations omitted from this path comparison.',T`\sum_{k\;odd}\frac4{\pi^2k^2}=1,\quad e_{held}/e_{ch}=\sqrt{N_a\operatorname{sinc}^2(\pi f_o/f_s)/W_{ch}}`,T`e_{held}/e_{ch}=${N(x.sampled/x.chopped)}`)
 ],[r('Held correction-path density',x.sampled*1e9,'nV/√Hz'),r('Chopped-path density',x.chopped*1e9,'nV/√Hz'),r('Alias count',x.count)],[{label:'Time-averaged baseband noise density',xLabel:'Frequency / clock rate',yLabel:'Noise density (nV/√Hz)',traces:[{label:'Sample and hold path',points:samples(u=>noisePaths(args,u*p.clock).sampled*1e9,.001,.49)},{label:'Ideal chopper path',points:samples(u=>noisePaths(args,u*p.clock).chopped*1e9,.001,.49)}]}],
 'Sampling folds all accepted source bands into the correction path. Ideal chopping translates bands with smaller harmonic weights. This explains a mechanism, not a universal noise ranking of complete amplifier products.',x.sampled*1e9,'nV/√Hz','Calculate the held-path density at 0.01 times the clock rate.','Multiply en by √Na and the defined sinc magnitude.',{table:{headers:['Path at selected frequency','Power / source PSD','Amplitude density (nV/√Hz)'],rows:[['Source',1,fmt(p.density*1e9)],['Sample and hold',fmt(x.fold),fmt(x.sampled*1e9)],['Square-wave multiplication',fmt(x.chop),fmt(x.chopped*1e9)]]}})}, {symbols:[[T`e_n,S_n,S_0,B,q`,'One-sided amplitude density (V/√Hz), two-sided source PSD (V²/Hz), its flat level, noise cutoff (Hz), and cutoff/clock ratio.'],[T`f_s,f_{ch},f_o,k,N_a,W_{ch}`,'Sample rate, chopper rate, observation frequency (Hz), signed harmonic index, alias count, and sum of accepted chopper harmonic power weights.']]}),
L('g5','Correlated double sampling: subtract two observations',[k('clock','Sample rate',1e5,2e4,192e3,'Hz'),k('ratio','Signal frequency / sample rate',.01,.001,.49),k('delay','Sample separation',1,1,2,'samples',1),k('rho','Adjacent noise correlation',0,0,.99),k('seed','Noise record seed',7,1,999,'',1)],
 'What disappears when two observations are subtracted, and what happens to their noise?',
 'Form y[n]=x[n]−x[n−d] from an ongoing sampled sequence. A constant offset cancels, but so does wanted DC. Model input noise as a stationary first-order correlated Gaussian sequence with 10 µV rms per sample, initialized from its stationary distribution.',
 'Increase noise correlation, then increase sample separation. Predict both the signal attenuation and the output noise before looking at the results.',p=>{const frequency=p.ratio*p.clock,x=cds({...p,frequency}),sigma=10e-6;return O([
 s('Define the two observations and their difference','Index n labels the current sample; d is a positive integer separation. This filter operates on ongoing history. A receiver starting with an empty delay line has an additional startup transient.',T`y[n]=x[n]-x[n-d],\quad x[n]=v[n]+V_{OS}+\eta[n]`,T`d=${p.delay},\quad f_s=${N(p.clock)}\,Hz,\quad f=${N(frequency)}\,Hz`),
 s('Take the z transform','A d-sample delay multiplies the transform by z⁻ᵈ. On the unit circle z=eʲω, factor the difference into a phase term and a sine to obtain its magnitude.',T`H(z)=1-z^{-d},\quad |H(e^{j\omega})|=2|\sin(\omega d/2)|,\quad\omega=2\pi f/f_s`,T`|H|=2|\sin(\pi\cdot${N(p.ratio)}\cdot${p.delay})|=${N(x.magnitude)}`),
 s('Check offset rejection against signal loss','At zero frequency both observations are equal, so their difference is zero. Near zero frequency, the same subtraction attenuates a slowly changing wanted signal.',T`H(1)=0,\quad |H|\simeq2\pi fd/f_s\quad(fd/f_s\ll1)`,T`1\,V\;peak\;input\ \longrightarrow\ ${N(x.magnitude)}\,V\;peak\;output`),
 s('Include the covariance between observations','Each input noise sample has variance σ². For the stated stationary first-order model, samples d steps apart have covariance σ²ρᵈ. Expand the square of their difference.',T`\sigma_y^2=\sigma^2+\sigma^2-2\operatorname{Cov}(\eta[n],\eta[n-d])=2\sigma^2(1-\rho^d)`,T`\sigma_y=${N(x.noise*1e6)}\,\mu V,\quad\rho^d=${N(p.rho**p.delay)}`),
 s('Compare the prediction with a reproducible noise record','The generator uses η[n]=ρη[n−1]+σ√(1−ρ²)ε[n], where independent ε are unit Gaussian draws. Subtract actual samples and measure their rms spread.',T`\eta[n]=\rho\eta[n-1]+\sigma\sqrt{1-\rho^2}\,\epsilon[n],\quad\epsilon[n]\sim\mathcal N(0,1)`,T`s_{record}=${N(x.measured*1e6)}\,\mu V,\quad\sigma=${N(sigma*1e6)}\,\mu V`)
 ],[r('Signal magnitude ratio',x.magnitude),r('Predicted difference noise',x.noise*1e6,'µV rms'),r('Measured record noise',x.measured*1e6,'µV rms')],[curve('Difference-filter magnitude','Frequency / sample rate','Magnitude',samples(u=>x.at(u*p.clock),0,.5)),curve('Seeded difference-noise record','Sample index','Noise (µV)',x.points)],
 'Double sampling rejects errors shared by the two observations. Independent sample noise grows by √2; positively correlated noise cancels partly. It also rejects wanted DC, so its usefulness depends on which two physical measurements should be compared.',x.noise*1e6,'µV','Calculate the difference noise from σ, ρ, and the separation d.','Use σ√[2(1−ρᵈ)].',{table:{headers:['Input component','Difference result','Reason'],rows:[['Constant offset','0','Equal in both observations'],['Selected 1 V peak sine',`${fmt(x.magnitude)} V peak`,'Frequency response at f/fs'],['Independent 10 µV rms noise',`${fmt(Math.SQRT2*10)} µV rms`,'Variances add'],['Selected correlated noise',`${fmt(x.noise*1e6)} µV rms`,'Subtract twice the covariance']]},handover:{app:'signal-lab',label:'Open the same difference filter in Signal Lab',patch:{rate:p.clock,sources:[{type:'sine',freq:frequency,amp:1}],blocks:[{type:'biquad',params:[1,p.delay===1?-1:0,p.delay===2?-1:0,0,0]}],from:{app:'mixed-signal-lab',id:'g5',label:'Correlated double sampling'}},note:'Transfers the exact FIR coefficients, sine frequency and sample rate. The stationary correlated-noise ensemble stays in this lesson; Signal Lab starts its filter delay state at zero.'}})}, {symbols:[[T`n,d,x[n],y[n],v[n],V_{OS},\eta[n]`,'Sample index, separation in samples, input/output, wanted signal, constant offset, and input noise (V).'],[T`z,H,\omega,f,f_s,\sigma,\rho,\epsilon[n]`,'Transform variable, difference-filter transfer, digital frequency (rad/sample), signal/sample frequencies (Hz), input rms noise 10 µV, adjacent correlation, and independent unit Gaussian draw.']]})
]
const zeroDriftSymbols={
 g1:[[T`v_1,v_2,v_3,V_1,P,U`,'Successive internal node voltages, ripple fundamental peak, periodic ripple peak, and square-wave ripple drive U=A·VOS (all V). Uppercase V1 is a harmonic amplitude; lowercase v1 is the first switch output.'],[T`f_c,h,a,t_k^-,t_k^+,\overline y`,'Filter corner (Hz), half-period (s), exponential state-retention factor, times immediately before and after a switch event, and cycle-mean output (V).']],
 g2:[[T`v,\dot v,\overline v,0^-,0^+`,'Output error state (V), its time derivative (V/s), cycle mean (V), and instants just before and just after an impulse. Time t is in seconds.']],
 g3:[[T`\dot v_c,0,t_a^-,t_a^+,\bar e_{record},s_{record}`,'Storage-voltage derivative (V/s), start of acquisition, instants before and after switch opening, ensemble mean residual (V), and sample standard deviation (V).']],
 g5:[[T`\sigma_y,\operatorname{Cov},s_{record}`,'Output rms noise (V), covariance between two input-noise samples (V²), and measured record standard deviation (V).']]
}
for(const lesson of ZERO_DRIFT_LESSONS)if(zeroDriftSymbols[lesson.id])lesson.symbols=[...lesson.symbols,...zeroDriftSymbols[lesson.id]]
