export const KB=1.380649e-23
export function chopper({gain=1000,offset=.001,input=10e-6,clock=1e5,corner=1000,start=1}={}){
 const tau=1/(2*Math.PI*corner),period=1/clock,half=period/2,a=Math.exp(-half/tau),dc=gain*input,amp=gain*offset,peak=amp*(1-a)/(1+a),initial=start?dc-peak:0
 let y=initial;const points=[],phases=[];for(let phase=0;phase<16;phase++){const m=phase%2?-1:1,pre=m*input,amplifier=gain*(pre+offset),demod=m*amplifier,before=y;for(let i=0;i<32;i++){const elapsed=i/32*half;points.push({x:(phase*half+elapsed)*1e6,y:demod+(before-demod)*Math.exp(-elapsed/tau),pre,amplifier,demod,m})}y=demod+(before-demod)*a;phases.push({phase,m,pre,amplifier,demod,before,after:y})}points.push({x:8*period*1e6,y,...phases.at(-1)})
 return{tau,period,a,dc,amp,peak,initial,points,phases,fundamental:4*amp/Math.PI/Math.hypot(1,clock/corner),approx:4*amp/Math.PI*corner/clock}
}
export function injection({charge=1e-15,cap=1e-12,resistance=1e6,clock=1e5,gain=1000}={}){const tau=resistance*cap,T=1/clock,a=Math.exp(-T/tau),jump=charge/cap,after=jump/(-Math.expm1(-T/tau)),before=after*a,mean=charge*resistance*clock;return{tau,T,a,jump,after,before,mean,inputMean:mean/gain,inputJump:jump/gain,at:t=>after*Math.exp(-t/tau)}}
function normalGenerator(seed){let x=seed>>>0;const u=()=>{x=(1664525*x+1013904223)>>>0;return(x+.5)/4294967296};return()=>Math.sqrt(-2*Math.log(u()))*Math.cos(2*Math.PI*u())}
export function autozero({cap=1e-12,acquire=10e-9,hold=10e-6,leak=100e-15,seed=7}={}){const offset=.001,resistance=1000,tau=resistance*cap,a=Math.exp(-acquire/tau),stored=offset*(1-a),settle=offset*a,droop=leak*hold/cap,residual=settle+droop,sigma=Math.sqrt(KB*300/cap*(-Math.expm1(-2*acquire/tau))),normal=normalGenerator(seed),draws=Array.from({length:4096},()=>residual-sigma*normal()),mean=draws.reduce((s,x)=>s+x,0)/draws.length,sd=Math.sqrt(draws.reduce((s,x)=>s+(x-mean)**2,0)/(draws.length-1));return{offset,resistance,tau,a,stored,settle,droop,residual,sigma,draws,mean,sd,steadyNoise:Math.sqrt(KB*300/cap)}}
export function noisePaths({clock=1e5,bandwidth=1e6,density=10e-9}={},f=1000){const count=Array.from({length:2*Math.ceil(bandwidth/clock)+5},(_,i)=>i-Math.ceil(bandwidth/clock)-2).filter(k=>Math.abs(f+k*clock)<bandwidth).length,sinc=f===0?1:Math.sin(Math.PI*f/clock)/(Math.PI*f/clock);let chop=0;const limit=Math.ceil((bandwidth+Math.abs(f))/clock)+1;for(let k=-limit;k<=limit;k++){if(k%2&&Math.abs(f-k*clock)<bandwidth)chop+=4/(Math.PI*k)**2}return{count,fold:count*sinc*sinc,chop,sampled:density*Math.sqrt(count)*Math.abs(sinc),chopped:density*Math.sqrt(chop)}}
export function cds({clock=1e5,frequency=1000,delay=1,sigma=10e-6,rho=0,seed=7}={}){const magnitude=2*Math.abs(Math.sin(Math.PI*frequency*delay/clock)),normal=normalGenerator(seed);let state=sigma*normal();const x=[];for(let i=0;i<8192;i++){state=rho*state+sigma*Math.sqrt(1-rho*rho)*normal();x.push(state)}const d=x.slice(delay).map((v,i)=>v-x[i]),mean=d.reduce((a,b)=>a+b,0)/d.length,measured=Math.sqrt(d.reduce((a,b)=>a+(b-mean)**2,0)/(d.length-1));return{magnitude,noise:sigma*Math.sqrt(2*(1-rho**delay)),measured,points:d.slice(0,256).map((y,x)=>({x,y:y*1e6})),at:f=>2*Math.abs(Math.sin(Math.PI*f*delay/clock))}}
export const chopperDrawing={elements:[],caption:'Behavioral differential signal flow. Each ×m box is an ideal synchronized polarity reversal. Offset enters inside the amplifier; the last box is the output storage state.',layout:{w:660,h:120,items:[{text:'vin',x:25,y:59},{wire:[42,55,65,55]},{box:[65,30,155,80]},{text:'× m(t)',x:110,y:59},{wire:[155,55,185,55]},{box:[185,30,345,80]},{text:'A × (input + VOS)',x:265,y:59},{wire:[345,55,375,55]},{box:[375,30,465,80]},{text:'× m(t)',x:420,y:59},{wire:[465,55,495,55]},{box:[495,30,615,80]},{text:'RC low-pass',x:555,y:59},{wire:[615,55,640,55]},{text:'y',x:650,y:59},{text:'Same polarity m = +1 or −1 in both switches',x:330,y:105}]}}
export function autozeroDrawing(p={}){const {cap=1e-12}=p;return{elements:[{type:'V',id:'VOS',value:.001},{type:'R',id:'Ron',value:1000},{type:'SW',id:'S1',closed:true},{type:'C',id:'C1',value:cap}],caption:'Acquisition topology: close S1 for ta to store an estimate of VOS through Ron. Then open S1 for hold; positive leakage removes charge from C1. The residual error is VOS minus the stored voltage.',layout:{w:430,h:220,items:[{el:'VOS',x:50,y:130,dir:'v'},{gnd:[50,150]},{wire:[50,110,50,60]},{wire:[50,60,100,60]},{el:'Ron',x:120,y:60,dir:'h'},{wire:[140,60,205,60]},{el:'S1',x:225,y:60,dir:'h'},{wire:[245,60,330,60]},{node:'vc',x:330,y:60,side:'r'},{wire:[330,60,330,110]},{el:'C1',x:330,y:130,dir:'v'},{gnd:[330,150]},{text:'Acquire → open switch → hold',x:215,y:200}]}}}
